### PR TITLE
versim support for L1 and L1 small sharded write-then-read-back gtests

### LINKED ISSUE #16195: Simulator doesn't work when buffers are allocated in "l1_small"

### PR DESCRIPTION
**Pull request by mpiseTT**
### Ticket
[Simulator doesn't work when buffers are allocated in "l1_small" #16195](https://github.com/tenstorrent/tt-metal/issues/16195)

### Problem description
The tt_metal/api gtests that we were using to verify L1 Small allocation and data transfers had to be updated to be compatible with tensix configuration used for versim

### What's changed
We updated relevant gtests to handle both versim and hardware device and tensix configurations

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp [hunk 1]
```diff
@@ -173,6 +194,10 @@ TEST_F(DeviceFixtureWithL1Small, TestWidthShardReadWrite) {
 }
 
 TEST_F(DeviceFixture, TestUnorderedHeightShardReadWrite) {
+    if (llrt::RunTimeOptions::get_instance().get_simulator_enabled()) {
+        GTEST_SKIP() << fmt::format("Skipping {} because it is not supported in simulator", __PRETTY_FUNCTION__);
```
Comment (nhuang-tt) [inline tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:198]: I'm not sure if `__PRETTY_FUNCTION__` is portable. Recently people have been trying to get tt-metal to compile on multiple platforms

File: tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp [hunk 2]
```diff
@@ -55,6 +57,22 @@ struct L1Config {
             {1 * num_cores_height * num_tiles_per_core_height * num_cores_height,
              num_tiles_per_core_width * num_cores_width});
     }
+
+    L1Config() = delete;
+    L1Config(T& testObj) {
+        if (true || llrt::RunTimeOptions::get_instance()
```
Comment (nhuang-tt) [inline tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:63]: Always true. Not needed?

File: tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp [hunk 3]
```diff
@@ -55,6 +57,22 @@ struct L1Config {
...
+                        .get_simulator_enabled()) {  // doesn't change anything on hw, but needed for versim
+            std::pair<unsigned, unsigned> min_dims = testObj.worker_grid_minimum_dims();
+            num_cores_width = std::min(min_dims.first, num_cores_width);
+            num_cores_height = std::min(min_dims.second, num_cores_height);
+        } else {
+            uint32_t num_cores_width = 1;
```
Comment (nhuang-tt) [inline tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:69]: Declared but unused?

File: tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp (hunk 1 above)
Comment (mpiseTT) [reply tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:198]: I'll change this to `__func__`

File: tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp (hunk 2 above)
Comment (mpiseTT) [reply tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:63]: Yes, because this is required of hw and sim, although normally this bounding check is _unavoidable_ for sim (because sim has restrictive # of worker cores, so much so that the tests here were triggering an assert in our code without this bounds enforcing). For hw, the bounding enforced in this code does nothing, because the # of workers that the test needs is less than # available in hw.

File: tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp (hunk 3 above)
Comment (mpiseTT) [reply tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:69]: Will remove this (forgot)

File: tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp [hunk 4]
```diff
@@ -123,7 +142,7 @@ bool l1_buffer_read_write(IDevice* device, const L1Config& test_config) {
 
 TEST_F(DeviceFixture, TestInterleavedReadWrite) {
     for (unsigned int id = 0; id < num_devices_; id++) {
-        L1Config test_config;
+        L1Config<decltype(*this)> test_config(*this);
```
Comment (jbaumanTT) [inline tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:145]: I think with CTAD (from C++17) we should be able to get rid of the decltype(*this).

Comment (mpiseTT) [reply tests/tt_metal/tt_metal/api/test_sharded_l1_buffer.cpp:145]: I think I agree. I don't recall why I specified the template argument explicitly. I'll check this out.

**Review by jbaumanTT — APPROVED** [review]

**Review by nhuang-tt — APPROVED** [review]
