### PR TITLE
#25012: Add int32 support for argmax

### LINKED ISSUE #25012: Argmax with int32 is not supported
### Describe the bug

Trying to run `ttnn.argmax` with integers results in an error:
```
RuntimeError: TT_FATAL @ /proj_sw/user_dev/sgligorijevic/jaxbringups/tt-metal/ttnn/cpp/ttnn/operations/reduction/argmax/device/argmax_op.cpp:57: input_tensor_a.dtype() == DataType::BFLOAT16
info:
Only BFLOAT16 is supported for inputs!
```

Trying to workaround argmax to be done in bfloat16 results in an incorrect result. My input looks something like:
```
input_data = torch.tensor([[49406.,   320.,  1125.,   539.,   320.,  2368., 49407.],
                          [49406.,   320.,  1125.,   539.,   320.,  1929., 49407.]])
```
and the output of argmax in bf16 is `[0, 0]` instead of `[6, 6]`, I suspect this is because both 49406 and 49407 when casted to bfloat16 are represented as 49408. Same happens when casted to TF32, either proper FP32 or INT32 support is needed.

### Steps to reproduce the issue

1. Run the following code:
```
import torch
import ttnn

input_data = torch.tensor([[49406.,   320.,  1125.,   539.,   320.,  2368., 49407.],
                          [49406.,   320.,  1125.,   539.,   320.,  1929., 49407.]])


with ttnn.manage_device(0) as dev:
    input_ttnn = ttnn.from_torch(input_data, dtype=ttnn.int32, layout=ttnn.ROW_MAJOR_LAYOUT, device=dev)

    res_ttnn = ttnn.argmax(input_ttnn, dim=-1, keepdim=False)
    res = ttnn.to_torch(res_ttnn)

```

### Expected behavior

_No response_

### Please complete the following environment information

Ubuntu 22.04
Metal hash 8fe3da9fb42bf368c275aa7657189f5dfc598d66 (admittedly 5 days out of date as of filing this bug)
N150 board

### PR DESCRIPTION
**Pull request by mgajewskiTT**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/25012

### Problem description
TTNN Argmax OP supported only BFloat16.

### What's changed
- Added support for Float32, UInt32, Int32 and UInt16,
- Updated docs,
- Added tests for different datatypes.

### Check that performance did not change

Tiles | Type | DEVICE KERNEL DURATION PER CORE MIN [ms] | DEVICE KERNEL DURATION PER CORE MAX [ms] | DEVICE KERNEL DURATION PER CORE AVG [ms]
-- | -- | -- | -- | --
Current implementation
64 | Single Core | 0.054 | 0.054 | 0.054
128 | Single Core | 2.856 | 2.856 | 2.856
256 | Single Core | 5.696 | 5.696 | 5.696
512 | Single Core | 13.487 | 13.487 | 13.487
1024 | Single Core | 26.961 | 26.961 | 26.961
2048 | Single Core | 44.491 | 44.491 | 44.491
4096 | Single Core | 107.798 | 107.798 | 107.798
64 | Mult Core | 0.002 | 0.005 | 0.002
128 | Mult Core | 0.078 | 0.147 | 0.080
256 | Mult Core | 0.143 | 0.213 | 0.146
512 | Mult Core | 0.273 | 0.345 | 0.277
1024 | Mult Core | 0.533 | 0.608 | 0.538
2048 | Mult Core | 1.053 | 1.132 | 1.060
4096 | Mult Core | 2.092 | 2.184 | 2.106
New implementation
64 | Single Core | 0.054 | 0.054 | 0.054
128 | Single Core | 2.855 | 2.855 | 2.855
256 | Single Core | 5.696 | 5.696 | 5.696
512 | Single Core | 13.487 | 13.487 | 13.487
1024 | Single Core | 26.961 | 26.961 | 26.961
2048 | Single Core | 44.491 | 44.491 | 44.491
4096 | Single Core | 107.798 | 107.798 | 107.798
64 | Mult Core | 0.002 | 0.005 | 0.002
128 | Mult Core | 0.078 | 0.147 | 0.080
256 | Mult Core | 0.143 | 0.213 | 0.146
512 | Mult Core | 0.273 | 0.345 | 0.277
1024 | Mult Core | 0.533 | 0.608 | 0.538
2048 | Mult Core | 1.052 | 1.132 | 1.061
4096 | Mult Core | 2.092 | 2.184 | 2.106

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes https://github.com/tenstorrent/tt-metal/actions/runs/16477071480
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable) https://github.com/tenstorrent/tt-metal/actions/runs/16444921453
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-quick-trigger.yaml) CI passes (if applicable)
- [ ] [TG demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by sjameelTT — APPROVED** [review]

File: tt_metal/hw/inc/utils/float32.h [hunk 1]
```diff
@@ -0,0 +1,55 @@
+// SPDX-FileCopyrightText: © 2043 Tenstorrent Inc.
```
Comment (bbradelTT) [inline tt_metal/hw/inc/utils/float32.h]: The date is wrong. I'm guessing this is because vi does not like the copyright symbol. 
You'll need to fix that (I haven't looked into how, would be good to know) or use a different editor such as pico/VSCode/Cursor
Also, the Inc should be changed.

Comment (mgajewskiTT) [reply tt_metal/hw/inc/utils/float32.h]: I am actually using VSCode, just helped myself on correcting comments in the file with Copilot - it changed a bit to much here...

Comment (mgajewskiTT) [reply tt_metal/hw/inc/utils/float32.h]: Fixed.

File: tests/ttnn/unit_tests/operations/reduce/test_argmax.py [hunk 2]
```diff
@@ -86,3 +86,60 @@ def test_argmax(device, tensor_shape, dim, keepdim, use_multicore):
     assert torch.allclose(
         torch_result, ttnn_result, atol=atol, rtol=rtol, equal_nan=True
     ), f"mismatch in allclose: torch: {torch_result}, ttnn: {ttnn_result}"
+
+
+@pytest.mark.parametrize(
```
Comment (nsorabaTT) [inline tests/ttnn/unit_tests/operations/reduce/test_argmax.py]: Can we add datatype as another parameter to the existing pytest function?

File: tt_metal/hw/inc/utils/float32.h [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+    - Handle special cases (NaN, infinity) first
+    - If signs differ:
+        - If f32_a is positive (sign bit 0), it is greater.
+        - If f32_a is negative (sign bit 1), it is not greater.
+    - If signs are the same:
+        - Positive numbers: higher bits mean greater value.
+        - Negative numbers: higher bits mean smaller value (reverse comparison).
+    */
+
+    // Handle NaN cases - NaN is never greater than anything
```
Comment (nsorabaTT) [inline tt_metal/hw/inc/utils/float32.h:34]: Should both
1. NaN > a? and
2. a > NaN?

Return false?

File: tt_metal/hw/inc/utils/uint32.h [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+
+#pragma once
+
+#include <stdint.h>
+
+inline constexpr uint32_t MIN_UINT32 = 0x00000000;  // Representation of minimum uint32 value
+inline constexpr uint32_t MAX_UINT32 = 0xFFFFFFFF;  // Representation of maximum uint32 value
+
+// Optimized function to compare two uint32 values
+bool uint32_greater(uint32_t uint32_a, uint32_t uint32_b) {
```
Comment (nsorabaTT) [inline tt_metal/hw/inc/utils/uint32.h]: I understand we need "optimized" implementations for bfloat16 and fp32. For uint32 and uint16, won't the native implementation in RISC-V cores suffice?

File: tt_metal/hw/inc/utils/float32.h (hunk 3 above)
Comment (mgajewskiTT) [reply tt_metal/hw/inc/utils/float32.h:34]: I found information like this: 
```
… IEEE 754 standard behavior where:
- NaN is not greater than any value (including itself),
- No value is greater than NaN,
- Any comparison involving NaN should return false.
```
In this case both return false when compared with NaN.

File: tt_metal/hw/inc/utils/uint32.h (hunk 4 above)
Comment (mgajewskiTT) [reply tt_metal/hw/inc/utils/uint32.h]: Removed.

File: tests/ttnn/unit_tests/operations/reduce/test_argmax.py (hunk 2 above)
Comment (mgajewskiTT) [reply tests/ttnn/unit_tests/operations/reduce/test_argmax.py]: Merged two tests into one and added some test shapes.

**Review by aczajkowskiTT — APPROVED** [review]
Approving, given CI passes and outstanding conversations are resolved.

File: tt_metal/hw/inc/utils/float32.h [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+    if (((f32_a & 0x7F800000) == 0x7F800000 && (f32_a & 0x007FFFFF) != 0) ||
+        ((f32_b & 0x7F800000) == 0x7F800000 && (f32_b & 0x007FFFFF) != 0)) {
```
Comment (bbradelTT) [inline tt_metal/hw/inc/utils/float32.h]: Would it be clearer if these use the const variables defined above?

I checked and see that tt_metal/hw/inc/utils/bfloat16.h does use the numbers directly instead of the const variables.

File: tt_metal/hw/inc/utils/float32.h [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+        return false;
+    }
+
+    // Handle zero cases (both +0 and -0 are equal)
+    if ((f32_a & 0x7FFFFFFF) == 0 && (f32_b & 0x7FFFFFFF) == 0) {
+        return false;
+    }
+
+    // Check if signs are different
+    if ((f32_a ^ f32_b) & 0x80000000) {
```
Comment (bbradelTT) [inline tt_metal/hw/inc/utils/float32.h]: Please have a const var at the top for all values, including 0x80000000

**Review by bbradelTT — APPROVED** [review]

File: tt_metal/hw/inc/utils/float32.h (hunk 6 above)
Comment (mgajewskiTT) [reply tt_metal/hw/inc/utils/float32.h]: Changed.

File: tt_metal/hw/inc/utils/float32.h (hunk 5 above)
Comment (mgajewskiTT) [reply tt_metal/hw/inc/utils/float32.h]: Changed.

**Review by abhullar-tt — APPROVED** [review]

**Review by nsorabaTT — APPROVED** [review]

**Review by blozano-tt — APPROVED** [review]
