### PR TITLE
Qwen2.5-VL bringup

### LINKED ISSUE #20630: [TT-Transformers] Remove deprecated models/demos/qwen and integrate into TTT
### Describe the bug

The old Qwen-7B implementation in `models/demos/qwen/` is currently outdated.

TT-Transformers supports Qwen weights out of the box, so we should remove the old implementation and update it to use TT-Transformers instead, similar to the ongoing Mistral/Mixtral work.

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### LINKED ISSUE #24273: Functional bringup
- Achieve correct output when compared with reference model from HF.
- Support Qwen2.5-VL-72B and Qwen2.5-VL-32B on T3K
- Also support Qwen2.5-VL-3B on N150 and N300

### PR DESCRIPTION
**Pull request by gwangTT**
### Ticket
[#18640](https://github.com/tenstorrent/tt-metal/issues/18640)
#24273 

### Problem description
Bring up Qwen 2.5 VL models for multimodal processing. Target is `Qwen2.5-VL-72B` on T3K but may bring up smaller models on the way (including `Qwen2.5-VL-3B` on N150/N300 and `Qwen2.5-VL-32B` on T3K)

Aim is to add multi-image support, no need to add frontend support for video at this time.

### What's changed
@yieldthought got the code into its first working shape ("0 to 60" as the saying goes). His commits and some of my early commits (the history is preserved [here](https://github.com/tenstorrent/tt-metal/pull/21752)) were squashed into [0e002fc](https://github.com/tenstorrent/tt-metal/pull/24236/commits/0e002fc1d033a91e8fe6549bf4fe5e45f0c9bd54) to help make the rebasing smoother (all the commits after that one is to fix issues from the rebasing -- notably, one issue of hung execution and one issue of garbage output in repeated batchs -- both are tough to debug). The downside to the smoother rebasing is that the commit history in this PR does not show Mark's large contribution to Qwen2.5-VL. So, I want to explicitly shout out to Mark: thank you for getting us to the first working version of Qwen2.5-VL and thank you for helping me along the way since then! 

There is a big architectural difference from Qwen2.5-VL to Llama multi-modal models:
- Qwen2.5-VL's vision model processes the image pixels into tokens that are mixed with the text-prompt tokens; then the mixture of such tokens are processed by the text model
- Llama multi-modal models are based on cross-attention mechanism (see this [article](https://j-qi.medium.com/inside-mllama-3-2-understanding-metas-vision-language-model-architecture-ae12ad24dcbf) for a detailed explanation)

One interesting challenge that stems from this image-text token mixture is that the positional embedding of each user's prompts can differ and must be computed and passed to the text model on a per-user basis. 

Both of the above (the arch diff and the positional embedding diff) required significant changes from the expected use of tt_transformer, which resulted in separate code for certain modules from tt_transformers. Though it is tempting to combine the code into tt_transformer through `if-else` conditionals, I choose to keep them separate for now until our work towards a clean tt_transformer library is soon underway.

CI tests are added to cover key demo test cases and key unit tests. 

As part of this PR, the obsolete `models/demos/qwen` is removed.

### What is next

Performance optimization of the model (specially the vision model) is out of the scope of this PR and is coming in the future in a separate PR. Progress is tracked by #24274.

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
  - https://github.com/tenstorrent/tt-metal/actions/runs/16652319482
- [x] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
  - https://github.com/tenstorrent/tt-metal/actions/runs/16652326131 --> errors are unrelated to this PR
- [x] ~~(bonus) T3K demo tests: https://github.com/tenstorrent/tt-metal/actions/runs/16658274266~~
  - skipping this due to extremely slow T3K CI pipelines; the last time I ran T3K pipeline, there was a single error with trace region, I fixed that already.
- [x] New/Existing tests provide coverage for changes
  - see: https://github.com/tenstorrent/tt-metal/pull/24236#issuecomment-3014032730

### CODE REVIEW

**Comment by gwangTT** [comment]
This PR is almost ready for review. I will open it up for reviews after:
- [x] I will rebase onto a more recent commit of `main` --> rebased on [v0.60.0-rc6](https://github.com/tenstorrent/tt-metal/tree/v0.60.0-rc6)

The reviews could go in parallel with:
- [x] add missing unit tests to the CI and have some successful runs in CI --> see: https://github.com/tenstorrent/tt-metal/pull/24236#issuecomment-3014032730

I have run all the CI tests on IRD machines but there are CI infra related work such as generating the weights' cache that can go in parallel with the reviews.

File: ttnn/cpp/ttnn/operations/normalization/layernorm/device/layernorm_op.cpp [hunk 1]
```diff
@@ -57,7 +57,12 @@ void LayerNorm::validate(
             TT_FATAL(
                 (gamma.value().padded_shape()[-1] == TILE_WIDTH &&
                  gamma.value().physical_volume() / TILE_WIDTH == a.padded_shape()[-1] / TILE_WIDTH),
-                "Error");
+                "Error with gamma.value().padded_shape(): {}, TILE_WIDTH: {}, gamma.value().physical_volume(): {}, "
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/normalization/layernorm/device/layernorm_op.cpp]: Please prepend a little more info:
"Gamma's last padded dim needs to equal tile width and gamma's volume needs to align with last padded dim of input. Error with ...

File: ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_2d_program_factory.cpp [hunk 2]
```diff
@@ -1454,7 +1454,7 @@ tt::tt_metal::operation::ProgramWithCallbacks matmul_multi_core_reuse_mcast_2d_o
     // TODO: Move these validates to op validate and properly check for this
     TT_FATAL(
         num_blocks_x <= num_cores_x,
-        "Num output blocks along x {} must be smaller than or equal to the number of columns in compute grid {}!",
+        "Num output blocks along x: {} must be smaller than or equal to the number of columns in compute grid: {}!",
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_2d_program_factory.cpp]: Instead of using `:` please put in parenthesis or surround by commas.
```
along x, {}, must
grid, {}!",
```
or
```
along x ({}) must
grid ({})!",
```

File: models/demos/qwen25_vl/compare.py [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+    if torch.all(torch.isnan(golden)) or torch.all(torch.isnan(calculated)):
+        logger.error("One tensor is all nan, the other is not.")
+        return False, 0.0
+
+    # Test if either is completely zero
+    if torch.any(golden.bool()) != torch.any(calculated.bool()):
+        logger.error("One tensor is all zero")
+        return False, 0.0
+
+    # For now, mask all infs and nans so that we check the rest... TODO
```
Comment (bbradelTT) [inline models/demos/qwen25_vl/compare.py]: New TODOs should have issue numbers. Otherwise chances are the work won't be tracked and won't happen.

**Comment by gwangTT** [comment]
Running the pipelines now to generate the weight caches for Qwen25-VL models (3B, 32B, 72B):
- [x] single card: https://github.com/tenstorrent/tt-metal/actions/runs/16029620808
- [x] t3k: https://github.com/tenstorrent/tt-metal/actions/runs/16034682576

Will revert the commits that help along the cache creation ([7dcab76](https://github.com/tenstorrent/tt-metal/pull/24236/commits/7dcab7641afca077e78125ea2aa3d84ab7711c3a), [fb9726f](https://github.com/tenstorrent/tt-metal/pull/24236/commits/fb9726f97bdf3b31ab88d7c4f8f910485b4831eb)) when caches are in place.
- [x] [6e2ad19](https://github.com/tenstorrent/tt-metal/pull/24236/commits/6e2ad1991e6f64e15b5483ae85c95e8fb68d7567) reverts [7dcab76](https://github.com/tenstorrent/tt-metal/pull/24236/commits/7dcab7641afca077e78125ea2aa3d84ab7711c3a)
- [x] [6e2ad19](https://github.com/tenstorrent/tt-metal/pull/24236/commits/6e2ad1991e6f64e15b5483ae85c95e8fb68d7567) reverts [fb9726f](https://github.com/tenstorrent/tt-metal/pull/24236/commits/fb9726f97bdf3b31ab88d7c4f8f910485b4831eb)

**Review by yieldthought — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/normalization/layernorm/device/layernorm_op.cpp (hunk 1 above)
Comment (gwangTT) [reply ttnn/cpp/ttnn/operations/normalization/layernorm/device/layernorm_op.cpp]: 5b06cd298a537e58fbe04aa3c3eae59dffe90861

File: ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_2d_program_factory.cpp (hunk 2 above)
Comment (gwangTT) [reply ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_2d_program_factory.cpp]: 51be1e4fc8e719ebff3e4c0c249dce83804c6f0b

File: models/demos/qwen25_vl/compare.py (hunk 3 above)
Comment (gwangTT) [reply models/demos/qwen25_vl/compare.py]: 57856a2f2da4982d46b417665f0f551ca199f2af

**Review by bbradelTT — APPROVED** [review]

**Review by llongTT — APPROVED** [review]

**Review by cglagovichTT — APPROVED** [review]

File: .github/workflows/single-card-demo-tests-impl.yaml [hunk 4]
```diff
@@ -86,6 +86,7 @@ jobs:
           #          { name: "yolov7", runner-label: "N300", performance: false, cmd: run_yolov7_demo, owner_id: U056BK5U81E}, # Dalar Vartanians
           #          # Moved to t3k tests until OOM on single card runners resolved
                     # { name: "qwen7b", runner-label: "N300", performance: false, cmd: run_qwen7b_func, owner_id: U03PUAKE719}, # Mark O'Connor
+                    { name: "qwen25_vl", runner-label: "N300", performance: true, cmd: run_qwen25_vl_func, owner_id: U07RY6B5FLJ},  #Gongyu Wang
```
Comment (williamlyTT) [inline .github/workflows/single-card-demo-tests-impl.yaml]: Set `performance: false` if running func tests

File: tests/scripts/single_card/run_single_card_demo_tests.sh [hunk 5]
```diff
@@ -21,6 +21,36 @@ run_qwen7b_func() {
...
+  # todo)) Qwen2.5-VL-7B-Instruct
+
+  # simple generation-accuracy tests for qwen25_vl_3b
+  MESH_DEVICE=N300 HF_MODEL=$qwen25_vl_3b WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest -n auto models/demos/qwen25_vl/demo/combined.py -k tt_vision --timeout 600 || fail=1
+  echo "LOG_METAL: demo/combined.py tests for $qwen25_vl_3b on N300 completed"
+
+  # complete demo tests
+  for qwen_dir in "$qwen25_vl_3b"; do
+    MESH_DEVICE=N150 HF_MODEL=$qwen_dir WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest -n auto models/demos/qwen25_vl/demo/demo.py --timeout 600 || fail=1
+    echo "LOG_METAL: Tests for $qwen_dir on N150 completed"
```
Comment (williamlyTT) [inline tests/scripts/single_card/run_single_card_demo_tests.sh]: In `.github/workflows/single-card-demo-tests-impl.yaml` the test only runs on N300, are these n150 lines needed?

**Review by skhorasganiTT — APPROVED** [review]

**Review by williamlyTT — APPROVED** [review]

File: tests/scripts/single_card/run_single_card_demo_tests.sh (hunk 5 above)
Comment (gwangTT) [reply tests/scripts/single_card/run_single_card_demo_tests.sh]: We could remove them; the lost coverage on N150 may be quite small and are already there by many other tests in the CI.

File: .github/workflows/single-card-demo-tests-impl.yaml (hunk 4 above)
Comment (gwangTT) [reply .github/workflows/single-card-demo-tests-impl.yaml]: c4031656e0b5eecb274f43a44f003c8c2393aa92

File: tests/scripts/single_card/run_single_card_demo_tests.sh (hunk 5 above)
Comment (gwangTT) [reply tests/scripts/single_card/run_single_card_demo_tests.sh]: 63f419ffeb99dce82dbf8a224efb483d04e93295

**Comment by ntarafdar** [comment]
@gwangTT can you point us to any CCL changes , sorry this is a big PR and need a bit of help to find where we should look exactly. 
FYI @grechsteinerTT

**Comment by gwangTT** [comment]
> @gwangTT can you point us to any CCL changes , sorry this is a big PR and need a bit of help to find where we should look exactly. FYI @grechsteinerTT

Sure can. Grayson file [this issue]( https://github.com/tenstorrent/tt-metal/issues/26024) to help us keep track of the work. I will get to that after I fought the moving target battle of this PR.

**Comment by gwangTT** [comment]
Encountered an issue while merging in the latest from `main`. The issue is filed here: #26044. Will continue the work here after that issue is addressed.

**Comment by gwangTT** [comment]
> Encountered an issue while merging in the latest from `main`. The issue is filed here: #26044. Will continue the work here after that issue is addressed.

Thanks, @sminakov-tt, for the quick fix. I cherry-picked the commit here to kick off testing.
