### PR TITLE
Fix inf/nan checks in unary operations

### LINKED ISSUE #27993: isnan doesn't return expected output
### Describe the bug

```
**Input A:**
tensor([[   nan, 0.5312, 0.0703, 0.9258],
        [0.0078,    inf,   -inf, 0.6016]], dtype=torch.bfloat16)

**Torch isnan result:**
tensor([[ True, False, False, False],
        [False, False, False, False]])

**TTNN isnan result:**
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.bfloat16)
```

### Steps to reproduce the issue

```
import torch
import ttnn

device_id = 0
device = ttnn.open_device(device_id=device_id)

torch_a = torch.rand([2, 4], dtype=torch.bfloat16)
torch_a[0, 0] = float('nan')
torch_a[1, 1] = float('inf')
torch_a[1, 2] = float('-inf')

# Convert to TTNN tensor
a = ttnn.from_torch(torch_a, layout=ttnn.TILE_LAYOUT, device=device)

# Run isinf
output = ttnn.isnan(a)

# Convert layout and bring back to torch
output = ttnn.to_layout(output, ttnn.ROW_MAJOR_LAYOUT)
output_torch = output.cpu().to_torch()

# Reference torch
torch_output = torch.isnan(torch_a)

print("Input A:")
print(torch_a)

print("\nTorch isnan result:")
print(torch_output)

print("\nTTNN isnan result:")
print(output_torch)

ttnn.close_device(device)
```

### Expected behavior

When the input tensor contains "nan" the output should have True or 1. 

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by Aswinmcw**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/27993
https://github.com/tenstorrent/tt-metal/issues/27994

### Problem description
+/-inf, nan check is not working properly

### What's changed
Fix the issue by using exponent and mantissa extraction

exponent will be 128 for +/- inf and mantissa will be 0, if !=0, then it is nan

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml) CI passes (if applicable)
- [ ] [Galaxy demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h [hunk 1]
```diff
@@ -35,12 +35,13 @@ template <bool APPROXIMATION_MODE, int ITERATIONS>
 inline void calculate_isinf() {
     // SFPU microcode
     for (int d = 0; d < ITERATIONS; d++) {
-        vFloat v = dst_reg[0];
-        v_if(v == std::numeric_limits<float>::infinity() || v == -std::numeric_limits<float>::infinity()) { v = 1.0f; }
-        v_else { v = 0.0f; }
+        vFloat in = dst_reg[0];
+        sfpi::vInt exp = sfpi::exexp(in);
+        sfpi::vInt man = sfpi::exman9(in);
+        vFloat out = 0.0f;
```
Comment (VirdhatchaniKN) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: sfpi::vConst0 ?

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h [hunk 2]
```diff
@@ -35,12 +35,13 @@ template <bool APPROXIMATION_MODE, int ITERATIONS>
...
+        v_if(exp == 128 && man == 0) { out = 1.0f; }
```
Comment (VirdhatchaniKN) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: sfpi::vConst1

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h [hunk 3]
```diff
@@ -49,11 +50,13 @@ template <bool APPROXIMATION_MODE, int ITERATIONS>
...
     // SFPU microcode
     for (int d = 0; d < ITERATIONS; d++) {
-        vFloat v = dst_reg[0];
-        v_if(v == std::numeric_limits<float>::infinity()) { v = 1.0f; }
-        v_else { v = 0.0f; }
+        vFloat in = dst_reg[0];
+        sfpi::vInt exp = sfpi::exexp(in);
+        sfpi::vInt man = sfpi::exman9(in);
+        vFloat out = 0.0f;
+        v_if(in > 0 && exp == 128 && man == 0) { out = 1.0f; }
```
Comment (VirdhatchaniKN) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: sfpi::vConst1 ?

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h [hunk 4]
```diff
@@ -49,11 +50,13 @@ template <bool APPROXIMATION_MODE, int ITERATIONS>
 inline void calculate_isposinf() {
     // SFPU microcode
     for (int d = 0; d < ITERATIONS; d++) {
-        vFloat v = dst_reg[0];
-        v_if(v == std::numeric_limits<float>::infinity()) { v = 1.0f; }
-        v_else { v = 0.0f; }
+        vFloat in = dst_reg[0];
+        sfpi::vInt exp = sfpi::exexp(in);
+        sfpi::vInt man = sfpi::exman9(in);
+        vFloat out = 0.0f;
```
Comment (VirdhatchaniKN) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: sfpi::vConst0 ?

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h [hunk 5]
```diff
@@ -62,11 +65,13 @@ template <bool APPROXIMATION_MODE, int ITERATIONS>
 inline void calculate_isneginf() {
     // SFPU microcode
     for (int d = 0; d < ITERATIONS; d++) {
-        vFloat v = dst_reg[0];
-        v_if(v == -std::numeric_limits<float>::infinity()) { v = 1.0f; }
-        v_else { v = 0.0f; }
+        vFloat in = dst_reg[0];
+        sfpi::vInt exp = sfpi::exexp(in);
+        sfpi::vInt man = sfpi::exman9(in);
+        vFloat out = 0.0f;
```
Comment (VirdhatchaniKN) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: Same here and for WH as well

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h [hunk 6]
```diff
@@ -62,11 +65,13 @@ template <bool APPROXIMATION_MODE, int ITERATIONS>
...
+        v_if(in < 0 && exp == 128 && man == 0) { out = 1.0f; }
```
Comment (VirdhatchaniKN) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: Same here and for WH as well

**Review by VirdhatchaniKN — CHANGES_REQUESTED** [review]

**Review by VirdhatchaniKN — APPROVED** [review]

**Review by mcw-anasuya — APPROVED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h [hunk 7]
```diff
@@ -49,11 +50,13 @@ template <bool APPROXIMATION_MODE, int ITERATIONS>
...
     // SFPU microcode
     for (int d = 0; d < ITERATIONS; d++) {
-        vFloat v = dst_reg[0];
-        v_if(v == std::numeric_limits<float>::infinity()) { v = 1.0f; }
-        v_else { v = 0.0f; }
+        vFloat in = dst_reg[0];
+        sfpi::vInt exp = sfpi::exexp(in);
+        sfpi::vInt man = sfpi::exman9(in);
+        vFloat out = sfpi::vConst0;
+        v_if(in > 0 && exp == 128 && man == 0) { out = sfpi::vConst1; }
```
Comment (ncvetkovicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: Just to check,`in>0` will check only for the sign bit? Wondering if there's an optimized way of checking this.

**Review by ncvetkovicTT — COMMENTED** [review]
Seems good. Could you please add an explanation of the condition in the comment of the function? Smth like:
```
/* Checks if the sign bit of the floating point number in DEST 
is negative. Checks if the exponent is 128 and mantissa is 0. 
If all of the three conditions are met, the number is marked as 
negative infinity, so '1' is written in the location of the DEST 
where the number was stored. Otherwise, `0` is written instead 
of the number.
*/
inline void calculate_isneginf() {
```

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h (hunk 7 above)
Comment (Aswinmcw) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: Yes that's to check if it is + inf or - inf, is there a way to get the signbit directly? I don't find any, something like exsgnbit?

Comment (ncvetkovicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: @amahmudTT do you know any way? I am not sure how the compiler will translate this.

Comment (Aswinmcw) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: @ncvetkovicTT i found a way to get the signbit to check +/- inf, PTAL

Comment (ncvetkovicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_isinf_isnan.h]: Ddi, thanks. I think that extracting the sign bit is more in line with how we check the mantissa and the exponent. Will approve.

**Review by ncvetkovicTT — APPROVED** [review]
lgtm, thanks!

**Review by dchenTT — APPROVED** [review]

**Comment by cmaryanTT** [comment]
Can you please document the perf impact of these changes

**Comment by Aswinmcw** [comment]
Perf for ttnn.isposinf with tensor mixed with [float("-inf"), float("inf"), float("nan"), 5.0, -5.0, 0.0, -0.0, 1e38, 1e-45]
32x32 : 2075.00 ns
1024x1024 : 25735.00 ns
Existing non working version:
32x32 : 1892.00 ns
1024x1024 : 25929.00 ns
cc. @cmaryanTT
