### PR TITLE
MGD Auto Discovery When MGD not provided

### LINKED ISSUE #32833: Add proper handling for multiple devices without ethernet connection
# Add proper handling for multiple devices without ethernet connection or custom topology auto-detect

## Description

When multiple devices (N300, P300, Blackhole, etc.) are present in a system but not connected via ethernet, attempting to open a single device results in either a segmentation fault or a fatal error. This issue affects users who have multiple devices installed but want to use them independently or in separate processes.

## Problem

The system currently auto-detects multiple devices and assumes they form a mesh topology (e.g., `n300_2x2_mesh_graph_descriptor.textproto`), which requires ethernet connectivity. When devices are not connected via ethernet, control plane initialization fails because it expects a full mesh cluster.

### Error Messages

**Error 1: Fatal assertion**
```
TT_FATAL: Physical chip id 0 not found in control plane chip mapping. 
You are calling for a chip outside of the fabric cluster. 
Check that your mesh graph descriptor specifies the correct topology
```

**Error 2: Segmentation fault**
```
Segmentation fault (core dumped)
```
Stack trace shows failure in control plane initialization:
- `ControlPlane::get_mesh_physical_chip_ids`
- `ControlPlane::get_logical_chip_to_physical_chip_mapping`
- `ControlPlane::init_control_plane`

## Affected Systems

- **N300**: 2x N300 cards without ethernet connection
- **P300**: 2x P300 cards without ethernet connection  
- **Blackhole**: 2x Blackhole devices without ethernet connection
- Potentially affects any multi-chip system where devices are not connected via ethernet

## Root Cause

1. **Auto-detection assumes mesh topology**: When multiple devices of the same type are detected, the system automatically configures them as a mesh cluster (e.g., `N300_2x2`), as defined in `tt_metal/fabric/mesh_graph.cpp:49-82`.

2. **Control plane requires full cluster**: Control plane initialization expects all devices in the detected mesh to be accessible via ethernet. When devices are not connected, the control plane cannot map physical chip IDs correctly.

3. **No fallback for independent devices**: The system lacks logic to detect when devices should be treated as independent units rather than a mesh cluster.

## Current Workaround

Users can work around this by using `TT_VISIBLE_DEVICES` to limit device visibility:

```bash
# Use only device 0
TT_VISIBLE_DEVICES=0 python script.py

# Use only device 1 in a separate process
TT_VISIBLE_DEVICES=1 python script.py
```

**Limitations of workaround:**
- Requires users to manually specify which device to use
- Users may need to specify different cache directories for separate processes
- Not a customer-friendly solution
- Does not address the underlying architectural issue

## Related Issues

- #29111: Segmentation fault with two Blackhole devices
- #29145: Similar segfault when opening device 0 on multi-chip systems

## Expected Behavior

1. **Auto-detect device connectivity**: The system should detect whether devices are connected via ethernet before assuming mesh topology.

2. **Support independent device operation**: When devices are not connected via ethernet, the system should allow opening individual devices without requiring mesh initialization.

3. **Graceful fallback**: If mesh topology is detected but ethernet connectivity is missing, the system should either:
   - Automatically fall back to independent device mode
   - Provide a clear error message explaining the configuration issue
   - Allow explicit configuration override

4. **Custom topology support**: The system should support custom topologies that don't match preset configurations in `mesh_graph.cpp`.

## Proposed Solution

1. **Enhanced device discovery**: 
   - Detect ethernet connectivity between devices during discovery
   - Distinguish between "mesh-capable" and "independent" device configurations

2. **Control plane initialization logic**:
   - Only initialize mesh control plane when ethernet connectivity is confirmed
   - Support control plane initialization for independent devices without mesh assumptions

3. **Configuration detection**:
   - Add logic to detect device configurations outside preset mesh configurations
   - Allow runtime configuration to specify device topology (mesh vs. independent)

4. **Error handling**:
   - Provide clear error messages when mesh topology is expected but ethernet is missing
   - Guide users on how to configure their system correctly

## Technical Details

The issue occurs during control plane initialization in `tt_metal/fabric/control_plane.cpp`. The control plane attempts to map logical chips to physical chips based on the detected mesh topology, but fails when devices are not actually connected via ethernet.

Key code locations:
- `tt_metal/fabric/mesh_graph.cpp:49-82`: Mesh graph descriptor mapping
- `tt_metal/fabric/control_plane.cpp`: Control plane initialization
- `tt_metal/distributed/mesh_device.cpp`: Mesh device creation logic

## Priority

**High** - This affects users with multiple devices who want to use them independently. The current workaround is not customer-friendly and limits usability.

## Additional Context

Previously, this may have worked because the second device was being masked out during control plane initialization. Recent changes to physical system discovery infrastructure now require seeing the whole cluster, which exposed this limitation.

### PR DESCRIPTION
**Pull request by Riddy21**
### Ticket

- https://github.com/tenstorrent/tt-metal/issues/32833
- https://github.com/tenstorrent/tt-metal/issues/32990

### Problem description

When multiple devices (N300, P300, Blackhole, etc.) are present in a system but not connected via ethernet, attempting to open a device results in either a segmentation fault or a fatal error. The system previously auto-detected multiple devices and assumed they formed a mesh topology (e.g., `n300_2x2_mesh_graph_descriptor.textproto`), which requires ethernet connectivity. When devices are not connected via ethernet, control plane initialization fails because it expects a full mesh cluster that doesn't match the actual physical topology.

### What's changed

Implemented auto-discovery based mesh graph generation that adapts to the actual physical topology instead of assuming preset mesh configurations. The system now:

1. **Auto-discovers physical connectivity**: Uses `PhysicalSystemDescriptor` to discover the actual ethernet connections (or lack thereof) between devices during initialization.

2. **Dynamic mesh shape matching**: `MeshGraph::generate_from_physical_system_descriptor()` builds a physical adjacency matrix from discovered hardware and tries different mesh shapes to find one that matches the actual connectivity. When devices aren't connected via ethernet, it finds a compatible mesh shape (e.g., independent 1x1 meshes) rather than assuming a connected mesh.

3. **Topology-aware control plane initialization**: The control plane now uses auto-discovery by default when no custom mesh graph descriptor is provided, allowing it to handle both connected and disconnected device configurations gracefully.

This eliminates the need for ClusterType classification and MGD assignment, users no longer need to manually set `TT_VISIBLE_DEVICES` as a workaround and enables independent operation of multiple devices without ethernet interconnects.

### Checklist
- [x] [APC](https://github.com/tenstorrent/tt-metal/actions/runs/19744398892)
- [x] [BH](https://github.com/tenstorrent/tt-metal/actions/runs/19744442340)
- [x] [T3K](https://github.com/tenstorrent/tt-metal/actions/runs/19744453444)
- [x] [Galaxy](https://github.com/tenstorrent/tt-metal/actions/runs/19744490427)

### CODE REVIEW

File: tt_metal/impl/context/metal_context.cpp [hunk 1]
```diff
@@ -634,24 +651,10 @@ void MetalContext::initialize_control_plane() {
...
-    TT_FATAL(!mesh_graph_desc_path.empty(), "No mesh graph descriptor found for cluster type");
-    TT_FATAL(
-        std::filesystem::exists(mesh_graph_desc_path),
-        "Mesh graph descriptor file not found: {}",
-        mesh_graph_desc_path.string());
+    // If no custom mesh graph descrriptor use auto discovery to generate mesh graph
+    log_info(tt::LogDistributed, "Using auto discovery to generate mesh graph.");
 
-    this->construct_control_plane(mesh_graph_desc_path);
+    this->construct_control_plane();
```
Comment (Riddy21) [inline tt_metal/impl/context/metal_context.cpp:750]: Changing control plane flow to auto discover topology

File: tt_metal/fabric/mesh_graph.cpp [hunk 2]
```diff
@@ -773,43 +758,266 @@ const MeshContainer<MeshHostRankId>& MeshGraph::get_host_ranks(MeshId mesh_id) c
...
+    }
+
+    // Append all 1D shapes at the end
+    mesh_shapes_to_try.insert(mesh_shapes_to_try.end(), one_d_shapes.begin(), one_d_shapes.end());
+
+    return mesh_shapes_to_try;
+}
+
+MeshGraph MeshGraph::generate_from_physical_system_descriptor(
+    const tt::tt_metal::PhysicalSystemDescriptor& physical_system_descriptor, FabricConfig fabric_config) {
```
Comment (Riddy21) [inline tt_metal/fabric/mesh_graph.cpp]: Auto detection algorithm:

1. Discover the current physical topology
2. Generate list of possible logical topologies from largest to smallest
3. Try topology mapping for each until valid is found
4. Mesh Graph is generated from topology

File: tt_metal/api/tt-metalium/experimental/fabric/topology_mapper.hpp [hunk 3]
```diff
@@ -262,6 +262,35 @@ class TopologyMapper {
...
+     * neighbors from the physical system descriptor and filters them to only include neighbors that are also part of
+     * the same mesh. The resulting map contains ASIC IDs mapped to their vectors of adjacent ASIC IDs within the mesh.
+     *
+     * @param physical_system_descriptor Reference to the physical system descriptor containing ASIC topology
+     * @param asic_id_to_mesh_rank Mapping of mesh IDs to ASIC IDs to mesh host ranks
+     * @return std::map<MeshId, PhysicalAdjacencyMap> Map from mesh ID to physical adjacency map
+     */
+    static std::map<MeshId, PhysicalAdjacencyMap> build_adjacency_map_physical(
+        const tt::tt_metal::PhysicalSystemDescriptor& physical_system_descriptor,
+        const std::map<MeshId, std::map<tt::tt_metal::AsicID, MeshHostRankId>>& asic_id_to_mesh_rank);
```
Comment (Riddy21) [inline tt_metal/api/tt-metalium/experimental/fabric/topology_mapper.hpp]: @cfjchu I'm exposing the logical and physical adjacency map building functions as static public functions you can use as well. FYI for Fabric Manager

File: tt_metal/fabric/mesh_graph.cpp [hunk 4]
```diff
@@ -773,43 +758,266 @@ const MeshContainer<MeshHostRankId>& MeshGraph::get_host_ranks(MeshId mesh_id) c
...
+                    // Avoid duplicates by checking if this shape is already in one_d_shapes
+                    if (std::find(one_d_shapes.begin(), one_d_shapes.end(), shape) == one_d_shapes.end()) {
+                        one_d_shapes.push_back(shape);
+                    }
+                } else {
+                    // Avoid duplicates by checking if this shape is already in mesh_shapes_to_try
+                    if (std::find(mesh_shapes_to_try.begin(), mesh_shapes_to_try.end(), shape) ==
+                        mesh_shapes_to_try.end()) {
+                        mesh_shapes_to_try.push_back(shape);
+                    }
```
[the remark this answers is not in the document]
Comment (Riddy21) [reply tt_metal/fabric/mesh_graph.cpp]: Not big enough to cause issues

**Comment by Riddy21** [comment]
@cfjchu @TT-BrianLiu @sjameelTT @aliuTT 

I noticed that our TT-metal t3k 2x4 mesh device tests are hard coded specifically to expect a 2x4 (vs 4x2) mesh shape. I believe this applies to Galaxy and BH devices as well. 

With some of the new Topology Mapper auto discovery, when I change the MGD to supply a 4x2 MGD instead I some tests which fail: https://github.com/tenstorrent/tt-metal/actions/runs/19744453444/job/56644693345. And if I change the convention to (small dim, large dim) other tests from other configs might fail.

Wondering if there is a specific reasoning to 2x4 vs 4x2, is there a rule to this convention so I can follow it? (edited)

**Review by jbaumanTT — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

File: tests/scripts/run_cpp_fabric_tests.sh [hunk 5]
```diff
@@ -55,13 +58,6 @@ tt-run --mock-cluster-rank-binding tests/tt_metal/tt_fabric/custom_mock_cluster_
...
-tt-run --mock-cluster-rank-binding tests/tt_metal/tt_fabric/custom_mock_cluster_descriptors/t3k_2x2_cluster_desc_mapping.yaml --rank-binding tests/tt_metal/distributed/config/2x2_multiprocess_rank_bindings.yaml --mpi-args "--mca btl self,tcp --mca btl_tcp_if_include eth0 --tag-output --allow-run-as-root" ./build/test/tt_metal/tt_fabric/fabric_unit_tests  --gtest_filter="MultiHost.TestSplit2x2Fabric1DSanity"
-tt-run --mock-cluster-rank-binding tests/tt_metal/tt_fabric/custom_mock_cluster_descriptors/t3k_2x2_cluster_desc_mapping.yaml --rank-binding tests/tt_metal/distributed/config/2x2_multiprocess_rank_bindings.yaml --mpi-args "--mca btl self,tcp --mca btl_tcp_if_include eth0 --tag-output --allow-run-as-root" ./build/test/tt_metal/tt_fabric/fabric_unit_tests  --gtest_filter="MultiHost.TestSplit2x2Fabric2DSanity"
-
```
Comment (Riddy21) [inline tests/scripts/run_cpp_fabric_tests.sh:64]: Removing t3k mock tests because these are generally stable and covered by other control plane init tests and t3k unit tests

Comment (Riddy21) [reply tests/scripts/run_cpp_fabric_tests.sh:64]: @cfjchu @aliuTT @tt-asaigal

File: tt_metal/fabric/mesh_graph.cpp
Comment (Riddy21) [inline tt_metal/fabric/mesh_graph.cpp:1]: Added 2 functions:

1. to build MG from mesh shape only, no need for MGD.

2. Another function to try topology mapping the biggest uniform mesh to the physical system

File: tt_metal/fabric/control_plane.cpp [hunk 6]
```diff
@@ -517,6 +517,49 @@ void ControlPlane::init_control_plane(
     this->mesh_graph_->print_connectivity();
 }
 
+void ControlPlane::init_control_plane_auto_discovery() {
```
Comment (Riddy21) [inline tt_metal/fabric/control_plane.cpp:520]: Control plane constructor helper without MGD provided

File: tt_metal/fabric/mesh_graph.cpp [hunk 7]
```diff
@@ -29,7 +38,34 @@ std::size_t std::hash<tt::tt_fabric::port_id_t>::operator()(const tt::tt_fabric:
...
+ * @brief Determines the maximum number of local Ethernet connections per direction between ASICs in the system.
+ *
+ * For each ASIC in the provided PhysicalSystemDescriptor, this function examines all neighboring ASICs and counts
+ * the number of Ethernet connections to each neighbor that are marked as local (i.e., connection.is_local is true).
+ * It returns the maximum number of such local connections found in any direction for any ASIC.
+ *
+ * @param psd The PhysicalSystemDescriptor representing the system's ASICs and their interconnections.
+ * @return The maximum number of local Ethernet connections per direction between any two ASICs.
+ */
+std::uint32_t get_num_connections_per_direction(const tt::tt_metal::PhysicalSystemDescriptor& psd) {
```
Comment (Riddy21) [inline tt_metal/fabric/mesh_graph.cpp]: anonymous helper function

File: tt_metal/fabric/control_plane.cpp [hunk 8]
```diff
@@ -517,6 +517,49 @@ void ControlPlane::init_control_plane(
...
+    auto& cluster = tt::tt_metal::MetalContext::instance().get_cluster();
+    const auto& driver = cluster.get_driver();
+    const auto& distributed_context = tt_metal::distributed::multihost::DistributedContext::get_current_world();
+    const auto& rtoptions = tt::tt_metal::MetalContext::instance().rtoptions();
+    auto fabric_config = tt::tt_metal::MetalContext::instance().get_fabric_config();
+
+    // NOTE: This algorithm is only supported for single host systems for now
+    TT_FATAL(
+        *distributed_context->size() == 1,
+        "Auto discovery is only supported for single host systems, since you are running on a {} host system,"
```
Comment (aliuTT) [inline tt_metal/fabric/control_plane.cpp]: "single process" instead of "host" is more appropriate here

File: tt_metal/fabric/topology_mapper_utils.cpp [hunk 9]
```diff
@@ -923,4 +927,93 @@ TopologyMappingResult map_mesh_to_physical(
...
+                }
+                // Make sure that the neighbor is in the mesh
+                if (mesh_asics.contains(neighbor)) {
+                    // Add each neighbor multiple times based on number of ethernet connections
+                    auto eth_connections = physical_system_descriptor.get_eth_connections(asic_id, neighbor);
+                    for (const auto& eth_connection : eth_connections) {
+                        // NOTE: IGNORE Z channels for Blackhole galaxy in intra mesh connectivity since they are
+                        // not used intra mesh communication on black hole
+                        if (cluster_type == tt::tt_metal::ClusterType::BLACKHOLE_GALAXY &&
+                            (z_channels.contains(eth_connection.src_chan) ||
```
Comment (aliuTT) [inline tt_metal/fabric/topology_mapper_utils.cpp:1000]: This is not true. We can have intramesh links built out of physical Z links

**Review by aliuTT — APPROVED** [review]
