### PR TITLE
#13787: Fix build with CMAKE_DISABLE_PRECOMPILE_HEADERS

### LINKED ISSUE #13787: Build is broken with precompiled headers disabled
Build is broken with precompiled headers disabled

### PR DESCRIPTION
**Pull request by afuller-TT**
### Ticket
closes #13787 
needed for #13698

### Problem description
When building with PCH disabled (set `CMAKE_DISABLE_PRECOMPILE_HEADERS` to True), the build fails because not all files include the headers they use.  They are only accidentally able to resolve certain dependencies.

This is a problem, because the first cut of `ccache` is going to skip PCH.  Also analysis tools (including the compiler) don't process non-included headers.  As evidenced by the one non-include change in this PR that the compiler is now detecting.

### What's changed
* Build with `CMAKE_DISABLE_PRECOMPILE_HEADERS = true`
* Fix failure
* GOTO step 1

### Checklist
- [x] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/11335836891)
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

https://github.com/tenstorrent/tt-metal/actions/runs/11335836891

### CODE REVIEW

File: tt_metal/tt_stl/reflection.hpp [hunk 1]
```diff
@@ -807,6 +807,7 @@ struct get_first_object_of_type_t<std::vector<T>> {
         for (auto& tensor : value) {
             return get_first_object_of_type<object_t>(tensor);
         }
+        throw std::out_of_range("No such element");
```
Comment (afuller-TT) [inline tt_metal/tt_stl/reflection.hpp:810]: Picked something arbitrary to satisfy the compiler's complaint that the f'n may exit without returning a value.  Looking to the owners for context re: are we guarnateed that this will never happen, and can we hint to the compiler as much?  Failing that, what is the desired outcome of this f'n?

**Review by blozano-tt — APPROVED** [review]

**Review by pavlejosipovic — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]

**Comment by tt-rkim** [comment]
@afuller-TT Do you mind putting the issue number with a colon in your final squashed commit message or edit your commits now, as enforced by git hooks?

File: ttnn/cpp/pybind11/events.cpp [hunk 2]
```diff
@@ -5,6 +5,8 @@
 #include "events.hpp"
 
 #include "tt_metal/impl/event/event.hpp"
+#include "pybind11/operators.h"
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/pybind11/events.cpp:8]: not sure this is the right include here. do you know whats missing?

**Review by ayerofieiev-tt — APPROVED** [review]
This is a good change, but we don't run builds w/o PCH on CI. 
This is going to happen again and again. 
If we need to guarantee - we need to have a CI job.

Please don't forget to update PR title

**Review by tt-aho — APPROVED** [review]

**Comment by afuller-TT** [comment]
From @ayerofieiev-tt
> This is a good change, but we don't run builds w/o PCH on CI.
This is going to happen again and again.
If we need to guarantee - we need to have a CI job.

Good call out.  But fear not, the reason I discovered these is precisely because I'm preparing a build that cannot use PCH, so this is a pre-req and shortly after we get this in we'll be having a build that will detect any regression here.

File: ttnn/cpp/pybind11/events.cpp (hunk 2 above)
Comment (afuller-TT) [reply ttnn/cpp/pybind11/events.cpp]: Thanks for looking it over.  Indeed that's the wrong one.  I think I got trigger happy :)

This file was complaining about unable to resolve `py::class_` and `module.def`.  Looks like `pybind11/pybind11.h` is probably the right include.  Updated.

**Comment by afuller-TT** [comment]
I'm going to go ahead and merge this without waiting on the final approvals.  It's had a number of eyes, including on the one code change.  The rest is just #includes.
