### PR TITLE
#6938: Implement softplus as a single kernel

### LINKED ISSUE #6938: Faster softplus needed
Currently, we are getting `0.1 ms` for softplus. We need something around `0.01 ms`. Maybe fusing is needed. It would be helpful if it supported sharded mode as well. 

**To Reproduce**
we are using `ttnn.softplus(delta_t, parameter1=1.0, parameter2=20.0, memory_config=ttnn.L1_MEMORY_CONFIG)`
where `delta_t` is of datatype `ttnn.bfloat16` and of shape `1,1,32,5120`

@kpaigwar @esmalTT

### PR DESCRIPTION
**Pull request by esmalTT**
Convert composite `softplus` operation to a single kernel implementation to improve performance. 

Previously, the composite version of `softplus` took 0.15 ms for an input shape of `(32, 32, 5120)`. After this change, the same input shape now takes approx. 0.01 ms. 

Due to problems with register pressure in the GS implementation of this kernel, we have decided to remove support for that architecture in this PR. Because `mish` uses `softplus` internally, it will also no longer be supported on Grayskull. I will open an issue to track this regression. 

Blocking issues:
- [X] https://github.com/tenstorrent/tt-metal/pull/8398

Closes https://github.com/tenstorrent/tt-metal/issues/6938

### CODE REVIEW

**Review by rtawfik01 — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/unary.hpp [hunk 1]
```diff
@@ -95,16 +94,13 @@ struct Softplus : public EltwiseUnary {
         return detail::input_tensors_to_validate(input_tensor, std::forward<Args>(args)...);
     }
 
-    static Tensor execute(const Tensor& input, const float beta, const float threshold, const std::optional<MemoryConfig>& memory_config_arg = std::nullopt) {
-        auto original_input_shape = input.get_shape();
-        auto input_4D = ttnn::unsqueeze_to_4D(input);
```
Comment (xanderchin) [inline ttnn/cpp/ttnn/operations/unary.hpp:100]: Is unsqueeze and squeeze(reshape) no longer needed with this update? Or were they not necessary prior to this?

**Review by xanderchin — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/unary.hpp (hunk 1 above)
Comment (esmalTT) [reply ttnn/cpp/ttnn/operations/unary.hpp:100]: Unsure about previously, but it is now not necessary because we are just invoking a single EltwiseUnary call.

Comment (xanderchin) [reply ttnn/cpp/ttnn/operations/unary.hpp:100]: @ayerofieiev-tt can you also take a look here? You'd recently ported over from python.

Comment (ayerofieiev-tt) [reply ttnn/cpp/ttnn/operations/unary.hpp:100]: Previously, one of the ops, from which softplus was combined, called for padding and it required 4D tensor.
I am sure this is now not required, which is awesome!

File: tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+#include "ckernel_sfpu_converter.h"
+#include "ckernel_sfpu_exp.h"
+#include "ckernel_sfpu_log.h"
+
+using namespace sfpi;
+
+namespace ckernel {
+namespace sfpu {
+
+template <bool APPROXIMATION_MODE>
```
Comment (ayerofieiev-tt) [inline tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h:18]: Would be fantastic to not carry both grayskull and wormhole versions as in this case they are identical.

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu_types.h
Comment (rtawfik01) [inline tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu_types.h:1]: Add this for GS as well

File: tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.cpp [hunk 3]
```diff
@@ -140,6 +143,16 @@ std::pair<string, string> get_op_init_and_func_parameterized(
         case UnaryOpType::UNARY_NE: op_init_and_name = {"unary_ne_tile_init();", fmt::format("unary_ne_tile({}, {}u);", idst, Converter::to_hex(param0))}; break;
         case UnaryOpType::UNARY_GT: op_init_and_name = {"unary_gt_tile_init();", fmt::format("unary_gt_tile({}, {}u);", idst, Converter::to_hex(param0))}; break;
         case UnaryOpType::UNARY_LT: op_init_and_name = {"unary_lt_tile_init();", fmt::format("unary_lt_tile({}, {}u);", idst, Converter::to_hex(param0))}; break;
+        case UnaryOpType::SOFTPLUS: {
+            TT_ASSERT(params.size() == 2, "Expected softplus to take 2 parameters");
+            float param1 = params[1];
+            op_init_and_name = {"softplus_tile_init();", fmt::format("softplus_tile({}, {}u, {}u, {}u);", idst,
```
Comment (ayerofieiev-tt) [inline tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.cpp:149]: I see it is the way here, but I wonder, why do we bake param values into a string?

**Review by ayerofieiev-tt — APPROVED** [review]
I love it! Thank you! Also, very educational for me

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu_types.h
Comment (esmalTT) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu_types.h:1]: Done

File: tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h (hunk 2 above)
Comment (esmalTT) [reply tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h:18]: While I agree, unfortunately they are subtly different (`_calculate_log_body_<false>(0);`).

File: tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.cpp (hunk 3 above)
Comment (esmalTT) [reply tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.cpp:149]: Not sure since I'm also just looking at this for the first time, but I think it is just a cheap and dirty way to get them in the binary at compile time.

File: tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h (hunk 2 above)
Comment (rtawfik01) [reply tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h:18]: We have separate folders for different devices because ckernel/llk calls differ for devices

File: tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+        a = beta_reciprocal * dst_reg[0];
+
+        dst_reg[0] = a;
+        dst_reg++;
+    }
+}
+
+template <bool APPROXIMATION_MODE>
+sfpi_inline void softplus_init() {}
+
```
Comment (rtawfik01) [inline tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h:45]: You can place the `exp_init<false>();` in the `softplus_init`, since the init values are not going to be rewritten by another init

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+
+using namespace sfpi;
+
+namespace ckernel {
+namespace sfpu {
+
+template <bool APPROXIMATION_MODE>
+inline void calculate_softplus_body(vFloat beta, vFloat beta_reciprocal, vFloat threshold) {
+    vFloat a = dst_reg[0];
+    vFloat a_beta = a * beta;
```
Comment (rtawfik01) [inline tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h:21]: Can you do the same check as grayskull here?
```
        v_if(a >= threshold) {
            dst_reg++;
            return;
        }
        v_endif;
```
It will be more performant than writing back to dst_reg

File: tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+template <bool APPROXIMATION_MODE, int ITERATIONS = 4>
+sfpi_inline void calculate_softplus(uint param0, uint param1, uint param2) {
+    vFloat beta = Converter::to_float(param0);
+    vFloat beta_reciprocal = Converter::to_float(param1);
+    vFloat threshold = Converter::to_float(param2);
+    for (int d = 0; d < ITERATIONS; d++) {
+        vFloat a = dst_reg[0] * beta;
+        v_if(a >= threshold) {
+            dst_reg++;
+            return;
```
Comment (rtawfik01) [inline tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h:27]: The return; needs to be replaced with continue;

**Review by rtawfik01 — CHANGES_REQUESTED** [review]

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h (hunk 5 above)
Comment (esmalTT) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h:21]: As discussed, this does not work as expected because vectors are SIMD.

File: tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h (hunk 6 above)
Comment (esmalTT) [reply tt_metal/hw/ckernels/grayskull/metal/llk_api/llk_sfpu/ckernel_sfpu_softplus.h]: No longer relevant, since GS will not be supported

**Review by TT-BrianLiu — APPROVED** [review]

**Review by rtawfik01 — APPROVED** [review]
