### PR TITLE
#21544: Fix MeshDevice visualization by using device_id instead of de…

### LINKED ISSUE #21544: Removing single device APIs from TTNN broke MeshDevice visualization
### Describe the bug

https://github.com/tenstorrent/tt-metal/pull/21344 removed some single device APIs which broke `ttnn.visualize_mesh_device(mesh_device)`.

### Steps to reproduce the issue

Open `MeshDevice` in any configuration (1x1 is the simplest), and try calling `ttnn.visualize_mesh_device`:
```
mesh_device = ttnn.open_mesh_device(ttnn.MeshShape(1, 1))
ttnn.visualize_mesh_device(mesh_device)
```

```
2025-05-02 02:42:34.247 | ERROR    | ttnn.distributed.distributed:_get_rich_table:61 - Error fetching device from MeshDevice at row 0, col 0: 'ttnn._ttnn.multi_device.MeshDevice' object has no attribute 'get_device'.

  MeshDevice(rows=1, cols=1):
┌──────────────────────────────┐
│            Empty             │
│            (0, 0)            │
│                              │
└──────────────────────────────┘
```

### Expected behavior

Legacy behavior printed the device like this:
```
   MeshDevice(rows=2, cols=4):
┌──────────────────────────────┬──────────────────────────────┬──────────────────────────────┬──────────────────────────────┐
│          Dev. ID: 4          │          Dev. ID: 0          │          Dev. ID: 3          │          Dev. ID: 7          │
│            (0, 0)            │            (0, 1)            │            (0, 2)            │            (0, 3)            │
│                              │                              │                              │                              │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│          Dev. ID: 5          │          Dev. ID: 1          │          Dev. ID: 2          │          Dev. ID: 6          │
│            (1, 0)            │            (1, 1)            │            (1, 2)            │            (1, 3)            │
│                              │                              │                              │                              │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘```

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by tt-dma**
…vice

### Ticket
Link to Github Issue: https://github.com/tenstorrent/tt-metal/issues/21544

### Problem description
We removed single-device APIs from ttnn python but forgot this last usage.

### What's changed
Add a pybind to fetch the device_id instead of device, and use that for MeshDevice visualization

CI: https://github.com/tenstorrent/tt-metal/actions/runs/14801882256

### CODE REVIEW

File: tt_metal/distributed/mesh_device.cpp [hunk 1]
```diff
@@ -389,6 +389,12 @@ IDevice* MeshDevice::get_device(size_t row_idx, size_t col_idx) const {
 
 IDevice* MeshDevice::get_device(const MeshCoordinate& coord) const { return view_->get_device(coord); }
 
+chip_id_t MeshDevice::get_device_id(const MeshCoordinate& coord) const {
+    auto device = get_device(coord);
+    TT_FATAL(device, "Device ID requested for MeshCoord {} not found.", coord);
+    return device->id();
+}
```
Comment (omilyutin-tt) [inline tt_metal/distributed/mesh_device.cpp:396]: Is it better to make it a lambda in pybind file? Avoids increasing the C++ API surface

**Review by omilyutin-tt — APPROVED** [review]
Thanks!

File: tt_metal/distributed/mesh_device.cpp (hunk 1 above)
Comment (tt-dma) [reply tt_metal/distributed/mesh_device.cpp]: Makes sense, going with that
