### PR TITLE
Configure edm builder for dispatch only if there is tunneling

### LINKED ISSUE #25118: 6U model perf regression on Llama 70B TG caused by Enable FD on Fabric for N300 and T3K PR.
[Enable FD on Fabric for N300 and T3K PR](https://github.com/tenstorrent/tt-metal/commit/74cdf6c309e1f0ba03c2000b04857d1b22effa5c) has caused a regression in many ops in the model. The following lists specific ops and regressions:

RMS_0:
From 16,701.6 ns → 17,188.8 ns
Regression: +2.9%

RMS_1:
From 16,336.7 ns → 16,820.1 ns
Regression: +3.0%

AllReduceAsync_DO:
From 13,234.2 ns → 14,440.9 ns
Regression: +9.1%

AllReduceAsync_FF2:
From 13,420.4 ns → 14,575.0 ns
Regression: +8.6%

LlamaReduceScatterCreateHeads:
From 7,971.5 ns → 8,363.3 ns
Regression: +4.9%

AllGatherAsync_Binary_Mult:
From 7,076.4 ns → 7,592.5 ns
Regression: +7.3%

AllGatherConcat:
From 8,390.8 ns → 8,785.2 ns
Regression: +4.7%

ReduceScatter_FF3:
From 7,168.5 ns → 7,492.6 ns
Regression: +4.5%

The commit causing the regression is 74cdf6c309e1f0ba03c2000b04857d1b22effa5c. The output from running the device perf test on this commit and the commit before is provided as reference in the attached files. Provided is also an image of the current perf test failures on latest main (some of these regressions still pass because the margins are too big).

Image

[6u_perf_1a67031f8a8b855f67a956b708ec898973bbe9db.log](https://github.com/user-attachments/files/21240692/6u_perf_1a67031f8a8b855f67a956b708ec898973bbe9db.log)
[6u_perf_74cdf6c309e1f0ba03c2000b04857d1b22effa5c.log](https://github.com/user-attachments/files/21240693/6u_perf_74cdf6c309e1f0ba03c2000b04857d1b22effa5c.log)

### PR DESCRIPTION
**Pull request by nhuang-tt**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/25118)

### Problem description
- Fixes 6U perf regression

### What's changed
- We should only configure the EDM Builder for dispatch only if the device is participating in a dispatch tunnel

Before:
Iteration : 0, Prefill Iteration : 0, tok/s/user : 191.26, Throughput : 6120.28 tok/s, Iteration Time : 5.23 ms
80L T/s/u estimate: 64.58306858713429

After:
Iteration : 0, Prefill Iteration : 0, tok/s/user : 284.32, Throughput : 9098.27 tok/s, Iteration Time : 3.52 ms
80L T/s/u estimate: 66.42449839842752

### Checklist
APC
https://github.com/tenstorrent/tt-metal/actions/runs/16327087096
T3K
https://github.com/tenstorrent/tt-metal/actions/runs/16327090741
T3K Unit
https://github.com/tenstorrent/tt-metal/actions/runs/16328342742
TG
https://github.com/tenstorrent/tt-metal/actions/runs/16327092161
TG Unit
https://github.com/tenstorrent/tt-metal/actions/runs/16328341561

### CODE REVIEW

**Review by mpiseTT — APPROVED** [review]

File: tt_metal/impl/dispatch/topology.cpp [hunk 1]
```diff
@@ -1416,6 +1416,16 @@ void build_tt_fabric_program(
     const auto topology = fabric_context.get_fabric_topology();
     const bool is_2D_routing = topology == Topology::Mesh;
 
+    const auto device_has_dispatch_tunnel = [&]() -> bool {
+        auto mmio_device_id =
```
Comment (jbaumanTT) [inline tt_metal/impl/dispatch/topology.cpp:1420]: Won't non-mmio intermediary devices on 4U have tunnels as well? Or is that a different concept?

Comment (nhuang-tt) [reply tt_metal/impl/dispatch/topology.cpp:1420]: This returns true for 4U. Non-mmio intermediately devices don't have tunnels if I understand this correctly.

On 4U, we have 4 MMIO devices. Each MMIO device has 2 tunnels coming out. And in each tunnel there are 4 devices.

Comment (jbaumanTT) [reply tt_metal/impl/dispatch/topology.cpp:1420]: Ok, fair enough. And the TG tests are passing anyway.

**Review by jbaumanTT — APPROVED** [review]
