### PR TITLE
[EXTERNAL PR] Optimised GCD implementation for int32 using pure SFPU

### LINKED ISSUE #17771: [Bounty $1800] ttnn.gcd doesn't support int32
**Describe the bug**

The [official documentation](https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api/ttnn.gcd.html) states that ttnn.gcd only supports INT32.  However, it's clear from testing that INT32 doesn't work properly.

Testing reveals that floating point inputs work as expected.

Note that the restriction on input values to the range [-1024, 1024] doesn't really make sense.  Looking at the internal implementation, the comments say "limited precision in bfloat16 format decreases support for input to the range [-1024, 1024]".  However, I believe bfloat16 actually has only 7 bits of significand precision.  Maybe the comment was supposed to say "float16"?

In any case, I think the ideal fix would be to add support for int32, and extend the maximum number of iterations to cover the full int32 input range.

**To Reproduce**

```py
import ttnn
import torch

device_id = 0
device = ttnn.open_device(device_id=device_id)
dtype = ttnn.int32

a_torch = torch.tensor([5, 10, 15])
b_torch = torch.tensor([3, 4, 5])
c_torch = torch.gcd(a_torch, b_torch)
print(c_torch)

a: ttnn.Tensor = ttnn.from_torch(a_torch, dtype=dtype, layout=ttnn.TILE_LAYOUT, device=device)
b: ttnn.Tensor = ttnn.from_torch(b_torch, dtype=dtype, layout=ttnn.TILE_LAYOUT, device=device)
c = ttnn.gcd(a, b)
print(c)

ttnn.close_device(device)
```

**Expected behavior**

Output should match PyTorch.

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version: e1a028f72b8dab4291585afebdcc781d14487c61

**Additional context**

```
2025-02-09 10:23:47.195 | INFO     | SiliconDriver   - Opened PCI device 0; KMD version: 1.31.0, IOMMU: disabled
2025-02-09 10:23:47.198 | INFO     | SiliconDriver   - Detected PCI devices: [0]
2025-02-09 10:23:47.198 | INFO     | SiliconDriver   - Using local chip ids: {0} and remote chip ids {1}
2025-02-09 10:23:47.252 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.10.0 (Device 0)
2025-02-09 10:23:47.253 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.10.0 (Device 1)
                  Metal | INFO     | Initializing device 0. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
tensor([1, 2, 5])
                  Metal | WARNING  | Circular buffer indices are not contiguous starting at 0. This will hurt dispatch performance. Non-contiguous indices: 2. First unused index: 1. Kernels: reader_unary_interleaved_start_id
                  Metal | WARNING  | Circular buffer indices are not contiguous starting at 0. This will hurt dispatch performance. Non-contiguous indices: 2. First unused index: 1. Kernels: writer_unary_interleaved_start_id, reader_unary_interleaved_start_id, eltwise_sfpu
ttnn.Tensor([    0,     0,     0], shape=Shape([3]), dtype=DataType::INT32, layout=Layout::TILE)
                  Metal | INFO     | Closing device 0
                  Metal | INFO     | Disabling and clearing program cache on device 0
                 Always | WARNING  | Attempting to push work to Device 0 which is not initialized. Ignoring...
                 Always | WARNING  | Attempting to push work to Device 0 which is not initialized. Ignoring...
                 Always | WARNING  | Attempting to push work to Device 0 which is not initialized. Ignoring...
                 Device | INFO     | Closing user mode device drivers
```

### PR DESCRIPTION
**Pull request by jasondavies**
### Ticket

See #17771.

### Problem description

The original implementation didn't support int32 at all.  It _did_ work for floating point tensors, but only with a limited range (±1024.0).  The use of `ttnn::remainder` made it quite inefficient.

### What's changed

I've implemented the binary GCD algorithm, but with some hand-rolled optimisations due to the lack of CTZ (count trailing zeroes).

My rudimentary benchmarks show a 50x improvement in performance for a `(1024, 1024)` tensor containing random values after initial program cache warmup.  Note that my implementation also works for all signed 32-bit integers, which is a much larger range.  Further optimisations such as SFPU-wide early-out could potentially be applied, though I'm not sure it's worth adding more complexity to the code.

There's also probably a case for writing this in C rather than assembly, but the lack of shift-by-lreg made it complicated and I wasn't sure how to mix C with assembly code.

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by jasondavies** [comment]
Only implemented for wormhole right now.

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gcd.h [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+inline void calculate_sfpu_gcd(const uint dst_offset)
+{
+    // Binary GCD algorithm
+    for (int d = 0; d < ITERATIONS; d++) {
+        constexpr uint dst_tile_size = 64;
+        TTI_SFPLOAD(p_sfpu::LREG0, 4, 3, 0); // a
+        TT_SFPLOAD(p_sfpu::LREG1, 4, 3, dst_offset * dst_tile_size); // b
+        TTI_SFPMOV(0, p_sfpu::LCONST_0, p_sfpu::LREG2, 0); // sa
+        TTI_SFPMOV(0, p_sfpu::LCONST_0, p_sfpu::LREG3, 0); // sb
+        TT_SFPABS(0, p_sfpu::LREG0, p_sfpu::LREG0, 0);
```
Comment (rdjogoTT) [inline tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gcd.h:26]: if all the args to a TT_ instruction are constexprs, you should call it as a TTI_ instruction instead since it is faster

File: tt_metal/include/compute_kernel_api/gcd.h [hunk 2]
```diff
@@ -0,0 +1,27 @@
+// SPDX-FileCopyrightText: © 2024 Tenstorrent Inc.
```
Comment (rdjogoTT) [inline tt_metal/include/compute_kernel_api/gcd.h:1]: might as well put 2025?

File: tt_metal/include/compute_kernel_api/gcd.h [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+#include "llk_math_eltwise_binary_sfpu_gcd.h"
+#define MAIN math_main()
+#define MATH(x) x
+#else
+#define MATH(x)
+#endif
+
+namespace ckernel {
+
+ALWI void gcd_tile(uint32_t idst0, uint32_t idst1) {
```
Comment (rdjogoTT) [inline tt_metal/include/compute_kernel_api/gcd.h:18]: would it be possible to add a comment here like for other similar compute kernel APIs? Mentioning that this is for int32 specifically.

**Comment by jasondavies** [comment]
Some further optimisations bring the time for `gcd_tile` from 51.22μs down to 50μs.

**Comment by jasondavies** [comment]
Is there a good way to see the compiled kernel code e.g. to investigate replay optimisations?

**Review by sjameelTT — COMMENTED** [review]
We're planning on replacing the ttnn::binary implementation with ttnn::experimental::binary_ng as the latter has more thorough broadcasting support. You may want to consider adding some code there. @patrickroberts you may want to keep an eye on this

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gcd.h [hunk 4]
```diff
@@ -0,0 +1,149 @@
+// SPDX-FileCopyrightText: © 2025 Tenstorrent Inc.
```
Comment (dchenTT) [inline tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gcd.h:1]: From other people's code review to my PR, the copyright is 2025 Tenstorrent AI ULC

Comment (jasondavies) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gcd.h:1]: Technically, I'm the copyright holder so I should set this to my own name for all original work, which makes it clear I'm contributing under the specified license.

Probably only makes sense to do this for new files unless anything substantial is added to existing files, in which case I can add another line with my name.  Similarly if Tenstorrent employees modify my files with substantial changes, they can add another line for their copyright information.

**Comment by jasondavies** [comment]
> We're planning on replacing the ttnn::binary implementation with ttnn::experimental::binary_ng

Thanks, I was able to get this working on my unpublished version.  One thing I noticed is a performance regression unrelated to my code: e.g. comparing ttnn.add with ttnn.experimental.add shows 456μs vs 526μs.  I haven't looked in detail but there seem to be small delays in between BINARY_OP zones when profiling binary_ng.  Is this a known/expected issue?

**Comment by jasondavies** [comment]
Can anyone advise on which semaphore could be used to signal from the SFPU to the TRISC-1 compute core?

I tried using `semaphore::MATH_DONE`, which actually worked just fine for long enough computations, but I think I'm doing something wrong as something gets stuck if I reduce the computation size, perhaps indicating a semaphore issue.

```cpp
// increment semaphore counter
semaphore_post(semaphore::MATH_DONE);

// .. issue some SFPU instructions

// SFPU decrements semaphore
t6_semaphore_get(semaphore::MATH_DONE);

// wait for semaphore to hit zero, gets stuck here
while (semaphore_read(semaphore::MATH_DONE) > 0);
```

Unsure if I'm conflicting with use of this semaphore elsewhere, or if there's a better way for the SFPU to indicate "I've finished one iteration and possibly set special values register, please check before deciding whether to issue more SFPU instructions"

**Comment by jasondavies** [comment]
I'm checking `llk_math_get_compute_special_value_flags()` after the above synchronisation point, followed by `llk_math_clear_compute_special_value_flags()`.  I'm also wondering if these special value flags are reliable?

**Comment by ttmtrajkovic** [comment]
@nvelickovicTT, @ncvetkovicTT 
for the question above.

**Comment by jasondavies** [comment]
Thank you.  This is a key question for maximising performance on this (and similar kernels in future).  To give a bit more background:

- I have a sequence of 7 instructions that I need to repeatedly run on the SFPU, until a success condition is achieved on all lanes.  The _average_ number of iterations is around ~23, but the worst case is ~45.
- Obviously, I can just repeat the inner loop 45 times, but this will be ~2x faster if I can signal that all lanes have completed and get TRISC-1 to start issuing instructions to store the results and load the next set of data.
- I've had limited success trying what I mentioned above, which is to trigger special values flags (by inserting an instruction that always generates NaN), then use a semaphore so TRISC-1 waits for the SFPU to possibly set special values.  TRISC-1 then issues more instructions if it sees special values (and clears them).
- This kind of works, but has spurious failures on large test cases.  Looking at special values specifically, I'm not sure how reliable they are as I tried generating Infinity instead of NaN and the flags that get set don't seem consistent (mix of 4, 8, 12).  So it's possible my failures relate to unreliability of these flags?  Or it's due to incorrect use of semaphores?

The main features that I need are:
- A way for the SFPU to signal to the RISC-V core "at least one lane not done" (or all lanes done) based on **lane condition codes**.  Using special value flags seems like a bit of a hack but maybe it's fine if these are reliable.
- A way for the compute RISC-V core to synchronise with the above signal.  There are 3 states: a) SFPU is busy, b) SFPU has finished an iteration but needs more iterations (not all lanes completed), c) SFPU has finished and all lanes completed.

Ideas on alternative approaches welcome.  I do think this is a key question for SFPU performance as not all problems can be solved with trivial fixed-length loops, and I'm pretty sure the hardware supports this type of usage at some level.  I don't know if it's supported with the current abstractions or if this requires lower level (firmware) modifications.

File: ttnn/cpp/ttnn/operations/eltwise/binary_ng/types.hpp [hunk 5]
```diff
@@ -31,6 +31,7 @@ enum class BinaryOpType {
     BITWISE_AND,
     BITWISE_OR,
     LEFT_SHIFT,
-    RIGHT_SHIFT
+    RIGHT_SHIFT,
+    GCD
```
[the remark this answers is not in the document]
Comment (jasondavies) [reply ttnn/cpp/ttnn/operations/eltwise/binary_ng/types.hpp:35]: Understood.  I have some pending changes I'm yet to push (with support for binary_ng) but I need some input on the RISCV_DEBUG_REG_FPU_STICKY_BITS question first - is there someone who can help with this?

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gcd.h [hunk 6]
```diff
@@ -0,0 +1,149 @@
...
+#include "ckernel.h"
+#include "ckernel_defs.h"
+#include "sfpi.h"
+
+using namespace sfpi;
+
+namespace ckernel {
+namespace sfpu {
+
+template <bool APPROXIMATION_MODE, int ITERATIONS = 8>
```
[the remark this answers is not in the document]
Comment (jasondavies) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gcd.h:16]: Great idea.  The same applies to add_int32, sub_int32, and other kernels.  May be worth doing as a separate pass.

File: ttnn/cpp/ttnn/operations/eltwise/binary_ng/types.hpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (jasondavies) [reply ttnn/cpp/ttnn/operations/eltwise/binary_ng/types.hpp:35]: > I am trying to figure out an answer for you, sorry for not replying.

No problem, it might be worth me creating a separate issue to track this question?  I may not end up using it for GCD anyway due to the performance overhead of synchronisation, plus the lack of reliability.  I tried to create a separate experiment that's similar to what I'm doing in GCD, but wasn't able to replicate the issue.  I also found a workaround for my GCD code which is to execute the NaN-generating instruction twice.

[the remark this answers is not in the document]
Comment (ncvetkovicTT) [reply ttnn/cpp/ttnn/operations/eltwise/binary_ng/types.hpp:35]: Sure, creating a separate tracker makes sense, because even if I provide you a reliable mechanism it might not boost the performance in the end, as you say.

**Comment by jasondavies** [comment]
Performance of `gcd_tile` is now down to 8.6μs, which is around 269 cycles per element.  The inner loop is 7 cycles, repeated 31 times (the worst case for 31-bit inputs), so the loop takes 217 cycles in total.

**Comment by ncvetkovicTT** [comment]
@jasondavies @cmaryanTT Just for clarity, we have agreed to address TRISC-to-SFPU sync mechanism possibilities in #18138, since it's not a necessity for this issue and might turn out to be just an experiment 😄.

**Comment by tt-rkim** [comment]
We have to reland the `binary_ng` changes as we had issues with performance. Sorry for the delay. cc: @cmaryanTT @patrickroberts

**Review by kkabilarTT — DISMISSED** [review]
Hi @jasondavies 
Can you please pull the latest changes from the main branch into your branch and resolve any conflicts.

**Comment by jasondavies** [comment]
Done.  Note that I should probably reimplement/fix LCM too at the same time as it uses GCD and the transition to int32 will probably break the existing implementation.

**Comment by kkabilarTT** [comment]
Ok, Please let me know when you have reimplemented/fixed LCM and rebase/pull-changes from main again and I can run the CI after

**Comment by jasondavies** [comment]
It's unclear exactly what the LCM API should look like, since strictly speaking if our outputs are constrained to 31 bits, we can only support input values of up to 15 bits.  The worst case is `LCM(2**15-1, 2**15-2) = (2**15)*(2**15-2)` which has 30 bits.

The calculation is pretty simple: `LCM(a, b) = (a / GCD(a, b)) * b`.  Probably the most straightforward approach is to state in the documentation that inputs up to 15 bits are supported.  This does also mean that we can potentially use just 15 iterations of the GCD LLK (ideally with some kind of check that inputs are within the supported range?)

**Comment by cmaryanTT** [comment]
@jasondavies I recommend just documenting it as you proposed. We have other OPs that limit input range to something other than the full range of the input dtype.

**Review by rdjogoTT — APPROVED** [review]

**Review by ncvetkovicTT — APPROVED** [review]
lgtm!

**Review by sjameelTT — APPROVED** [review]

**Review by patrickroberts — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Comment by jasondavies** [comment]
> One key concern about this refactoring is its effect on perf.

I'd be surprised if ttnn.{gcd,lcm} is used in any models or performance tests at the moment.

**Review by dchenTT — APPROVED** [review]

**Comment by jasondavies** [comment]
Looks like I need to update Python tests.  This has also uncovered a bug with negative values for LCM.

**Comment by tt-rkim** [comment]
Beautiful! This is what we want to see.
Please let us know when you've fixed locally and ready to run APC again.

**Comment by jasondavies** [comment]
Done!  This passes the Python tests locally now.

**Comment by jasondavies** [comment]
^ @tt-rkim

**Comment by jasondavies** [comment]
I just noticed `tests/sweep_framework/sweeps/composite/binary/gcd/gcd.py` contains bfloat16, so that particular test will fail.  (Same for lcm/lcm.py.)

Sorry, I didn't spot this earlier!  Part of the issue with preparing a PR like this is that it's not clear how to run sweep tests locally.

**Comment by tt-rkim** [comment]
No worries - that particular set of unit tests is dubious to me. I'm wondering if we need delete them.

This is something we can discuss with the ops team.

Once you re-push a fix, we can rerun

**Comment by jasondavies** [comment]
@tt-rkim Fix pushed.

**Comment by tt-rkim** [comment]
giving her a spin: https://github.com/tenstorrent/tt-metal/actions/runs/14886843638

**Comment by jasondavies** [comment]
@tt-rkim I can't believe I missed a third LCM test in `tests/ttnn/unit_tests/operations/eltwise/test_binary_composite.py` (negative values only).  This is definitely all the tests in `tests/` that refer to gcd/lcm now.  Sorry about this!

**Comment by Aswinmcw** [comment]
Running:
https://github.com/tenstorrent/tt-metal/actions/runs/14889166204

**Comment by jasondavies** [comment]
OK, everything passed except for profiler-regression on N150 (some kind of timeout).

**Comment by tt-rkim** [comment]
LOL I love reading logs

```
2025-05-07T19:33:51.6268649Z models/demos/ttnn_falcon7b/tests/multi_chip/test_falcon_causallm.py::test_falcon_causal_lm[wormhole_b0-20-2-BFLOAT16-L1-falcon_7b-layers_2-decode_batch32]                   Metal | INFO     | Initializing device 0. Program cache is NOT enabled
2025-05-07T19:33:51.6271166Z            BuildKernels | INFO     | Skipping deleting built cache
2025-05-07T19:33:51.6272160Z                   Metal | INFO     | AI CLK for device 0 is:   1000 MHz
2025-05-07T19:33:52.2355870Z                   Metal | INFO     | Profiler started on device 0
2025-05-07T19:33:53.6759610Z                   Metal | INFO     | Enabling program cache on MeshDevice 0
2025-05-07T19:33:55.6132500Z 
2025-05-07T19:58:36.0681834Z Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]Error while downloading from https://cdn-lfs.hf.co/repos/fb/9d/fb9d2cbe2e913461ae463cd35cb5a43ad1c5115ba9e913382f147e2f1ea66f3d/b4515a8e32f81ab4fef65e10891fdb188bc45c4195620d447bc3263e132d9de5?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model-00001-of-00002.safetensors%3B+filename%3D%22model-00001-of-00002.safetensors%22%3B&Expires=1746650035&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc0NjY1MDAzNX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9yZXBvcy9mYi85ZC9mYjlkMmNiZTJlOTEzNDYxYWU0NjNjZDM1Y2I1YTQzYWQxYzUxMTViYTllOTEzMzgyZjE0N2UyZjFlYTY2ZjNkL2I0NTE1YThlMzJmODFhYjRmZWY2NWUxMDg5MWZkYjE4OGJjNDVjNDE5NTYyMGQ0NDdiYzMyNjNlMTMyZDlkZTU%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=OuO1fn-r2UHUufOKRRixvRR4z-7RVIyIvj5fZ6wrfHGvUd5lmUs2ZjYI5LCtxFYVdJ3Zpn8NQ5ubhFPYHNC1vuVZpFszfX6IZhru9rDiP35ohAiw8vhKKbgI3sLlZmQvYyih1ZRnyzAKugRTxc--CitHtLHq70d13J7FUj2RJf8mwREmCa9ZkWRBxYtFKPIPhbXtGBD%7Eqb%7Ex%7Eymgok9Xp3ImGiP4rOShEJM3A4pfzc0MPDbYWnMtfiTvddaHe%7ENmVSjawzYwu-8S7beFetv7BWJtTtNI1d7iMClFx6Kl3xdisS7jv0ybQJHcrBMGH44CaHxCGi9cLYCnU0dd31-P%7Ew__&Key-Pair-Id=K3RPWS32NSSJCE: HTTPSConnectionPool(host='cdn-lfs.hf.co', port=443): Read timed out.
2025-05-07T19:58:36.0700640Z Trying to resume download...
2025-05-07T20:00:16.6772861Z 
```

So looks like there was some almost 30 minute long timeout trying to download weights for falcon7b. We've had weird network issues before... gonna gloss that over with a wave of my hand and retry the job. I'm sure it's fine. Let's wait for the retry. Doesn't seem like something that would be affected by your changes at all.

**Comment by tt-rkim** [comment]
retry https://github.com/tenstorrent/tt-metal/actions/runs/14889166204

**Comment by jasondavies** [comment]
Same timeout error again.

**Comment by Aswinmcw** [comment]
rerunning few times passed
https://github.com/tenstorrent/tt-metal/actions/runs/14889166204
@jasondavies @tt-rkim

**Comment by jasondavies** [comment]
@Aswinmcw Thank you!

**Comment by ncvetkovicTT** [comment]
@jasondavies Thank you for your contribution! 🚀
