### PR TITLE
SELU: Fix incorrect formula and reduce asymptotic error

### LINKED ISSUE #21487: Wrong asymptote at -inf for ttnn.selu
### Describe the bug

When `x-> -inf`, `ttnn.selu(x)` converges towards -1.671875 (~ `-scale`) whereas `torch.selu(x)` converges towards -1.7578125 (`- scale * alpha`). 
This is a ~5% error relative to torch (absolute error of 0.1)

When x < 0, `selu(x)` should be `scale * alpha *(exp(x) - 1)`.  The limit at `x = -inf` should therefore be `- scale * alpha` rather than just `-scale`.

### Steps to reproduce the issue

_No response_

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by nmauriceTT**
### Ticket
#21487

### Problem description

`x -> -inf` asymptote of `ttnn.selu(x)` is wrong: it is ~ `-alpha` (by default -1.671875) instead of `-scale * alpha` (-1.7578125). 

Right now, it computes:
`scale * max(x, 0) + min(0, alpha * (exp(x) - 1))`
Instead of
`scale * (max(x, 0) + min(0, alpha * (exp(x) - 1)))`

The error relative to torch is roughly ~5% (absolute error of ~0.1) when `x < -20`

### What's changed
- Fix formula of composite operation to produce a more accurate asymptote (relative error of ~0.5%, absolute error of ~0.01) when `x < -20`.

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [x] New/Existing tests provide coverage for changes (` tests/ttnn/unit_tests/operations/eltwise/test_eltwise_selu.py`)

### CODE REVIEW

**Review by cmaryanTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp [hunk 1]
```diff
@@ -560,9 +560,9 @@ Tensor _selu(
 
     // term 1
     Tensor x_max = ttnn::maximum(ttnn::DefaultQueueId, x, 0.0f, std::nullopt, output_mem_config);
-    Tensor result_term1 = ttnn::multiply(x_max, scale, std::nullopt, output_mem_config);
+    Tensor sum_max_term2 = ttnn::add(x_max, result_term2, std::nullopt, output_mem_config);
     x_max.deallocate();
```
Comment (dchenTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp:564]: Shall we reuse x as in place, instead of allocate then deallocate x_max

Comment (KalaivaniMCW) [reply ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp:564]: @dchenTT sometimes models or other ops may don't want the inputs to be changed..
but yeah we can use inplace add on intermediate tensors like x_max

File: ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp [hunk 2]
```diff
@@ -560,9 +560,9 @@ Tensor _selu(
 
     // term 1
     Tensor x_max = ttnn::maximum(ttnn::DefaultQueueId, x, 0.0f, std::nullopt, output_mem_config);
-    Tensor result_term1 = ttnn::multiply(x_max, scale, std::nullopt, output_mem_config);
+    Tensor sum_max_term2 = ttnn::add(x_max, result_term2, std::nullopt, output_mem_config);
```
Comment (KalaivaniMCW) [inline ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp:563]: ttnn::add_(x_max, result_term2);

File: ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp (hunk 1 above)
Comment (dchenTT) [reply ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp:564]: yeah, that is what I mean

File: ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp (hunk 2 above)
Comment (KalaivaniMCW) [inline ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp:563]:
```
ttnn::add_(x_max, result_term2);
ttnn::multiply_(x_max, scale);
```

**Review by patrickroberts — APPROVED** [review]
Pending the requested change by @dchenTT  and @KalaivaniMCW

File: ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp (hunk 1 above)
Comment (nmauriceTT) [reply ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp:564]: I've changed `ttnn::add` and `ttnn::multiply` to their in-place equivalents  (`ttnn::add_` and `ttnn::multiply_` respectively).

File: ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp [hunk 3]
```diff
@@ -560,9 +560,9 @@ Tensor _selu(
...
     x_max.deallocate();
-    Tensor result_selu = ttnn::add(result_term1, result_term2, std::nullopt, output_mem_config);
+    Tensor result_selu = ttnn::multiply(sum_max_term2, scale, std::nullopt, output_mem_config);
```
[the remark this answers is not in the document]
Comment (nmauriceTT) [reply ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp]: Done.
