### PR TITLE
Fix moreh sum in BH

### LINKED ISSUE #19911: BH TTNN Unit test failure in moreh sum test
moreh sum test is failing on BH

https://github.com/tenstorrent/tt-metal/actions/runs/14143705878/job/39628534546
```
FAILED tests/ttnn/unit_tests/operations/test_moreh_sum.py::test_moreh_sum_integer[int32-dim-w-TILE_HEIGHT, TILE_WIDTH] - assert False
```

### PR DESCRIPTION
**Pull request by Aswinmcw**
### Ticket
#19911 

### Problem description
BH TTNN Unit test failure in moreh sum test

### What's changed
Remove conversion of 2's complement <-> sign magnitude

negative int numbers are not adding properly in WH, so they are converting it to sign magnitude, then add then convert it to 2's complement to get the actual result

Image

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
https://github.com/tenstorrent/tt-metal/actions/runs/14350752082
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable)
https://github.com/tenstorrent/tt-metal/actions/runs/14350754948
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by KalaivaniMCW — APPROVED** [review]
Look good !

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_int_sum.h [hunk 1]
```diff
@@ -16,47 +16,21 @@ using namespace sfpi;
...
-
 template <bool APPROXIMATION_MODE>
 inline void calculate_sum_int_col() {
     for (size_t i = 0; i < 2; ++i) {
         vInt a = dst_reg[i];
-        a = sfpu_twos_comp_to_sign_mag(a);
 
         for (size_t j = 2; j < 8; j += 2) {
             vInt b = dst_reg[i + j];
-            b = sfpu_twos_comp_to_sign_mag(b);
```
Comment (umadevimcw) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_int_sum.h:49]: Why we don't need this on BH?

**Review by umadevimcw — APPROVED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_int_sum.h (hunk 1 above)
Comment (Aswinmcw) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_int_sum.h:49]: negative int numbers are not adding properly in WH, so they are converting it to sign magnitude, then add then convert it to 2's complement to get the actual result

**Review by VirdhatchaniKN — APPROVED** [review]

**Review by razorback3 — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]
Do you know the reason for the WH workaround of conversion of 2's complement <-> sign magnitude not working on BH?

**Comment by Aswinmcw** [comment]
> Do you know the reason for the WH workaround of conversion of 2's complement <-> sign magnitude not working on BH?

workaround on WH is because negative inputs are not handled properly so due to that they changed the sign and performed the operation, but in case of BH, direct operation works so no need to additional workaround

**Review by nvelickovicTT — APPROVED** [review]
