### PR TITLE
Convert Hal into a Singleton

### LINKED ISSUE #14756: Convert Hal from global to singleton
Currently Hal is a global that is initialized in the constructor of some class.

https://github.com/tenstorrent/tt-metal/blob/5ccabf915553fdf472f2376293ecb35ab6a20b11/tt_metal/llrt/hal.cpp#L13

https://github.com/tenstorrent/tt-metal/blob/5ccabf915553fdf472f2376293ecb35ab6a20b11/tt_metal/llrt/tt_cluster.cpp#L70

Other classes call Hal methods in their constructors.
https://github.com/tenstorrent/tt-metal/blob/ca28cf90690eb9701f8411eef7b79c9f9d2d5a1a/tt_metal/impl/dispatch/device_command.hpp#L754-L755

Depending on the order of construction, a race condition could occur that would cause segmentation fault.

It may be the case that presently the order of construction guarantees that no race condition will happen.

A safer design choice would be to use the singleton pattern for the Hal.

We can `inline` the `instance` method for performance, and also cache references where necessary.

Recommended design pattern (Meyer’s Singleton + inheritance)

```C++
class HalSingleton : public Hal {
private:
    HalSingleton() = default;
    HalSingleton(const HalSingleton&) = delete;
    HalSingleton(HalSingleton&&) = delete;
    ~HalSingleton() = default;

    HalSingleton& operator=(const HalSingleton&) = delete;
    HalSingleton& operator=(HalSingleton&&) = delete;

public:
    static inline HalSingleton& getInstance() {
        static HalSingleton instance;
        return instance;
    }
};
```

### PR DESCRIPTION
**Pull request by blozano-tt**
### Ticket
Closes #14756 

### Problem description
See issue
(Global variable provides opportunity for race conditions, use before initialization).

### What's changed
Use thread safe singleton instead of global throughout the code base.
C++17 gives us an inline variable, this replaces the global usage of hal.

### Checklist
https://github.com/tenstorrent/tt-metal/actions/runs/11906843372 (latest commit)
https://github.com/tenstorrent/tt-metal/actions/runs/11863772087
- [x] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_metal/llrt/hal.cpp [hunk 1]
```diff
@@ -2,45 +2,55 @@
...
+// Once it knows the architecture it can self initialize architecture specific memory maps
+Hal::Hal() {
+    this->arch_ = tt::ARCH::Invalid;
+    if(std::getenv("TT_METAL_SIMULATOR_EN")) {
+        auto arch_env = std::getenv("ARCH_NAME");
+        TT_FATAL(arch_env, "ARCH_NAME env var needed for VCS");
+        this->arch_ = tt::get_arch_from_string(arch_env);
+    }else {
+        std::vector<chip_id_t> physical_mmio_device_ids = tt::umd::Cluster::detect_available_device_ids();
+        //TT_ASSERT(physical_mmio_device_ids.size() > 0, "Could not detect any devices");
```
Comment (blozano-tt) [inline tt_metal/llrt/hal.cpp:27]:
```suggestion
        //TT_FATAL(physical_mmio_device_ids.size() > 0, "Could not detect any devices");
```

File: tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_prefetcher.cpp [hunk 2]
```diff
@@ -2906,9 +2906,6 @@ int main(int argc, char **argv) {
     auto slow_dispatch_mode = getenv("TT_METAL_SLOW_DISPATCH_MODE");
     TT_FATAL(slow_dispatch_mode, "This test only supports TT_METAL_SLOW_DISPATCH_MODE");
 
-    // TODO(abhullar): Have to initialize the HAL explicitly here because it is accessed before Device initializes it
-    tt::ARCH arch = tt::Cluster::instance().arch();
-    hal.initialize(arch);
```
Comment (blozano-tt) [inline tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/test_prefetcher.cpp:2911]: No need to do this anymore, because the Hal Singleton will be constructed on first use.

File: tt_metal/llrt/hal.cpp [hunk 3]
```diff
@@ -2,45 +2,55 @@
...
-            initialize_bh();
-            break;
-
-        default:
-            TT_THROW("Unsupported arch for HAL");
+// Hal Constructor determines the platform architecture by using UMD
+// Once it knows the architecture it can self initialize architecture specific memory maps
+Hal::Hal() {
+    this->arch_ = tt::ARCH::Invalid;
+    if(std::getenv("TT_METAL_SIMULATOR_EN")) {
```
Comment (abhullar-tt) [inline tt_metal/llrt/hal.cpp:21]: this looks like it was copied from `Cluster::detect_arch_and_target()` could you just:
```suggestion
    this->arch_ = tt::Cluster::instance().arch()
```
since Cluster is a singleton

**Review by abhullar-tt — DISMISSED** [review]

File: tt_metal/llrt/hal.cpp (hunk 3 above)
Comment (blozano-tt) [reply tt_metal/llrt/hal.cpp]: Latest commit uses common inline function.

**Comment by blozano-tt** [comment]
@CodiumAI-Agent /review

**Comment by blozano-tt** [comment]
@CodiumAI-Agent /improve

**Review by tt-aho — APPROVED** [review]
This seems okay to me, but should get @abhullar-tt's approval before merge

**Comment by blozano-tt** [comment]
> This seems okay to me, but should get @abhullar-tt's approval before merge

Thanks for taking a look!

**Review by pgkeller — APPROVED** [review]
