### PR TITLE
#23749: Correctly call Cluster destructor

### LINKED ISSUE #23749: Cluster not being cleaned up
### Describe the bug

The tt_cluster descriptor is never called, due to MetalContext being an Indestructible.
This leads to memory leaks which might have other effects, such as having multiple UMD devices open.

### Steps to reproduce the issue

Run any test

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by tt-dma**
https://github.com/tenstorrent/tt-metal/issues/23749
Cluster destructor wasn't being called. Workaround for now is to use atexit to do that, and we can investigate better options down the road (MetalContext owned by user and passed through API?)

https://github.com/tenstorrent/tt-metal/actions/runs/16301687404
https://github.com/tenstorrent/tt-metal/actions/runs/16301697216

### CODE REVIEW

File: tt_metal/impl/context/metal_context.cpp [hunk 1]
```diff
@@ -237,6 +237,10 @@ MetalContext::MetalContext() {
     hal_ = std::make_unique<Hal>(get_platform_architecture(rtoptions_), is_base_routing_fw_enabled);
     cluster_ = std::make_unique<Cluster>(rtoptions_, *hal_);
     distributed_context_ = distributed::multihost::DistributedContext::get_current_world();
+
+    // We do need to call Cluster teardown at the end of the program, use atexit temporarily until we have clarity on
+    // how MetalContext lifetime will work through the API.
+    std::atexit([]() { MetalContext::instance().~MetalContext(); });
```
Comment (jbaumanTT) [inline tt_metal/impl/context/metal_context.cpp:243]: Wouldn't it be simpler to change `static tt::stl::Indestructible<MetalContext> inst;` to `static MetalContext inst;`?

Comment (tt-dma) [reply tt_metal/impl/context/metal_context.cpp:243]: @omilyutin-tt Thoughts on keeping Indestructible vs switch to singleton if we want to make sure Cluster destructor is called?

File: tt_metal/impl/context/metal_context.cpp [hunk 2]
```diff
@@ -237,6 +237,10 @@ MetalContext::MetalContext() {
     hal_ = std::make_unique<Hal>(get_platform_architecture(rtoptions_), is_base_routing_fw_enabled);
     cluster_ = std::make_unique<Cluster>(rtoptions_, *hal_);
     distributed_context_ = distributed::multihost::DistributedContext::get_current_world();
+
+    // We do need to call Cluster teardown at the end of the program, use atexit temporarily until we have clarity on
+    // how MetalContext lifetime will work through the API.
```
Comment (cfjchu) [inline tt_metal/impl/context/metal_context.cpp:242]: @tt-dma IIRC, I made similar changes at some point, but I had an issue between tests where it was doing fabric re-init?

File: tt_metal/impl/context/metal_context.cpp (hunk 1 above)
Comment (omilyutin-tt) [reply tt_metal/impl/context/metal_context.cpp:243]: Is it possible to not do this? what part of `Cluster` do we actually want to clean up?

In terms of memory "leaking" this is intentional and this is not a leak, as the memory remains accessible. Can we expose a method on cluster to close whatever needs to be closed, and do it in teardown?

Comment (omilyutin-tt) [reply tt_metal/impl/context/metal_context.cpp:243]: Overall this is becoming convoluted, so I think there is a stronger push for making this non-static, which would be ideal and resolve all of our problems :)

Comment (tt-dma) [reply tt_metal/impl/context/metal_context.cpp:243]: I looked into moving cluster init/teardown into MetalContext init/teardown and it's nontrivial due to the fact that MetalContext init is called later than a bunch of accesses to Cluster. It's definitely more convoluted, but moving Cluster teardown would likely make it even more so.

I agree that we should make a stronger push to make MetalContext non-static, but I'm running out of time. I'm thinking we out this PR in with `atexit` for now, and then hopefully make the push for more sweeping MetalContext/API changes soon.

File: tt_metal/impl/context/metal_context.cpp (hunk 2 above)
Comment (tt-dma) [reply tt_metal/impl/context/metal_context.cpp:242]: Do you remember what tests had issues, or if there's some pipeline I can run to check?

Comment (cfjchu) [reply tt_metal/impl/context/metal_context.cpp:242]: IIRC APC/T3K unit tests were problematic when it was doing fabric reinitialization between test runs.

File: tt_metal/impl/context/metal_context.cpp (hunk 1 above)
Comment (tt-dma) [reply tt_metal/impl/context/metal_context.cpp:243]: Issue to track that here: https://github.com/tenstorrent/tt-metal/issues/25042

File: tt_metal/impl/context/metal_context.cpp (hunk 2 above)
Comment (tt-dma) [reply tt_metal/impl/context/metal_context.cpp:242]: T3K unit tests look fine on this branch, perhaps the issue was related to other init/teardown code movement: https://github.com/tenstorrent/tt-metal/actions/runs/16301697216

File: tt_metal/impl/context/metal_context.cpp (hunk 1 above)
Comment (broskoTT) [reply tt_metal/impl/context/metal_context.cpp:243]: @omilyutin-tt you can't just use an external lib (which is UMD in this case) and chose not to call its destructors. The lib was not written to be used like that

File: tt_metal/impl/context/metal_context.cpp (hunk 2 above)
Comment (tt-dma) [reply tt_metal/impl/context/metal_context.cpp:242]: Latest T3K unit tests: https://github.com/tenstorrent/tt-metal/actions/runs/16381122864
Same failure as main: https://github.com/tenstorrent/tt-metal/actions/runs/16379593733/job/46288736972

**Review by cfjchu — APPROVED** [review]
