### PR TITLE
Format broken Kernel APIs Tables

### LINKED ISSUE #15735: [Bug Report] Local API doc tables broken
**Describe the bug**
For local docs, kernel api pages with param tables in them are broken. This is not an extension or browser issue, just a formatting one as i've tried with both firefox and chromium w/o extension as well.

These are the broken function docs:
Host APIs:
- UpdateCircularBufferTotalSize
- UpdateDynamicCircularBufferAddress

Kernel APIs:
- All noc APIs
- All CB APIs (all are half-broken)
- copy_tile
- move_copy_tile (all functions)
- All Compute APIs except transpose_wh_init
- All kernel arg APIs except get_compile_time_arg_val
- All Packing APIs

**To Reproduce**
1. Pull latest tt-metal commit
2. `cd docs/`
3. `make all`
4. Navigate to a page like http://localhost:8888/tt-metalium/tt_metal/apis/kernel_apis/data_movement/noc_async_read.html

**Expected behavior**
Tables should be normal like the one below

**Screenshots**
Normal:
Image

Broken:
Image

**Please complete the following environment information:**
- OS: Artix Linux
- Version as of: https://github.com/tenstorrent/tt-metal/commit/0a73de03aff5190c22dec7e9b4eb27c3da161097

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by gsarabandoTT**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/15735)

### Problem description
Multiple Kernel APIs description tables were resulting in broken views due to wrong formatting.

### What's changed
Tracked API files with broken tables and adjusted formatting.

### CODE REVIEW

**Comment by gsarabandoTT** [comment]
Hey guys @rtawfik01 @rdjogoTT @ttmtrajkovic @aliuTT, Can you confirm the formatting changes to the tables are safe to merge?

**Review by aliuTT — APPROVED** [review]

File: tt_metal/include/compute_kernel_api/bcast.h [hunk 1]
```diff
@@ -189,17 +188,14 @@ ALWI void any_tiles_bcast(uint32_t icb0, uint32_t icb1, uint32_t itile0, uint32_
  * DOX-TODO(AP): verify that the bcast tile is actually required to be filled
  * with zeros.
  *
- * | Argument       | Description                                              | Type          | Valid Range | Required
- * |
+ * | Argument       | Description                                              | Type          | Valid Range | Required |
```
Comment (rdjogoTT) [inline tt_metal/include/compute_kernel_api/bcast.h:191]: "Valid range" column spacing is smaller on line 191 than 192

File: tt_metal/include/compute_kernel_api/matmul.h [hunk 2]
```diff
@@ -97,13 +90,11 @@ ALWI void matmul_tiles_math(uint32_t idst) {
...
  *
- * | Argument       | Description                                                   | Type     | Valid Range | Required
- * |
+ * | Argument       | Description                                                   | Type     | Valid Range                                         | Required |
  * |----------------|---------------------------------------------------------------|----------|-----------------------------------------------------|----------|
- * | in0_cb_id      | The identifier of the first input circular buffer (CB)        | uint32_t | 0 to 31 | False    | |
- * in1_cb_id      | The identifier of the second input circular buffer (CB)       | uint32_t | 0 to 31 | False    | |
- * transpose      | The transpose flag for performing transpose operation on B    | uint32_t | Any positive value will
- * indicate tranpose is set    | False    |
+ * | in0_cb_id      | The identifier of the first input circular buffer (CB)        | uint32_t | 0 to 31 | False                                     |          |
```
Comment (rdjogoTT) [inline tt_metal/include/compute_kernel_api/matmul.h:95]: "False" should be 1 column to the right in this line and the next (extra col added)

**Review by rdjogoTT — APPROVED** [review]

File: tt_metal/include/compute_kernel_api/bcast.h (hunk 1 above)
Comment (gsarabandoTT) [reply tt_metal/include/compute_kernel_api/bcast.h:191]: Well spotted, thank you

**Comment by gsarabandoTT** [comment]
Hey guys @davorchap, @mywoodstock. Could you confirm the formatting updates to the API description tables are good to merge? Thank you!

**Review by davorchap — APPROVED** [review]
