### PR TITLE
#29702: ttnn.gather fails for some cases where rank 4 fix

### LINKED ISSUE #29702: ttnn.gather fails for some cases where rank > 4
### Describe the bug

ttnn.gather throws errors in certain cases for rank > 4.

For input shape [1, 2, 128, 1, 768], index shape [1, 2, 8, 1, 768], dim=2, I get this error:

```
E           RuntimeError: TT_FATAL @ /home/yiding/projects/tt/model-bringup/tt-metal/ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:319: false
E           info:
E           Attempting to reshape between two shapes with different volumes
```

For input shape [1, 2, 128, 1, 768], index shape [1, 2, 8, 1, 128], dim=4, I get a different error:

```
E           RuntimeError: TT_FATAL @ /home/yiding/projects/tt/model-bringup/tt-metal/ttnn/cpp/ttnn/operations/data_movement/gather/gather.cpp:85: output_tensor.logical_shape() == original_lshape
E           info:
E           Output tensor transformation did not create correct output shape! Got: Shape([1, 2, 8, 32, 128]), expected: Shape([1, 2, 8, 1, 128])
```

### Steps to reproduce the issue

Add these two cases into `tt-metal/tests/ttnn/unit_tests/operations/test_gather.py` `test_gather_general`:

```
@pytest.mark.parametrize(
    "input_shape, index_shape, dim",
    [
        ...,
        ([1, 2, 128, 1, 768], [1, 2, 8, 1, 768], 2),
        ([1, 2, 8, 1, 768], [1, 2, 8, 1, 128], -1),
    ],
)
```

### Expected behavior

Both these cases should work. 
If I reshape the first two dimensions into a single dimension then it works correctly.

If it's not supported the error message should be clearer.

### Please complete the following environment information

tt-metal version: 5be2f8ac0
hardware: p150

### PR DESCRIPTION
**Pull request by mgajewskiTT**
### Ticket
#29702

### Problem description
ttnn.gather threw errors when the tensor rank was greater than 4, due to an issue in the post-device work output transformation.

### What's changed
- Fixed `post_gather_transform_tensor` functions,
- Added test cases from issue to `test_gather.py`,
- Updated docs with supported types and layouts table.

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes - https://github.com/tenstorrent/tt-metal/actions/runs/18647593962
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes - https://github.com/tenstorrent/tt-metal/actions/runs/18647597540

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/data_movement/gather/gather.cpp [hunk 1]
```diff
@@ -64,20 +64,25 @@ Tensor post_gather_transform_tensor(
...
+    if (orig_rank <= 4) {
         output_tensor = ttnn::squeeze_from_4D(output_tensor, orig_rank);
+        if (!is_dim_last_idx) {
+            output_tensor = ttnn::transpose(output_tensor, dim, -1, index_tensor.memory_config());
+        }
     } else if (orig_rank > 4) {
+        if (!is_dim_last_idx) {
+            const auto index_dim = (dim < 0) ? (orig_rank + dim) : dim;
+            const auto dim_adj =
+                (orig_rank <= 4) ? index_dim : (index_dim + (output_tensor.padded_shape().rank() - orig_rank));
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/data_movement/gather/gather.cpp:131]: Please add an explanation of what this does and how it works properly with the rest of the code.

File: tests/ttnn/unit_tests/operations/data_movement/test_gather.py [hunk 2]
```diff
@@ -15,6 +15,8 @@
 @pytest.mark.parametrize(
     "input_shape, index_shape, dim",
     [
+        ([1, 2, 128, 1, 768], [1, 2, 8, 1, 768], 2),
+        ([1, 2, 8, 1, 768], [1, 2, 8, 1, 128], -1),
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/data_movement/test_gather.py]: Please add a test with the second last dim not being 1 and with 6 dimensions and dim -2:
```
([1, 2, 8, 2, 768], [1, 2, 8, 2, 128], -1),
([1, 1, 2, 8, 2, 768], [1, 1, 2, 8, 2, 128], -2)
```

Comment (mgajewskiTT) [reply tests/ttnn/unit_tests/operations/data_movement/test_gather.py]: Added.

File: ttnn/cpp/ttnn/operations/data_movement/gather/gather.cpp (hunk 1 above)
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/data_movement/gather/gather.cpp:131]: Added, also added docs for the helper functions in this file.

**Review by bbradelTT — APPROVED** [review]

**Review by nsorabaTT — APPROVED** [review]

**Review by nardoTT — APPROVED** [review]
