### PR TITLE
#13609: Uplift dram and l1 allocators to use dram/l1 specific alignment

### LINKED ISSUE #13609: allocator uses 32B alignment for both DRAM and L1
**Describe the bug**
during device->allocator->dispatch path (which uses dataflow_api, and it uses the pre-defined 32B alignment from jitbuild)
the alignment is decided by compare l1 alignment and dram alignment and set it with the larger one, so it will always be 32B.

This caused pcc mismatch when we use 16B page size (a stick in row major layout) in interleaved_to_sharded, and sharded_to_interleaved, and pad

**Expected behavior**
we should have 16B aligment for L1, and 32B for DRAM. This can be done with seperating l1_alignement and dram_alignment in allocator config.

### PR DESCRIPTION
**Pull request by abhullar-tt**
### Ticket
#13609

### Problem description
Using the max of DRAM and L1 alignment for both DRAM and L1 buffers was causing pcc mismatches in i2s and s2i.

### What's changed
Use L1/DRAM specific alignment for respective allocations. This will require some ops to be uplifted to handle re-alignment
@yugaoTT and @ntarafdar to add corresponding op changes

### Checklist
**Below post commits were triggered 12/03**
- [x] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/12956459836)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/runs/12956461469)
- [x] [Run microbenchmarks](https://github.com/tenstorrent/tt-metal/actions/runs/12956474089)
- [x] [T3000 frequent tests](https://github.com/tenstorrent/tt-metal/actions/runs/12956470735)
- [x] [ttnn sweeps](https://github.com/tenstorrent/tt-metal/actions/runs/12892223851)

### CODE REVIEW

File: tt_metal/hw/inc/dataflow_api.h [hunk 1]
```diff
@@ -921,9 +941,10 @@ struct InterleavedPow2AddrGen {
     const uint32_t bank_base_address;
     const uint32_t log_base_2_of_page_size;  // WARNING: This struct is used for optimized get_noc_addr in which case
                                              // you know that bank_unit_size is a power of 2
-    const uint32_t aligned_log_base_2_of_page_size = this->log_base_2_of_page_size > LOG_BASE_2_OF_ALLOCATOR_ALIGNMENT
+    const uint32_t log_base_2_of_allocator_alignment = interleaved_addr_gen::get_log_base2_of_allocator_alignment<DRAM>();
```
Comment (tt-aho) [inline tt_metal/hw/inc/dataflow_api.h:944]: `log_base_2_of_allocator_alignment` can be constexpr?

File: tt_metal/hw/inc/dataflow_api.h [hunk 2]
```diff
@@ -1019,9 +1040,10 @@ template <bool DRAM>
 struct InterleavedPow2AddrGenFast {
     uint32_t bank_base_address;             // Base address for the whole tensor.
     const uint32_t log_base_2_of_page_size; // Num bytes in bank unit.
-    const uint32_t aligned_log_base_2_of_page_size = this->log_base_2_of_page_size > LOG_BASE_2_OF_ALLOCATOR_ALIGNMENT
+    const uint32_t log_base_2_of_allocator_alignment = interleaved_addr_gen::get_log_base2_of_allocator_alignment<DRAM>();
```
Comment (tt-aho) [inline tt_metal/hw/inc/dataflow_api.h:1043]: `log_base_2_of_allocator_alignment` can be constexpr?

**Review by tt-aho — DISMISSED** [review]
Changes look good.

Will the op changes be added to this PR before merge?
Want to make sure no models break with these changes

**Comment by abhullar-tt** [comment]
> Changes look good.
> 
> Will the op changes be added to this PR before merge? Want to make sure no models break with these changes

yes, before merging we will run all the model tests

File: tt_metal/hw/inc/dataflow_api.h [hunk 3]
```diff
@@ -557,7 +577,7 @@ std::uint64_t get_noc_addr_helper(std::uint32_t noc_xy, std::uint32_t addr) {
 uint64_t get_dram_noc_addr(const uint32_t id, const uint32_t page_size, const uint32_t bank_base_address, const uint32_t offset = 0, uint8_t noc = noc_index) {
     uint32_t bank_offset_index = interleaved_addr_gen::get_bank_offset_index<true>(id);
     uint32_t bank_index = interleaved_addr_gen::get_bank_index<true>(id, bank_offset_index);
-    uint32_t addr = (bank_offset_index * align(page_size, ALLOCATOR_ALIGNMENT)) + bank_base_address + offset + bank_to_dram_offset[bank_index];
+    uint32_t addr = (bank_offset_index * align(page_size, interleaved_addr_gen::get_allocator_alignment<true>())) + bank_base_address + offset + bank_to_dram_offset[bank_index];
```
Comment (arikTT) [inline tt_metal/hw/inc/dataflow_api.h:580]: Is there a reason you use true/flase in lines 580/589 where you use DRAM/ in line 915. I find the latter much more readable

File: ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp [hunk 4]
```diff
@@ -1653,7 +1653,7 @@ operation::ProgramWithCallbacks pad_rm_sharded_width_only(
 
     // FIXME: assumes that this was sharded using DRAM alignment so that gaps are left in the tensor.
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp:1654]: Should this comment be udpated as well?

File: tech_reports/prog_examples/shard_data_rm/shard_data_rm.md [hunk 5]
```diff
@@ -63,7 +63,7 @@ uint32_t shard_size = shard_height * shard_width;
 uint32_t input_unit_size = sizeof(uint32_t);
 uint32_t shard_width_bytes = shard_width * data_size;
 uint32_t num_units_per_row = shard_width * input_unit_size;
-uint32_t padded_offset_bytes = align(input_unit_size, device->get_allocator_alignment());
+uint32_t padded_offset_bytes = align(input_unit_size, device->get_allocator_alignment(BufferType::L1));
```
Comment (bbradelTT) [inline tech_reports/prog_examples/shard_data_rm/shard_data_rm.md:66]: It might be good to add more info about when you need or when the infra uses different alignments and why.

**Review by bbradelTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp [hunk 6]
```diff
@@ -676,7 +676,7 @@ operation::ProgramWithCallbacks transpose_hc_multi_core(
     // TODO: noc_async_write only require 16B alignment for both DRAM and L1 for Blackhole, so instead of reading in
     // face-lines from C tiles to form a single tile, we can load a single tile and then write out its face-lines to C
     // tiles
-    uint32_t alignment = dst_buffer->buffer_type() == tt::tt_metal::BufferType::DRAM ? DRAM_ALIGNMENT : L1_ALIGNMENT;
+    uint32_t alignment = device->get_allocator_alignment(dst_buffer->buffer_type());
```
Comment (tt-aho) [inline ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp:679]: Use `dst_buffer->alignment()` instead

File: ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp [hunk 7]
```diff
@@ -1653,7 +1653,7 @@ operation::ProgramWithCallbacks pad_rm_sharded_width_only(
...
     // if this changes, we should change the stick step to be 16B (L1 alignment).
-    auto dram_alignment_bytes = tt::tt_metal::hal.get_alignment(tt::tt_metal::HalMemType::DRAM);
+    auto dram_alignment_bytes = tt::tt_metal::hal.get_alignment(tt::tt_metal::HalMemType::L1);
```
Comment (tt-aho) [inline ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp:1656]: Should be renamed to `l1_alignment_bytes`?

File: tt_metal/impl/device/device.hpp [hunk 8]
```diff
@@ -196,8 +196,8 @@ class Device {
     allocator::Statistics get_memory_allocation_statistics(const BufferType &buffer_type) const;
     allocator::Statistics get_memory_allocation_statistics(const BufferType &buffer_type, SubDeviceId sub_device_id) const;
 
-    uint32_t get_allocator_alignment() const;
-    uint32_t get_allocator_alignment(SubDeviceId sub_device_id) const;
+    uint32_t get_allocator_alignment(const BufferType &buffer_type) const;
+    uint32_t get_allocator_alignment(SubDeviceId sub_device_id, const BufferType &buffer_type) const;
```
Comment (tt-aho) [inline tt_metal/impl/device/device.hpp:200]: Can you make sub_device_id the last arg to keep it consistent with other apis?

File: tt_metal/impl/device/device.cpp [hunk 9]
```diff
@@ -3385,14 +3386,14 @@ allocator::Statistics Device::get_memory_allocation_statistics(const BufferType
...
     const auto& allocator = this->get_initialized_allocator();
-    return allocator->config.alignment;
+    return (buffer_type == BufferType::DRAM) ? this->allocator_->config.dram_alignment : this->allocator_->config.l1_alignment;
 }
 
-uint32_t Device::get_allocator_alignment(SubDeviceId sub_device_id) const {
+uint32_t Device::get_allocator_alignment(SubDeviceId sub_device_id, const BufferType &buffer_type) const {
     const auto& allocator = this->get_initialized_allocator(sub_device_id);
-    return allocator->config.alignment;
+    return (buffer_type == BufferType::DRAM) ? this->allocator_->config.dram_alignment : this->allocator_->config.l1_alignment;
```
[the remark this answers is not in the document]
Comment (abhullar-tt) [reply tt_metal/impl/device/device.cpp:3396]: will update

File: tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py [hunk 10]
```diff
@@ -164,14 +164,15 @@ def test_sharded_rm(
         ),
     )
 
-    yt = ttnn.interleaved_to_sharded(xt, grid_size, shard_size, shard_scheme, shard_orientation)
+    yt = ttnn.interleaved_to_sharded(xt, grid_size, shard_size, shard_scheme, shard_orientation, keep_l1_aligned=True)
```
Comment (yugaoTT) [inline tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py:167]: will keep_l1_aligned be removed in the final PR (ie, always use L1 alignment for sharded in L1)?

File: tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py [hunk 11]
```diff
@@ -164,14 +164,15 @@ def test_sharded_rm(
...
 
     zt = ttnn.sharded_to_interleaved(
         yt,
         ttnn.MemoryConfig(
             memory_layout=ttnn.TensorMemoryLayout.INTERLEAVED,
             buffer_type=ttnn.BufferType.L1,
         ),
+        is_l1_aligned=True,
```
Comment (yugaoTT) [inline tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py:175]: same here

**Review by yugaoTT — APPROVED** [review]

File: tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py (hunk 10 above)
Comment (llongTT) [reply tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py:167]: Maybe in a different PR. To avoid making this PR super heavy.

File: tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/common.h [hunk 12]
```diff
@@ -929,8 +929,9 @@ inline void gen_dispatcher_paged_write_cmd(
     uint32_t start_page,
```
Comment (sjameelTT) [inline tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/common.h:929]: we probably want to change this to buffer_type at some point (unrelated to this PR)

File: ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp [hunk 13]
```diff
@@ -171,7 +171,7 @@ operation::ProgramWithCallbacks groupnorm_multi_core_sharded(
     uint32_t per_core_N = a.shard_spec().value().shape[1];
     uint32_t per_core_Mt = per_core_M / TILE_HEIGHT;
     uint32_t per_core_Nt = (per_core_N + TILE_WIDTH - 1) / TILE_WIDTH;
-    uint32_t per_core_N_bytes_padded = round_up_to_mul32(per_core_N * datum_size_bytes);
+    uint32_t per_core_N_bytes_padded = round_up_to_mul16(per_core_N * datum_size_bytes);
```
Comment (sjameelTT) [inline ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp:174]: do we have a tt::round_up(value, alignment)?

**Comment by abhullar-tt** [comment]
@llongTT could you re-run post-commit, BH post commit, Model tests, and ttnn sweeps and update the links in the PR description

**Comment by yugaoTT** [comment]
Please also run the device perf and model pipelines, there are CNN models using group norm so need to make sure those are passing

**Comment by abhullar-tt** [comment]
@cmaryanTT we may need to announce when this change goes in because using l1/dram specific alignment for allocating buffers could expose noc violations when doing misaligned dram -> l1 reads. We could explain how ops are handling this

File: ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp (hunk 13 above)
Comment (llongTT) [reply ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp:174]: Yeah I think there are multiple implementation of the same functionality.

File: tt_metal/impl/dispatch/memcpy.hpp [hunk 14]
```diff
@@ -32,6 +32,14 @@ static inline void memcpy_to_device(void* __restrict dst, const void* __restrict
     uint8_t* dst8 = (uint8_t*)dst;
 
     if (size_t num_lines = n / inner_blk_size) {
+        if ((uintptr_t)dst8 % sizeof(__m256i) != 0) {
```
Comment (jvegaTT) [inline tt_metal/impl/dispatch/memcpy.hpp:35]: Modulo can be quite expensive op and since sizeof is used I don't know how well the optimizer is at realizing this can be done very quickly using bitwise rather than division. I am assuming this is a 256b datatype, if so you could use bitwise operations itself

**Review by jvegaTT — APPROVED** [review]

File: tt_metal/impl/dispatch/memcpy.hpp (hunk 14 above)
Comment (jvegaTT) [reply tt_metal/impl/dispatch/memcpy.hpp:35]: Same applies to __m128i below

Comment (llongTT) [reply tt_metal/impl/dispatch/memcpy.hpp:35]: This is host side code so I think it's OK

File: tech_reports/prog_examples/shard_data_rm/shard_data_rm.md (hunk 5 above)
Comment (llongTT) [reply tech_reports/prog_examples/shard_data_rm/shard_data_rm.md:66]: Added a bit more info regarding the get_allocator_alignment() call

File: ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp (hunk 7 above)
Comment (llongTT) [reply ttnn/cpp/ttnn/operations/data_movement/pad/device/pad_program_factory.cpp]: Renamed

File: ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp (hunk 6 above)
Comment (llongTT) [reply ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp:679]: function call switched

File: tt_metal/impl/dispatch/memcpy.hpp (hunk 14 above)
Comment (jvegaTT) [reply tt_metal/impl/dispatch/memcpy.hpp:35]: Its host side but it is in the memory copy to device function which I don't think can be parallelized away, however given that it is not inside the for loop I think your right, the gain is way too small to matter.

File: ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp (hunk 13 above)
Comment (llongTT) [reply ttnn/cpp/ttnn/operations/normalization/groupnorm/device/multi_core/groupnorm_op_multi_core.cpp]: changed to tt::round_up

**Comment by llongTT** [comment]
> @llongTT could you re-run post-commit, BH post commit, Model tests, and ttnn sweeps and update the links in the PR description

Have them running now.

**Comment by llongTT** [comment]
> Please also run the device perf and model pipelines, there are CNN models using group norm so need to make sure those are passing

Have them running now.

**Comment by cmaryanTT** [comment]
> @cmaryanTT we may need to announce when this change goes in because using l1/dram specific alignment for allocating buffers could expose noc violations when doing misaligned dram -> l1 reads. We could explain how ops are handling this

Noted. @llongTT - please announce on #tt-metal-developers with a brief description of the change and the risks.

Also, @llongTT will be presenting this in the learning forum in a couple of weeks.

**Review by sjameelTT — APPROVED** [review]

**Review by pgkeller — APPROVED** [review]

**Review by aliuTT — APPROVED** [review]

**Review by llongTT — APPROVED** [review]

**Review by mywoodstock — APPROVED** [review]

File: tt_metal/impl/device/device.hpp
Comment (omilyutin-tt) [inline tt_metal/impl/device/device.hpp:1]: Please fix the clang diagnostic errors

**Review by omilyutin-tt — CHANGES_REQUESTED** [review]
Changes to mesh device lgtm

File: tt_metal/impl/device/device.hpp
Comment (llongTT) [reply tt_metal/impl/device/device.hpp:1]: Those are out of date

File: ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp [hunk 15]
```diff
@@ -675,8 +675,7 @@ operation::ProgramWithCallbacks transpose_hc_multi_core(
     // TODO: noc_async_write only require 16B alignment for both DRAM and L1 for Blackhole, so instead of reading in
     // face-lines from C tiles to form a single tile, we can load a single tile and then write out its face-lines to C
     // tiles
-    uint32_t alignment = dst_buffer->buffer_type() == tt::tt_metal::BufferType::DRAM ? hal::get_dram_alignment()
-                                                                                     : hal::get_l1_alignment();
+    uint32_t alignment = dst_buffer->buffer_type() == tt::tt_metal::BufferType::DRAM ? hal::get_dram_alignment();
```
[the remark this answers is not in the document]
Comment (llongTT) [reply ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_program_factory.cpp]: out of date

**Review by omilyutin-tt — APPROVED** [review]
