### PR TITLE
[Fabric] Fix ccl tests after pkt hdr updates

### LINKED ISSUE #35696: [Fabric] CCL tests compilation issue after pkt hdr updates
After adding the infra for dynamically sized packet headers, some CCL tests are failing due to compilation issues.

`error: cannot bind packed field 'pkt_hdr_forward->routing_fields.value' to 'volatile long unsigned int&'`

### PR DESCRIPTION
**Pull request by aagarwalTT**
### Ticket
Closes https://github.com/tenstorrent/tt-metal/issues/35696

### Problem description
1. Compilation failed when attempting to use `std::swap` on `LowLatencyRoutingFieldsT` fields:
```
error: cannot bind packed field 'pkt_hdr_forward->routing_fields.value' to 'volatile long unsigned int&'
```

This occurred in kernels that alternate packet headers for bidirectional fabric load balancing. The root cause: `LowLatencyRoutingFieldsT` is marked `__attribute__((packed))`, which prevents the compiler from creating references to its fields (required by `std::swap`).

2. Additionally, with pkt hdr updates to support extension words as well, the existing kernels were missing swapping of the entire routing fields (value + extension route buffer)

3. The 1d mcast encoding was missing the edge case handling for 0 range hops

### What's changed
1. We dont need to swap the routing fields particularly, just swapping the pkt hdrs will work

2. Fixed the edge case as an early return (all NOOPs)

### Checklist

- [x] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml?query=branch:aagarwal/fix-glx-nightly)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:aagarwal/fix-glx-nightly)
- [ ] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:aagarwal/fix-glx-nightly)
- [x] [Galaxy nightly tests] (https://github.com/tenstorrent/tt-metal/actions/runs/20971344415)
- [x] [T3k unit] (https://github.com/tenstorrent/tt-metal/actions/runs/20943642376)
- [x] [multi-host] (https://github.com/tenstorrent/tt-metal/actions/runs/20943682786)
- [ ] New/Existing tests provide coverage for changes

#### Model tests

If your changes cover model-related code, you should run tests corresponding to affected models and platforms (Single card, T3K, Galaxy). "Choose your pipeline" workflows facilitate running multiple kinds of tests in a single run. Each offers `models-mandatory` and `models-extended` presets.
The former includes a minimal set of tests, to be run always. The latter extends that with additional ones - use your best judgement in deciding which is the most appropriate for your PR.

- [ ] [(Single) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:aagarwal/fix-glx-nightly)
  - [ ] `models-mandatory` preset (runs: [Device perf regressions](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) and [Frequent model and ttnn tests](https://github.com/tenstorrent/tt-metal/actions/workflows/fast-dispatch-full-regressions-and-models.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(T3K) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:aagarwal/fix-glx-nightly)
  - [ ] `models-mandatory` preset (runs: [Unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-model-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(Galaxy) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:aagarwal/fix-glx-nightly)
  - [ ] `models-mandatory` preset (runs: [Quick tests](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-model-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

### CODE REVIEW

File: tt_metal/fabric/fabric_edm_packet_header.hpp [hunk 1]
```diff
@@ -726,6 +726,23 @@ struct LowLatencyRoutingFieldsT {
...
+     */
+    static void swap_volatile(
+        volatile LowLatencyRoutingFieldsT<ExtensionWords>* a, volatile LowLatencyRoutingFieldsT<ExtensionWords>* b) {
+        uint32_t temp_value = a->value;
+        a->value = b->value;
+        b->value = temp_value;
+
+        for (uint32_t i = 0; i < ExtensionWords; i++) {
+            uint32_t temp_buf = a->route_buffer[i];
+            a->route_buffer[i] = b->route_buffer[i];
```
Comment (llongTT) [inline tt_metal/fabric/fabric_edm_packet_header.hpp]: Can you just call swap on the primitive values inside the loop?

File: tt_metal/fabric/fabric_edm_packet_header.hpp [hunk 2]
```diff
@@ -751,6 +768,16 @@ struct LowLatencyRoutingFieldsT<0> {
...
         return result;
     }
+
+    /**
+     * Swap two volatile routing field instances.
+     * Used in kernels that alternate packet headers for load balancing (e.g., bidirectional fabric writes).
+     */
+    static void swap_volatile(volatile LowLatencyRoutingFieldsT<0>* a, volatile LowLatencyRoutingFieldsT<0>* b) {
+        uint32_t temp = a->value;
+        a->value = b->value;
```
Comment (llongTT) [inline tt_metal/fabric/fabric_edm_packet_header.hpp]: Same here.

File: tt_metal/fabric/fabric_edm_packet_header.hpp (hunk 1 above)
Comment (aagarwalTT) [reply tt_metal/fabric/fabric_edm_packet_header.hpp]: but calling std::swap would essentially bring us back to the original problem of the compiler not being able to bind references for the values in the packed struct, right?

Comment (llongTT) [reply tt_metal/fabric/fabric_edm_packet_header.hpp]: I see, the compiler fails even with swap of uint32_t type as well.
Then we have to do such manual swap.
Just to make sure the code handles generic types or the packet header only contains uint32_t compatible types.

Comment (SeanNijjar) [reply tt_metal/fabric/fabric_edm_packet_header.hpp]: is the problem that the fields of the stuct are packed?

Comment (aagarwalTT) [reply tt_metal/fabric/fabric_edm_packet_header.hpp]: yes. I could try removing the packed attribute but that might introduce some implicit padding and could complicate the header size calculation especially when we have dynamically sized the routing fields.

**Review by jbaumanTT — APPROVED** [review]

**Review by jvegaTT — COMMENTED** [review]
Bh apc is hanging on a ccl test in this pipeline. Can you investigate this before merging since it might be related?

**Comment by aagarwalTT** [comment]
> Bh apc is hanging on a ccl test in this pipeline. Can you investigate this before merging since it might be related?

Looks like a device side issue

2026-01-09 23:24:56.565 | critical |          Always | TT_THROW: Device 7: Timed out while waiting for active ethernet core (x=31,y=25) to become active again. Try resetting the board. Minimum tt-firmware version is 18.10.0 (assert.hpp:104)

I can re-run the pipeline

**Review by jvegaTT — APPROVED** [review]
Thanks for checking, approving
