### PR TITLE
Fix CB size calculation in non-sharded `matmul` with transpose-A and user core grid

### LINKED ISSUE #36426: [matmul] L1 OOM on n150 when specifying core grid for some shapes
### Component / Area

ops

### Issue Type (optional)

Out of Memory

### Observed

ttnn.matmul  (8192, 11008) @  (8192, 4096), transpose_a=True, core_grid = ttnn.CoreGrid(y=compute_grid.y, x=compute_grid.x)
 fails for some shapes with L1 OOM

```
2026-01-23 20:46:27.088 | critical |          Always | TT_THROW: Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=7)] grow to 1721472 B which is beyond max L1 size of 1499136 B (assert.hpp:104)
Traceback (most recent call last):
  File "/home/pasha/projects/tt-metal/./experiments/matmul_example.py", line 41, in <module>
    test_matmul(device)
  File "/home/pasha/projects/tt-metal/./experiments/matmul_example.py", line 22, in test_matmul
    c = ttnn.matmul(
  File "/home/pasha/projects/tt-metal/ttnn/ttnn/decorators.py", line 449, in __call__
    result = self.function(*function_args, **function_kwargs)
RuntimeError: TT_THROW @ /home/pasha/projects/tt-metal/tt_metal/impl/program/program.cpp:908: tt::exception
info:
Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=7)] grow to 1721472 B which is beyond max L1 size of 1499136 B
```

### Expected

No OOM

### 1. Steps (exact commands)

```python
import ttnn
import torch

device = ttnn.open_device(device_id=0)


def test_matmul(device):
    shape_a = (8192, 11008)
    shape_b = (8192, 4096)
    
    a = ttnn.rand(shape_a, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device, low=0.0, high=1.0, seed=42)
    b = ttnn.rand(shape_b, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device, low=0.0, high=1.0, seed=43)

    torch_a = ttnn.to_torch(a)
    torch_b = ttnn.to_torch(b)
    
    # Get core grid from device
    compute_grid = device.compute_with_storage_grid_size()
    core_grid = ttnn.CoreGrid(y=compute_grid.y, x=compute_grid.x)
    
    # ttnn matmul with transpose_a=True, core_grid, and compute_kernel_config
    c = ttnn.matmul(
        a,
        b,
        transpose_a=True,
        core_grid=core_grid,
    )
    
    # torch equivalent: transpose A then matmul
    torch_c = torch.matmul(torch_a.transpose(-1, -2), torch_b)

    ttnn_out_torch = ttnn.to_torch(c)

    print(f"ttnn output shape: {ttnn_out_torch.shape}")
    print(f"torch output shape: {torch_c.shape}")
    print(f"Absolute difference: {torch.abs(torch_c - ttnn_out_torch).max()}")
    print(f"Relative difference: {torch.abs(torch_c - ttnn_out_torch).max() / torch_c.abs().max()}")


try:
    test_matmul(device)
finally:
    ttnn.close_device(device)
```

### 2. Input data / link or description

 (8192, 11008) @  (8192, 4096), transpose_a=True, core_grid = ttnn.CoreGrid(y=compute_grid.y, x=compute_grid.x)

When core_grid is None, issues disappears, but AFAIK None core_grid has slightly worse performance. Seems like op lacks some L1 allocation check, and chooses wrong program factory. 

### 3. Frequency

Always

### 1. Software Versions

Ubuntu 24
Latest main at the moment (6cf84a1e2ba0cdee0712bcaa0237535aa8f630c2) 

### 2. Hardware Details

n150

### Is this a regression?

Unknown

### Regression Details

_No response_

### Logs & Diagnostics

_No response_

### Priority

P2

### Impact

_No response_

### PR DESCRIPTION
**Pull request by gajanan-choudhary**
### Ticket
Fixes #36426.

### Problem description
* Non-sharded, transpose-A `matmul` with user-provided `core_grid` was failing with L1/SRAM out-of-memory error
* Root-cause was that `matmul` circular buffer size calculations did not account for this code-path.
    - Both sharded and non-sharded cases for `transpose` require an additional circular buffer to hold the transpose. 
    - Sharded `matmul` code-path handled this correctly
    - Non-sharded `matmul` code-path did not handle this correctly for user-specified core grid.
    - See comments in #36426 for function calls that are taken for this failing configuration

### What's changed
* Adds in missing memory to be requested for non-sharded transpose-A `matmul` case with user-specified core grid
* Updates `test_matmul.py` with a new test that covers the affected configuration. New test takes about 10 seconds to run.

### Checklist

- [x] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml?query=branch:gchoudhary/36426-fix-CB-size-calculations-in-non-sharded-transpose_a-matmul)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:gchoudhary/36426-fix-CB-size-calculations-in-non-sharded-transpose_a-matmul)
- [x] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:gchoudhary/36426-fix-CB-size-calculations-in-non-sharded-transpose_a-matmul)
- [x] New/Existing tests provide coverage for changes: `tests/ttnn/unit_tests/operations/matmul/test_matmul.py::test_matmul_transpose_with_core_grid`

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/matmul/device/utilities/matmul_utilities.cpp [hunk 1]
```diff
@@ -41,10 +41,6 @@ uint32_t get_estimated_size_of_cbs(
         auto* in0_buffer = input_tensor_a.buffer();
         const auto in0_tile = utilities::get_matmul_tile(input_tensor_a, transpose_a);
         in0_shard_width_in_tiles = in0_buffer->shard_spec().shape()[1] / in0_tile.get_width();
-        if (transpose_a) {
-            // An intermediate CB (c_10) of same size is needed to hold the transposed data
-            in0_shard_width_in_tiles *= 2;
-        }
```
Comment (gajanan-choudhary) [inline ttnn/cpp/ttnn/operations/matmul/device/utilities/matmul_utilities.cpp:47]: Changes below also account for both sharded and non-shared code-paths, so this is being removed from here.

File: tests/ttnn/unit_tests/operations/matmul/test_matmul.py [hunk 2]
```diff
@@ -1877,6 +1877,57 @@ def test_matmul_with_transpose_a_or_b(device, n_size, c, m, k, n, transpose_a, t
     assert_with_pcc(torch_output_tensor, output, 0.999)
 
 
+@pytest.mark.parametrize(
+    "m, k, n",
+    [
+        (8193, 512, 2048),
+        (11008, 256, 2048),
```
[the remark this answers is not in the document]
Comment (gajanan-choudhary) [reply tests/ttnn/unit_tests/operations/matmul/test_matmul.py:1876]: 1. The test currently takes less than 10 seconds to run, and
2. This failure occurs only in larger `m`/`k`/`n` configurations

so we will not implement this suggestion

File: tests/ttnn/unit_tests/operations/matmul/test_matmul.py [hunk 3]
```diff
@@ -1877,6 +1877,57 @@ def test_matmul_with_transpose_a_or_b(device, n_size, c, m, k, n, transpose_a, t
...
+        # (11008, 8192, 4096), #Original issue: too slow to run, also requires lower PCC
+        # (50272, 16384, 384), #Original issue: too slow to run, also requires lower PCC
```
[the remark this answers is not in the document]
Comment (gajanan-choudhary) [reply tests/ttnn/unit_tests/operations/matmul/test_matmul.py]: Removed the commented test in latest commit.

File: tests/ttnn/unit_tests/operations/matmul/test_matmul.py [hunk 4]
```diff
@@ -1877,6 +1877,55 @@ def test_matmul_with_transpose_a_or_b(device, n_size, c, m, k, n, transpose_a, t
...
+        (11008, 256, 2048),
+    ],
+)
+@pytest.mark.parametrize("transpose_a", [True])  # "False, " makes torch.matmul() too slow
+@pytest.mark.parametrize("transpose_b", [False])  # ", True" makes ttnn.matmul() too slow for now
+def test_matmul_transpose_with_core_grid(device, m, k, n, transpose_a, transpose_b):
+    torch.manual_seed(0)
+
+    shape_a = (k, m) if transpose_a == True else (m, k)
+    shape_b = (n, k) if transpose_b == True else (k, n)
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/matmul/test_matmul.py]: Just have
```
# transpose a to test corner case for CB size estimate
transpose_a = True
transpose_b = False
shape_a = (k, m)
shape_b = (k, n)
```
and remove the pytest parameters.

**Review by bbradelTT — APPROVED** [review]

File: tests/ttnn/unit_tests/operations/matmul/test_matmul.py (hunk 4 above)
Comment (gajanan-choudhary) [reply tests/ttnn/unit_tests/operations/matmul/test_matmul.py]: Done in 7575dc9

**Review by gajanan-choudhary — COMMENTED** [review]
Just adding the output comparison of the new test on this branch versus on `main` as a separate comment since PR descriptions are used for commit body when merging the PR into main:

* Output of the new test on WH with this branch:
    ```
    ================================================================================== short test summary info ===================================================================================
    PASSED tests/ttnn/unit_tests/operations/matmul/test_matmul.py::test_matmul_transpose_with_core_grid[transpose_b=False-transpose_a=True-m=8193-k=512-n=2048]
    PASSED tests/ttnn/unit_tests/operations/matmul/test_matmul.py::test_matmul_transpose_with_core_grid[transpose_b=False-transpose_a=True-m=11008-k=256-n=2048]
    ===================================================================================== 2 passed in 8.39s ======================================================================================
    ```
* Output of the new test on WH with the `main` branch reproducing the failures seen in #36426:
    ```
    ================================================================================== short test summary info ===================================================================================
    FAILED tests/ttnn/unit_tests/operations/matmul/test_matmul.py::test_matmul_transpose_with_core_grid[transpose_b=False-transpose_a=True-m=8193-k=512-n=2048] - RuntimeError: TT_THROW @ /localdev/gchoudhary/tt-metal/tt_metal/impl/program/program.cpp:932: tt::exception
    info:
    Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=7)] grow to 1520928 B which is beyond max L1 size of 1499136 B
    ...
    FAILED tests/ttnn/unit_tests/operations/matmul/test_matmul.py::test_matmul_transpose_with_core_grid[transpose_b=False-transpose_a=True-m=11008-k=256-n=2048] - RuntimeError: TT_THROW @ /localdev/gchoudhary/tt-metal/tt_metal/impl/program/program.cpp:932: tt::exception
    info:
    Statically allocated circular buffers on core range [(x=0,y=0) - (x=7,y=7)] grow to 1721632 B which is beyond max L1 size of 1499136 B
    ```
