### PR TITLE
Move recreation of inspector logging directory in its initilization

### LINKED ISSUE #23523: TT_INSPECTOR: std::filesystem::remove_all throws exception
### Describe the bug
```
unknown file: Failure
C++ exception with description "filesystem error: cannot remove all: No such file or directory [/home/jchu/tt-metal-worktree/distributed-launch/generated/inspector] [/home/jchu/tt-metal-worktree/distributed-launch/generated/inspector/programs_l
og.yaml]" thrown in SetUp().
```
Context: I'm running with multiple processes so there is a race condition because the file directory creation/removal is not multi-process safe. 

### Steps to reproduce the issue

_No response_

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by tt-vjovanovic**
With this change, removal and creation of `generated/inspector` directory is moved into Inspector logger class from `rtoptions.cpp`. This way, one can disable its failure by setting `TT_METAL_INSPECTOR_INITIALIZATION_IS_IMPORTANT` environment variable to `0`.
Also, we won't initialize Inspector data if Inspector is not enabled.

### CODE REVIEW

File: tt_metal/impl/debug/inspector_impl.cpp [hunk 1]
```diff
@@ -11,8 +11,20 @@
 namespace tt::tt_metal::inspector {
 
 Logger::Logger(const std::filesystem::path& logging_path)
-    : programs_ostream(logging_path / "programs_log.yaml", std::ios::trunc)
-    , kernels_ostream(logging_path / "kernels.yaml", std::ios::trunc) {
+    : initialized(false)
+{
+#define ADDITIONAL_ERROR_TEXT "\nYou can disable exception by setting TT_METAL_INSPECTOR_INITIALIZATION_IS_IMPORTANT=0 in your environment variables. Note that this will not throw an exception, but will log a warning instead. Running without Inspector logger will impact tt-triage functionality."
```
Comment (tt-dma) [inline tt_metal/impl/debug/inspector_impl.cpp]: `string_view` or `constexpr string` here instead of define?

Comment (tt-vjovanovic) [reply tt_metal/impl/debug/inspector_impl.cpp]: Well, this is old school string concatenation (C style), not sure how it works for c++ strings... Maybe I can use string_view and then add it as a format parameter...

Comment (tt-dma) [reply tt_metal/impl/debug/inspector_impl.cpp]: If TT_INSPECTOR_THROW is like TT_THROW, can ADDITIONAL_ERROR_TEXT just be supplied as an arg using `{}` as well?

Comment (tt-vjovanovic) [reply tt_metal/impl/debug/inspector_impl.cpp]: done

**Review by tt-dma — APPROVED** [review]

**Review by tt-aho — APPROVED** [review]

**Review by tt-asaigal — APPROVED** [review]
