### PR TITLE
Expose TelemetryRunning health metric that survives UMD initialization failures

### LINKED ISSUE #30929: Handling situations where telemetry cannot be obtained
Telemetry must be robust and reliable. However, when devices are down or in a bad state and need to be reset, we can't read any metrics. In fact, `tt::umd::Cluster` initialization will fail altogether. For example, on ClosetBox today (Oct 21):

metal-wh-11:

```
2025-10-21 14:05:24.217 | info     |             UMD | Harvesting mask for chip 3 is 0x204 (NOC0: 0x204, simulated harvesting mask: 0x0). (cluster.cpp:394)
2025-10-21 14:05:24.318 | info     |             UMD | Harvesting mask for chip 2 is 0x82 (NOC0: 0x82, simulated harvesting mask: 0x0). (cluster.cpp:394)
2025-10-21 14:05:24.322 | info     |             UMD | Harvesting mask for chip 1 is 0x120 (NOC0: 0x120, simulated harvesting mask: 0x0). (cluster.cpp:394)
2025-10-21 14:05:24.326 | info     |             UMD | Harvesting mask for chip 0 is 0x300 (NOC0: 0x300, simulated harvesting mask: 0x0). (cluster.cpp:394)
2025-10-21 14:05:24.330 | info     |             UMD | Harvesting mask for chip 7 is 0x280 (NOC0: 0x280, simulated harvesting mask: 0x0). (cluster.cpp:394)
2025-10-21 14:05:24.339 | info     |             UMD | Harvesting mask for chip 6 is 0x220 (NOC0: 0x220, simulated harvesting mask: 0x0). (cluster.cpp:394)
2025-10-21 14:05:25.321 | info     |          Always | WebSocket client connected (total clients: 1) (collection_endpoint.cpp:100)
2025-10-21 14:05:29.395 | critical |          Always | Fatal exception during telemetry thread initialization: Timeout waiting for Ethernet core service remote IO request. (telemetry_collector.cpp:295)
2025-10-21 14:05:29.395 | info     |          Always | Telemetry thread stopped (telemetry_collector.cpp:300)
```

metal-wh-10:

```
2025-10-21 14:04:51.837 | critical |          Always | Fatal exception during telemetry thread initialization: No existing board type for board id 0x401e1e5200030166 (telemetry_collector.cpp:295)
2025-10-21 14:04:51.837 | info     |          Always | Telemetry thread stopped (telemetry_collector.cpp:300)
2025-10-21 14:04:53.317 | info     |          Always | WebSocket client connected (total clients: 1) (collection_endpoint.cpp:100)
```

These exceptions were thrown from the constructor of `tt::umd::Cluster` and caused the telemetry thread to abort. This means no telemetry is broadcast.

There should be some way of detecting this state via telemetry metrics. A couple of possible solutions:

1. Create a host-level metric named e.g. `TelemetryAvailable` or `UMDInitialized`. This would be set to a BAD state if an exception is caught during initialization. The question then becomes whether to run the telemetry thread loop indefinitely (nothing would change because only this metric would exist), forcing users to restart telemetry, or simple sleeping for some fixed duration (e.g., 2*monitori_interval, ensuring there is enough time for a scraper to pick up the telemetry) and then dying, allowing the app to be restarted by the orchestrator (i.e., Kubernetes). The latter is probably a better idea. Eventually, it may be possible to detect a device reset, although in this case where UMD is *not* initialized at all, it is not yet clear. We will need to keep in touch with the UMD team working on reset signaling.

2. (Not mutually exclusive with solution 1): Split up metric *creation* from metric *initialization*. We generally know all the metric names (except maybe ARC, which is accessible only on certain devices) from FSD and could create them before we know which chip IDs they are associated with. Once UMD is successfully initialized, we could then have a second initialization or binding step that actually initiates device polling. The metrics would need to first come up in an "invalid" state and, unfortunately, I don't think the Prometheus protocol supports this except maybe as a custom attribute. We would need to rely on default values. It arguably could be better to simply avoid creating metrics that aren't readable and simply use the solution in [1].

### PR DESCRIPTION
**Pull request by kkfernandezTT**
### Ticket
Fixes #30929

### Problem description
When devices are down or in a bad state requiring reset, `tt::umd::Cluster` initialization fails with exceptions, causing the telemetry thread to abort completely. This means no metrics are exposed, making it impossible to detect the failure state via monitoring systems like Prometheus.

Example failures from ClosetBox (Oct 21):
- metal-wh-11: "Timeout waiting for Ethernet core service remote IO request"
- metal-wh-10: "No existing board type for board id 0x401e1e5200030166"

These exceptions prevent any telemetry from being broadcast, leaving monitoring systems blind to the failure.

### What's changed
Implemented solution [1] from the issue: expose a host-level `TelemetryRunning` boolean metric that survives UMD initialization failures.

**Key changes:**
- Added `SystemBoolMetric` class for host-level health metrics (separate from hierarchical device metrics) in tt_telemetry/include/telemetry/metric.hpp:89-117
- Create `TelemetryRunning` metric before UMD initialization in tt_telemetry/telemetry/telemetry_collector.cpp:269, ensuring it exists regardless of initialization outcome
- Wrapped UMD initialization in try-catch block at tt_telemetry/telemetry/telemetry_collector.cpp:282-338:
  - Success: `TelemetryRunning = true`
  - Failure: `TelemetryRunning = false` (error details in logs)
- When initialization fails, expose the failure metric for a configurable duration (default 30s via `--failure-exposure-duration` flag) before exiting
- Send periodic heartbeats during failure exposure to prevent watchdog timeout
- Extended `prom_formatter.cpp` to handle system metrics with simplified path format (`hostname/system/MetricName`)
- Updated `TelemetrySnapshot` infrastructure with system metric fields and JSON serialization
- Added Docker Compose monitoring stack with Prometheus and Grafana for testing and demonstration

**Impact:**
Monitoring systems can now detect telemetry failures via the `TelemetryRunning` metric. When the metric is `false`, orchestrators (e.g., Kubernetes) can restart the telemetry pod, enabling self-healing infrastructure. Error details remain in application logs to avoid Prometheus label cardinality issues.

**Prometheus output:**
```
# HELP TelemetryRunning System-level health metric
# TYPE TelemetryRunning gauge
TelemetryRunning{} 1
```

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml) CI passes (if applicable)
- [ ] [Galaxy demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_telemetry/include/telemetry/metric.hpp [hunk 1]
```diff
@@ -85,6 +85,37 @@ class BoolMetric: public Metric {
...
+
+    void set_value(bool value) {
+        value_ = value;
+        changed_since_transmission_ = true;
+        timestamp_ =
+            std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch())
+                .count();
+    }
+
+    void set_labels(const std::unordered_map<std::string, std::string>& labels) {
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/include/telemetry/metric.hpp]: I think the labels are probably not a great idea, although I can see the utility of having an error attribute dumped to Prometheus. However, I think this should be done in a more generic way and scrapped from this PR. The question is: is this typically done in other telemetry systems (the usage of arbitrary strings to describe conditions attached as attributes)? Sysadmins can check the log to see what happened if they need to. 

My recommendation is to remote it, open another issue, and then do it as a separate PR. I think that we would want to think about having a more generic mechanism of setting arbitrary attributes. And when those attributes are present in a snapshot, they are emitted, otherwise they are omitted. This could become a part of the base metric class instead of needing this special SystemMetric case.

File: tt_telemetry/telemetry/telemetry_collector.cpp [hunk 2]
```diff
@@ -185,7 +188,26 @@ static void send_initial_snapshot(const std::vector<std::shared_ptr<TelemetrySub
     }
 }
 
+// Helper to build system metric path with labels embedded
+static std::string get_system_metric_path_with_labels(const SystemBoolMetric& metric) {
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/telemetry/telemetry_collector.cpp]: This is unnecessary. There is already a function to return the path from the metric itself, so why not embed "system" in there?

File: tt_telemetry/telemetry/telemetry_collector.cpp [hunk 3]
```diff
@@ -185,7 +188,26 @@ static void send_initial_snapshot(const std::vector<std::shared_ptr<TelemetrySub
...
+    // Format: hostname/system/MetricName
+    // Labels will be added by prom_formatter from the metric's label map
+    return std::string(hostname_) + "/system/" + metric.name();
+}
+
 static void update_delta_snapshot_with_local_telemetry(std::shared_ptr<TelemetrySnapshot> snapshot) {
+    // Update system metrics
+    for (size_t i = 0; i < system_bool_metrics_.size(); i++) {
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/telemetry/telemetry_collector.cpp]: I think this should just be a bool metric. No need to add another fundamental type. Especially if labels are removed.

File: tt_telemetry/telemetry/telemetry_collector.cpp [hunk 4]
```diff
@@ -242,25 +265,91 @@ static void telemetry_thread(
...
+                log_info(tt::LogAlways, "Our hostname is: {}", topology_translation->my_host_name);
+
+                create_ethernet_metrics(
+                    bool_metrics_, uint_metrics_, double_metrics_, cluster, fsd, topology_translation, hal);
+                create_arc_metrics(bool_metrics_, uint_metrics_, double_metrics_, cluster, topology_translation, hal);
+                log_info(tt::LogAlways, "Initialized metrics");
+
+                // Update TelemetryRunning metric to success state
+                telemetry_running.set_value(true);
+            } catch (const std::exception& e) {
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/telemetry/telemetry_collector.cpp:321]: I think this can be done more elegantly. I don't like the idea of a second while loop inside of a catch. Catch blocks should be very small. What I recommend doing instead is, inside the catch block, mark the telemetry running metric as bad and then just set an end time, similar to how you do now (can be a single line of code). 

Then, in the main loop, modify the condition so that it has an end condition. By default, the loop should run infinitely (maybe the end time is infinite or the end time is an optional that, if empty, just means the loop runs forever).

File: tt_telemetry/telemetry/telemetry_collector.cpp [hunk 5]
```diff
@@ -242,25 +265,91 @@ static void telemetry_thread(
...
+                // Error details are logged above and available in application logs
+                telemetry_running.set_value(false);
+
+                // Run failure exposure loop to allow Prometheus to scrape the failure state
+                auto failure_start = std::chrono::steady_clock::now();
+                auto failure_duration = std::chrono::seconds(failure_exposure_duration_seconds);
+                auto failure_end = failure_start + failure_duration;
+
+                // Calculate end time as system_clock time for display
+                auto now_system = std::chrono::system_clock::now();
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/telemetry/telemetry_collector.cpp]: I don't think we need this. It just adds a wall of code to read. If you feel wall clock time is needed, I would refactor into a function so as not to have all this code in the main function.

**Review by btrzynadlowski-tt — CHANGES_REQUESTED** [review]

File: tt_telemetry/include/telemetry/metric.hpp (hunk 1 above)
Comment (kkfernandezTT) [reply tt_telemetry/include/telemetry/metric.hpp]: Agree

File: tt_telemetry/telemetry/telemetry_collector.cpp (hunk 3 above)
Comment (kkfernandezTT) [reply tt_telemetry/telemetry/telemetry_collector.cpp]: Sure

File: tt_telemetry/telemetry/arc/arc_metrics.cpp [hunk 6]
```diff
@@ -182,9 +182,7 @@ void ARCUintMetric::update(
     uint64_t old_value = value_;
     changed_since_transmission_ = new_value != old_value;
     value_ = new_value;
-    timestamp_ =
-        std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch())
-            .count();
+    set_timestamp_now();
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/telemetry/arc/arc_metrics.cpp:185]: Can you also update ethernet metrics to use this new function?

File: tt_telemetry/telemetry/telemetry_collector.cpp [hunk 7]
```diff
@@ -242,25 +276,61 @@ static void telemetry_thread(
             watchdog_timeout_seconds,
             MONITOR_INTERVAL_SECONDS.count());
 
+        // Create TelemetryRunning system metric BEFORE UMD initialization
+        system_bool_metrics_.push_back(
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/telemetry/telemetry_collector.cpp]: I don't think we need a system_bool_metrics_. Why not just store this in bool_metrics? Just retain a pointer or reference to this specific metric if you need it in the function body (system_bool_metrics_.back() is very confusing).

File: tt_telemetry/include/telemetry/metric.hpp [hunk 8]
```diff
@@ -45,7 +45,13 @@ class Metric {
 
     Metric(MetricUnit metric_units = MetricUnit::UNITLESS) : units(metric_units) {}
 
+    Metric(std::vector<std::string> path, MetricUnit metric_units = MetricUnit::UNITLESS) :
+        units(metric_units), custom_path_(std::move(path)) {}
+
     virtual const std::vector<std::string> telemetry_path() const {
+        if (!custom_path_.empty()) {
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/include/telemetry/metric.hpp]: This is confusing. System metrics should not abuse the base class but derive from it. Right now, there is only a single "system" metric -- so you can just create a new header file that defines TelemetryRunningMetric. If you envision there being more of these, you can call it SystemMetric or TelemetryStateMetric, or whatever (see how I do ARC metrics -- they just take a name to differentiate them but otherwise they are pretty much the same). 

Then your derived class just implements the path method. No need to modify the base Metric constructor.

File: tt_telemetry/telemetry/telemetry_collector.cpp [hunk 9]
```diff
@@ -242,25 +276,61 @@ static void telemetry_thread(
...
+            std::make_unique<BoolMetric>(std::vector<std::string>{"system", "TelemetryRunning"}));
+        system_bool_metrics_.back()->set_value(false);  // Initially not running
+
+        // Keep reference for updates (safe since vector never removes elements)
+        auto& telemetry_running = *system_bool_metrics_.back();
```
Comment (btrzynadlowski-tt) [inline tt_telemetry/telemetry/telemetry_collector.cpp]: Ah, you do have a reference here.

**Review by btrzynadlowski-tt — CHANGES_REQUESTED** [review]

File: tt_telemetry/telemetry/telemetry_collector.cpp (hunk 9 above)
Comment (kkfernandezTT) [reply tt_telemetry/telemetry/telemetry_collector.cpp]: I just realized this is unsafe if the vector reallocates, hence changing to index access.

File: tt_telemetry/include/telemetry/metric.hpp (hunk 8 above)
Comment (kkfernandezTT) [reply tt_telemetry/include/telemetry/metric.hpp]: Good recommendation 👍🏻

File: tt_telemetry/telemetry/arc/arc_metrics.cpp (hunk 6 above)
Comment (kkfernandezTT) [reply tt_telemetry/telemetry/arc/arc_metrics.cpp:185]: Yes, done

**Review by btrzynadlowski-tt — APPROVED** [review]
