### PR TITLE
#19983: Deregionify linker scripts, compute LMA

### LINKED ISSUE #19819: [Bug Report] Large(ish) compute kernels don't compile
**Describe the bug**
I have a large compute kernel (around 650 LoC) and when I compile it I think it is overflowing the space allocated to it by the linker script, I get the error:

`BuildKernels | ERROR    | trisc2 link failure -- cmd: cd /opt/tenstorrent/0.56/tt-metal/built/15db9cc90e/4098/kernels/compute/16026678697130539632/trisc2/ && /opt/tenstorrent/0.56/tt-metal/runtime/sfpi/compiler/bin/riscv32-unknown-elf-g++ -O3 -Wl,--just-symbols=/opt/tenstorrent/0.56/tt-metal/built/15db9cc90e/4098/firmware/trisc2/trisc2_weakened.elf -mcpu=tt-wh -std=c++17 -flto -ffast-math -fno-exceptions -Wl,-z,max-page-size=16 -Wl,-z,common-page-size=16 -nostartfiles -T/opt/tenstorrent/0.56/tt-metal/runtime/hw/toolchain/wormhole/kernel_trisc2.ld -Wl,--emit-relocs trisck.o /opt/tenstorrent/0.56/tt-metal/runtime/hw/lib/wormhole/tmu-crt0k.o /opt/tenstorrent/0.56/tt-metal/runtime/hw/lib/wormhole/substitutes.o -o /opt/tenstorrent/0.56/tt-metal/built/15db9cc90e/4098/kernels/compute/16026678697130539632/trisc2/trisc2.elf
           BuildKernels | ERROR    | /opt/tenstorrent/0.56/tt-metal/runtime/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.4.0/../../../../riscv32-unknown-elf/bin/ld: address 0xffb00504 of /opt/tenstorrent/0.56/tt-metal/built/15db9cc90e/4098/kernels/compute/16026678697130539632/trisc2/trisc2.elf section `.data' is not within region `TRISC2_LOCAL_DATA_MEM'
/opt/tenstorrent/0.56/tt-metal/runtime/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.4.0/../../../../riscv32-unknown-elf/bin/ld: /opt/tenstorrent/0.56/tt-metal/built/15db9cc90e/4098/kernels/compute/16026678697130539632/trisc2/trisc2.elf section `.bss' will not fit in region `TRISC2_LOCAL_DATA_MEM'
/opt/tenstorrent/0.56/tt-metal/runtime/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.4.0/../../../../riscv32-unknown-elf/bin/ld: address 0xffb00504 of /opt/tenstorrent/0.56/tt-metal/built/15db9cc90e/4098/kernels/compute/16026678697130539632/trisc2/trisc2.elf section `.data' is not within region `TRISC2_LOCAL_DATA_MEM'
/opt/tenstorrent/0.56/tt-metal/runtime/sfpi/compiler/bin/../lib/gcc/riscv32-unknown-elf/12.4.0/../../../../riscv32-unknown-elf/bin/ld: region `TRISC2_LOCAL_DATA_MEM' overflowed by 4 bytes
collect2: error: ld returned 1 exit status`

**To Reproduce**
I attach my current files in a zip including the compute kernel. This will recreate the issue, however note that I am unsure if it will terminate properly yet as it won't compile.

**Expected behavior**
Expected behaviour is for it to compile and launch, as I say I am unsure if it will terminate but just compiling and launching would be success

[fft_one_cpy.zip](https://github.com/user-attachments/files/19495065/fft_one_cpy.zip)

**Screenshots**

**Please complete the following environment information:**
- OS: Ubuntu 22
- Version of software (eg. commit): Metal 0.56 release

**Additional context**

### PR DESCRIPTION
**Pull request by nathan-TT**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/19983
https://github.com/tenstorrent/tt-metal/issues/19819

### Problem description
Memory regions won't play well with a dynamic stack size.  Nor do they give a helpful overflow failure mode.

This preparatory patch removes them

### What's changed
* Use explicit start addresses for text, data & stack
* Manually compute data-like section LMAs
* Add .phdr meta-data non-loadable section, containing size limits
* Check sizes when loading image
* Rename `__fw_export_end_text` to `__fw_export_text_end` for consistency

The `memory.ld` file no longer contains memory regions.  the next patch will rearrange the files, without otherwise changing contents.

### Checklist
- [YES] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [YES] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_metal/llrt/tt_elffile.cpp [hunk 1]
```diff
@@ -332,6 +332,34 @@ void ElfFile::Impl::LoadImage() {
...
+            // Specifies phdr size limits
+            auto bytes = GetContents(section);
+            auto words = std::span(reinterpret_cast<uint32_t const *>(bytes.data()), bytes.size() / sizeof(uint32_t));
+            for (unsigned ix = 0; ix != words.size(); ix++) {
+                if (ix >= GetSegments().size())
+                    continue;
+                uint32_t limit = words[ix];
+                auto const &seg = GetSegments()[ix];
+                if (seg.membytes > limit) {
+                    TT_THROW("{}: phdr[{}] [{},+{}) overflows limit of {} bytes", path_, ix,
```
Comment (pgkeller) [inline tt_metal/llrt/tt_elffile.cpp:346]: If this check and the one below can be triggered by code issues (eg, text too big, data too big) we need more specific error messages, like: "data overflows limit: blah blah.  Try reducing number of global variables in file xyz".  Or some such

Comment (nathan-TT) [reply tt_metal/llrt/tt_elffile.cpp]: telling the user 'decrease code size' or 'reduce globals' is the best we can do at this point -- we don't have visibility of the inputs to the executable.  But of course they do now have the executable to examine.

The other error is a consistency check, the loader has several other cases, which all mean we messed up somewhere.

Comment (nathan-TT) [reply tt_metal/llrt/tt_elffile.cpp]: to avoid embedding linker-script knowledge into tt_elffile, we could have the reason strings placed in the .phdrs section.  But that's probably over-engineering, until we find what I have here is inadequate

**Review by jbaumanTT — APPROVED** [review]

**Review by nhuang-tt — APPROVED** [review]

**Review by aliuTT — APPROVED** [review]
