### PR TITLE
#12046: Populate/use Buffer ctor "allocate" field in CreateBuffer() & deallocate()

### LINKED ISSUE #12046: [FeatureRequest/Bug] Buffer::deallocate() should be NOP if Buffer wasn't allocated in first place (allocate=false on Buffer constructor)
**Describe the bug**

When tt-torge/tt-mlir uses tt-metal, they will pre-allocate memory for tensors, but use tt-metal `CreateBuffer()` API for creating a Buffer as a view over existing memory, and then override the address to be the pre-allocated address. We (tt-mlir) want to control alloc/dealloc of these Buffers when they are created as views over Tensors we manage and pass to metal APIs.  Example from https://github.com/tenstorrent/tt-mlir/blob/main/runtime/include/tt/runtime/detail/ttmetal.h#L158 : 

```
  std::shared_ptr<::tt::tt_metal::Buffer> buffer = ::tt::tt_metal::CreateBuffer(shardedBufferConfig);
  buffer->set_address(tensorRef->address());
```
Works okay functionally, except for couple issue that this ticket aims to resolve:

1. `CreateBuffer()` path will allocate more memory needlessly, and update global `detail::BUFFER_MAP` during `Buffer::allocate()` to keep track of this buffer (which later points to not-used address).
2. During teardown via `Device::close()` all `Buffers` in `detail::BUFFER_MAP` (raw ptrs) are iterated over and attempted to be deallocated, which will lead to segfault on `buffer.deallocate()` call if the Buffer object is already deallocated and destroyed by tt-forge. Spoiler: It is, so we hit this case in our first tt-metal backend workloads.

**Repro**

See https://github.com/tenstorrent/tt-mlir/issues/408, it shows this:

```
Thread 1 "pt_main_thread" received signal SIGSEGV, Segmentation fault.
0x00007ffff48d9653 in tt::tt_metal::DeallocateBuffer(tt::tt_metal::Buffer&) () from /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libtt_metal.so
(gdb) bt
#0  0x00007ffff48d9653 in tt::tt_metal::DeallocateBuffer(tt::tt_metal::Buffer&) () from /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libtt_metal.so
#1  0x00007ffff482803a in tt::tt_metal::Device::close() () from /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libtt_metal.so
#2  0x00007ffff48435a0 in tt::DevicePool::close_device(int) const () from /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libtt_metal.so
#3  0x00007ffff6a5d3c3 in tt::runtime::ttmetal::closeDevice (device=...) at /localdev/kmabee/mlir2/runtime/lib/ttmetal/runtime.cpp:63
#4  0x00007ffff69347cd in tt::runtime::closeDevice (device=...) at /localdev/kmabee/mlir2/runtime/lib/runtime.cpp:135

```

**Proposal**

Part feature-request, part bug-fix, we think it makes sense to:

1. Expose already existing `bool allocate` flag on `Buffer` constructor to `InterleavedBufferConfig/ShardedBufferConfig` config members via top level API `CreateBuffer(config)` and store it as state in `Buffer` class. This flag already guards call to `this->allocate()` in Buffer constructor, which is great.  This solves issue number 1 if tt-forge sets `allocate=false` on the config object for our usage.
2. In `Buffer::deallocate()` add `this->allocate_ == false` to the existing list of early-exit conditions so this function does nothing for Buffers that were never allocated to begin with.  This solves issue number 2.

I have tired making these changes locally and they solve the tt-mlir segfault problem, will aim to put up a PR for them shortly.

Edit: PR for propose changes with passing CI here:

https://github.com/tenstorrent/tt-metal/pull/12128

### PR DESCRIPTION
**Pull request by kmabeeTT**
Hello, tt-mlir developer here, putting up a PR for a change we'd (@kmabeeTT / @nsmithtt ) like with passing post-commit

### Ticket
Closes #12046 - see ticket for details

### Problem description
tt-mlir/tt-forge project wants to create `Buffer` objects with existing constructor flag `allocate=false` as view of existing memory that they allocate/deallocate, and have `Buffer::deallocate()` do nothing if buffer was created with `allocate=false`. Solves segfault during `Device:close()` which would loop over all Buffers in `detail::BUFFER_MAP` and deallocate these buffers again that tt-mlir had already deallocated/destroyed.

### What's changed

Kind of a simple change, hopefully not too controversial. 

 - Buffer constructor already had "allocate" field which protected against Buffer::allocate() from being called, and BUFFER_MAP insert.
 - Now, it's driven by CreateBuffer, added to Shard/Interleave configs, stored as state in Buffer class, and respected by Buffer::deallocate() to early exit if !allocate.
 - Solves segfault on metal Device::close() in tt-mlir where Buffer is created as view over memory and lifetime (alloc/dealloc) is managed by tt-mlir, but attempted to be deallocated again during teardown, so will be created with allocate=false now.

Not sure how this change impacts ttnn/async if at all (probably not at all), but I get the impression the `allocate=false` on Buffer constructor was originally used by them.  The only thing I think that would impact that is:

1. A few more calls to `this->allocate()` gaurded by (`if this->allocate_`) in Buffer constructors, similiar to main constructor
2. `Buffer::deallocate()` early exit now include the term to early exist if Buffer was created with `allocate=false`

### Checklist
- [x] Post commit CI passes : https://github.com/tenstorrent/tt-metal/actions/runs/10649195297
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

Not sure about other 3 bullets here, don't think they are applicable for this change, others please let me know.

### CODE REVIEW

**Comment by nsmithtt** [comment]
@kmabeeTT, I think there's a merge conflict.

Metal folks, can we get a review for this?

File: tt_metal/tt_metal.cpp [hunk 1]
```diff
@@ -976,7 +976,7 @@ uint32_t CreateSemaphore(
 
 std::shared_ptr<Buffer> CreateBuffer(const InterleavedBufferConfig &config) {
     return std::make_shared<Buffer>(
-        config.device, config.size, config.page_size, config.buffer_type, config.buffer_layout);
+        config.device, config.size, config.page_size, config.buffer_type, config.buffer_layout, std::nullopt, std::nullopt, config.allocate);
```
Comment (abhullar-tt) [inline tt_metal/tt_metal.cpp:979]: sorry for the late review, generally looks okay to me. I don't love that we have to pass in the nullopt to the buffer constructor. It would probably be better for the buffer ctor to accept buffer configs. This isn't in the scope of this PR so Ill open up a separate issue for that :)

**Review by abhullar-tt — APPROVED** [review]
Sorry for the late review, looks okay to me. I don't love that

**Comment by kmabeeTT** [comment]
> @kmabeeTT, I think there's a merge conflict.

Yep, newly introduced, rebased and re-running [CI](https://github.com/tenstorrent/tt-metal/actions/runs/10732070717) - thx for approval Almeet, hope to merge this tomorrow unless others object.
