### PR TITLE
Use scaling factor to compute ttnn.mean for multi-dim non w,h case + scaling factor fixes  (#28644)

### LINKED ISSUE #28644: [BOUNTY $1000] Support scaling in ttnn.mean for reduction over any dimension
## 📝 Background
Currently, `ttnn.mean` uses a single reduce OP call when _any one_ of the following is true:

1. We reduce on _all_ dimensions to return a scalar  
2. We reduce on only _one_ dimension and that dimension is either the last (W) or last but one (H)  
3. We reduce on _two_ dimensions and _both_ are last and last but one (H and W)  

See `single_reduce_op` in `ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp`.

When neither of these conditions are met:
1. _transpose_ the reduction dimension to be the H dimension (-2)
2. Invoke reduction kernel
3. _transpose_ again to negate the operation in (1)
4. Finally, use `ttnn.mul_sfpu` to scale down the values.

For performance reasons, we want to avoid (4) and instead pass the scalar to the reduction kernel invocation in (2).

## 🎯 What Success Looks Like
- Modify `reduce_nd_loop` lambda function to accept a scalar value
- Compute the correct `scalar` according to reduction dimensions
- Plumb through the lambda function to pass this scalar to the invocation of "SUM" kernel
- Confirm correct operation with passing unit tests in `tests/ttnn/unit_tests/operations/reduce/test_reduction.py`
-  Prove performance improvement with before/after measurements for inputs of different sizes

## 💡 Problem to Solve
Avoid post-reduction scaling step for mean; instead, pass the scalar directly to the reduction kernel.

## 🧭 Guidance & Starting Points
- Update `reduce_nd_loop` and related kernel invocation logic.
- Ensure all relevant tests pass.

## 🔎 Possible Approaches
- Refactor to compute and pass scalar at reduction call.
- Update tests and validate correctness/performance.

---

## 📚 Resources
- [Original issue #25548](https://github.com/tenstorrent/tt-metal/issues/25548)

### PR DESCRIPTION
**Pull request by yiding**
### Ticket

#28644

### Problem description
Remove ttnn.mul_sfpu call when computing multidimensional ttnn.mean on dimensions that are not the last 2 dimensions.

### What's changed

1. Fixed `reduce_nd_loop` applying scalars per axis reduction, and instead only apply it on the first axis. This corrects the issue that multipliers are effectively applied multiple times, once per reduction axis. Note: that behavior of `scalar` param is still sometimes incorrect when hitting other code paths (for example, ttnn.sum with a non -1, -2 dimension will call code that ignores scalar param).

2. Fixed scaling factor computation for multi-dimensional non w,h mean reduction. This used to use the volume of the input tensor, which is only correct for reducing to scalar tensors. Added a test to check this, existing tests do not cover this as assert_with_pcc ignores differences by constant factors.

3. The original ticket: multi-dim non w,h mean scaling is performed in `reduce_nd_loop`  instead of a separate mul_sfpu call.

### Perf

The performance improvement should be most apparent on reductions on small axis. Test was performed on P150. The effect of mul_sfpu seems small in even this worst-case scenario, however the traces demonstrate that it has indeed been eliminated.

Aggregate report from tracy:

*shape=(2, 2, 1024, 1024) dim=(0, 1)*

Before:
```
    %                                OP Code Joined  Device_Time_Sum_us  Ops_Count
52.21              Transpose (in0:dram_interleaved)            13251.46         10
25.57 PermuteDeviceOperation (in0:dram_interleaved)             6490.56         10
21.83                 Reduce (in0:dram_interleaved)             5539.40         10
 0.39   UnaryDeviceOperation (in0:dram_interleaved)               99.17          5
```

After:
```
    %                                OP Code Joined  Device_Time_Sum_us
52.29              Transpose (in0:dram_interleaved)            13232.29
25.81 PermuteDeviceOperation (in0:dram_interleaved)             6531.49
21.90                 Reduce (in0:dram_interleaved)             5542.71
```

*shape=(2, 2, 4096, 4096) dim=(0, 1)*

Before:
```
    %                                OP Code Joined  Device_Time_Sum_us  Ops_Count
52.56              Transpose (in0:dram_interleaved)           210945.69         10
25.54 PermuteDeviceOperation (in0:dram_interleaved)           102496.66         10
21.67                 Reduce (in0:dram_interleaved)            86981.73         10
 0.23   UnaryDeviceOperation (in0:dram_interleaved)              925.89          5
```

After:
```
    %                                OP Code Joined  Device_Time_Sum_us  Ops_Count
52.53              Transpose (in0:dram_interleaved)           209601.36         10
25.63 PermuteDeviceOperation (in0:dram_interleaved)           102254.18         10
21.84                 Reduce (in0:dram_interleaved)            87148.82         10
```

Test code:
```
@pytest.mark.parametrize("shape", [(2, 2, 1024, 1024), (2, 2, 4096, 4096)])
@pytest.mark.parametrize("dim", [[0, 1]])
def test_benchmark_perf_mean_nd(device, shape, dim):
    import tracy

    # best case for mul_sfpu removal.
    torch.manual_seed(0)
    torch_input_tensor = torch_random(shape, -1, 1, dtype=torch.bfloat16)

    tracy.signpost(f"warmup-{"-".join(str(x) for x in shape)}")
    # warmup
    input_tensor = ttnn.from_torch(torch_input_tensor, layout=ttnn.TILE_LAYOUT, device=device)
    output_tensor = ttnn.mean(input_tensor, dim=dim, keepdim=True)

    tracy.signpost(f"test-{"-".join(str(x) for x in shape)}")
    # test
    for _ in range(5):
        output_tensor = ttnn.mean(input_tensor, dim=dim, keepdim=True)
        output_tensor = ttnn.to_torch(output_tensor)
```

### Checklist
- [x] test_reduction.py tests pass
- [x] test_reduction_mean.py tests pass

- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml) CI passes (if applicable)
- [ ] [Galaxy demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by bbradelTT** [comment]
@nsorabaTT is on PTO this week and will be back next week.

**Comment by marty1885** [comment]
@yiding FYI CI tests are failing. May you look into it?

**Comment by yiding** [comment]
The failing test looks entirely unrelated.

File: ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp [hunk 1]
```diff
@@ -217,7 +218,7 @@ static Tensor reduce_impl(
                             /*keepdim=*/true,
                             memory_config,
                             compute_kernel_config,
-                            scalar,
+                            first ? scalar : 1.0,
```
Comment (nsorabaTT) [inline ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp]: Nit: This seems repeated. Can you instead add a local variable that computes the effective scale factor for each `i_dim` and then use that here?

It will also help eliminate the need for `first` since you can just go by testing for `i_dim == (rank - 1)`

Also consider adding an inline comment about why the scale factor is 1.0 for every loop execution except the first.

File: tests/ttnn/unit_tests/operations/reduce/test_reduction_mean.py [hunk 2]
```diff
@@ -28,3 +28,22 @@ def test_mean(device, batch_size, h, w, dim, keepdim):
...
+    """Use assert_allclose with ones() to test that mean's scaling factor is
+    computed correctly.
+    """
+    torch_input_tensor = torch.ones(shape, dtype=torch.bfloat16)
+    torch_output_tensor = torch.mean(torch_input_tensor, dim=dim, keepdim=keepdim, dtype=torch.bfloat16)
+
+    input_tensor = ttnn.from_torch(torch_input_tensor, layout=ttnn.TILE_LAYOUT, device=device)
+    ttnn.fill_implicit_tile_padding(input_tensor, 42)  # garbage padding to test that mean removes it
+
+    output_tensor = ttnn.mean(input_tensor, dim=dim, keepdim=keepdim)
```
Comment (nsorabaTT) [inline tests/ttnn/unit_tests/operations/reduce/test_reduction_mean.py:47]: Could you also add a flavor of this test when a scale factor is passed to `ttnn.mean`? This should check that the user supplied scale factor is honored and used correctly.

**Review by nsorabaTT — CHANGES_REQUESTED** [review]
Thanks for working on this bounty. Overall, the PR is in a good shape. I have added two minor comments below. Please address them and I will approve.

We will also need the pipelines green before the merge. I will kick them off.

**Comment by nsorabaTT** [comment]
> Thanks for working on this bounty. Overall, the PR is in a good shape. I have added two minor comments below. Please address them and I will approve.
> 
> We will also need the pipelines green before the merge. I will kick them off.

Please rebase your branch on top of the latest changes in main and resolve conflicts (if any).

File: tests/ttnn/unit_tests/operations/reduce/test_reduction_mean.py (hunk 2 above)
Comment (yiding) [reply tests/ttnn/unit_tests/operations/reduce/test_reduction_mean.py:47]: I can, but there's another code path where scalar is still broken so I didn't do it. I can add the tests and disable the broken cases and file a bug for that.

Edit: #29721 to track this.

Comment (nsorabaTT) [reply tests/ttnn/unit_tests/operations/reduce/test_reduction_mean.py:47]: That works!

**Comment by yiding** [comment]
Rebased, pulled out the scalar computation, and added a (disabled) test for scalar.

**Review by nsorabaTT — APPROVED** [review]

**Comment by yiding** [comment]
Hm, there's one related failure but I can't reproduce it locally:

[related failure](https://github.com/tenstorrent/tt-metal/actions/runs/18140695002/job/51640776805?pr=28869#step:6:21389)

```
FAILED tests/ttnn/unit_tests/operations/reduce/test_reduction_mean.py::test_mean_scaling[keepdim=True-dim=[0, 1]-shape=(2, 3, 4, 5)] - AssertionError: Max ATOL Delta: 5.0, Max RTOL Delta: 0.83203125
```

**Comment by nsorabaTT** [comment]
> Hm, there's one related failure but I can't reproduce it locally:
> 
> [related failure](https://github.com/tenstorrent/tt-metal/actions/runs/18140695002/job/51640776805?pr=28869#step:6:21389)
> 
> ```
> FAILED tests/ttnn/unit_tests/operations/reduce/test_reduction_mean.py::test_mean_scaling[keepdim=True-dim=[0, 1]-shape=(2, 3, 4, 5)] - AssertionError: Max ATOL Delta: 5.0, Max RTOL Delta: 0.83203125
> ```

Can you run with different seeds to check? You can do something like `pytest .... --count=50` to run multiple times. Use `-x` to exit on the first failure.

**Comment by yiding** [comment]
That's one of the tests I added that is averaging ones(), so seed shouldn't matter. FWIW I am using blackhole and test seems like it's on wormhole. 

Edit: I'm dumb I forgot to rebuild.

Edit2: Okay I found my bug. It's removing using a `first` variable to check for the first reduction. I can't just check for `rank - 1` because the first loop iteration might be be the first reduction, if that dimension is not being reduced.

**Comment by yiding** [comment]
I fixed my bug by putting back the bool first = ... check, since I think it's simpler than trying to intuit whether the dimension being looped over is the first dimension that's being reduced.

Also I can re-enable the new test I added for non-unity scaling factor, as the problem I was thinking of only apply to sum and not mean, and mean was failing due to my bug.
