### PR TITLE
Reductions - Squeeze Outputs, Add Correction Support to std and var

### LINKED ISSUE #12937: Unsupported cases for `aten.var.correction` conversion
When trying to convert `aten.var.correction` to `ttnn.var`, we ran into the issues below with tt-metal and currently don't support them:

- [ ] `correction != 0` is not supported (e.g. unbiased variance). tt-metal kernel only supports `correction = 0`
- [ ] All-dimension reduction is not supported (`dim=[]`). It triggers tt-metal assertion failure `Unsupported reduction operation`
- [ ] Same `keepdim = false`, `reduction dim < rank - 2`, non-tile-aligned shape related issues listed in tenstorrent/tt-metal#12936

### LINKED ISSUE #16928: ttnn.l1_loss and ttnn.mse_loss give unsqueezed tensors when using reduction (SUM or MEAN)
ttnn.l1_loss and ttnn.mse_loss give unsqueezed tensors when using reduction (SUM or MEAN). Eg tensor is shaped [1, 1, 1, 1]. While with golden function tensor is shaped: [1].

* Steps to reproduce

1. Checkout `ngrujic/fix-unit-tests` branch (soon to be merged into `main`).
2. You can reproduce this error with sweep test `tests/sweep_framework/sweeps/losses/mse_loss.py`. To run:

```
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name losses.mse_loss
```

or 

```
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name losses.l1_loss
```

Tests will be failing since resulting tensors are differently shaped than golden tensors.

Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

### PR DESCRIPTION
**Pull request by edwinleeTT**
### Ticket
#16928 - loss gives unsqueezed tensors  
#12937 - var does not support correction flag

### Problem description
This PR addresses a few issues:

1. TTNN sum/mean loss operations always returned unsqueezed tensors (e.g., [1,1,1,1]), while PyTorch always returned scalars (0D).
2. Generic reductions had a default of `keepdim=True` while PyTorch defaulted to `False`. This resulted in TTNN producing unsqueezed tensors when compared to PyTorch when run with otherwise identical inputs.
3. The `std` and `var` reductions did not support Bessel's correction, with no `correction` argument. Their implementation corresponded to keeping `correction=False`. 
4. Prod had very low PCC for specific dimensions on >4D tensors on Blackhole, causing failures in BH CI.

### What's changed

1. Loss mean/sum reductions match PyTorch and always squeeze outputs to 0D now. Tests are updated.
2. Generic reduces will also default to `keepdim=False`, and tests were updated.
3. A new `correction` argument was added for use in `std` and `var` reductions, which defaults to `true` to match PyTorch. Parameter is added to unit tests.
4. Prod PCC issues seem to be caused by identity permutations. These are okay on WH but are problematic on BH. Updated prod to prevent it from performing identity permutations, and removed the BH skip on `test_prod`.

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI [passes](https://github.com/tenstorrent/tt-metal/actions/runs/14951383832)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests [passes](https://github.com/tenstorrent/tt-metal/actions/runs/14951380544)
- [x] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI [passes](https://github.com/tenstorrent/tt-metal/actions/runs/14984596733) (if applicable)
- [x] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI [passes](https://github.com/tenstorrent/tt-metal/actions/runs/14984594490)
- [x] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI [passes](https://github.com/tenstorrent/tt-metal/actions/runs/14984594490) 
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/loss/loss.cpp [hunk 1]
```diff
@@ -41,9 +41,9 @@ Tensor loss_function(
 
     switch (reduce_mode) {
         case LossReductionMode::SUM:
-            return ttnn::sum(result, std::nullopt, true, memory_config.value_or(ref.memory_config()));
+            return ttnn::sum(result, std::nullopt, false, memory_config.value_or(ref.memory_config()));
```
Comment (nsorabaTT) [inline ttnn/cpp/ttnn/operations/loss/loss.cpp:44]: Nit: An inline comment like `/*argument=/*` will help read what is being assigned null and false.

**Review by nsorabaTT — APPROVED** [review]
> These are okay on WH but are problematic on BH.

Can you elaborate on why they are problematic on BH?

**Review by bbradelTT — APPROVED** [review]

**Comment by bbradelTT** [comment]
@sjameelTT Hopefully the permutation BH problem is known. If not, please let us know and create an issue.

**Comment by bbradelTT** [comment]
I kicked off more pipelines (some are green, some are red on main) before rush hour to see if there are any other changes that are needed:
https://github.com/tenstorrent/tt-metal/actions/runs/14970863741
https://github.com/tenstorrent/tt-metal/actions/runs/14970854293
https://github.com/tenstorrent/tt-metal/actions/runs/14970857510
https://github.com/tenstorrent/tt-metal/actions/runs/14970859742
https://github.com/tenstorrent/tt-metal/actions/runs/14970861890
https://github.com/tenstorrent/tt-metal/actions/runs/14970863741

**Comment by bbradelTT** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/14970854293/job/42051672234
https://github.com/tenstorrent/tt-metal/actions/runs/14970859742/job/42051745544
https://github.com/tenstorrent/tt-metal/actions/runs/14970861890/job/42051788303

failed with a binary device operation fatal. E.g. the last one
```
FAILED models/demos/t3000/mixtral8x7b/tests/test_mixtral_moe_prefill.py::test_mixtral_moe_inference[wormhole_b0-True-32768] - RuntimeError: TT_FATAL @ /work/ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:238: dim_a == dim_b
info:
Incompatible dimensions 4096 and 32768
backtrace:
```

Might be a bad commit or might be related to this change, in which case some tests might need to be updated.

**Comment by sjameelTT** [comment]
@bbradelTT I was unaware of the identity permutation issue on BH. Please create an issue and assign both me and @ntarafdar

File: ttnn/cpp/ttnn/operations/loss/loss.cpp (hunk 1 above)
Comment (edwinleeTT) [reply ttnn/cpp/ttnn/operations/loss/loss.cpp:44]: Added!

**Comment by bbradelTT** [comment]
@ayerofieiev-tt changing the default keepdim value will affect backwards compatibility and upstream projects. The benefit will be that we'll be aligned with pytorch, and I think this is a necessary change that's better done earlier. I'm not how much forge/pytorch would be affected.

**Comment by edwinleeTT** [comment]
> https://github.com/tenstorrent/tt-metal/actions/runs/14970854293/job/42051672234 https://github.com/tenstorrent/tt-metal/actions/runs/14970859742/job/42051745544 https://github.com/tenstorrent/tt-metal/actions/runs/14970861890/job/42051788303
> 
> failed with a binary device operation fatal. E.g. the last one
> 
> ```
> FAILED models/demos/t3000/mixtral8x7b/tests/test_mixtral_moe_prefill.py::test_mixtral_moe_inference[wormhole_b0-True-32768] - RuntimeError: TT_FATAL @ /work/ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:238: dim_a == dim_b
> info:
> Incompatible dimensions 4096 and 32768
> backtrace:
> ```
> 
> Might be a bad commit or might be related to this change, in which case some tests might need to be updated.

I added the `keepdim` flag to those tests where it looked necessary. Those three suites are now green (i.e. the flagged Mixtral/Grok dimension issues are resolved): 
https://github.com/tenstorrent/tt-metal/actions/runs/14985236123
https://github.com/tenstorrent/tt-metal/actions/runs/14985714655
https://github.com/tenstorrent/tt-metal/actions/runs/14990812877

**Review by pavlejosipovic — APPROVED** [review]

**Review by skhorasganiTT — APPROVED** [review]

**Review by uaydonat — APPROVED** [review]

**Review by mbahnasTT — APPROVED** [review]

**Review by TT-BrianLiu — APPROVED** [review]
