### PR TITLE
[skip ci] Add debug build for gcc12 in APC

### LINKED ISSUE #23391: Build failed on tt-metal with GCC Compiler
### Describe the bug

Building Debug type of tt-metal is failed with GCC Compiler toolchain.

The command i ran : 
```bash
./build_metal.sh --debug --cxx-compiler-path /usr/bin/g++-12 --c-compiler-path  /usr/bin/gcc-12
```

Then i saw the compilers is set to GCC toolchain properly.
```bash
INFO: C++ compiler: /usr/bin/g++-12
INFO: C compiler: /usr/bin/gcc-12
...
-- Using specifed C++ compiler: /usr/bin/g++-12
-- Using specifed C compiler: /usr/bin/gcc-12
```

Finally, some of unused variables in the source are regarded as error during compilation.
- part of error log.
```
root/tt-metal/tt_metal/tt_metal.cpp:1178:27: error: variable ‘start_core’ set but not used [-Werror=unused-but-set-variable]
 1178 |                 CoreCoord start_core = core_range.start_coord;
      |                           ^~~~~~~~~~
/root/tt-metal/tt_metal/tt_metal.cpp:1179:27: error: variable ‘end_core’ set but not used [-Werror=unused-but-set-variable]
 1179 |                 CoreCoord end_core = core_range.end_coord;
```

### Steps to reproduce the issue

No reproduce step because i had this issue on latest version with provided script. (`build_metal.sh`)
Please try the same build command given in description.

### Expected behavior

_No response_

### Please complete the following environment information

- OS Version : 22.04.4 LTS
- Version of Software : main branch , 9a2171 (commit hash)

### PR DESCRIPTION
**Pull request by blozano-tt**
### Ticket
Closes https://github.com/tenstorrent/tt-metal/issues/23391

### Problem description
We were not running gcc-12 debug mode compile in CI AND it is currently broken.

### What's changed
We run it.
I fix it, by disabling set but unused check, and other things.

### Checklist
- [ ] [build artifact](https://github.com/tenstorrent/tt-metal/actions/runs/15596292921) CI passes
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp [hunk 1]
```diff
@@ -258,12 +258,12 @@ TEST(DistributedContextExtraTest, IsendIrecvWait) {
     if (*ctx->rank() == 0) {
         auto req = ctx->isend(
             tt::stl::as_writable_bytes(tt::stl::Span<int>{buf_send.data(), buf_send.size()}), Rank{1}, Tag{7});
-        auto status = req->wait();
+        [[maybe_unused]] auto status = req->wait();
```
Comment (afuller-TT) [inline tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp]: ... looks like always unused?  Why not:

```suggestion
        req->wait();
```

File: tt_metal/tt_metal.cpp [hunk 2]
```diff
@@ -1175,8 +1175,8 @@ uint32_t CreateSemaphore(
             std::optional<uint32_t> semaphore_id;
             TT_FATAL(crs.ranges().size() > 0, "Expecting a non-empty CoreRangeSet!");
             for (const auto& core_range : crs.ranges()) {
-                CoreCoord start_core = core_range.start_coord;
-                CoreCoord end_core = core_range.end_coord;
+                // CoreCoord start_core = core_range.start_coord;
+                // CoreCoord end_core = core_range.end_coord;
```
Comment (afuller-TT) [inline tt_metal/tt_metal.cpp]: rm -rf baby!

```suggestion
```

**Review by afuller-TT — APPROVED** [review]

File: tt_metal/tt_metal.cpp (hunk 2 above)
Comment (ayerofieiev-tt) [reply tt_metal/tt_metal.cpp]: +1 please remove

**Review by ayerofieiev-tt — APPROVED** [review]

File: tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp (hunk 1 above)
Comment (blozano-tt) [reply tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp]: There is a commented out check on the next line.

File: tt_metal/third_party/tt_llk
Comment (nhuang-tt) [inline tt_metal/third_party/tt_llk:1]: Need to revert the tt_llk changes

**Review by nhuang-tt — APPROVED** [review]

File: tt_metal/third_party/tt_llk
Comment (blozano-tt) [reply tt_metal/third_party/tt_llk:1]: no idea how I did this

File: tt_metal/impl/device/device.cpp [hunk 3]
```diff
@@ -653,7 +653,7 @@ void Device::initialize_and_launch_firmware() {
     bool skip_physical = this->arch() == ARCH::BLACKHOLE and hal.is_coordinate_virtualization_enabled();
     if (not skip_physical) {
         for (tt::umd::CoreCoord core : pcie_cores) {
-            tt::umd::CoreCoord translated_coord =
+            [[maybe_unused]] tt::umd::CoreCoord translated_coord =
```
Comment (tt-dma) [inline tt_metal/impl/device/device.cpp]: Is this droppable? My upcoming PR moves and deletes this code.

Comment (blozano-tt) [inline tt_metal/impl/device/device.cpp]:
```suggestion
            tt::umd::CoreCoord translated_coord =
```

Comment (blozano-tt) [reply tt_metal/impl/device/device.cpp]: Yes, I removed it, to not cause you a merge conflict. It was not necessary to keep it, because I disabled the warning now.

File: ttnn/core/tensor/tensor_impl.cpp [hunk 4]
```diff
@@ -429,7 +429,7 @@ std::string to_string(
 template <typename T>
 std::string to_string(
     const Tensor& tensor, std::optional<DataType> original_dtype, std::optional<Layout> original_layout) {
-    const auto tile = tensor.tensor_spec().tile();
+    [[maybe_unused]] const auto tile = tensor.tensor_spec().tile();
```
Comment (blozano-tt) [inline ttnn/core/tensor/tensor_impl.cpp]:
```suggestion
    const auto tile = tensor.tensor_spec().tile();
```

File: tt_metal/impl/dispatch/kernel_config/demux.cpp [hunk 5]
```diff
@@ -174,7 +174,7 @@ void DemuxKernel::CreateKernel() {
     }
     TT_ASSERT(compile_args.size() == 30);
     const auto& grid_size = device_->grid_size();
-    tt_cxy_pair my_virtual_core =
+    [[maybe_unused]] tt_cxy_pair my_virtual_core =
```
Comment (blozano-tt) [inline tt_metal/impl/dispatch/kernel_config/demux.cpp]:
```suggestion
    tt_cxy_pair my_virtual_core =
```

File: tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp [hunk 6]
```diff
@@ -258,12 +258,12 @@ TEST(DistributedContextExtraTest, IsendIrecvWait) {
...
         // EXPECT_EQ(status.count, buf_send.size());
     } else if (*ctx->rank() == 1) {
         auto req = ctx->irecv(
             tt::stl::as_writable_bytes(tt::stl::Span<int>{buf_recv.data(), buf_recv.size()}), Rank{0}, Tag{7});
-        auto status = req->wait();
+        [[maybe_unused]] auto status = req->wait();
```
Comment (blozano-tt) [inline tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp]:
```suggestion
        auto status = req->wait();
```

File: tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp [hunk 7]
```diff
@@ -258,7 +258,7 @@ TEST(DistributedContextExtraTest, IsendIrecvWait) {
     if (*ctx->rank() == 0) {
         auto req = ctx->isend(
             tt::stl::as_writable_bytes(tt::stl::Span<int>{buf_send.data(), buf_send.size()}), Rank{1}, Tag{7});
-        auto status = req->wait();
+        [[maybe_unused]] auto status = req->wait();
```
Comment (blozano-tt) [inline tests/tt_metal/multihost/single_host_mp_tests/test_context.cpp]:
```suggestion
        auto status = req->wait();
```

File: tt_metal/distributed/mesh_workload_utils.cpp [hunk 8]
```diff
@@ -37,7 +37,8 @@ void write_go_signal(
 
     void* cmd_region = sysmem_manager.issue_queue_reserve(cmd_sequence_sizeB, cq_id);
 
-    auto dispatch_core_config = MetalContext::instance().get_dispatch_core_manager().get_dispatch_core_config();
+    [[maybe_unused]] auto dispatch_core_config =
+        MetalContext::instance().get_dispatch_core_manager().get_dispatch_core_config();
```
Comment (blozano-tt) [inline tt_metal/distributed/mesh_workload_utils.cpp]:
```suggestion
   auto dispatch_core_config = MetalContext::instance().get_dispatch_core_manager().get_dispatch_core_config();
```

File: tt_metal/distributed/mesh_workload_utils.cpp [hunk 9]
```diff
@@ -37,7 +37,7 @@ void write_go_signal(
 
     void* cmd_region = sysmem_manager.issue_queue_reserve(cmd_sequence_sizeB, cq_id);
 
-    auto dispatch_core_config = MetalContext::instance().get_dispatch_core_manager().get_dispatch_core_config();
+   auto dispatch_core_config = MetalContext::instance().get_dispatch_core_manager().get_dispatch_core_config();
```
Comment (blozano-tt) [inline tt_metal/distributed/mesh_workload_utils.cpp]:
```suggestion
    auto dispatch_core_config = MetalContext::instance().get_dispatch_core_manager().get_dispatch_core_config();
```

**Review by tt-dma — APPROVED** [review]
