### PR TITLE
 fix for sharded allocater when num banks == num cores

### LINKED ISSUE #5226: Sharded Allocater Number of Banks == Number of Shards Bug
Bug when this is true. Should be using compute_cores API to get this instead.

### PR DESCRIPTION
**Pull request by ntarafdar**
Use compute_cores when determining how many banks we have available to shard.

### CODE REVIEW

**Review by yugaoTT — APPROVED** [review]

**Review by tt-nshanker — APPROVED** [review]

File: tt_metal/impl/device/device.cpp [hunk 1]
```diff
@@ -90,6 +90,7 @@ void Device::initialize_allocator(const std::vector<uint32_t>& l1_bank_remap) {
         .worker_log_to_physical_routing_x=soc_desc.worker_log_to_physical_routing_x,
         .worker_log_to_physical_routing_y=soc_desc.worker_log_to_physical_routing_y,
         .l1_bank_remap = l1_bank_remap,
+        .compute_grid_size = this->compute_with_storage_grid_size()
```
Comment (TT-billteng) [inline tt_metal/impl/device/device.cpp:93]: would the allocator ever be responsible for a region OTHER than the whole chip?

**Review by TT-billteng — APPROVED** [review]
