### PR TITLE
#14367: Inline operator[] Again for RuntimeArgsData

### LINKED ISSUE #14367: [Bug Report] RuntimeArgsData::operator[] is not inlined but called very often.
**Describe the bug**
operator[] implementation is in the cpp and not inlined.
**To Reproduce**
Run any op.
**Expected behavior**
It should be inlined.

**Screenshots**
Screenshot 2024-10-27 at 1 10 10 PM

### PR DESCRIPTION
**Pull request by blozano-tt**
### Ticket
Closes #14367 

### Problem description
My previous commit separated header and implementation for these functions, to keep our internal dependencies private.
However, a performance degradation was reported by @dmakoviichuk-tt
This PR restores the functions to inline for performance
It also keeps TT_FATAL and TT_ASSERT out of public header file. 

### What's changed
runtime_data_args.cpp removed
runtime_data_args.hpp now has inlined operator[]

### Checklist
https://github.com/tenstorrent/tt-metal/actions/runs/11577847420
- [x] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_metal/impl/kernels/runtime_args_data.hpp [hunk 1]
```diff
@@ -16,19 +21,60 @@ struct RuntimeArgsData {
...
 
-    const std::uint32_t& at(std::size_t index) const;
+    inline const std::uint32_t& operator[](std::size_t index) const noexcept {
+        assert(in_bounds(index));
+        return this->rt_args_data[index];
+    }
 
-    std::uint32_t * data() noexcept;
+    inline std::uint32_t & at(std::size_t index) {
+        if (in_bounds_or_throw(index)) [[likely]] {
```
Comment (dmakoviichuk-tt) [inline tt_metal/impl/kernels/runtime_args_data.hpp:53]: btw it is bette to do check if (something is bad) throw, compiler automatically recognizes the pattern and you don't need to add likely/unlikely.

**Review by dmakoviichuk-tt — APPROVED** [review]

File: tt_metal/impl/kernels/runtime_args_data.hpp (hunk 1 above)
Comment (blozano-tt) [reply tt_metal/impl/kernels/runtime_args_data.hpp:53]: ok, I'll adjust

File: tt_metal/impl/kernels/runtime_args_data.hpp [hunk 2]
```diff
@@ -16,19 +21,60 @@ struct RuntimeArgsData {
     std::uint32_t * rt_args_data;
     std::size_t rt_args_count;
 
-    std::uint32_t & operator[](std::size_t index);
+    inline bool in_bounds(std::size_t index) const noexcept {
+        if(index >= rt_args_count) [[unlikely]] {
```
Comment (tt-aho) [inline tt_metal/impl/kernels/runtime_args_data.hpp:25]: Question on why we are trying to avoid having TT_FATAL in headers?
Seems like we'll end up duplicating assertion code formatting if anything in our header files needs to assert, and may lead to inconsistent formatting down the line?

Comment (blozano-tt) [reply tt_metal/impl/kernels/runtime_args_data.hpp:25]: TT_FATAL and TT_ASSERT `should be` internal logging implementation details.
Both depend on `libfmt`, which again, should be a private/internal dependency.

`runtime_args_data.hpp` happens to be a public header file, because it gives the definition of `RuntimeArgsData` to `host_api.h`.

If we keep our internal logging macros in public header files... 
We leak our internal logging implementation details, and force a dependency `fmt` on customer.

What if customer code uses a different version of fmt?

File: tt_metal/impl/kernels/runtime_args_data.hpp (hunk 1 above)
Comment (blozano-tt) [reply tt_metal/impl/kernels/runtime_args_data.hpp]: Thanks for the suggestion, I like it better now.

File: tt_metal/impl/kernels/runtime_args_data.hpp (hunk 2 above)
Comment (tt-aho) [reply tt_metal/impl/kernels/runtime_args_data.hpp]: I see. Is this the only public header that was using these assertions? Just concerned about consistency/duplication down the line

**Review by tt-aho — APPROVED** [review]

File: tt_metal/impl/kernels/runtime_args_data.hpp (hunk 2 above)
Comment (blozano-tt) [reply tt_metal/impl/kernels/runtime_args_data.hpp]: Probably not, but I had to start somewhere. :-)

**Comment by blozano-tt** [comment]
I kept seeing a failure in CI ... I suspect I need to rebase on latest main. Rerunning after rebase.
