### PR TITLE
Fix conv2d DRAM slicing L1 estimation for tile-padded edge slices

### LINKED ISSUE #41918: L1 memory error in Conv2d (MapTR model)
### Describe the bug 

- Conv2d fails with `Statically allocated circular buffers in program 37 clash with L1 buffers on core range [(x=0,y=0) - (x=7,y=5)]. L1 buffer allocated at 693760 and static circular buffer region ends at 1087328` error - [apr12_conv2d_org_l1.log](https://github.com/user-attachments/files/26654876/apr12_conv2d_org_l1.log)
- MapTR model is affected by this error - https://github.com/tenstorrent/tt-xla/issues/4202

### Repro

```
git checkout kkannan/apr12_maptr_conv2d_l1_error
git submodule update --init --recursive
pytest tests/ttnn/unit_tests/operations/conv2d/test_conv2d_org.py -svv
```

### PR DESCRIPTION
**Pull request by kamalrajkannan78**
### Summary

closes https://github.com/tenstorrent/tt-metal/issues/41918

`get_input_memory_config()` computed the shard spec using raw (unpadded) output dimensions, but the halo op produces tile-padded output. For edge slices where the output width isn't a multiple of 32, the halo op pads the output to the next tile boundary (e.g., width 4 → 32). The shard spec was computed for the unpadded width, resulting in a much smaller L1 estimate than the actual runtime usage. The auto-slicer accepted a slice count that didn't actually fit in L1, causing circular buffers to clash with L1 data buffers.

The fix changes `get_input_memory_config()` to use `get_input_slice_and_padding() + calculate_output_image_size()` instead of raw output dimensions. This matches what get_L1_usage() already does, so the planner now sees the same padded dimensions as the executor. 

Nightly L2 for convs -  https://github.com/tenstorrent/tt-metal/actions/runs/24564784684
Sanity tests - https://github.com/tenstorrent/tt-metal/actions/runs/24558782980

### CODE REVIEW

**Review by saiarthiraguram — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp [hunk 1]
```diff
@@ -581,7 +581,9 @@ class Conv2dSliceAttr : public ttnn::operations::op_slicing::OpSliceAttr {
             slice_config.num_slices,
             sliced_input_tensor_memory_config,
             conv_L1_usage);
-        return std::max(conv_L1_usage.halo_input_size + conv_L1_usage.halo_output_size, conv_L1_usage.total_size);
+        // Account for spatial layout: halo output is placed at (L1_free - halo_input - halo_output)
+        // and CBs grow from the bottom, so we need all three to fit without overlap.
+        return conv_L1_usage.halo_input_size + conv_L1_usage.halo_output_size + conv_L1_usage.conv_op_size;
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: I believe this calculation should depend on the values of reallocate_halo_output and deallocate_halo_input since if the deallocate_halo_input is true we are freeing up the space of the halo input after the halo op and before conv micro op, and if we are reallocating it we essentially move it to reduce the memory fragmentation. So in some situations we are going to overestimate the needed memory space and increase the number of slices where it is not needed

Comment (kamalrajkannan78) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: Thanks for the review! You're right. 

I dug deeper and the root issue is that get_L1_usage reads from the user's conv_config (which has deallocate_activation=false by default), but the original max() formula assumed halo_input would always be freed. When deallocate_activation is false, all three regions coexist and max() underestimates.

Updated the fix to be conditional on both flags:

- When both deallocate_activation and reallocate_halo_output are true: halo_input is freed and halo_output is compacted, so peak = max(halo_input + halo_output, total_size)
- Otherwise: sum of all three (halo_input + halo_output + conv_op) since they may all coexist in L1

This fix works for my case. If this looks good to you, I'll trigger the L2 nightly pipeline to confirm there are no regressions.

Comment (dstoiljkovicTT) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: This looks okay to me please rerun the L2 Nightly and Sanity tests a post the passing pipleines

Comment (kamalrajkannan78) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: I've triggered L2 Nightly and Sanity tests 

- Nightly L2 for convs - https://github.com/tenstorrent/tt-metal/actions/runs/24506525226
- Sanity tests - https://github.com/tenstorrent/tt-metal/actions/runs/24506298273

In Nightly L2(convs), all cases are passing except N300, which is currently in the queue and is expected to pass as well.

In sanity tests, below performance case alone is failing

```
models/demos/stable_diffusion_xl_base/tests/test_sdxl_op_unit_test_perf.py::test_conv2d_auto_sliced_vae_performance - AssertionError: Performance outside expected range. Got 1552076.00 ns, expected 3142259 ± 1.5% (3095125.11-3189392.88 ns)
assert 3095125.1149999998 <= 1552076.0
```

I will update the current fix to address this too, confirm the fix with you and then re-trigger the pipeline.

Comment (kamalrajkannan78) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: I investigated the SDXL regression and found the real root cause — it's not about the max() vs sum() formula.

The actual bug is in get_input_memory_config(). It computes the shard spec using unpadded output dimensions, but the halo op produces tile-padded output.

Example from my crash case (output 60x100, 4 width slices):

- Last slice has output width 4, but halo op pads it to 32 (tile-aligned)
- get_input_memory_config estimated L1 based on width 4 — small shard, looks like it fits
- At runtime, halo op produces width 32 — much larger shard, overflows L1 → crash

The fix: Changed get_input_memory_config() to use get_input_slice_and_padding() + calculate_output_image_size() instead of raw output dimensions. This matches what get_L1_usage() already does. Now the planner sees the same padded dimensions as the executor.

Reverted the conditional sum() formula — the original max() is correct once the estimation is accurate. SDXL stays at 2 slices (no regression), and my crash case is fixed.

pushed the updated fix now. will rebase & re-trigger the pipelines & attach the pipeline results in description

In N150, 

**Before Fix**

- [apr17_conv2d_before_fix.log](https://github.com/user-attachments/files/26817995/apr17_conv2d_before_fix.log)
- [apr17_sdxl_conv_before_fix.log](https://github.com/user-attachments/files/26818005/apr17_sdxl_conv_before_fix.log)

**After old fix (sum formula)**

- [apr17_conv2d_after_old_fix.log](https://github.com/user-attachments/files/26817991/apr17_conv2d_after_old_fix.log)
- [apr17_sdxl_conv_after_old_fix.log](https://github.com/user-attachments/files/26818002/apr17_sdxl_conv_after_old_fix.log)

**After current fix** 

- [apr17_conv2d_after_new_fix.log](https://github.com/user-attachments/files/26817985/apr17_conv2d_after_new_fix.log)
- [apr17_sdxl_conv_after_new_fix.log](https://github.com/user-attachments/files/26817999/apr17_sdxl_conv_after_new_fix.log)

Comment (kamalrajkannan78) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: All tests are passing in sanity test pipeline - https://github.com/tenstorrent/tt-metal/actions/runs/24558782980

Comment (kamalrajkannan78) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: All tests are passing in Nightly L2 tests pipeline - https://github.com/tenstorrent/tt-metal/actions/runs/24564784684

Comment (kamalrajkannan78) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp]: @dstoiljkovicTT could you pls re-review this PR?

**Review by dstoiljkovicTT — APPROVED** [review]
