### PR TITLE
#33587: Add row_column mixed bcast support for ternary

### LINKED ISSUE #39181: [eltwise]: Legacy path of `ttnn.where` on NaN tensor produces wrong result
### Component / Area

ops

### Issue Type (optional)

Bad Outputs

### Observed

When an unsupported implicit broadcasting configuration is requested in `ttnn.where` op, fallback happens to the legacy (composite) implementation of the op; for example, `ttnn.where` with the following shapes occurs in GPT-2 attention mask computation:
- (`predicate`, `true_value`, `false_value`) = ([8, 4, 1], [8, 4, 768], [1, 1, 1])

However, when `false_value` tensor is a splat tensor filled with `NaN` or `Inf`, the legacy fallback path doesn't produce correct outputs:
```
result = predicate * true_values + (1 - predicate) * false_values

// for predicate = true
result = 1 * true + (1 - 1) * INF
         = true + 0 * INF
         = true + NaN 
         = NaN
```

### Expected

The legacy path handles the `NaN` / `Inf` values correctly, or implicit broadcasting support is extended to cover the provided scenario.

### 1. Steps (exact commands)

[reproducer_where_nan.py](https://github.com/user-attachments/files/25762697/reproducer_where_nan.py)

### 2. Input data / link or description

/

### 3. Frequency

Always

### 1. Software Versions

/

### 2. Hardware Details

n150

### Is this a regression?

Unknown

### Regression Details

_No response_

### Logs & Diagnostics

_No response_

### Priority

None

### Impact

_No response_

### PR DESCRIPTION
**Pull request by mouliraj-mcw**
### Ticket
Link to Github Issue #33587

### Problem Description

Currently, the ternary infra does not support mixed Row–Column broadcast.

### What's Changed

Added support for mixed Row–Column broadcast in the ternary infra.

### Checklist
- [ ] [Sanity tests](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:mouliraj/ternary_broadcast)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:mouliraj/ternary_broadcast)
- [ ] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:mouliraj/ternary_broadcast)
- [ ] New/Existing tests provide coverage for changes
- [ ] (Optional) Ran [clang-tidy code analysis](https://github.com/tenstorrent/tt-metal/actions/workflows/code-analysis.yaml) on the PR branch to catch linting errors early

#### Model tests

If your changes cover model-related code, you should run tests corresponding to affected models and platforms (Single card, T3K, Galaxy). "Choose your pipeline" workflows facilitate running multiple kinds of tests in a single run. Each offers `models-mandatory` and `models-extended` presets.
The former includes a minimal set of tests, to be run always. The latter extends that with additional ones - use your best judgement in deciding which is the most appropriate for your PR.

- [ ] [(Single) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:{{branch_name}})
  - [ ] `models-mandatory` preset (runs: [Device perf regressions](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) and [Frequent model and ttnn tests](https://github.com/tenstorrent/tt-metal/actions/workflows/fast-dispatch-full-regressions-and-models.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(T3K) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:{{branch_name}})
  - [ ] `models-mandatory` preset (runs: [Unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-model-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(Galaxy) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:{{branch_name}})
  - [ ] `models-mandatory` preset (runs: [Quick tests](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/eltwise/ternary/device/kernels/dataflow/ternary_reader_row_col_bcast_ttt.cpp [hunk 1]
```diff
@@ -0,0 +1,310 @@
...
+// TTT reader for mixed row+column broadcast.
+// Each tensor independently can be: full(H,W), row(1,W), col(H,1), or scalar(1,1).
+//
+// Defines used per tensor (A=predicate, B=true, C=false):
+//   SRC_BCAST_A      = 1 when tensor A has W=1 (col broadcast or scalar) → pushed before tw loop
+//   SRC_ROW_BCAST_A  = 1 when tensor A has H=1 (row broadcast, NOT scalar) → pushed inside tw loop, first-row fill
+//   SRC_SCALAR_A     = 1 when tensor A is (1,1) → pushed before tw loop, first-element fill
+//   SRC_SHARDED_A    = 1 when tensor A is sharded in L1
+
+#include <stdint.h>
```
Comment (Aswinmcw) [inline ttnn/cpp/ttnn/operations/eltwise/ternary/device/kernels/dataflow/ternary_reader_row_col_bcast_ttt.cpp:5]: needed?

File: ttnn/cpp/ttnn/operations/eltwise/ternary/device/kernels/dataflow/tts_tst_reader_row_col_bcast.cpp [hunk 2]
```diff
@@ -0,0 +1,186 @@
+// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
```
Comment (Aswinmcw) [inline ttnn/cpp/ttnn/operations/eltwise/ternary/device/kernels/dataflow/tts_tst_reader_row_col_bcast.cpp]:
```suggestion
// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
```

**Review by Aswinmcw — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/eltwise/ternary/device/kernels/dataflow/tts_tst_reader_row_col_bcast.cpp [hunk 3]
```diff
@@ -0,0 +1,172 @@
...
+    uint32_t tensor_next_nd_shift = tensor_nD_stride - tensor_d_stride * D;
+
+    uint32_t num_tiles_read = 0;
+    for (uint32_t nd = start_nd; nd < cND && num_tiles_read < num_tiles; ++nd, start_d = 0) {
+        for (uint32_t d = start_d; d < D && num_tiles_read < num_tiles; ++d, start_n = 0) {
+            for (uint32_t n = start_n; n < N && num_tiles_read < num_tiles; ++n, start_c = 0) {
+                for (uint32_t c = start_c; c < C && num_tiles_read < num_tiles; ++c, start_th = 0) {
+                    for (uint32_t th = start_th; th < Ht && num_tiles_read < num_tiles; ++th) {
+#if SRC_BCAST_A
+                        cb_reserve_back(predicate_cb, onetile);
```
Comment (mateusznowakTT) [inline ttnn/cpp/ttnn/operations/eltwise/ternary/device/kernels/dataflow/tts_tst_reader_row_col_bcast.cpp]: Please migrate this PR to use Metal1.1 APIs

**Review by mateusznowakTT — CHANGES_REQUESTED** [review]

**Review by mateusznowakTT — APPROVED** [review]

**Review by KalaivaniMCW — APPROVED** [review]
