### PR TITLE
#12187: Enabling cmd buffer fifo on bh

### LINKED ISSUE #12187: MatmulMultiCoreMultiDRAMIn0MCastIn1MCast ND hanging on BH
https://github.com/tenstorrent/tt-metal/issues/11623 has been tracking ND hangs on BH CI. 

Ran for small number of iterations locally on IRD machines without seeing hang but increasing test iterations was able to reproduce the hang on IRD (I used yyz-bh-26 and saw hang after ~20 iterations)

Reducing the sub-block dimensions as (merged to main in https://github.com/tenstorrent/tt-metal/pull/12186) enables test to run for 1000 iterations (on yyz-bh-26). 

To run test with workaround: 
```
TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=CommonFixture.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast --gtest_repeat=<N>
```

Without workaorund:
```
TT_METAL_DISABLE_BH_ND_WORKAROUND=1 TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=CommonFixture.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast --gtest_repeat=<N>
```

### PR DESCRIPTION
**Pull request by abhullar-tt**
### Ticket
#12187 

### Problem description
CMD buffer on BH has issues so we were suggested to enable CMD buffer FIFO instead. Without this change we see ND behaviour 

### What's changed
- Enable CMD buffer FIFO on noc init
- uplift noc_cmd_buf_ready to check for available space in FIFO (16 entries are available to each of the four buffers)
- enables `TT_METAL_DISABLE_BH_ND_WORKAROUND=1 TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=CommonFixture.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast --gtest_repeat=1000` (previously was only able to get around 20 iterations) 

Note: This doesn't try to use the cmd buffer FIFOs in a performant way

### Checklist
- [x] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/10799423024)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/runs/10799433487)

### CODE REVIEW

**Review by tt-aho — APPROVED** [review]

File: tt_metal/hw/inc/blackhole/noc_nonblocking_api.h [hunk 1]
```diff
@@ -56,7 +56,9 @@ inline __attribute__((always_inline)) uint32_t NOC_CFG_READ_REG(uint32_t noc, ui
 }
 
 inline __attribute__((always_inline)) bool noc_cmd_buf_ready(uint32_t noc, uint32_t cmd_buf) {
-    return (NOC_CMD_BUF_READ_REG(noc, cmd_buf, NOC_CMD_CTRL) == NOC_CTRL_STATUS_READY);
+    // Command buffer FIFO supports 16 commands, once it is full the overflow register for the cmd_buf will be set
+    // CMD_BUF_AVAIL holds available buffer space in [28:24], [20:16], [12:8], [4:0] for buffers 3, 2, 1, 0 respectively
+    return bool((NOC_CMD_BUF_READ_REG(noc, cmd_buf, CMD_BUF_AVAIL) >> (cmd_buf << 3)) & 0x1F);
```
Comment (abhullar-tt) [inline tt_metal/hw/inc/blackhole/noc_nonblocking_api.h:61]: **pgm sweep results**
```
 with change:
2.62, 2.87, 2.99, 3.24, 3.67, 7.18, 7.25, 7.74, 3.73, 6.27, 5.68, 7.25, 7.47, 12.23, 4.02, 4.18, 13.78, 17.69, 
2.63, 2.90, 3.07, 3.26, 3.68, 7.24, 7.28, 7.75, 3.73, 6.28, 5.68, 7.26, 7.51, 12.22, 4.03, 4.19, 13.99, 17.88, 
2.67, 2.91, 3.10, 3.33, 3.71, 7.24, 7.27, 7.74, 3.74, 6.29, 5.68, 7.26, 7.55, 12.34, 4.05, 4.21, 13.85, 18.32, 
2.67, 2.91, 3.04, 3.37, 3.79, 7.30, 7.36, 7.78, 3.79, 6.29, 5.70, 7.35, 7.63, 12.41, 4.07, 4.23, 13.91, 19.25, 
2.85, 2.98, 3.27, 3.63, 3.99, 7.40, 7.49, 7.97, 4.09, 6.44, 5.74, 7.49, 7.82, 12.88, 4.23, 4.44, 14.65, 21.16, 
3.04, 3.08, 3.93, 4.33, 4.63, 7.69, 7.74, 8.21, 4.98, 6.43, 5.81, 7.76, 8.27, 13.77, 4.39, 4.62, 15.33, 30.72,

without change:
2.59, 2.88, 3.09, 3.28, 3.67, 7.18, 7.27, 7.73, 3.74, 6.16, 5.55, 7.23, 7.48, 12.16, 3.94, 4.12, 13.76, 19.37, 
2.60, 2.89, 3.09, 3.27, 3.68, 7.21, 7.26, 7.79, 3.77, 6.16, 5.56, 7.21, 7.47, 12.18, 3.95, 4.13, 13.98, 19.49, 
2.63, 2.90, 3.11, 3.31, 3.70, 7.21, 7.24, 7.75, 3.73, 6.19, 5.57, 7.24, 7.51, 12.26, 3.97, 4.16, 13.79, 19.74, 
2.64, 2.90, 3.13, 3.36, 3.77, 7.29, 7.31, 7.79, 3.78, 6.19, 5.58, 7.30, 7.60, 12.33, 4.00, 4.17, 13.83, 20.40, 
2.84, 2.94, 3.23, 3.54, 3.97, 7.38, 7.48, 8.04, 4.03, 6.24, 5.62, 7.50, 7.74, 12.82, 4.15, 4.35, 14.33, 21.68, 
2.99, 3.06, 3.87, 4.27, 4.66, 7.73, 7.68, 8.15, 5.01, 6.35, 5.69, 7.67, 8.25, 13.84, 4.31, 4.44, 15.31, 30.69,
```
