### PR TITLE
#22198: Uint32 support for ttnn.sort index tensor added

### LINKED ISSUE #22138: Update ttnn.sort and ttnn.gather documentation
# Problem statement

- `ttnn.sort` documentation shows wrong data type of input arguments:
```
- dim (*) – The dimension along which to sort. Defaults to -1 (last dimension).
- descending (*) – If True, sorts in descending order. Defaults to False.
- stable (*) – If True, ensures the original order of equal elements is preserved. Defaults to False.
- memory_config (*) – Specifies the memory configuration for the output tensor. Defaults to None.
- out (*) – Preallocated output tensors for the sorted values and indices. Defaults to None.
```
- `ttnn.gather` does not have documentation in `ttnn` docs.

# Solution

- Correct `ttnn.sort` documentation in python binding to correctly show input datatypes,
- Add `ttnn.gather` function link to `.rst` docs file so that function will be available in `ttnn` docs.

### LINKED ISSUE #22198: Unify index tensor datatype
# Problem

Currently due to limitation with ttnn.transpose only uint16 datatype is supported for index tensor in ttnn.sort which limits the maximum available index that can be placed in it.

# Solution

Once the support for int32/uint32 types will be added for ttnn.transpose unify index tensor datatype in ttnn.sort OP and lock it on one of those, update docs and tests.

### PR DESCRIPTION
**Pull request by mgajewskiTT**
### Ticket

[Unify index tensor datatype for ttnn.sort](https://github.com/tenstorrent/tt-metal/issues/22198)

This PR also resolves https://github.com/tenstorrent/tt-metal/issues/22138

### Problem description

Due to the added ability to use 32-bit variables in the `transpose` and `topk_local_sort` LLKs, the  operation has been updated to accept this type of data.

### What's changed
* Added ability to use uint32 for index tensor when sort dimension is larger than max value of uint16,
* Updated documentation.
* Small performance updates to Single Row Single Core and Single row Multi Core implementations.

### Performance updates

Wormhole measurements:

Tiles | Cores used | Tiles processed by core | Tile Width | DEVICE KERNEL DURATION PER CORE MIN [ms] | DEVICE KERNEL DURATION PER CORE MAX [ms] | DEVICE KERNEL DURATION PER CORE AVG [ms] | Bandwidth MElem/s
-- | -- | -- | -- | -- | -- | -- | --
Current Single Row Multi Core
64 | 32 | 2 | 32 | 5.246 | 5.246 | 5.246 | 0.390
128 | 64 | 2 | 32 | 3.029 | 3.036 | 3.031 | 1.352
256 | 64 | 4 | 32 | 5.855 | 5.855 | 5.856 | 1.399
512 | 64 | 8 | 32 | 11.845 | 11.852 | 11.847 | 1.383
1024 | 64 | 16 | 32 | 23.698 | 23.704 | 23.699 | 1.383
2048 | 64 | 32 | 32 | 48.680 | 48.687 | 48.682 | 1.346
4096 | 64 | 64 | 32 | 98.468 | 98.475 | 98.472 | 1.331
8192 | 64 | 128 | 32 | 204.805 | 204.812 | 204.806 | 1.280
New Single Row Multi core
64 | 32 | 2 | 32 | 1.425 | 1.427 | 1.426 | 1.437
128 | 64 | 2 | 32 | 2.832 | 2.838 | 2.833 | 1.446
256 | 64 | 4 | 32 | 5.513 | 5.519 | 5.514 | 1.486
512 | 64 | 8 | 32 | 11.225 | 11.232 | 11.226 | 1.460
1024 | 64 | 16 | 32 | 22.438 | 22.444 | 22.439 | 1.460
2048 | 64 | 32 | 32 | 24.207 | 24.215 | 24.210 | 2.707
4096 | 64 | 64 | 32 | 52.158 | 52.166 | 52.162 | 2.513
8192 | 64 | 128 | 32 | 111.831 | 111.838 | 111.834 | 2.344

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by bbradelTT — COMMENTED** [review]
What is the reason for the perf improvement?

Why is the duration for the first entry of Current Single Row Multi Core much bigger than for the second entry?

Why do the 64 core 16 and 32 tile entries have about the same duration in New Single Row Multi core
? It seems like in the current, there is a consistent decrease.

File: ttnn/cpp/ttnn/operations/experimental/reduction/sort/device/sort_device_operation.cpp [hunk 1]
```diff
@@ -108,6 +108,17 @@ void SortDeviceOperation::validate_on_program_cache_miss(
                 "input tensor shape: {}",
                 output_indices_shape,
                 input_tensor_shape);
+            TT_FATAL(
+                tensor_args.output_tensors.at(0)->dtype() == tensor_args.input_tensor.dtype(),
+                "Output values tensor dtype must be the same as input tensor dtype. Got output values tensor dtype: {} "
+                "and input tensor dtype: {}",
+                tensor_args.output_tensors.at(0)->dtype(),
+                tensor_args.input_tensor.dtype());
+            TT_FATAL(
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/reduction/sort/device/sort_device_operation.cpp:117]: Is there a test that has uint16 input and uint32 output and vice versa?

Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/experimental/reduction/sort/device/sort_device_operation.cpp:117]: Added test.

**Comment by mgajewskiTT** [comment]
> What is the reason for the perf improvement?
> 
> Why is the duration for the first entry of Current Single Row Multi Core much bigger than for the second entry?
> 
> Why do the 64 core 16 and 32 tile entries have about the same duration in New Single Row Multi core ? It seems like in the current, there is a consistent decrease.

While working on Cross core data exchange strategy we noticed that there are some things that can be also applied in current Single Row … strategies. For example, the use of topk_merge LLK in some substages instead of always using topk_local_sort LLK improves performance. A few other adjustments were also made. 

64 tiles is the last case that is handled by Single Row Singe Core, that’s why it takes more time to process it. However, if the tensor had up to 64 tiles in the sorted dimension but high Ht, this approach would be much faster because each core would process one h.

I was also surprised; I checked this twice on two different machines and the result is valid.

**Comment by bbradelTT** [comment]
Thanks for the explanation. That helps. Having Current Single Row Multi Core and New Single Row Multi core would indicate that all the rows are for single row multi core.

**Review by bbradelTT — APPROVED** [review]

**Review by sjameelTT — APPROVED** [review]

**Review by aczajkowskiTT — APPROVED** [review]
