### PR TITLE
Add ability to assign dram noc endpoint for each noc to avoid dram arbiter bug on BH

### LINKED ISSUE #20336: p150a test_benchmark.py fail
Running this test exposes a weird behavior on p150a:
```
TT_METAL_SLOW_DISPATCH_MODE=1 pytest "tests/ttnn/unit_tests/benchmarks/test_benchmark.py::test_matmul_2d_host_perf"  
```
I had to make some modifications given the current state of main and my intentions - I wanted to run a 13x10 core grid matmul sweep in order to get the matmul hang that's being investigated under #16439 and related issues. I  wasn't interested in tracing, so I did the following:
```
diff --git a/tests/ttnn/unit_tests/benchmarks/test_benchmark.py b/tests/ttnn/unit_tests/benchmarks/test_benchmark.py
index 0dec5c0df0..5146af74d1 100644
--- a/tests/ttnn/unit_tests/benchmarks/test_benchmark.py
+++ b/tests/ttnn/unit_tests/benchmarks/test_benchmark.py
@@ -75,11 +75,7 @@ profiler_log_path = PROFILER_LOGS_DIR / PROFILER_DEVICE_SIDE_LOG


 def get_device_freq():
-    setup = device_post_proc_config.default_setup()
-    setup.deviceInputLog = profiler_log_path
-    deviceData = import_log_run_stats(setup)
-    freq = deviceData["deviceInfo"]["freq"]
-    return freq
+    return 1350


 matmul_shapes_bfloat16 = [
@@ -112,10 +108,10 @@ matmul_shapes_bfloat8_b = [
     (2048, 3072, 3072, True, True, 1, 1, 1),
     (3072, 3072, 3072, True, True, 2, 1, 1),
     (3072, 3072, 4096, True, True, 2, 1, 1),
-    (3072, 4096, 4096, True, True, 1, 2, 2),
-    (4096, 4096, 4096, False, False, 1, 2, 2),
-    (8192, 8192, 8192, False, False, 2, 4, 4),
-    (16384, 16384, 16384, False, False, 4, 8, 8),
+    # Other shapes throw an error that per_core_N != out_block_w, not important
+    # (3072, 4096, 4096, True, True, 1, 2, 2),
+    # (4096, 4096, 4096, False, False, 1, 2, 2),
+    # (8192, 8192, 8192, False, False, 2, 4, 4),
+    # (16384, 16384, 16384, False, False, 4, 8, 8),
 ]

 matmul_shapes_bfloat4_b = [
@@ -142,17 +138,17 @@ matmul_configs = [
     (ttnn.bfloat8_b, ttnn.MathFidelity.HiFi2, False),
     (ttnn.bfloat8_b, ttnn.MathFidelity.LoFi, False),
     (ttnn.bfloat4_b, ttnn.MathFidelity.LoFi, False),
-    (ttnn.bfloat16, ttnn.MathFidelity.HiFi2, True),
-    (ttnn.bfloat16, ttnn.MathFidelity.HiFi4, True),
-    (ttnn.bfloat8_b, ttnn.MathFidelity.HiFi2, True),
-    (ttnn.bfloat8_b, ttnn.MathFidelity.LoFi, True),
-    (ttnn.bfloat4_b, ttnn.MathFidelity.LoFi, True),
+    # (ttnn.bfloat16, ttnn.MathFidelity.HiFi2, True),
+    # (ttnn.bfloat16, ttnn.MathFidelity.HiFi4, True),
+    # (ttnn.bfloat8_b, ttnn.MathFidelity.HiFi2, True),
+    # (ttnn.bfloat8_b, ttnn.MathFidelity.LoFi, True),
+    # (ttnn.bfloat4_b, ttnn.MathFidelity.LoFi, True),
 ]


-@pytest.mark.skip(reason="WH didt hang, need to skip CI and run locally only")
+# @pytest.mark.skip(reason="WH didt hang, need to skip CI and run locally only")
 @pytest.mark.parametrize("device_params", [{"l1_small_size": 24576, "trace_region_size": 3855488}], indirect=True)
-@pytest.mark.parametrize("grid_size", [(8, 8)])
+@pytest.mark.parametrize("grid_size", [(13, 10)])
 @pytest.mark.parametrize("tile_h", [32])
 @pytest.mark.parametrize("tile_w", [32])
 @pytest.mark.parametrize("num_warmup_iterations", [5])
@@ -208,10 +204,15 @@ def test_matmul_2d_host_perf(
                 matmul_shapes = matmul_shapes_bfloat4_b
             for m, k, n, in0_sharded, out_sharded, in0_block_w_div, num_out_blocks_h, num_out_blocks_w in matmul_shapes:
                 profiler.clear()
+
+                m = (m // 8) * grid_size[1]
+                n = (n // 8) * grid_size[0]
+                k = (k // 8) * grid_size[0]

                 in0_shape = [1, 1, m, k]
                 in1_shape = [1, 1, k, n]

+
                 in0_block_w = k // grid_size[0] // 32 // in0_block_w_div
                 per_core_M = m // grid_size[1] // tile_h
                 per_core_N = n // grid_size[0] // tile_w
@@ -308,6 +309,7 @@ def test_matmul_2d_host_perf(
                 )

                 for iter in range(0, num_warmup_iterations):
+                    time.sleep(50 / 1000)
                     output_t = ttnn.matmul(
                         in0_t,
                         in1_t,
@@ -321,6 +323,7 @@ def test_matmul_2d_host_perf(
                 if use_trace:
                     tid = ttnn.begin_trace_capture(device, cq_id=0)
                     for iter in range(0, num_measurement_iterations):
+                        time.sleep(50 / 1000)
                         output_t = ttnn.matmul(
                             in0_t,
                             in1_t,
@@ -339,6 +342,7 @@ def test_matmul_2d_host_perf(
                 else:
                     profiler.start(f"run")
                     for iter in range(0, num_measurement_iterations):
+                        time.sleep(50 / 1000)
                         output_t = ttnn.matmul(
                             in0_t,
                             in1_t,
```
**Note:** The 50ms sleeps are there in order to slow down the issuing of subsequent matmuls and allow the hardware to cool down, in case that was causing an issue. However, even a 50ms delay shows the same behavior described below:

Expected behavior:
* The test passes

Observed behavior:
* Test fails with an error `FAILED`, tries to close the device and the terminal session stays frozen. 
* After 60secs or so, I get disconnected from the machine and cannot reconnect from VSCode or terminal
* The machine goes into `completing*` state, then `completing`, then `idle/mixed` depending on the reservation count
* I cannot reconnect unless I first release the current reservation, reserve again and then reconnect.
* If I repeat the test left unchanged, I get the same error, and I believe it's for the same shape 

Conditions:
* num_measurement_iterations - 100
* machine - `bh-32`
* device - p150a
* FW version - v80.15.0.0
* tt-metal commit - d6fabf0611169b2392f2eb482d4b0ff7da4edb8d
* AI clk - 1350 MHz

The test passes if I put num_measurement_iterations = 1

### PR DESCRIPTION
**Pull request by abhullar-tt**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/20336

### Problem description
BH dram noc endpoint arbiter seems to drop requests from one noc if both nocs are issuing multiple back to back requets.

[SYS-1419](https://tenstorrent.atlassian.net/browse/SYS-1419) for more details

### What's changed
Update metal soc desc dram spec to specify different endpoints per noc and propagate this to `get_optimal_dram_bank_to_reader_assignment` by accepting the noc 

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/runs/15990457624) CI passes
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/runs/15990465236) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/runs/15917669909) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/runs/15917655833) CI passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by blozano-tt — APPROVED** [review]

File: tt_metal/api/tt-metalium/device.hpp [hunk 1]
```diff
@@ -92,7 +92,7 @@ class IDevice {
         const std::vector<CoreCoord>& logical_cores) const = 0;
 
     // Returns the optimal DRAM bank coordinates to logical worker assignment
-    virtual std::vector<CoreCoord> get_optimal_dram_bank_to_logical_worker_assignment() = 0;
+    virtual std::vector<CoreCoord> get_optimal_dram_bank_to_logical_worker_assignment(NOC noc = NOC::NOC_0) = 0;
```
Comment (blozano-tt) [inline tt_metal/api/tt-metalium/device.hpp]: `NOC` object is defined in public API already? Just want to make sure we are not exposing something we don't want to.

File: tt_metal/soc_descriptors/blackhole_140_arch.yaml [hunk 2]
```diff
@@ -20,57 +20,57 @@ dram:
       [9-5, 9-7, 9-6],
   ]
 
-# Dram view parameters are used by tt-metal and are not recognized by UMD.
-# Eth and worker dram endpoints represent subchannel id from dram array.
-# For example, a dram view where channel is 0 and worker_endpoint is 2 would resolve to dram core at position [0,2] which is 0-11.
+# Eth and worker dram endpoints represent subchannel id from dram array for each noc.Add commentMore actions
```
Comment (tt-aho) [inline tt_metal/soc_descriptors/blackhole_140_arch.yaml]: Minor typo `Add comment`

File: tt_metal/hw/inc/dataflow_api.h [hunk 3]
```diff
@@ -961,6 +961,15 @@ FORCE_INLINE void noc_async_read_tile(
     uint32_t src_addr = s.get_addr(id, bank_offset_index, bank_index, offset);
     uint32_t src_noc_xy = interleaved_addr_gen::get_noc_xy<DRAM>(bank_index, noc);
 
+    // DPRINT << "DRAM " << (uint32_t)DRAM
```
Comment (nhuang-tt) [inline tt_metal/hw/inc/dataflow_api.h]: Delete?

File: tt_metal/impl/context/metal_context.cpp [hunk 4]
```diff
@@ -647,12 +647,11 @@ void MetalContext::generate_device_bank_to_noc_tables(chip_id_t device_id) {
     const auto allocator = L1BankingAllocator(config);
     const auto& soc_d = cluster_->get_soc_desc(device_id);
     const size_t num_dram_banks = allocator.get_num_banks(BufferType::DRAM);
-    std::vector<CoreCoord> dram_noc_coord_per_bank(num_dram_banks);
     dram_bank_offset_map_[device_id].clear();
     dram_bank_offset_map_[device_id].resize(num_dram_banks);
     for (unsigned bank_id = 0; bank_id < num_dram_banks; bank_id++) {
-        dram_noc_coord_per_bank[bank_id] =
-            soc_d.get_preferred_worker_core_for_dram_view(allocator.get_dram_channel_from_bank_id(bank_id));
+        // dram_noc_coord_per_bank[bank_id] =
```
Comment (nhuang-tt) [inline tt_metal/impl/context/metal_context.cpp]: Guess this can be deleted now

**Review by nhuang-tt — APPROVED** [review]

File: tt_metal/api/tt-metalium/device.hpp (hunk 1 above)
Comment (abhullar-tt) [reply tt_metal/api/tt-metalium/device.hpp]: yes in `tt_metal/api/tt-metalium/data_types.hpp`

File: tt_metal/soc_descriptors/wormhole_b0_80_arch.yaml [hunk 5]
```diff
@@ -18,81 +18,82 @@ dram:
     [5-5, 5-6, 5-7]
   ]
 
-# Dram view parameters are used by tt-metal and are not recognized by UMD.
-# Eth and worker dram endpoints represent subchannel id from dram array.
-# For example, a dram view where channel is 0 and worker_endpoint is 2 would resolve to dram core at position [0,2] which is 0-11.
+# Dram view parameters are used by tt-metal and are not recognized by UMD.Add commentMore actions
+# Eth and worker dram endpoints represent subchannel id from dram array for each noc.
```
Comment (tt-aho) [inline tt_metal/soc_descriptors/wormhole_b0_80_arch.yaml]: Minor typo `Add comment`

**Review by tt-aho — APPROVED** [review]

**Comment by nsextonTT** [comment]
Ran into some issues in BHPC. Going to rerun failed tests.
https://github.com/tenstorrent/tt-metal/actions/runs/15949194345

Edit: Test failures were repeatable. Could you please investigate?

**Comment by abhullar-tt** [comment]
> Ran into some issues in BHPC. Going to rerun failed tests. https://github.com/tenstorrent/tt-metal/actions/runs/15949194345
> 
> Edit: Test failures were repeatable. Could you please investigate?

yes these are being looked into before merging, @bbradelTT is helping take a look at the matmul pcc issues. These have now been resolved

**Review by bbradelTT — APPROVED** [review]

File: tt_metal/api/tt-metalium/device.hpp (hunk 1 above)
Comment (jbaumanTT) [inline tt_metal/api/tt-metalium/device.hpp]: I'd prefer to not have a default value for this argument. That will require more code changes, now, but will help ensure clients actually think about which NOC they're using.

Comment (abhullar-tt) [reply tt_metal/api/tt-metalium/device.hpp]: Done

File: ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_dram_sharded_program_factory.cpp [hunk 6]
```diff
@@ -98,10 +101,32 @@ tt::tt_metal::operation::ProgramWithCallbacks create_program_dram_sharded(
...
+    uint32_t start_core_y = 0;
+    auto compute_with_storage_grid_size = device->compute_with_storage_grid_size();
+    uint32_t num_mcast_cores = compute_with_storage_grid_size.x * compute_with_storage_grid_size.y;
+
+    CoreCoord top_left_core = {(std::size_t)start_core_x, (std::size_t)start_core_y};
+    CoreCoord bottom_right_core = {
+        (std::size_t)start_core_x + compute_with_storage_grid_size.x - 1,
+        (std::size_t)start_core_y + compute_with_storage_grid_size.y - 1};
+    auto top_left_core_physical = device->worker_core_from_logical_core(top_left_core);
+    auto bottom_right_core_physical = device->worker_core_from_logical_core(bottom_right_core);
```
Comment (tt-asaigal) [inline ttnn/cpp/ttnn/operations/matmul/device/matmul_op_multi_core_reuse_mcast_dram_sharded_program_factory.cpp:114]: nit: maybe rename to virtual?

**Review by tt-asaigal — APPROVED** [review]

**Review by jbaumanTT — APPROVED** [review]

**Review by tt-dma — APPROVED** [review]

**Review by cfjchu — APPROVED** [review]

**Review by aliuTT — APPROVED** [review]
