### PR TITLE
#10211: Fix iterating cores in core range

### LINKED ISSUE #10211: CoresInCoreRangeGenerator iterates over cores outside of the given core range in certain cases
`CoresInCoreRangeGenerator` seems to iterate over cores outside of the given core range when the core range dimensions don't span the entire grid.

1. Create an instance of `CoresInCoreRangeGenerator` with a core range that doesn't span the entire grid.
2. Start iterating over the cores in this object. Eventually, the cores returned will be outside of the core range boundaries.

Iterating over the cores in a core range should only return cores within the boundary of that core range.

### PR DESCRIPTION
**Pull request by sagarwalTT**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/10211)

### Problem description
Iterating over the cores in a core range sometimes iterates over cores outside the boundaries of the core range. This commit fixes that by only iterating over the cores within the boundaries of the given core range.

### What's changed
Inside the `CoreRange` class, a nested class called `CoreIterator` is responsible for handling the iteration over cores in a core range. The iterator lazily generates the successive core to be traversed after the current core. `CoresInCoreRangeGenerator` is no longer used anywhere and so it has been removed. In order to be able to use `CoreIterator`, the `CoreRange` class has two new methods - `begin()` and `end()` - which are used when the iterator is called. Since `end` was already being used as a member variable, I renamed it to `end_`. I also renamed `start` to `start_` to be consistent. Most of the files that have been modified are because of these member variable names being changed.

### Checklist
- [x] Post commit CI passes
- [ ] Model regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by bbradelTT — APPROVED** [review]
Given that, based on the Google style guide, which I've been told we're loosely following, you're switching the field name syntax of CoreRange from struct to class, have you considered switching CoreRange to a class? And if so, why leave it as a struct?

**Review by TT-BrianLiu — COMMENTED** [review]
`start` and `end` is used really commonly for `CoreRange`. Should we rename it to something like `start_coord` and `end_coord`?

**Comment by yan-zaretskiy** [comment]
You should implement both row-wise and col-wise iteration.

**Comment by sagarwalTT** [comment]
> You should implement both row-wise and col-wise iteration.

I can modify the implementation to support col-wise iteration as well. However, if I implement support for col-wise iteration, I was thinking of leaving row-wise iteration as the default usage for `begin()` and `end()` so that users can cleanly iterate row by row when calling `CoreRange` in a for loop. Col-wise iteration could be implemented as a separate method that users would have to explicitly call and wouldn't be called implicitly in a for loop over `CoreRange`.

> `start` and `end` is used really commonly for `CoreRange`. Should we rename it to something like `start_coord` and `end_coord`?

I'm fine with leaving it as `start_` and `end_` as `CoreRange` doesn't have a lot of member variables currently, and I don't think it's ambiguous what a member variable named `start_`/`end_` for a class called `CoreRange` refers to.

**Review by yugaoTT — APPROVED** [review]

File: tt_metal/common/core_coord.h [hunk 1]
```diff
@@ -66,19 +66,19 @@ inline CoreCoord get_core_coord_from_relative(const RelativeCoreCoord &in, const
 }
 
 struct CoreRange {
-    CoreCoord start;
-    CoreCoord end;
+    CoreCoord start_;
+    CoreCoord end_;
```
Comment (ayerofieiev-tt) [inline tt_metal/common/core_coord.h:70]: I am not clear how renaming variables from proper start/end to start_/end_ help to address the iteration problem.
It makes code worse and it makes this PR unreasonable large.

Can you please revert the change to names?

**Review by ayerofieiev-tt — CHANGES_REQUESTED** [review]
CoreRange::start_/end_ names are not good. They are used actively all over the place. Please follow the recommendation from @TT-BrianLiu . I hope search-replace will be trivial

**Comment by TT-BrianLiu** [comment]
> CoreRange::start_/end_ names are not good. They are used actively all over the place. Please follow the recommendation from @TT-BrianLiu . I hope search-replace will be trivial

I agree. If something is named `arg_` or `_arg`, it should only be used internally, but it's used everywhere.

File: tests/tt_metal/tt_metal/unit_tests/common/core_coord_fixture.hpp [hunk 2]
```diff
@@ -24,9 +24,17 @@ class CoreCoordHarness : public ::testing::Test {
...
     CoreRange sc1 = CoreRange({1, 1}, {1, 1});
     CoreRange sc2 = CoreRange({0, 1}, {0, 1});
     CoreRange sc3 = CoreRange({0, 2}, {0, 2});
     CoreRange sc4 = CoreRange({1, 2}, {1, 2});
+
+    // CoreRange cr1_iterator = CoreRange({0, 0}, {0, 1}, {1, 0}, {1, 1});
+    // CoreRange cr2_iterator = CoreRange({3, 3}, {3, 4}, {4, 3}, {4, 4}, {5, 3}, {5, 4});
+    // CoreRange cr3_iterator = CoreRange({1, 2}, {2, 2});
+    // CoreRange cr15_iterator = CoreRange({0, 1}, {0, 2});
+    // CoreRange cr17_iterator = CoreRange({2, 3});
```
Comment (eyonland) [inline tests/tt_metal/tt_metal/unit_tests/common/core_coord_fixture.hpp:39]: Do we need the comments?

**Review by eyonland — APPROVED** [review]

File: tests/tt_metal/tt_metal/unit_tests/common/core_coord_fixture.hpp (hunk 2 above)
Comment (sagarwalTT) [reply tests/tt_metal/tt_metal/unit_tests/common/core_coord_fixture.hpp:39]: Ah, I meant to remove those comments before creating this PR but forgot to do so. I'll remove them before merging into main.

**Review by arakhmati — APPROVED** [review]

**Review by pgkeller — CHANGES_REQUESTED** [review]
took a quick look, I agree w/ the other comments about start_, end_.
we use the "_" for accessing members of a class w/ private scope internal to the class
since we use the core range more as a "struct", a container that conveniently holds  public members the anyone reaches in to access, IMHO, they should use "_", makes the code harder to read

**Comment by sagarwalTT** [comment]
I have renamed `start_`/`end_` to `start_coord`/`end_coord`

**Review by tt-asaigal — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by pgkeller — APPROVED** [review]

**Review by eyonland — APPROVED** [review]
