### PR TITLE
TT-Switch MeshDevice API fix and and Distributed Context barrier

### LINKED ISSUE #31340: TT-Switch: API Support to restrict DistributedContext to compute-only meshes
TT-Switch introduces a new type of mesh that performs no compute. 

@aagarwalTT mentioned there are number of spots that use `distributed_context->barrier();`. However, in a number of cases, this barrier should only apply to the compute-only mesh. 

Take a look at the following code-snippets to see how this could get implemented:
```
    // Returns distributed context for `mesh_id`.
    // Throws if `mesh_id` is unknown.
    const std::shared_ptr<tt::tt_metal::distributed::multihost::DistributedContext>& get_distributed_context(
        MeshId mesh_id) const;

    // Returns the distributed context with only one host.
    const std::shared_ptr<tt::tt_metal::distributed::multihost::DistributedContext>& get_host_local_context() const;
```

```
distributed_contexts_.emplace(local_mesh_id, global_context->create_sub_context(mpi_neighbors));
```

@aagarwalTT could you add some more input on which cases should be targetting compute-only meshes vs. all-meshes?

### PR DESCRIPTION
**Pull request by Riddy21**
## Ticket

https://github.com/tenstorrent/tt-metal/issues/31340
https://github.com/tenstorrent/tt-metal/issues/32920

## Problem description

TT-switch meshes are routing devices, not compute devices. The codebase allowed creating `MeshDevice` instances on switch meshes, causing errors. Test barriers also incorrectly included switch ranks, causing hangs since switches don't run workloads.

## What's changed

- **Device validation**: Added checks in `MeshDevice::create()` and `create_unit_meshes()` to prevent device creation on switch meshes with clear error messages
- **Compute-only context**: Added `get_compute_only_distributed_context()` that excludes switch meshes from barriers
- **Test updates**: Updated fabric test fixtures to use compute-only context for barriers
- **New tests**: Added `test_mesh_device_ttswitch.cpp` with 5 test cases covering compute/switch mesh device creation scenarios
- **Test config**: Added TT-switch test configuration files and updated test scripts

Run tests with, these are examples with how the TT-Switch is created and opening devices on them.

Note the negative tests to hang because throwing on multi-host causes barrier to hang, [ticket about this](https://github.com/tenstorrent/tt-metal/issues/33125)
```
  tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/t3k_2x2_ttswitch_rank_bindings.yaml ./build/test/ttnn/unit_tests_ttnn --gtest_filter="MeshDeviceTTSwitchFixture.TestOpenCloseComputeMeshDevice"
  tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/t3k_2x2_ttswitch_rank_bindings.yaml ./build/test/ttnn/unit_tests_ttnn --gtest_filter="MeshDeviceTTSwitchFixture.TestOpenMeshDeviceWithExplicitPhysicalDeviceIds"
  tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/t3k_2x2_ttswitch_rank_bindings.yaml ./build/test/ttnn/unit_tests_ttnn --gtest_filter="MeshDeviceTTSwitchFixture.TestOpenCloseSwitchMeshDevice"
  tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/t3k_2x2_ttswitch_rank_bindings.yaml ./build/test/ttnn/unit_tests_ttnn --gtest_filter="MeshDeviceTTSwitchFixture.TestOpenUnitMeshesOnComputeMeshFabricNodes"
  tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/t3k_2x2_ttswitch_rank_bindings.yaml ./build/test/ttnn/unit_tests_ttnn --gtest_filter="MeshDeviceTTSwitchFixture.TestOpenUnitMeshesOnSwitchFabricNodes"
```

## Checklist
[T3K](https://github.com/tenstorrent/tt-metal/actions/runs/19944930586)
[APC](https://github.com/tenstorrent/tt-metal/actions/runs/19944921058)

### CODE REVIEW

File: tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp [hunk 1]
```diff
@@ -0,0 +1,372 @@
...
+            l1_small_size_,
+            trace_region_size_,
+            tt::tt_metal::DispatchCoreConfig{tt::tt_metal::DispatchCoreType::WORKER},
+            {},     // l1_bank_remap
+            0,      // worker_l1_size (0 = dynamically determined)
+            false,  // init_profiler
+            true,   // use_max_eth_core_count_on_all_devices
+            true);  // initialize_fabric_and_dispatch_fw - this is critical!
+        // Note: devices map is intentionally not stored - devices remain in DevicePool and stay open
+    }
```
Comment (Riddy21) [inline tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp]: Still not sure how to initialize the TT-switch hosts with devices? I'm guessing its like this

File: tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp [hunk 2]
```diff
@@ -123,6 +123,11 @@ class ControlPlane {
     // Returns the distributed context with only one host.
     const std::shared_ptr<tt::tt_metal::distributed::multihost::DistributedContext>& get_host_local_context() const;
 
+    // Returns the distributed context for compute-only meshes (excludes switch meshes).
+    // This context includes all hosts that have compute meshes, but excludes hosts that only have switch meshes.
+    const std::shared_ptr<tt::tt_metal::distributed::multihost::DistributedContext>&
+    get_compute_only_distributed_context() const;
```
Comment (aagarwalTT) [inline tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp]: why did we decide to put this API here instead of in tt_metal/api/tt-metalium/distributed_context.hpp?

File: tt_metal/distributed/mesh_device.cpp [hunk 3]
```diff
@@ -235,10 +235,20 @@ std::shared_ptr<MeshDevice> MeshDevice::create(
...
             auto mapped_devices = SystemMesh::instance().get_mapped_devices(config.mesh_shape(), config.offset());
+            // Validate that none of the fabric node IDs are on switch meshes
+            for (const auto& fabric_node_id : mapped_devices.fabric_node_ids) {
+                TT_FATAL(
+                    !mesh_graph.is_switch(fabric_node_id.mesh_id),
+                    "Cannot create devices on tt-switch meshes. Fabric node {} maps to mesh_id {} which is a switch. "
+                    "Use get_compute_mesh_ids() to get valid compute mesh IDs.",
+                    fabric_node_id,
+                    *fabric_node_id.mesh_id);
+            }
```
Comment (aagarwalTT) [inline tt_metal/distributed/mesh_device.cpp:252]: if we are adding this check here then I think we need to add some handling in device pool such that we automatically open devices on the switch mesh. We would need that to setup fabric. Maybe @tt-asaigal would have some insights here as well.

File: tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp [hunk 4]
```diff
@@ -0,0 +1,375 @@
...
+            tt::tt_fabric::FabricReliabilityMode::STRICT_SYSTEM_HEALTH_SETUP_MODE);
+    }
+
+    // Helper function to initialize fabric on all devices on this host
+    // Opens all devices, initializes fabric (routing tables, fabric programs, router sync),
+    // and keeps them open so fabric routers stay running
+    // NOTE: We do NOT close these devices because closing them would terminate
+    // the fabric routers. The routers must stay running for other hosts to
+    // successfully sync with them. The devices will be cleaned up when the
+    // test fixture is torn down or the process exits.
```
Comment (aagarwalTT) [inline tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp]: This may not work as expected because whenever fabric comes up on a mesh, it waits for peer handshake over eth. If I understand correctly based on your comments, then this will only work for the 1st test in the fixture since the routers at the edge of the meshes will be able to handshake properly. But from 2nd test onwards, since one mesh (switch mesh) already has fabric running, that mesh won't initiate the handshake again and as a result the 'compute' mesh will be stuck at the sync step. I think we should tear down the switch mesh as well. 

Moreover, this maybe needed because we could change the fabric topology on the compute mesh, and the fabric must be updated on the switch mesh accordingly.

This may however not be needed if we try to add some handling for the switch mesh at the device pool level itself.

File: tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp (hunk 2 above)
Comment (Riddy21) [reply tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp]: I put the API here instead of distributed context because the compute context API relies on the mesh graph, which is owned by the control plane. in distributed context, we aren't sure if mesh graph has been instantiated yet unless control plane has been initialized

File: tt_metal/distributed/mesh_device.cpp (hunk 3 above)
Comment (Riddy21) [reply tt_metal/distributed/mesh_device.cpp:252]: I think that is the right thing to do, we should handle in the device pool that devices automatically open for switch meshes and setup fabric, I agree. Because it still needs to participate in all the distributed context barriers but should be transparent to the user when instantiating a mesh device

File: tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp (hunk 2 above)
Comment (Riddy21) [reply tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp]: We could put this in metal context similar to here?

[metal_context.cpp](https://github.com/tenstorrent/tt-metal/pull/32651/files#diff-6f640f15de38536897fb9cf858ecd1a93970ca9a11b6657b2463228ebec1224d)

File: tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp (hunk 4 above)
Comment (Riddy21) [reply tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp]: I will open and handle devices automatically in device pool for switch meshes

File: tt_metal/distributed/mesh_device.cpp (hunk 3 above)
Comment (tt-asaigal) [reply tt_metal/distributed/mesh_device.cpp:252]: Don't seen any issues with what's being requested conceptually. Based on the MGD we determine which meshes/nodes are switches, and automatically open devices/instantiate fabric on them. We likely don't even need to do a full fledged device initialization (ex loading dispatch or command queue kernels, since we're just slow dispatching fabric kernels).

I would be careful about where we put this logic And functionality though. I don't think it should be entirely in device pool, given how integrated the definition of a switch is with mesh graph/fabric.

I can see something like this happening:

User specifies switch in MGD -> CP Marks its local cluster as switch/compute -> Fabric Builder queries CP to determine which config it needs to build kernels for -> Device Pool/Metal Context load FW on device based on CP query

File: tests/scripts/t3000/run_t3000_unit_tests.sh [hunk 5]
```diff
@@ -139,6 +139,12 @@ run_t3000_ttnn_multiprocess_tests() {
 
   tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/2x2_multiprocess_rank_bindings.yaml ./build/test/ttnn/multiprocess/unit_tests_dual_rank_2x2
 
+  # Test opening/closing mesh devices on compute mesh and TT-Switch
+  tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/t3k_2x2_ttswitch_rank_bindings.yaml ./build/test/ttnn/unit_tests_ttnn --gtest_filter="MeshDeviceTTSwitchFixture.*"
+
+  # Currently hangs because of barrier hanging on multi-host when exceptions are thrown https://github.com/tenstorrent/tt-metal/issues/33125
+  #tt-run --mpi-args "$mpi_args" --rank-binding tests/tt_metal/distributed/config/t3k_2x2_ttswitch_rank_bindings.yaml ./build/test/ttnn/unit_tests_ttnn --gtest_filter="MeshDeviceTTSwitchFixture.TestOpenCloseSwitchMeshDevice"
```
Comment (Riddy21) [inline tests/scripts/t3000/run_t3000_unit_tests.sh]: @tt-asaigal I assigned this issue to you for now, we should look into failure handling for multi-host tests at some point and have some kind of timeout if a rank fails on a barrier.

https://github.com/tenstorrent/tt-metal/issues/33125

File: tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp [hunk 6]
```diff
@@ -0,0 +1,349 @@
...
+        // Close all active devices to ensure proper fabric handshake between tests.
+        // This is critical because fabric routers wait for peer handshake, and if
+        // devices remain open from a previous test, the handshake won't be re-initiated,
+        // causing subsequent tests to hang.
+        if (tt::DevicePool::is_initialized()) {
+            auto active_devices = tt::DevicePool::instance().get_all_active_devices();
+            if (!active_devices.empty()) {
+                tt::DevicePool::instance().close_devices(active_devices);
+            }
+        }
```
Comment (Riddy21) [inline tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp]: Still need to close devices on the tt-switch because device deconstructor doesn't run on non-compute hosts

File: tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp [hunk 7]
```diff
@@ -0,0 +1,349 @@
...
+            {},  // Empty device_ids - DevicePool will automatically add switch devices if on switch mesh
+            1,   // num_command_queues
+            l1_small_size_,
+            trace_region_size_,
+            tt::tt_metal::DispatchCoreConfig{tt::tt_metal::DispatchCoreType::WORKER},
+            {},     // l1_bank_remap
+            false,  // init_profiler
+            true,   // use_max_eth_core_count_on_all_devices
+            true);  // initialize_fabric_and_dispatch_fw
+    }
```
Comment (Riddy21) [inline tests/ttnn/unit_tests/gtests/test_mesh_device_ttswitch.cpp]: I see that a host doesn't participate in the device pool init, if I don't call mesh_device or CreateDevice on it. If I make tt-switch automatically initialize fabric automatically without mesh device, what should I call to trigger the init on non-compute devices? I'm trying to call DevicePool::initialize directly, but I'm not sure that's the way?

I was thinking about putting a device pool initialize in control plane or metal context, but you would have to know the switch host calls metal context for tt-switch, but then you still have to rely on something calling metal context or control plane

@tt-asaigal @aagarwalTT

File: tt_metal/distributed/mesh_device.cpp (hunk 3 above)
Comment (Riddy21) [reply tt_metal/distributed/mesh_device.cpp:252]: I've changed this so that device pool will automatically include tt-switch meshes. However some process still must call `DevicePool::initialize`, was thinking if we should include that call in control plane by any chance? @tt-asaigal  

```
tt::tt_fabric::ControlPlane& MetalContext::get_control_plane() {
    std::lock_guard<std::mutex> lock(control_plane_mutex_);
    if (!control_plane_) {
       this->initialize_control_plane_impl();
        
        // Automatically initialize DevicePool for switch meshes
        // Switch meshes need DevicePool initialized even if no mesh device is opened
        if (control_plane_ && control_plane_->is_local_host_on_switch_mesh()) {
            if (!tt::DevicePool::is_initialized()) {
                auto switch_device_ids = control_plane_->get_switch_mesh_device_ids();
                if (!switch_device_ids.empty()) {
                    log_info(
                        tt::LogMetal,
                        "Auto-initializing DevicePool for switch mesh with {} devices",
                        switch_device_ids.size());
                    // Initialize DevicePool with switch devices using defaults
                    tt::DevicePool::initialize(
                        switch_device_ids,
                        1,  // num_hw_cqs
                        DEFAULT_L1_SMALL_SIZE,
                        DEFAULT_TRACE_REGION_SIZE,
                        DispatchCoreConfig{DispatchCoreType::WORKER},
                        {},  // l1_bank_remap
                        0,   // worker_l1_size (0 = dynamically determined)
                        false,  // init_profiler
                        true,   // use_max_eth_core_count_on_all_devices
                        true);  // initialize_fabric_and_dispatch_fw
                }
            }
        }
    }
```

File: tt_metal/impl/device/device_pool.cpp [hunk 8]
```diff
@@ -297,6 +298,28 @@ void DevicePool::initialize(
...
+            for (auto switch_device_id : switch_device_ids) {
+                TT_ASSERT(
+                    std::find(device_ids_to_open.begin(), device_ids_to_open.end(), switch_device_id) ==
+                        device_ids_to_open.end(),
+                    "Switch device {} is already in the list of devices to open. This should not happen.",
+                    switch_device_id);
+                device_ids_to_open.push_back(switch_device_id);
+            }
+        }
+    }
```
Comment (Riddy21) [inline tt_metal/impl/device/device_pool.cpp]: I've changed this so that device pool will automatically include tt-switch meshes. However some process still must call `DevicePool::initialize`, was thinking if we should include that call in control plane by any chance? @tt-asaigal  

```
tt::tt_fabric::ControlPlane& MetalContext::get_control_plane() {
    std::lock_guard<std::mutex> lock(control_plane_mutex_);
    if (!control_plane_) {
       this->initialize_control_plane_impl();
        
        // Automatically initialize DevicePool for switch meshes
        // Switch meshes need DevicePool initialized even if no mesh device is opened
        if (control_plane_ && control_plane_->is_local_host_on_switch_mesh()) {
            if (!tt::DevicePool::is_initialized()) {
                auto switch_device_ids = control_plane_->get_switch_mesh_device_ids();
                if (!switch_device_ids.empty()) {
                    log_info(
                        tt::LogMetal,
                        "Auto-initializing DevicePool for switch mesh with {} devices",
                        switch_device_ids.size());
                    // Initialize DevicePool with switch devices using defaults
                    tt::DevicePool::initialize(
                        switch_device_ids,
                        1,  // num_hw_cqs
                        DEFAULT_L1_SMALL_SIZE,
                        DEFAULT_TRACE_REGION_SIZE,
                        DispatchCoreConfig{DispatchCoreType::WORKER},
                        {},  // l1_bank_remap
                        0,   // worker_l1_size (0 = dynamically determined)
                        false,  // init_profiler
                        true,   // use_max_eth_core_count_on_all_devices
                        true);  // initialize_fabric_and_dispatch_fw
                }
            }
        }
    }
```

Comment (tt-asaigal) [reply tt_metal/impl/device/device_pool.cpp]: Synced offline. This shouldn't be done in control plane. It is the responsibility of the application managing the switch to load Fabric FW.

This application can either be the Fabric Manager (when we have a persistent Fabric) or some sort of a lightweight event loop that: loads fabric -> manages queries/etc when the application is running -> turns fabric off on the switch when the application is complete.

File: tt_metal/api/tt-metalium/experimental/fabric/mesh_graph.hpp [hunk 9]
```diff
@@ -134,6 +138,8 @@ class MeshGraph {
     std::unordered_set<MeshId> get_meshes_connected_to_switch(SwitchId switch_id) const;
     bool is_mesh_connected_to_switch(MeshId mesh_id, SwitchId switch_id) const;
     std::optional<SwitchId> get_switch_for_mesh(MeshId mesh_id) const;
+    // Check if a mesh_id corresponds to a switch
+    bool is_switch(MeshId mesh_id) const;
```
Comment (aagarwalTT) [inline tt_metal/api/tt-metalium/experimental/fabric/mesh_graph.hpp]: I think we should make the switch APIs in this file consistent with the ones in CP header, that is add mesh suffix with switch. For example, is_switch_mesh(...) and so on.

File: tests/tt_metal/tt_metal/perf_microbenchmark/routing/tt_fabric_test_common.hpp [hunk 10]
```diff
@@ -1468,8 +1468,10 @@ class TestFixture : public IDeviceInfoProvider, public IRouteManager, public IDi
     }
 
     void barrier() const override {
-        const auto& distributed_context = tt::tt_metal::distributed::multihost::DistributedContext::get_current_world();
-        distributed_context->barrier();
+        // Use compute-only distributed context to exclude switch meshes from barriers
+        // Switch meshes don't run workloads, so they shouldn't participate in test synchronization
+        auto& distributed_context = tt::tt_metal::MetalContext::instance().compute_only_distributed_context();
+        distributed_context.barrier();
```
Comment (aagarwalTT) [inline tests/tt_metal/tt_metal/perf_microbenchmark/routing/tt_fabric_test_common.hpp]: couple of points here:
1. If the users are now only needed to use compute only distributed context, should we update/rename the APIs such that the compute only context is the 'default compute context'?
2. Why did we remove the const qualifier?

File: tt_metal/impl/device/device_pool.cpp [hunk 11]
```diff
@@ -297,6 +298,28 @@ void DevicePool::initialize(
...
+                tt::LogMetal,
+                "Detected switch mesh on local host. Adding {} switch devices to pool",
+                switch_device_ids.size());
+            // Add switch devices to the list of devices to open
+            // Error out if any switch device is already in device_ids_to_open (shouldn't happen)
+            for (auto switch_device_id : switch_device_ids) {
+                TT_ASSERT(
+                    std::find(device_ids_to_open.begin(), device_ids_to_open.end(), switch_device_id) ==
+                        device_ids_to_open.end(),
+                    "Switch device {} is already in the list of devices to open. This should not happen.",
```
Comment (aagarwalTT) [inline tt_metal/impl/device/device_pool.cpp]: why do we have this restriction? In my opinion we shouldn't add this unless we add an API/formalize a way to open devices on the switch mesh

File: tests/tt_metal/multihost/fabric_tests/intermesh_routing.cpp [hunk 12]
```diff
@@ -95,7 +95,10 @@ TEST_F(InterMeshSplit1x2FabricFixture, MultiHopUnicast) {
     run_send_recv(1, 2);
     run_send_recv(2, 1);
     run_send_recv(3, 0);
-    distributed_context->barrier();
+    // Use compute-only distributed context to exclude switch meshes from barriers
+    // Switch meshes don't run workloads, so they shouldn't participate in test synchronization
+    auto& compute_only_context = tt::tt_metal::MetalContext::instance().compute_only_distributed_context();
```
Comment (aagarwalTT) [inline tests/tt_metal/multihost/fabric_tests/intermesh_routing.cpp]: tt::tt_metal::MetalContext::instance().compute_only_distributed_context() was already called at the top of this function

File: tests/tt_metal/multihost/fabric_tests/intermesh_routing.cpp [hunk 13]
```diff
@@ -196,22 +199,25 @@ TEST_F(IntermeshNanoExabox2x4FabricFixture, RandomizedIntermeshUnicastBwd) {
...
         for (uint32_t i = 0; i < num_iterations; i++) {
             multihost_utils::run_unicast_recv_step(this, tt::tt_metal::distributed::multihost::Rank{sender_rank});
         }
-        log_info(tt::LogTest, "{} rank done processing unicasts", *(distributed_context->rank()));
+        log_info(tt::LogTest, "{} rank done processing unicasts", *distributed_context.rank());
     }
-    distributed_context->barrier();
+    // Use compute-only distributed context to exclude switch meshes from barriers
+    // Switch meshes don't run workloads, so they shouldn't participate in test synchronization
+    auto& compute_only_context = tt::tt_metal::MetalContext::instance().compute_only_distributed_context();
```
Comment (aagarwalTT) [inline tests/tt_metal/multihost/fabric_tests/intermesh_routing.cpp]: same here, we are querying context twice

File: tt_metal/distributed/mesh_device.cpp [hunk 14]
```diff
@@ -236,10 +236,20 @@ std::shared_ptr<MeshDevice> MeshDevice::create(
     const DispatchCoreConfig& dispatch_core_config,
     tt::stl::Span<const std::uint32_t> l1_bank_remap,
     size_t worker_l1_size) {
+    const auto& mesh_graph = MetalContext::instance().get_control_plane().get_mesh_graph();
     auto [scoped_devices, fabric_node_ids, mesh_shape] =
         [&]() -> std::tuple<std::shared_ptr<ScopedDevices>, std::vector<tt::tt_fabric::FabricNodeId>, MeshShape> {
         if (config.physical_device_ids().empty()) {
             auto mapped_devices = SystemMesh::instance().get_mapped_devices(config.mesh_shape(), config.offset());
+            // Validate that none of the fabric node IDs are on switch meshes
```
Comment (aagarwalTT) [inline tt_metal/distributed/mesh_device.cpp:244]: if we are adding this validation here then ideally we should update the existing get_mesh_ids to return only the compute mesh ids else we will need to update each file and will potentially cause confusion for the users of this API

On the contrary, we can leave it as is, drop the validation and internally handle the switch mesh case which could potentially solve the device pool init issue that you mentioned in the other thread. This of course needs to play well with the fabric manager or other event loop (that Aditya mentioned), whenever it comes to life.

File: tt_metal/impl/device/device_pool.cpp (hunk 8 above)
Comment (aagarwalTT) [reply tt_metal/impl/device/device_pool.cpp]: Can we think about adding a thin wrapper (something like a fabric switch manager) until the full blown fabric manager is implemented? It could expose methods to setup and teardown the switch mesh which would internally handle init and teardown of device pool. This will help in consolidating the workload/test side changes until we have a formal solution. Otherwise we will have to deal with users coming up with their own solutions to open/close switch mesh devices.

File: tt_metal/impl/device/device_pool.cpp (hunk 11 above)
Comment (Riddy21) [reply tt_metal/impl/device/device_pool.cpp]: There is currently no API to formalize opening devices on switch meshes, so in reality, we shouldn't ever run into a case when a switch device is already in the device pool before we add it, that's why I put it here? plz correct me if I'm wrong

File: tt_metal/distributed/mesh_device.cpp (hunk 14 above)
Comment (Riddy21) [reply tt_metal/distributed/mesh_device.cpp:244]: I don't understand why we need to drop the validation? It should be invalid to create a MeshDevice on a switch device since it is already created. we will still internally handle the switch mesh case

File: tt_metal/impl/device/device_pool.cpp (hunk 11 above)
Comment (Riddy21) [reply tt_metal/impl/device/device_pool.cpp]: Nvm, I get it

File: tests/tt_metal/tt_metal/perf_microbenchmark/routing/tt_fabric_test_common.hpp (hunk 10 above)
Comment (Riddy21) [reply tests/tt_metal/tt_metal/perf_microbenchmark/routing/tt_fabric_test_common.hpp]: Fixed

File: tt_metal/api/tt-metalium/experimental/fabric/fabric_switch_manager.hpp
Comment (Riddy21) [inline tt_metal/api/tt-metalium/experimental/fabric/fabric_switch_manager.hpp:1]: @aagarwalTT I added a switch manager class, its a singleton, so once we have fabric manager it can be initialized once and persist. However for now, we can just we can just call this to start the fabric switch manager. You can use it for any test setup.

Comment (Riddy21) [reply tt_metal/api/tt-metalium/experimental/fabric/fabric_switch_manager.hpp:1]: I kept it as a singleton with state instead of static functions in case you need it for fabric builder

File: tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp [hunk 15]
```diff
@@ -0,0 +1,317 @@
...
+        }
+
+        // Check if this is T3k
+        if (tt::tt_metal::MetalContext::instance().get_cluster().get_cluster_type() !=
+            tt::tt_metal::ClusterType::N300_2x2) {
+            GTEST_SKIP() << "This test is only for N300 2x2";
+        }
+
+        // setup tt-switch manager
+        tt::tt_fabric::FabricSwitchManager::instance().setup();
```
Comment (Riddy21) [inline tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp]: Setup and tear down for each test

File: tt_metal/api/tt-metalium/experimental/fabric/fabric_switch_manager.hpp
Comment (Riddy21) [reply tt_metal/api/tt-metalium/experimental/fabric/fabric_switch_manager.hpp:1]: I took the implementation out of device pool and kept it as create device because I think it is a more modular and standard way of initializing the switch mesh than using the device pool directly. But we can switch it to that if you see fit

File: tt_metal/fabric/control_plane.cpp [hunk 16]
```diff
@@ -2925,6 +2925,35 @@ std::string ControlPlane::get_galaxy_cabling_descriptor_path(tt::tt_fabric::Fabr
     return root_dir + std::string(it->second);
 }
 
+bool ControlPlane::is_local_host_on_switch_mesh() const {
+    const auto& local_mesh_ids = this->get_local_mesh_id_bindings();
+    const auto& mesh_graph = this->get_mesh_graph();
+    for (const auto& mesh_id : local_mesh_ids) {
```
Comment (tt-asaigal) [inline tt_metal/fabric/control_plane.cpp:3035]: Do we ever expect a single host to own a switch mesh and a compute mesh. If not should we assert in case we enter such an undefined state?

File: tt_metal/fabric/fabric_switch_manager.cpp [hunk 17]
```diff
@@ -0,0 +1,74 @@
...
+    // Create devices for the switch mesh
+    const auto& switch_device_ids =
+        tt::tt_metal::MetalContext::instance().get_control_plane().get_switch_mesh_device_ids();
+
+    // Only create devices if there are switch devices
+    if (switch_device_ids.empty()) {
+        return;
+    }
+
+    tt::tt_metal::detail::CreateDevices(
```
Comment (tt-asaigal) [inline tt_metal/fabric/fabric_switch_manager.cpp]: Note for future: Switch meshes don't need dispatch firmware initialized

File: tt_metal/fabric/fabric_switch_manager.cpp [hunk 18]
```diff
@@ -0,0 +1,74 @@
...
+        std::unordered_set<tt::ChipId> switch_device_ids_set(switch_device_ids.begin(), switch_device_ids.end());
+
+        for (auto* device : active_devices) {
+            if (switch_device_ids_set.find(device->id()) != switch_device_ids_set.end()) {
+                switch_devices_to_close.push_back(device);
+            }
+        }
+
+        if (!switch_devices_to_close.empty()) {
+            tt::DevicePool::instance().close_devices(switch_devices_to_close);
```
Comment (tt-asaigal) [inline tt_metal/fabric/fabric_switch_manager.cpp]: Why not just call `CloseDevices`?

File: tt_metal/impl/context/metal_context.hpp [hunk 19]
```diff
@@ -197,6 +198,7 @@ class MetalContext {
     tt_fabric::FabricTensixConfig fabric_tensix_config_ = tt_fabric::FabricTensixConfig::DISABLED;
     tt_fabric::FabricUDMMode fabric_udm_mode_ = tt_fabric::FabricUDMMode::DISABLED;
     std::shared_ptr<distributed::multihost::DistributedContext> distributed_context_;
+    mutable std::shared_ptr<distributed::multihost::DistributedContext> compute_only_distributed_context_;
```
Comment (tt-asaigal) [inline tt_metal/impl/context/metal_context.hpp]: I might be missing something here - why is this mutable? I understand that the getter is lazy initializing this member, though where are we accessing the metal context as a const object?

File: tests/scripts/t3000/run_t3000_unit_tests.sh (hunk 5 above)
Comment (tt-asaigal) [reply tests/scripts/t3000/run_t3000_unit_tests.sh]: Please take a look at the helpers we expose in `tests/tt_metal/multihost/common/multihost_test_tools.hpp`. The purpose of an API like `expect_equal_all_ranks` is to handle cases like the one you're encountering.

File: tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp [hunk 20]
```diff
@@ -0,0 +1,317 @@
+// SPDX-FileCopyrightText: © 2024 Tenstorrent Inc.
```
Comment (tt-asaigal) [inline tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp:1]: Is there any reason these tests are in ttnn? TT-Switch is not something we want application code in the TTNN layer to even know about.

File: tt_metal/impl/context/metal_context.hpp [hunk 21]
```diff
@@ -95,6 +95,7 @@ class MetalContext {
     tt_fabric::FabricConfig get_fabric_config() const;
 
     distributed::multihost::DistributedContext& global_distributed_context();
+    distributed::multihost::DistributedContext& compute_only_distributed_context();
```
Comment (tt-asaigal) [inline tt_metal/impl/context/metal_context.hpp]: API naming thought: Our goal with TT-Switch is to hide this entirely from users of the distributed runtime layer. When we name this API `compute_only_distributed_context`, we're informing the user of the existence of compute vs switch meshes. Does it make sense to name this as `distributed_context` (this becomes the default API for users)?

File: tt_metal/fabric/fabric_switch_manager.cpp [hunk 22]
```diff
@@ -0,0 +1,74 @@
...
+        false,                   // init_profiler
+        true,                    // use_max_eth_core_count_on_all_devices
+        true);                   // initialize_fabric_and_dispatch_fw
+}
+
+void FabricSwitchManager::teardown() {
+    // Close devices for switch meshes to ensure proper fabric handshake between tests.
+    // This is critical because fabric routers wait for peer handshake, and if
+    // devices remain open from a previous test, the handshake won't be re-initiated,
+    // causing subsequent tests to hang.
```
Comment (tt-asaigal) [inline tt_metal/fabric/fabric_switch_manager.cpp:60]: We should look into keeping the routers installed on device and setting them on standby. The next time a workload runs, the switch host simply needs to turn them on again by setting a value in L1 for example. The router will then get reactivated and wait for a handshake.

This way we can bypass having to reinit fabric firmware each time. fyi @ubcheema

File: tt_metal/impl/context/metal_context.hpp (hunk 21 above)
Comment (Riddy21) [reply tt_metal/impl/context/metal_context.hpp]: the problem with this is that if we make this the default distributed context, internal users like control plane would not treat switch meshes as part of that, there would have to be a wide scale renaming in order for all internal users to use the full distributed context, we can just call it `distributed context` or something

File: tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp (hunk 20 above)
Comment (Riddy21) [reply tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp:1]: I'll move these to tt-metal

File: tt_metal/impl/context/metal_context.hpp (hunk 19 above)
Comment (Riddy21) [reply tt_metal/impl/context/metal_context.hpp]: I meant to delete it but left it in, sorry

File: tt_metal/fabric/fabric_switch_manager.cpp (hunk 18 above)
Comment (Riddy21) [reply tt_metal/fabric/fabric_switch_manager.cpp]: Didn't know that function existed, will do

File: tt_metal/fabric/fabric_switch_manager.cpp [hunk 23]
```diff
@@ -0,0 +1,74 @@
...
+void FabricSwitchManager::setup() {
+    // Create devices for the switch mesh
+    const auto& switch_device_ids =
+        tt::tt_metal::MetalContext::instance().get_control_plane().get_switch_mesh_device_ids();
+
+    // Only create devices if there are switch devices
+    if (switch_device_ids.empty()) {
+        return;
+    }
+
```
Comment (aagarwalTT) [inline tt_metal/fabric/fabric_switch_manager.cpp:33]: we need to pipe in fabric config and also call SetFabricConfig so that we actually setup fabric on the switch mesh.

File: tt_metal/fabric/fabric_switch_manager.cpp [hunk 24]
```diff
@@ -0,0 +1,74 @@
...
+        true,                    // use_max_eth_core_count_on_all_devices
+        true);                   // initialize_fabric_and_dispatch_fw
+}
+
+void FabricSwitchManager::teardown() {
+    // Close devices for switch meshes to ensure proper fabric handshake between tests.
+    // This is critical because fabric routers wait for peer handshake, and if
+    // devices remain open from a previous test, the handshake won't be re-initiated,
+    // causing subsequent tests to hang.
+    if (tt::DevicePool::is_initialized()) {
```
Comment (aagarwalTT) [inline tt_metal/fabric/fabric_switch_manager.cpp]: why don't we cache the chip <> device handles map returned by CreateDevices API and just pass that to CloseDevices API?

File: tt_metal/impl/context/metal_context.hpp (hunk 21 above)
Comment (aagarwalTT) [reply tt_metal/impl/context/metal_context.hpp]: I agree with @tt-asaigal that we should think about the user's POV when naming these APIs. The cost of internal rename should be minimal compared to the risk of exposing APIs to the users that could cause confusion. Also looks like we have lesser instances of distributed context usage internally in the control plane, so it should not be that big of an issue?

File: tt_metal/impl/context/metal_context.hpp (hunk 19 above)
Comment (aagarwalTT) [reply tt_metal/impl/context/metal_context.hpp]: Can we bring back the `const` qualifier in the getter once we fix this?

File: tt_metal/impl/context/metal_context.cpp [hunk 25]
```diff
@@ -402,6 +399,60 @@ distributed::multihost::DistributedContext& MetalContext::global_distributed_con
...
+    for (const auto& [rank, mesh_binding] : global_logical_bindings) {
+        const auto& [mesh_id, _] = mesh_binding;
+        // Check if this mesh_id is a compute mesh (not a switch)
+        if (std::find(compute_mesh_ids.begin(), compute_mesh_ids.end(), mesh_id) != compute_mesh_ids.end()) {
+            compute_mpi_ranks.insert(rank.get());
+        }
+    }
+
+    // If no compute meshes found, fall back to host_local_context
+    if (compute_mpi_ranks.empty()) {
```
Comment (aagarwalTT) [inline tt_metal/impl/context/metal_context.cpp]: when could this happen? And should it be a failure case?

File: tt_metal/distributed/mesh_device.cpp (hunk 14 above)
Comment (aagarwalTT) [reply tt_metal/distributed/mesh_device.cpp:244]: I was suggesting that as an alternative to:
1. updating the existing call sites of get_mesh_ids to only query for compute mesh ids, or
2. updating the existing get_mesh_ids API o only return compute mesh ids

File: tt_metal/fabric/control_plane.cpp (hunk 16 above)
Comment (Riddy21) [reply tt_metal/fabric/control_plane.cpp:3035]: I was considering potential cases where this may happen, but if this is not going to happen, then I'll assert

File: tt_metal/fabric/fabric_switch_manager.cpp (hunk 23 above)
Comment (Riddy21) [reply tt_metal/fabric/fabric_switch_manager.cpp:33]: I thought this is already done in device pool?

https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/impl/device/device_manager.cpp#L316

File: tests/scripts/t3000/run_t3000_unit_tests.sh (hunk 5 above)
Comment (Riddy21) [reply tests/scripts/t3000/run_t3000_unit_tests.sh]: No that's not exactly the problem, its not that they both finish with different values, but the problem is if one rank throws an exception, the other rank will hang indefinitely on the barrier waiting for device initialization to complete. expect equal all ranks doesn't really help the issue at that point I don't think?

File: tt_metal/distributed/mesh_device.cpp (hunk 14 above)
Comment (Riddy21) [reply tt_metal/distributed/mesh_device.cpp:244]: I've changed get mesh id to only return compute mesh ids now, but I think its still good to keep the validation here in case someone tries to create a mesh device on the wrong host,.

File: tt_metal/fabric/fabric_switch_manager.cpp (hunk 22 above)
Comment (Riddy21) [reply tt_metal/fabric/fabric_switch_manager.cpp:60]: Ticket here:
https://github.com/tenstorrent/tt-metal/issues/34040

File: tt_metal/fabric/control_plane.cpp (hunk 16 above)
Comment (tt-asaigal) [reply tt_metal/fabric/control_plane.cpp:3035]: The check here only ensures that a host doesn't span multiple switch meshes. It doesn't check for cases where a host is bound to a switch and a compute mesh both. Do we want to guard against this?

**Review by tt-asaigal — APPROVED** [review]

File: tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp [hunk 26]
```diff
@@ -0,0 +1,227 @@
...
+#include "impl/context/metal_context.hpp"
+#include <llrt/tt_cluster.hpp>
+#include "ttnn/device.hpp"
+#include "ttnn/distributed/api.hpp"
+#include "tests/ttnn/unit_tests/gtests/ttnn_test_fixtures.hpp"
+
+namespace ttnn {
+namespace test {
+
+class MeshDeviceTTSwitchFixture : public TTNNFixtureBase {
```
Comment (aagarwalTT) [inline tests/tt_metal/multihost/ttswitch_tests/test_mesh_device_ttswitch.cpp]: since the tests are in metal, can we update the base fixture and the namespace?

File: tt_metal/fabric/fabric_switch_manager.cpp (hunk 23 above)
Comment (aagarwalTT) [reply tt_metal/fabric/fabric_switch_manager.cpp:33]: the code block that you have pointed to is only for setting up fabric for fast dispatch on clusters that have mmio tunnel. Since fast dispatch runs over fabric, if there is no active fabric workload, we setup a minimal fabric just to support the fast dispatch client. If a workload needs fabric, we need to explicitly set the fabric config. 

See the log here: https://github.com/tenstorrent/tt-metal/blob/main/tt_metal/impl/device/device_manager.cpp#L317

**Comment by Riddy21** [comment]
Thanks for bearing with me through this PR, I know there was a lot of reviews since I was not very familiar with the mesh device code. Thanks a lot! @aagarwalTT @tt-asaigal

File: tt_metal/fabric/fabric_switch_manager.cpp [hunk 27]
```diff
@@ -0,0 +1,76 @@
...
+    // Only create devices if there are switch devices
+    if (switch_device_ids.empty()) {
+        switch_devices_.clear();
+        return;
+    }
+
+    // Set fabric config explicitly before creating devices
+    // This is required for workloads that need fabric (not just minimal fabric for dispatch)
+    // Check if fabric config is already set, and if not, set it to FABRIC_2D for inter-mesh routing
+    tt::tt_fabric::FabricConfig current_fabric_config = tt::tt_fabric::FabricConfig::FABRIC_2D;
```
Comment (aagarwalTT) [inline tt_metal/fabric/fabric_switch_manager.cpp]: would it be better to take in the fabric config as a parameter to FabricSwitchManager::setup()? Since the current flow is that the workload itself is calling FabricSwitchManager::setup(), it knows which fabric config it wants to setup.

**Review by aagarwalTT — APPROVED** [review]

**Review by aliuTT — APPROVED** [review]

File: tests/tt_metal/multihost/ttswitch_tests/main.cpp
Comment (blozano-tt) [inline tests/tt_metal/multihost/ttswitch_tests/main.cpp:1]: I'm pretty sure gtest can create int main for you, so you don't need to add this code at all.

Comment (blozano-tt) [reply tests/tt_metal/multihost/ttswitch_tests/main.cpp:1]: https://chatgpt.com/share/6941a0b2-d9e8-8001-9da0-26430f08fa91

**Review by tt-rkim — APPROVED** [review]

File: tests/tt_metal/multihost/ttswitch_tests/main.cpp
Comment (Riddy21) [reply tests/tt_metal/multihost/ttswitch_tests/main.cpp:1]: Just following the convention set out by other tests in that suite, this way its consistent.

**Review by bbradelTT — APPROVED** [review]
