### PR TITLE
Fixed bug where the command size is incorrectly calculated to be greater than the max prefetcher command size

### LINKED ISSUE #18524: Prefetcher command size error
Branch: `asarje/prefetcher-error`
Test: `pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_transpose.py::test_resnet50_fold[16-128-128-16-1-2]`

The above gives the following message and hangs on Blackhole (did not try on WH yet) :
```
                 Always | DEBUG    | Generated prefetcher command of size 131136 B exceeds max command size 131072 B
FAILED^Z
```

### PR DESCRIPTION
**Pull request by sagarwalTT**
### Ticket
#18524 

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes (https://github.com/tenstorrent/tt-metal/actions/runs/13713360723)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable) (https://github.com/tenstorrent/tt-metal/actions/runs/13708792097)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_metal/impl/buffers/dispatch.cpp [hunk 1]
```diff
@@ -69,6 +69,13 @@ BufferDispatchConstants generate_buffer_dispatch_constants(
     return buf_dispatch_constants;
 }
 
+void update_byte_offset_in_cq(uint32_t& byte_offset, bool issue_wait, uint32_t num_sub_devices) {
```
Comment (aliuTT) [inline tt_metal/impl/buffers/dispatch.cpp:72]: This api name is suggesting a general update api. So I would expect usage to be like this:
```
void update_byte_offset_in_cq(byte_offset, bytes_to_add)

if (dispatch_params.issue_wait) {
    update_byte_offset_in_cq(byte_offset, hal.get_alignment(HalMemType::HOST) * num_sub_devices)
}
```
Otherwise, I would name this api `check_for_issue_wait_and_update_offset` or something like that

Comment (sagarwalTT) [reply tt_metal/impl/buffers/dispatch.cpp]: I've renamed it to `update_offset_on_issue_wait_cmd`

**Review by tt-aho — APPROVED** [review]
