### PR TITLE
Fix Remainder issues

### LINKED ISSUE #16394: Remainder against 0 returns left hand side. Should be all NaN
The following test will fail on the second `assert`:

```
def test_broken_remainder(device):

    torch_lhs = torch.ones(32, 32, dtype=torch.bfloat16)
    torch_rhs = torch.zeros(32, 32, dtype=torch.bfloat16)

    golden = torch.remainder(torch_lhs, torch_rhs)

    tt_lhs = ttnn.from_torch(torch_lhs, layout=ttnn.TILE_LAYOUT, device=device, dtype=ttnn.bfloat16)
    tt_rhs = ttnn.from_torch(torch_rhs, layout=ttnn.TILE_LAYOUT, device=device, dtype=ttnn.bfloat16)

    tt_result = ttnn.remainder(tt_lhs, tt_rhs)
    result = ttnn.to_torch(tt_result)

    assert torch.all(torch.isnan(golden)) # will all be nan
    assert torch.all(torch.isnan(result)) # none will be nan. In fact they will all be ones
```

The expected behaviour would be that remainder against 0 is `nan`

### LINKED ISSUE #16406: ttnn.remainder does not handle some negative inputs correctly
The following test will fail:
```
def test_broken_remainder(device):

    torch_lhs = torch.ones(32, 32, dtype=torch.bfloat16)*95
    torch_rhs = torch.ones(32, 32, dtype=torch.bfloat16)*(-94.5)

    golden = torch.remainder(torch_lhs, torch_rhs) # all -94.0

    tt_lhs = ttnn.from_torch(torch_lhs, layout=ttnn.TILE_LAYOUT, device=device, dtype=ttnn.bfloat16)
    tt_rhs = ttnn.from_torch(torch_rhs, layout=ttnn.TILE_LAYOUT, device=device, dtype=ttnn.bfloat16)

    tt_result = ttnn.remainder(tt_lhs, tt_rhs)
    result = ttnn.to_torch(tt_result) # all 0.5


    assert torch.allclose(result, golden, atol=0.01, rtol=0)
```

If you swap which operand is negative the test still fails, the sign of golden/result is just flipped too.

~~When both operands are negative it seems to work.~~ Try making the LHS -248 and the RHS -27.5, bad data comes out.

### LINKED ISSUE #17415: ttnn.remainder binary low PCC
**Describe the bug**
ttnn.remainder binary has low PCC is almost all test cases. PCC is between 0.96 and 0.99

**To Reproduce**
1. Go to sweep test `tests/sweep_framework/sweeps/eltwise/binary/remainder/remainder.py`
2. Generate parameters by running the command:
```
python3 tests/sweep_framework/sweeps_parameter_generator.py --elastic cloud --module-name eltwise.binary.remainder.remainder
```
3. Run the sweep test by running the command:
```
python3 tests/sweep_framework/sweeps_runner.py --elastic cloud --module-name eltwise.binary.remainder.remainder
```
4. See the error. Results can be found on elastic cloud as explained here: `https://github.com/tenstorrent/tt-metal/tree/main/tests/sweep_framework`

93% of tests should fail with low PCC.

### PR DESCRIPTION
**Pull request by umadevimcw**
### Ticket
#16406 
#16394 
#17415 

### Problem description
- Results are incorrect for negative divisor
- Nan is not handled 

### What's changed
- Updated the logic to handle negative divisor and nan (used device value)

### Checklist
- [ttnn - Run sweeps](https://github.com/tenstorrent/tt-metal/actions/runs/12905473076) - remainder_unary_sharded
- [ttnn - Run sweeps](https://github.com/tenstorrent/tt-metal/actions/runs/12905464214) - remainder_unary
- [ttnn - Run sweeps](https://github.com/tenstorrent/tt-metal/actions/runs/12905446676) -  remainder_scalar_pytorch2
- [ttnn - Run sweeps](https://github.com/tenstorrent/tt-metal/actions/runs/12905434985) - remainder_forge
- [ttnn - Run sweeps](https://github.com/tenstorrent/tt-metal/actions/runs/12905422405) - remainder 
- [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/runs/12905404511) - Post commit

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by VirdhatchaniKN — APPROVED** [review]

**Review by mcw-anasuya — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp [hunk 1]
```diff
@@ -366,40 +366,48 @@ Tensor ExecutePrelu::invoke(
...
+}
 // Binary remainder will be overloaded by unary remainder in another PR
 Tensor ExecuteBinaryRemainder::invoke(
     const Tensor& input_a, const Tensor& input_b, const std::optional<MemoryConfig>& output_mem_config) {
     auto arch = input_a.device()->arch();
     TT_FATAL(arch != tt::ARCH::GRAYSKULL, "Op is supported on Wormhole or Blackhole");
     DataType input_dtype = input_a.get_dtype();
+
+    float t_nan = tt::tt_metal::experimental::hal::get_nan();
+
```
Comment (eyonland) [inline ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp:393]: What is being done t_nan?

File: ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp [hunk 2]
```diff
@@ -366,40 +366,48 @@ Tensor ExecutePrelu::invoke(
...
-                ttnn::div(input_a, input_b, true, "floor", output_mem_config),
-                std::nullopt,
-                output_mem_config),
-            std::nullopt,
-            output_mem_config);
-        result = ttnn::where(ttnn::ge(result, input_b), ttnn::subtract(result, input_b), result);
-        result = ttnn::where(ttnn::ltz(input_b), ttnn::add(result, input_b), result);
-        result = ttnn::where(ttnn::eq(input_a, input_b, std::nullopt, output_mem_config), 0.0f, result);
-        return result;
+    bool do_typecast = (input_dtype == DataType::FLOAT32 && input_b.get_dtype() == DataType::FLOAT32) ? false : true;
```
Comment (patrickroberts) [inline ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp:395]:
```suggestion
    const auto do_typecast = input_dtype != DataType::FLOAT32 or input_b.get_dtype() != DataType::FLOAT32;
```

File: ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp [hunk 3]
```diff
@@ -366,40 +366,48 @@ Tensor ExecutePrelu::invoke(
...
+
+    Tensor a = input_a;
+    Tensor b = input_b;
+
+    // Typecast inputs if needed
+    if (do_typecast) {
+        a = typecast(input_a, DataType::FLOAT32);
+        b = typecast(input_b, DataType::FLOAT32);
     }
```
Comment (patrickroberts) [inline ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp:404]:
```suggestion
    const auto& a = do_typecast ? typecast(input_a, DataType::FLOAT32) : input_a;
    const auto& b = do_typecast ? typecast(input_b, DataType::FLOAT32) : input_b;
```

File: ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp (hunk 1 above)
Comment (umadevimcw) [reply ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_composite_op.cpp:393]: we are using device's nan value and using it instead of nan

**Review by KalaivaniMCW — APPROVED** [review]

**Review by mouliraj-mcw — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Review by patrickroberts — APPROVED** [review]

**Review by yan-zaretskiy — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by cfjchu — APPROVED** [review]
