### PR TITLE
Make Trace Runtime Measurement in query_op_runtime More Stable

### LINKED ISSUE #4571: getOpRuntime returns highly inconsistent results across identical runs
I am working on a feature intended to enhance op performance by moving input/output tensors from DRAM to L1. This optimization sometimes improves runtime, but for other operations it can cause slowdowns. 

The idea was to use getOpRuntime at compilation time to determine which ops should remain in DRAM vs. be placed in L1, ensuring only those that benefit from L1 are promoted.

**Problem:**
When testing, getOpRuntime results are highly inconsistent even under identical conditions:
- Running the same code on the same input with the same environment yields vastly different runtimes. Because of that some ops that are always faster in L1 in actual runtime sometimes fail to be promoted, purely because getOpRuntime occasionally reports a slower runtime.
- Logging shows the reported runtime can fluctuate by 2× or more between consecutive runs.
- As a result, memory placement decisions become essentially random.

**Current Tests:**
The existing tests for getOpRuntime only validate that:
- No error is returned
- The runtime reported is > 0

These tests pass, but they don’t catch the significant instability in reported runtimes.

**Example to reproduce:**
- Temp branch I used to log results: [bmalesevic/temp-check-op-runtime](https://github.com/tenstorrent/tt-mlir/compare/main...bmalesevic/temp-check-op-runtime)
- Commands: 

  ```
  cmake --build build -- TestOpModelLib
  ./build/test/unittests/OpModel/TTNN/Lib/TestOpModelLib --gtest_filter=*OpModelReluParam*
  ```
- Results for three runs on same build:
```
Run1:
OpModel<ttnn.relu>::getOpRuntime: 48679
[       OK ] ReluTests/OpModelReluParam.ReluOp/0 (2595 ms)
OpModel<ttnn.relu>::getOpRuntime: 18521
[       OK ] ReluTests/OpModelReluParam.ReluOp/1 (514 ms)
OpModel<ttnn.relu>::getOpRuntime: 19827
[       OK ] ReluTests/OpModelReluParam.ReluOp/2 (468 ms)
OpModel<ttnn.relu>::getOpRuntime: 19115
[       OK ] ReluTests/OpModelReluParam.ReluOp/3 (2 ms)
OpModel<ttnn.relu>::getOpRuntime: 28020
[       OK ] ReluTests/OpModelReluParam.ReluOp/4 (395 ms)
Run2:
OpModel<ttnn.relu>::getOpRuntime: 26595
[       OK ] ReluTests/OpModelReluParam.ReluOp/0 (2589 ms)
OpModel<ttnn.relu>::getOpRuntime: 19471
[       OK ] ReluTests/OpModelReluParam.ReluOp/1 (390 ms)
OpModel<ttnn.relu>::getOpRuntime: 31700
[       OK ] ReluTests/OpModelReluParam.ReluOp/2 (456 ms)
OpModel<ttnn.relu>::getOpRuntime: 19709
[       OK ] ReluTests/OpModelReluParam.ReluOp/3 (2 ms)
OpModel<ttnn.relu>::getOpRuntime: 30157
[       OK ] ReluTests/OpModelReluParam.ReluOp/4 (441 ms)
Run3:
OpModel<ttnn.relu>::getOpRuntime: 26120
[       OK ] ReluTests/OpModelReluParam.ReluOp/0 (2418 ms)
OpModel<ttnn.relu>::getOpRuntime: 26595
[       OK ] ReluTests/OpModelReluParam.ReluOp/1 (418 ms)
OpModel<ttnn.relu>::getOpRuntime: 26595
[       OK ] ReluTests/OpModelReluParam.ReluOp/2 (372 ms)
OpModel<ttnn.relu>::getOpRuntime: 22677
[       OK ] ReluTests/OpModelReluParam.ReluOp/3 (2 ms)
OpModel<ttnn.relu>::getOpRuntime: 21371
[       OK ] ReluTests/OpModelReluParam.ReluOp/4 (399 ms)
Run4:
OpModel<ttnn.relu>::getOpRuntime: 28851
[       OK ] ReluTests/OpModelReluParam.ReluOp/0 (2489 ms)
OpModel<ttnn.relu>::getOpRuntime: 60077
[       OK ] ReluTests/OpModelReluParam.ReluOp/1 (434 ms)
OpModel<ttnn.relu>::getOpRuntime: 19827
[       OK ] ReluTests/OpModelReluParam.ReluOp/2 (396 ms)
OpModel<ttnn.relu>::getOpRuntime: 19471
[       OK ] ReluTests/OpModelReluParam.ReluOp/3 (2 ms)
OpModel<ttnn.relu>::getOpRuntime: 21490
[       OK ] ReluTests/OpModelReluParam.ReluOp/4 (478 ms)
```

### PR DESCRIPTION
**Pull request by arminaleTT**
### Ticket
https://github.com/tenstorrent/tt-mlir/issues/4571

### Problem description
The op runtimes returned by this API are not stable enough. The same inputs to can result in a runtime that varies by 2x, making the number useless for the forge optimizer.

### What's changed
- Added warmup iterations prior to collecting trace runtime
  - Empirical analysis showed that the first 3-6 trace executions have higher variance and are generally much higher than the average excluding those
- Collected trace runtime from more iterations and dropped the outliers
- Closes https://github.com/tenstorrent/tt-mlir/issues/4571

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-quick-trigger.yaml) CI passes (if applicable)
- [ ] [TG demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [X] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by arminaleTT** [comment]
APC: https://github.com/tenstorrent/tt-metal/actions/runs/17467697381

File: ttnn/api/ttnn/graph/graph_query_op_runtime.hpp [hunk 1]
```diff
@@ -89,16 +90,28 @@ auto capture_op_trace(Op op, MeshDevice* device, Args&&... args) {
...
             auto start = std::chrono::high_resolution_clock::now();
             ttnn::operations::trace::execute_trace(device, trace_id, ttnn::DefaultQueueId, /* blocking = */ true);
             auto end = std::chrono::high_resolution_clock::now();
-            duration += std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
+
+            if (i >= WARMUP_TRACE_EXECUTIONS) {
+                durations[i - WARMUP_TRACE_EXECUTIONS] =
+                    std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
+            }
         }
```
Comment (TT-BrianLiu) [inline ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: For warmup, I think it's cleaner to just do:
- Run the workload `WARMUP_TRACE_EXECUTIONS` times without measuring
- Run the workload `NUM_TRACE_EXECUTIONS` times (ie. no code change)

File: ttnn/api/ttnn/graph/graph_query_op_runtime.hpp [hunk 2]
```diff
@@ -89,16 +90,28 @@ auto capture_op_trace(Op op, MeshDevice* device, Args&&... args) {
...
 
         ttnn::operations::trace::release_trace(device, trace_id);
-        return duration / NUM_TRACE_EXECUTIONS;
+
+        // Remove outliers before averaging
+        std::sort(durations.begin(), durations.end());
+        size_t offset = NUM_OUTLIERS_TO_REMOVE / 2;
+        auto begin_it = durations.begin() + offset;
+        auto end_it = durations.end() - offset;
+        uint64_t sum = std::accumulate(begin_it, end_it, static_cast<uint64_t>(0));
```
Comment (TT-BrianLiu) [inline ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: With warmup, do we still need to remove outliers?

**Review by TT-BrianLiu — CHANGES_REQUESTED** [review]

File: ttnn/api/ttnn/graph/graph_query_op_runtime.hpp (hunk 2 above)
Comment (arminaleTT) [reply ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: Fast/small unary ops unfortunately still have some instability so yes, this is needed

Comment (TT-BrianLiu) [reply ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: how large is the variance? Shouldn't average handle it?

Comment (arminaleTT) [reply ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: It can be up to 20,000-30,000 ns for a ReLu op where the average runtime excluding outliers is 20,000 ns

Comment (TT-BrianLiu) [reply ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: You could bump up the execution count if you want a better average, or use device time for more stable measurement

Comment (arminaleTT) [reply ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: This API provides runtime estimates to the forge/ttmlir optimizer during graph compilation. i.e. forge is evaluating different potential ttnn ops/op parameters and uses this API to get a perf estimate of each option by executing the option on the device. Extracting device time using the profiler would be the gold standard but it is not a practical option in this setting.

If you are strongly opposed to having the outlier removal code, I can rerun some tests and bump up the execution count, but there is a limit as higher execution count == longer graph compile time in forge

Comment (TT-BrianLiu) [reply ttnn/api/ttnn/graph/graph_query_op_runtime.hpp]: why is device time not practical? For a graph that is just a single op, e2e runtime is expected to have large fluctuations.

**Review by TT-BrianLiu — APPROVED** [review]
Looks good!
