### PR TITLE
Stopped deallocating DRAM input convs

### LINKED ISSUE #30734: Conv2d deallocate input dealocates inputs in DRAM
### Describe the bug

tests/ttnn/nightly/unit_tests/operations/conv/test_conv2d.py::test_conv2d_act_dealloc
cheeks for this functionality and has a variant where input is in DRAM.

Original idea behind this flag is to reduce memory pressure in L1 since conv2d is a composite op and runs at least halo + conv2d (microp). After halo is done input can be deallocate and leave more space in L1 for conv2d micro op.

To align with original intent, deallocate_activation in Conv2DConfig should be renamed to deallocate_activation_in_L1, and deallocate activations only if they started from L1.

### PR DESCRIPTION
**Pull request by astancovTT**
### Ticket
closes https://github.com/tenstorrent/tt-metal/issues/30734

### Problem description
Previously setting `Conv2d.deallocate_activation` deallocated inputs even if it was in DRAM.

### What's changed
- Stopped `Conv2d.deallocate_activation` deallocating DRAM inputs

### Checklist
- [X] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI [passes](https://github.com/tenstorrent/tt-metal/actions/runs/19102150256)
- [X] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI [passes](https://github.com/tenstorrent/tt-metal/actions/runs/19102166243)
- [X] [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI [relevants test pass](https://github.com/tenstorrent/tt-metal/actions/runs/19102171224)
- [X] [Nightly tt-metal L2 tests](https://github.com/tenstorrent/tt-metal/blob/main/.github/workflows/tt-metal-l2-nightly.yaml) CI [passes](https://github.com/tenstorrent/tt-metal/actions/runs/19102337480)

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp [hunk 1]
```diff
@@ -670,7 +670,7 @@ Result conv2d_L1(
                 conv_config.in_place,
                 conv_config.config_tensors_in_dram);
 
-            if (conv_config.deallocate_activation) {
+            if (should_deallocate_act) {
                 input_tensor_post_tm.deallocate(/*force*/ true);
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp:674]: Isn't here the case that input_tensor_post_tm can be sharded and the input_tesnor whose memory config you checked for the should_deallocate_act value calculation is in DRAM then we should deallocate the input_tensor_post_tm because it is its sharded copy, right?

Comment (astancovTT) [reply ttnn/cpp/ttnn/operations/conv/conv2d/conv2d.cpp:674]: It will be deallocated inside tensor destructor, but you're right it would affect the halo reallocation in case it is not deallocated at this spot (before halo output is reallocated) - fixed

**Review by dstoiljkovicTT — APPROVED** [review]
