### PR TITLE
Fix ODR violations

### LINKED ISSUE #21850: ODR violation warning with EthProcessorTypes
### Describe the bug

EthProcessorTypes has different definitions for wormhole and blackhole, but they are not wrapped in a namespace. When everything is linked into libtt_metal.so, LTO -Wodr flags them. 

```sh
[514/635] Linking CXX shared library tt_metal/libtt_metal.so
./tt_metal/hw/inc/wormhole/core_config.h:18:12: warning: type ‘EthProcessorTypes’ violates the C++ One Definition Rule [-Wodr]
   18 | enum class EthProcessorTypes : uint8_t { DM0 = 0, COUNT = 1 };
      |            ^
./tt_metal/hw/inc/blackhole/core_config.h:18:12: note: an enum with different value name is defined in another translation unit
   18 | enum class EthProcessorTypes : uint8_t { DM0 = 0, DM1 = 1, COUNT = 2 };
      |            ^
./tt_metal/hw/inc/wormhole/core_config.h:18:51: note: name ‘COUNT’ differs from name ‘DM1’ defined in another translation unit
   18 | enum class EthProcessorTypes : uint8_t { DM0 = 0, COUNT = 1 };
      |                                                   ^
./tt_metal/hw/inc/blackhole/core_config.h:18:51: note: mismatching definition
   18 | enum class EthProcessorTypes : uint8_t { DM0 = 0, DM1 = 1, COUNT = 2 };
      |                                                   ^
```

Edit: Found another one in tests:
```sh
[1093/1206] Linking CXX executable test/tt_metal/unit_tests_llk
./tests/tt_metal/tt_metal/llk/test_broadcast.cpp:67:6: warning: type ‘tt::tt_metal::unit_tests::compute::broadcast::BroadcastDim’ violates the C++ One Definition Rule [-Wodr]
   67 | enum BroadcastDim : uint8_t { ROW = 0, COL = 1, SCALAR = 2 };
      |      ^
./tests/tt_metal/tt_metal/llk/test_unary_broadcast.cpp:59:6: note: an enum with different number of values is defined in another translation unit
   59 | enum BroadcastDim : uint8_t { ROW, COL, SCALAR, NONE, NUM_DIMS };
      |      ^
```

### Steps to reproduce the issue

Build with link-time-optimization enabled and -Wodr.

### Expected behavior

Build without ODR warning.

### Please complete the following environment information

Fedora 42
$ gcc --version
gcc (GCC) 15.1.1 20250425 (Red Hat 15.1.1-1)

### PR DESCRIPTION
**Pull request by ruizhangTT**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/21850

### Problem description

- WH/BH HAL implementations introduced incompatible enum definitions.
- Two llk tests introduced incompatible enum definitions.

Though the definitions are in different files, GCC reports these as violations of the One Definition Rule, when LTO is enabled.

### What's changed
Wrap the enums in distinct namespaces.  No changes in code logic.

Cherrypicked on top of [nsexton/DNM-reenable-LTO](https://github.com/tenstorrent/tt-metal/tree/nsexton/DNM-reenable-LTO) and verified GCC is happy about ODR.

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/runs/17138887065) pending

### CODE REVIEW

**Comment by nsextonTT** [comment]
Could you please add a comment to the respective core_config.h files instructing to wrap in a namespace when included to avoid ODR violations with other core_config enum definitions?

**Comment by ruizhangTT** [comment]
> Could you please add a comment to the respective core_config.h files instructing to wrap in a namespace when included to avoid ODR violations with other core_config enum definitions?

Done.

**Review by nsextonTT — APPROVED** [review]

File: tt_metal/llrt/hal/tt-1xx/wormhole/wh_hal_active_eth.cpp [hunk 1]
```diff
@@ -23,6 +19,9 @@
 
 namespace tt::tt_metal::wormhole {
 
+// Wrap enum definitions in arch-specific namespace so as to not clash with other archs.
+#include "core_config.h"
```
Comment (omilyutin-tt) [inline tt_metal/llrt/hal/tt-1xx/wormhole/wh_hal_active_eth.cpp:23]: Is it possible to push down namespaces into individual files?

**Review by jbaumanTT — APPROVED** [review]

File: tt_metal/llrt/hal/tt-1xx/wormhole/wh_hal_active_eth.cpp (hunk 1 above)
Comment (ruizhangTT) [reply tt_metal/llrt/hal/tt-1xx/wormhole/wh_hal_active_eth.cpp:23]: I think it's possible, but device-side code needs to be changed to either add a `using namespace` or use `#ifdef` is strip out the `namespace` when compiling for device.  Another way is to create a new file called `core_config_host.h` which wraps `core_config.h` in a namespace, and only used by host.  Seems to me not worth it.

**Comment by ruizhangTT** [comment]
Looks like the fix in llk test introduces an error for clang:
```
In file included from /work/build/tests/tt_metal/tt_metal/llk/CMakeFiles/unit_tests_llk.dir/Unity/unity_0_cxx.cxx:7:
/work/tests/tt_metal/tt_metal/llk/test_broadcast.cpp:99:8: error: 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig' has a field 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig::api_convention' whose type uses the anonymous namespace [-Werror=subobject-linkage]
   99 | struct BroadcastConfig {
      |        ^~~~~~~~~~~~~~~
/work/tests/tt_metal/tt_metal/llk/test_broadcast.cpp:99:8: error: 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig' has a field 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig::eltwise_op' whose type uses the anonymous namespace [-Werror=subobject-linkage]
/work/tests/tt_metal/tt_metal/llk/test_broadcast.cpp:99:8: error: 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig' has a field 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig::broadcast_dim' whose type uses the anonymous namespace [-Werror=subobject-linkage]
/work/tests/tt_metal/tt_metal/llk/test_broadcast.cpp:99:8: error: 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig' has a field 'tt::tt_metal::unit_tests::compute::broadcast::BroadcastConfig::tile_shape' whose type uses the anonymous namespace [-Werror=subobject-linkage]
```

Maybe I shouldn't put the structs into the anonymous namespace.  Will take another look.
