### PR TITLE
[TT-Transformers] Fix long context test cases with max_seq_len override

### LINKED ISSUE #33853: QB2 model demos failing
### Describe the bug

Customer facing demo scripts do not run out of the box.

GOTO: https://github.com/tenstorrent/tt-metal/tree/main/models/tt_transformers#run-the-demo

Using Automatic Setup, the available commands are:
```
# Batch-1
pytest models/tt_transformers/demo/simple_text_demo.py -k "performance and batch-1"

# Batch-32
pytest models/tt_transformers/demo/simple_text_demo.py -k "performance and batch-32"

# Long context with custom parameters
pytest models/tt_transformers/demo/simple_text_demo.py -k "long-context" --max_seq_len=16384

# Long-context
pytest models/tt_transformers/demo/simple_text_demo.py -k "performance and long"
```

This one does not work and produces failures, other three seem to work correctly and pass:
`pytest models/tt_transformers/demo/simple_text_demo.py -k "long-context" --max_seq_len=16384` 

### Steps to reproduce the issue

Based on models tests, this configuration is consistently failing:
`pytest models/tt_transformers/demo/simple_text_demo.py -k "long-context" --max_seq_len=16384`

To reproduce, goto:
`https://github.com/tenstorrent/tt-metal/tree/main/models/tt_transformers#run-the-demo`

Complete prerequisites, set your HF_TOKEN, then for each model, example:
export HF_MODEL=deepseek-ai/DeepSeek-R1-Distill-Llama-70B
export HF_MODEL=mistralai/Mistral-7B-Instruct-v0.3
export HF_MODEL=Qwen/Qwen2.5-7B

Test will fail (other configurations pass)
```
19.25s call     models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-64k]
18.58s call     models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-64k]
16.99s call     models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-32k]
16.74s call     models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-32k]
16.20s call     models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-16k]
16.07s call     models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-16k]
0.49s setup    models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-32k]
0.49s setup    models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-64k]
0.48s setup    models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-16k]
0.48s setup    models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-16k]
0.44s setup    models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-64k]
0.44s setup    models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-32k]
0.01s teardown models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-64k]
0.01s teardown models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-16k]
0.00s teardown models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-32k]
0.00s teardown models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-16k]
0.00s teardown models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-32k]
0.00s teardown models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-64k]
====================================================================================================================== short test summary info ======================================================================================================================
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-64k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-32k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-16k] - AssertionError: Prompt prefill tokens (16199) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16199) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-64k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-32k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-16k] - AssertionError: Prompt prefill tokens (16199) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16199) <= 16384
===================================================================================================== 6 failed, 34 deselected, 4 warnings in 109.80s (0:01:49) ======================================================================================================
2025-12-04 00:17:19.836 | info     |          Device | Closing user mode device drivers (tt_cluster.cpp:442)
```

```
From initial setup that downloaded the weights:
2025-12-03 21:06:06.467 | INFO     | models.tt_transformers.tt.model_config:__init__:464 - Inferring device name: P150x4
2025-12-03 21:06:06.468 | INFO     | models.tt_transformers.tt.model_config:__init__:507 - Checkpoint directory: deepseek-ai/DeepSeek-R1-Distill-Llama-70B
2025-12-03 21:06:06.468 | INFO     | models.tt_transformers.tt.model_config:__init__:508 - Tokenizer file: deepseek-ai/DeepSeek-R1-Distill-Llama-70B/tokenizer.model
2025-12-03 21:06:06.468 | INFO     | models.tt_transformers.tt.model_config:__init__:509 - Cache directory: model_cache/deepseek-ai/DeepSeek-R1-Distill-Llama-70B/P150x4
2025-12-03 21:06:06.468 | INFO     | models.tt_transformers.tt.model_config:__init__:510 - Model name: DeepSeek-R1-Distill-Llama-70B
```

I attached logs from `export HF_MODEL=mistralai/Mistral-7B-Instruct-v0.3` test.  Setting max_seq_len to 32k did not resolve the issue entirely, although it reduced failures from 6 to 2.

[mistral_max_seq_len_32k.txt](https://github.com/user-attachments/files/23944951/mistral_max_seq_len_32k.txt)
[mistral_max_seq_len_16.txt](https://github.com/user-attachments/files/23944952/mistral_max_seq_len_16.txt)

### Expected behavior

SUCCEED for all tests on relevant machines.  In this case the focus is on QB2

### Please complete the following environment information

QB2-GE

### PR DESCRIPTION
**Pull request by gwangTT**
### Ticket
Close https://github.com/tenstorrent/tt-metal/issues/33853

### Problem description
Summarized information from the issue:

Running `pytest models/tt_transformers/demo/simple_text_demo.py -k "long-context" --max_seq_len=16384` incorrectly gives error:
```
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-64k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-32k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-16k] - AssertionError: Prompt prefill tokens (16199) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16199) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-64k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-32k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-16k] - AssertionError: Prompt prefill tokens (16199) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16199) <= 16384
```

The expected result is that the test clips the prompt sequence if its length exceeds the `max_seq_len` passed on the command line (e.g., `16384` in the issue), reserves space for the to-be-generated tokens in the total token budget (represented by `max_seq_len`), and then successfully finish the text generation test.

This test failure can be seen on both WH and BH devices. 

### What's changed
This PR fix the bug that caused the above failed test cases by correctly reserve space in the context for the generated tokens. 

The bug is in the beginning of the `preprocess_inputs_prefill` function in `models/tt_transformers/tt/common.py`:
- `max_prefill_len` is the override-able total token budget (i.e., `max_seq_len` as passed in from `simple_text_demo.py`)
- `max_context_len` is the model's maximum context length as specified by the model creators (e.g, from HF's `config.json` of a model)
- `max_prefill_len <= max_context_len` must be true (there is actually [a check for this](https://github.com/tenstorrent/tt-metal/blob/9ca166977b524a70ec0f8ba75c36a8107c7428fe/models/tt_transformers/demo/simple_text_demo.py#L893-L896) in `simple_text_demo.py`)
- Thus it is incorrect that the existing `if max_prefill_len >= m_args.max_context_len:` prevents the reservation of space (through `max_prefill_len -= max_generated_tokens`) for the generated tokens in the `max_seq_len` token budget.

Using this fix, `pytest models/tt_transformers/demo/simple_text_demo.py -k "long-context" --max_seq_len=16384` ran successfully with tests running on IRD machines, e.g. with `mistralai/Mistral-7B-Instruct-v0.3` on P150 machine:

- overly long input sequence is clipped correctly, leaving space for the generated tokens (200 in length in this test case)
```bash
2025-12-10 07:26:46.277 | INFO     | models.tt_transformers.tt.common:preprocess_inputs_prefill:165 - Encoded prompt lengths:69164
2025-12-10 07:26:46.277 | INFO     | models.tt_transformers.tt.common:preprocess_inputs_prefill:173 - Left-clipping prompts to 16184
```

- all test cases are successful
```bash
================================================================= short test summary info ==================================================================
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-performance-long-context-64k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-performance-long-context-32k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-performance-long-context-16k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-accuracy-long-context-64k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-accuracy-long-context-32k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-accuracy-long-context-16k]
================================================= 6 passed, 34 deselected, 4 warnings in 851.45s (0:14:11) =================================================
2025-12-10 07:35:45.329 | info     |          Device | Closing user mode device drivers (tt_cluster.cpp:446)
```

### Checklist
**Tests to check regressions**
- [x] Black demo tests CI passes
  - https://github.com/tenstorrent/tt-metal/actions/runs/20090540893 -- failed test cases not due to this PR
- [x] Single-card demo tests CI passes
  - https://github.com/tenstorrent/tt-metal/actions/runs/20090561065 -- failed test cases not due to this PR
- [x] T3000 demo tests
  - https://github.com/tenstorrent/tt-metal/actions/runs/20090576280 -- failed test cases not due to this PR

**Added new test case** to mistral CI to catch regression of `pytest models/tt_transformers/demo/simple_text_demo.py -k "long-context" --max_seq_len=16384` (we just need `"performance and long-context-16k" -- max_seq_len=16384`)
- [x] https://github.com/tenstorrent/tt-metal/actions/runs/20091495905 -- saw "Left-clipping prompts to 16184" in [the log
](https://github.com/tenstorrent/tt-metal/actions/runs/20091495905/job/57640250312#step:7:6162)

**Before merging:**
- [x] revert ff200f1fa2d82899cb9b232371b7b1b8232db040
  - through [f4fe051](https://github.com/tenstorrent/tt-metal/pull/34136/commits/f4fe0511ed5becfb9f88dfe1d782d94fba5a5028) 

**Test again after addressing review comments**
- [x] https://github.com/tenstorrent/tt-metal/actions/runs/20138158787

**Before merging**
- [x] revert bbe06896cb990b218924af7b6000e77313c01309
  - through 0c30227b9aee73cf6ec163fa5fd3eb2aebcdc011

### CODE REVIEW

File: tests/scripts/t3000/run_t3000_demo_tests.sh [hunk 1]
```diff
@@ -235,6 +235,8 @@ run_t3000_mistral_tests() {
   hf_model="mistralai/Mistral-7B-Instruct-v0.3"
   tt_cache_path=$TT_CACHE_HOME/$hf_model
   TT_CACHE_PATH=$tt_cache_path HF_MODEL=$hf_model pytest models/tt_transformers/demo/simple_text_demo.py --timeout 10800 -k "not performance-ci-stress-1"
+  # test max_seq_len overrides -- needs to CI=false to avoid skipping the long-context-16k test case
+  CI=false TT_CACHE_PATH=$tt_cache_path HF_MODEL=$hf_model pytest models/tt_transformers/demo/simple_text_demo.py --timeout 300 -k "performance and long-context-16k" --max_seq_len=16384
```
Comment (tt-rkim) [inline tests/scripts/t3000/run_t3000_demo_tests.sh]: `CI=false`? You want to test a non-CI case, in CI? Can you not re-code the skip logic so you don't have to do this? This seems like such an anti-pattern.

Is there any way to do this without adding 5 more minutes to t3000 demo tests? You're already running a full model with what looks to be a 3 hour timeout right above

Comment (gwangTT) [reply tests/scripts/t3000/run_t3000_demo_tests.sh]: > CI=false? You want to test a non-CI case, in CI? Can you not re-code the skip logic so you don't have to do this? This seems like such an anti-pattern.

Good point! Maybe I could combine this with an existing CI test without losing coverage? I can look for a solution.

> Is there any way to do this without adding 5 more minutes to t3000 demo tests? You're already running a full model with what looks to be a 3 hour timeout right above

The 5 minutes was already mostly in the CI already. What this new test case added is less than a minute:
- start:
```
Thu, 11 Dec 2025 00:33:36 GMT ============================= test session starts ==============================
```
- end:
```
Thu, 11 Dec 2025 00:33:59 GMT PASSED
```

Comment (gwangTT) [reply tests/scripts/t3000/run_t3000_demo_tests.sh]: The anti-pattern in the run script is fixed in [51501e6](https://github.com/tenstorrent/tt-metal/pull/34136/commits/51501e6de75ef9d9f9838f99e129b26203c7f806)

Unfortunately, this is a specific test case that cannot be merged with existing ones -- there is currently no long-context test case in CI for this model. So, we are going to still need this new test case. I lower the timeout value to 2 minute, seeing that the last run in CI took under a minute.

Comment (gwangTT) [reply tests/scripts/t3000/run_t3000_demo_tests.sh]: @tt-rkim ^

**Review by cglagovichTT — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Review by yieldthought — APPROVED** [review]
