### PR TITLE
Fix BH performance: Remove unnecessary NOC_BRCST_EXCLUDE resets

### LINKED ISSUE #14828: BH performance - Resetting NOC_BRCST_EXCLUDE on every NOC write causes 3-6% degradation for small transfers
**Describe the bug**
Running NOC BW sweep tests on BH shows that the changes made for L-shape multicast transfers caused 3-6% degradation in transfer BW when transfer size are less than 2048 bytes for unicast and near multicast.

**To Reproduce**
BW sweep tests can be done using `tests/tt_metal/tt_metal/perf_microbenchmark/dispatch/sweep_bw_and_latency.sh | tee log`. In order to reproduce the issue, a regular run should compared with a code change that eliminates the write to `NOC_BRCST_EXCLUDE`.

**Expected behavior**
Current run results on main branch can be found at https://docs.google.com/spreadsheets/d/1nN1ZPUNc2f0d6YEenBOHS7BdkpGlBysZ6SCArinGOrE/edit?pli=1&gid=2113527795#gid=2113527795. 

**Additional context**
The reg reset is needed after an L-shape multicast is used. Currently it is reset on every write operation, a change need to be made where the reg is reset only after using L-shape multicast.

### PR DESCRIPTION
**Pull request by msudumbrekar-TT**
Fixes #14828

This change removes unconditional NOC_BRCST_EXCLUDE register writes from general NOC write operations on Blackhole architecture. The register reset was causing 3-6% performance degradation for small transfers (< 2048 bytes).

Changes:
- Commented out NOC_BRCST_EXCLUDE writes in ncrisc_noc_fast_write()
- Commented out NOC_BRCST_EXCLUDE writes in ncrisc_noc_fast_write_loopback_src()
- Preserved the write in ncrisc_noc_fast_write_exclude_region() where it's needed

This aligns BH implementation with Quasar (tt-2xx) architecture where these writes are also removed.

Performance testing on BH hardware show improvements for several transfer sizes with no regressions.

### CODE REVIEW

File: tt_metal/hw/inc/internal/tt-1xx/blackhole/noc_nonblocking_api.h [hunk 1]
```diff
@@ -304,7 +304,7 @@ inline __attribute__((always_inline)) void ncrisc_noc_fast_write(
     NOC_CMD_BUF_WRITE_REG(noc, cmd_buf, NOC_RET_ADDR_MID, (uint32_t)(dest_addr >> 32) & NOC_PCIE_MASK);
     NOC_CMD_BUF_WRITE_REG(
         noc, cmd_buf, NOC_RET_ADDR_COORDINATE, (uint32_t)(dest_addr >> NOC_ADDR_COORD_SHIFT) & NOC_COORDINATE_MASK);
-    NOC_CMD_BUF_WRITE_REG(noc, cmd_buf, NOC_BRCST_EXCLUDE, 0);
+    // NOC_CMD_BUF_WRITE_REG(noc, cmd_buf, NOC_BRCST_EXCLUDE, 0);
```
Comment (abhullar-tt) [inline tt_metal/hw/inc/internal/tt-1xx/blackhole/noc_nonblocking_api.h]: delete the lines rather than commenting out and I think you can also remove: `ncrisc_noc_fast_write_exclude_region`

**Review by abhullar-tt — APPROVED** [review]
could you also remove the same from quasar/noc_nonblocking_api.h?
