### PR TITLE
Add support for int32 to transpose_wh_tile (fixes ttnn.{permute,transpose}).

### LINKED ISSUE #19950: Integer permute produces incorrect data
The following test will fail:
```
def test_integer_permute(device):

    torch_input = torch.randint(-10, 10, (1, 2, 1, 1))
    torch_output = torch.permute(torch_input, [0, 2, 3, 1])

    input_tensor = ttnn.from_torch(torch_input, layout=ttnn.TILE_LAYOUT, dtype=ttnn.int32, device=device)
    output_tensor = ttnn.permute(input_tensor, [0, 2, 3, 1])
    output_tensor = ttnn.to_torch(output_tensor)

    assert torch_output.shape == output_tensor.shape
    assert torch.all(torch_output == output_tensor)
```

If permute isn't intended to be supported for integer data types yet, an informative error should be thrown stating so instead.

### LINKED ISSUE #22383: Insufficient reset of state/config/context in LLK after transpose_wh_dest
### Describe the bug

Something is happening that breaks normal usage of ttnn after running int32 permute tests.

I've narrowed it down to running int32 permute an odd number of times, which indicates there's some kind of context or config state that doesn't get reset properly afterwards, or there's a missing reset that needs to occur at the beginning of non-int32 normal usage.

### Steps to reproduce the issue

1. Switch to https://github.com/jasondavies/tt-metal/tree/permute-int32-bfloat16-failure-leak
2. Run `pytest 'tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations[dtype=DataType.INT32-perm=[0, 3, 1, 2]-shape=[1, 1, 32, 32]]'` and observe failure
3. Run `pytest 'tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations[dtype=DataType.INT32-perm=[0, 3, 1, 2]-shape=[1, 1, 32, 32]]'` again and observe success.
4. Go to 2.

### Expected behavior

Bfloat16 should work normally and not be affected by using int32 beforehand by a completely separate process.

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by jasondavies**
### Ticket

Closes #19950

### Problem description

ttnn.permute and ttnn.transpose don't work for int32.

The root cause was that all transpose LLKs failed for int32.  See tenstorrent/tt-llk#134, which solves the issue by adding optional 32b support to `_llk_math_transpose_dest_`.

### What's changed

The `transpose_wh_tile` implementation has been changed to use a combination of unpack with `transpose_of_faces=true` to swap the middle two faces while unpacking to dest, and then `transpose_dest` with `transpose_of_faces=false` to transpose _within_ each 16x16 face using the new support for 32b values in the transpose_dest LLK API.

This fixes int32 permute/transpose for tile layouts and row major layouts.

Notes:

During implementation, a pre-existing potential race condition issue was found: https://github.com/tenstorrent/tt-metal/issues/22298 - which affects the existing bfloat16 transpose/permute implementation.  This is difficult to reproduce reliably without restricting to a single core.  However, for int32, it seems to occur slightly more frequently, causing transpose/permute test failures.

Since this is a pre-existing issue, the decision was made to note the int32 CI failure here:

- https://github.com/tenstorrent/tt-metal/actions/runs/15493207396

Here is a successful int32 CI run with 5000 NOPs inserted in the MATH thread just after `transpose_wh_tile`:

- https://github.com/tenstorrent/tt-metal/actions/runs/15536271366

These tests have been disabled for int32 until a fix is found for https://github.com/tenstorrent/tt-metal/issues/22298

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_metal/include/compute_kernel_api/transpose_wh.h [hunk 1]
```diff
@@ -65,14 +87,27 @@ ALWI void transpose_wh_init_short(uint32_t icb) {
...
+#if defined(TRISC_MATH) || defined(TRISC_UNPACK)
+    const std::uint32_t src_format = get_operand_src_format(icb);
+    const bool is_32bit = (src_format & 0xf) == (std::uint32_t)DataFormat::Int32;
+
+    if (is_32bit) {
+        copy_tile_init(icb);
+        copy_tile(icb, itile, idst);
+
+        transpose_wh_dest_init_short();
+        transpose_wh_dest<true>(idst);
```
Comment (jasondavies) [inline tt_metal/include/compute_kernel_api/transpose_wh.h:99]: @nvelickovicTT This is the key change that might be causing issues when combined with tilize/untilize?

**Comment by sjameelTT** [comment]
Hey, could you add some tests on the ttnn side too?

```
tests/tt_eager/python_api_testing/unit_testing/misc/test_transpose.py
tests/ttnn/unit_tests/operations/test_permute.py
```

I would suggest at least a single tile test and 3-4 multi tile tests. Maybe something like HW transpose for:

- 1,1,32,32
- 1,1,64,64
- 1,1,33,33
- 3,3,33,33
- 3,3,3,33,33

**Comment by jasondavies** [comment]
Can anyone suggest how to modify `tests/tt_metal/tt_metal/llk/test_transpose.cpp` test to support 32-bit values?

I updated it to support transpose_wh_dest here: 61bc0c3515d29fd6c28be127f2172e2b34bd3365

In `tests/tt_metal/tt_metal/test_kernels/dataflow/reader_unary_transpose_wh.cpp` there's a couple of comments saying `// TODO(AP): assumed 16-bits`.

Even a pointer to a similar test that works with 32-bit values (integer or float32) would be useful for comparison.

File: tt_metal/include/compute_kernel_api/transpose_wh.h [hunk 2]
```diff
@@ -65,8 +87,20 @@ ALWI void transpose_wh_init_short(uint32_t icb) {
  */
  // clang-format on
 ALWI void transpose_wh_tile(uint32_t icb, uint32_t itile, uint32_t idst) {
-    UNPACK((llk_unpack_A<BroadcastType::NONE, false>(icb, itile, false)));
-    MATH((llk_math_eltwise_unary_datacopy<A2D, BroadcastType::NONE, DST_ACCUM_MODE>(idst)));
+#if defined(TRISC_MATH) || defined(TRISC_UNPACK)
+    const std::uint32_t src_format = get_operand_src_format(icb);
+    const bool is_32bit = (src_format & 0xf) == (std::uint32_t)DataFormat::Int32;
+    if (is_32bit) {
+        copy_tile_init(icb);
```
Comment (nvelickovicTT) [inline tt_metal/include/compute_kernel_api/transpose_wh.h:94]: We generally don't call this level of API in other calls of this level API.
So, this would instead be:
`copy_tile_to_dst_init_short(cbid);`

But, even more so, `init()` calls shouldn't be in non-init API's.
The init should go to `transpose_wh_tile_init() or transpose_wh_tile_init_short()`

File: tt_metal/include/compute_kernel_api/transpose_wh.h [hunk 3]
```diff
@@ -65,8 +87,20 @@ ALWI void transpose_wh_init_short(uint32_t icb) {
...
+        copy_tile(icb, itile, idst);
```
Comment (nvelickovicTT) [inline tt_metal/include/compute_kernel_api/transpose_wh.h:95]: Similarly, this would become:

```
    UNPACK((llk_unpack_A<BroadcastType::NONE, false, EltwiseBinaryReuseDestType::NONE, UnpackToDestEn>(in_cb_id, in_tile_index)));
    MATH((llk_math_eltwise_unary_datacopy<A2D, BroadcastType::NONE, DST_ACCUM_MODE, UnpackToDestEn>( dst_tile_index, in_cb_id)));
```

File: tt_metal/include/compute_kernel_api/transpose_wh.h [hunk 4]
```diff
@@ -24,26 +28,44 @@ namespace ckernel {
  */
  // clang-format on
 ALWI void transpose_wh_init(uint32_t icb, uint32_t ocb) {
-    MATH((llk_math_eltwise_unary_datacopy_init<A2D, BroadcastType::NONE, DST_ACCUM_MODE>(true, true, icb)));
+
```
[the remark this answers is not in the document]
Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h:31]: Thank you.  There are a couple of issues with this approach unfortunately:

- We only include `llk_math_common_api.h` for `TRISC_MATH`, so this won't work for `UNPACK(...)`
- Even if we put the definition somewhere like `tt_metal/hw/ckernels/wormhole_b0/metal/llk_io/llk_operands.h`, we still run into issues where we can't use the function as a template parameter as it's not `constexpr`.  So unfortunately we always need an if-statement here AFAIK to pick between unpack_to_dest_en=true or false as a template param.

**Comment by jasondavies** [comment]
Some additional information:

- all FLOAT32/BFLOAT16 tests pass after I run `tt-smi -r 0` to reset the card.
- 117 failed, 435 passed for INT32, but the failures are mostly due to PCC slightly below 0.9999 e.g. 0.999.  The only unusual one is 0.8228 for test_permute_adversarial.  A handful of other failures are exceptions thrown probably due to issues with my tests.

**Comment by jasondavies** [comment]
Strangely the INT32 tests fail intermittently.  Run the following:

```sh
pytest -k INT32 tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations
```

1 failed, 19 passed:

> FAILED tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations[dtype=DataType.INT32-perm=[0, 2, 3, 1]-shape=[32, 32, 32, 32] - AssertionError: 0.9997898862904101

Run again:

1 failed, 19 passed (note it's a different permutation that failed):

> FAILED tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations[dtype=DataType.INT32-perm=[2, 0, 3, 1]-shape=[32, 32, 32, 32] - AssertionError: 0.9992814913405051

Run again:

20 passed.

**Comment by jasondavies** [comment]
The following change reliably induces failures in the non-int32 cases _after_ executing _one_ int32 test:

```diff
--- a/tt_metal/include/compute_kernel_api/transpose_wh_dest.h
+++ b/tt_metal/include/compute_kernel_api/transpose_wh_dest.h
@@ -38,7 +38,7 @@ ALWI void transpose_wh_dest_init_short() { MATH((llk_math_transpose_dest_init<is
 template <bool is_32bit = false>
 ALWI void transpose_wh_dest(uint32_t idst) {
     UNPACK((llk_unpack_set_srcb_dummy_valid()));
-    MATH((llk_math_transpose_dest<is_32bit>(idst)));
+    //MATH((llk_math_transpose_dest<is_32bit>(idst)));
 }

 }  // namespace ckernel
```

Note that trying to execute a second int32 test seems to result in a hang.

I don't fully understand what `llk_unpack_set_srcb_dummy_valid()` does (and the naming is confusing as it calls SET_DVALID for both SrcA and SrcB). Hopefully I've eliminated `llk_math_transpose_dest` as the cause of the issues though.

This is llk_unpack_set_srcb_dummy_valid:

```cpp
inline void _llk_unpack_set_srcb_dummy_valid_()
{
    TTI_STALLWAIT(p_stall::STALL_UNPACK, p_stall::UNPACK);
    TTI_UNPACR_NOP(SrcB, p_unpacr_nop::UNP_SET_DVALID);
    TTI_UNPACR_NOP(SrcA, p_unpacr_nop::UNP_SET_DVALID);
}
```

Maybe some kind of cleanup/reset of unpacker state is missing from transpose_wh_dest?  Given that transpose_wh_dest isn't really widely used, I wouldn't be surprised if issues like this have been undetected up until now.

**Comment by jasondavies** [comment]
To reproduce, you can try:

```sh
pytest -x -k 'INT32' tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations
pytest -x -k 'not INT32' tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations
```

Commenting out the llk_unpack_set_srcb_dummy_valid call seems to prevent the non-int32 cases from failing.

**Comment by jasondavies** [comment]
Just to summarise, there are two possibly unrelated issues right now:

1. Intermittent test failures for int32, e.g. `tests/ttnn/unit_tests/operations/test_permute.py::test_permute_4d_other_permutations[dtype=DataType.INT32-perm=[1, 2, 3, 0]-shape=[32, 32, 32, 32]]` if run repeatedly will eventually fail.  I suspect some kind of sync issue?
2. The config state leakage problem where running int32 tests seems to break all non-int32 tests that are run afterwards.  I suspect this is something that isn't properly reset in the int32 case.  Is there a good way to diagnose what this might be, e.g. dump for a specific core after each test and diff?

For the first issue, I'll try and narrow down further so it can be extracted as a standalone case.

For the second, advice or help on trying to figure out why this is happening would be great.

**Comment by nvelickovicTT** [comment]
If the problems still persists when you reduce to just transpose kernel, another thing to try is to "unroll and flatten" the compute kernel.
Mainly it boils down to unrolling [this](https://github.com/tenstorrent/tt-metal/blob/21dead5def4ed0df0b0a5d84ab1ac453fad9656f/ttnn/cpp/ttnn/operations/data_movement/permute/device/kernels/compute/transpose_xw_tiled.cpp#L37) loop, and replacing compute API calls with their implementations. For example:

```
transpose_wh_tile(cb_tilize, 0, 0);
```
becomes something like
```
#if defined(TRISC_MATH) || defined(TRISC_UNPACK)
    const std::uint32_t src_format = get_operand_src_format(icb);
    const bool is_32bit = (src_format & 0xf) == (std::uint32_t)DataFormat::Int32;
    if (is_32bit) {
        UNPACK((llk_unpack_A_init<BroadcastType::NONE, false, EltwiseBinaryReuseDestType::NONE, UnpackToDestEn>(
           0 /*transpose*/, false /*transpose within 16x16 face*/, icb)));

        MATH((llk_math_eltwise_unary_datacopy_init<A2D, BroadcastType::NONE, DST_ACCUM_MODE>(
            false /*transpose of faces*/, false /*transpose within 16x16 face*/, icb)));

        //transpose_wh_dest_init_short<true>();
        MATH((llk_math_transpose_dest_init<true>()));

        // copy_tile(icb, itile, idst);
        UNPACK((llk_unpack_A<BroadcastType::NONE, false, EltwiseBinaryReuseDestType::NONE, UnpackToDestEn>(
            icb, itile)));
        MATH((llk_math_eltwise_unary_datacopy<A2D, BroadcastType::NONE, DST_ACCUM_MODE, UnpackToDestEn>(
            idst, icb)));

        //transpose_wh_dest<true>(idst);
        UNPACK((llk_unpack_set_srcb_dummy_valid()));

        MATH((llk_math_transpose_dest<true>(idst)));
    } else {
        UNPACK((llk_unpack_A<BroadcastType::NONE, false>(icb, itile, false)));
        MATH((llk_math_eltwise_unary_datacopy<A2D, BroadcastType::NONE, DST_ACCUM_MODE>(idst)));
    }
```

and similar for other calls.

What this allows than is to group all UNPACK/MATH/PACK calls together, which should make it easier to experiment with artificial delays in different places.

**Comment by jasondavies** [comment]
> 2. The config state leakage problem where running int32 tests seems to break all non-int32 tests that are run afterwards.  I suspect this is something that isn't properly reset in the int32 case.  Is there a good way to diagnose what this might be, e.g. dump for a specific core after each test and diff?

Finally found a reproducible test for this, which happens _every other_ run which is interesting (and explains why it was hard to reproduce reliably): #22383

**Comment by aczajkowskiTT** [comment]
@nvelickovicTT @sjameelTT Merging this PR would help with an incoming TopK fix, what is the ETA?

**Comment by jasondavies** [comment]
@nvelickovicTT Updated tt-llk ref in case you want to run Wormhole integration tests again.  Note that many of the int32 permute tests fail due to the PCC being slightly below the `0.9999` target used on these tests.

I believe these tests should actually check for exact equality in many cases, and the PCC check has been hiding this pre-existing bug which affects bfloat16 too:

- #22298

In other words, I think we should probably just update PCC slightly to make these tests pass, while the pre-existing issue is tackled separately (PCC can be replaced with equality checks when that issue is resolved).

Once the Blackhole PR lands in tt-llk, we can run integration tests on that too.

**Comment by jasondavies** [comment]
@fvranicTT Would be good to run Wormhole tests on this.

**Comment by jasondavies** [comment]
@fvranicTT Sorry, I forgot there was a trig workaround in this PR, I've reverted it now.

**Comment by tt-rkim** [comment]
What appears to be the same test hangs on both N150 + N300... maybe it uses transpose underneath?

https://github.com/tenstorrent/tt-metal/actions/runs/15485918241/job/43601784970?pr=21270

**Comment by nvelickovicTT** [comment]
> @nvelickovicTT Updated tt-llk ref in case you want to run Wormhole integration tests again. Note that many of the int32 permute tests fail due to the PCC being slightly below the `0.9999` target used on these tests.
> 
> I believe these tests should actually check for exact equality in many cases, and the PCC check has been hiding this pre-existing bug which affects bfloat16 too:
> 
> * [Reproducible permute/transpose failures on single core (possible race condition) #22298](https://github.com/tenstorrent/tt-metal/issues/22298)
> 
> In other words, I think we should probably just update PCC slightly to make these tests pass, while the pre-existing issue is tackled separately (PCC can be replaced with equality checks when that issue is resolved).
> 
> Once the Blackhole PR lands in tt-llk, we can run integration tests on that too.

@jasondavies I would avoid changing PCC, especially in the wrong direction. The issue you reported should be fixed with this [PR](https://github.com/tenstorrent/tt-metal/pull/22731). It's not in yet, but if you want, you can try it locally and see if it resolves #22298.

**Comment by jasondavies** [comment]
@nvelickovicTT These tests are completely broken -- PCC shouldn't be used to check permutations at all as they should be bit-preserving: equality checks should be used instead.

The use of PCC is hiding a pre-existing issue affecting permutations of all datatypes, which you linked to.

I thought we had established that issue was most likely a race (which is why inserting NOPs works around it) and unrelated to the 4GB one?

**Comment by nvelickovicTT** [comment]
Sorry, maybe I missed something, but you referenced #22298 as the issue that track this problem. And in that issue there is a comment (https://github.com/tenstorrent/tt-metal/issues/22298#issuecomment-2904861682) referring to the #22336 issue which should get resolved with the PR I linked above. That is why I suggested to try that out.

Anyway, even if that is not the case, I still don't find lowering PCC a good idea. It hides the problem. As you say, if anything, the PCC should be 1.
My suggestion is: keep the same PCC, skip the int32 tests with comment saying what PCC they return and link to an issue that tracks it.

**Comment by jasondavies** [comment]
@nvelickovicTT It's an easy mistake to make because the 4GB issue was discovered while debugging the race condition issue, so there's a lot of discussion about both in the race condition issue.

I did respond to the comment you linked to explaining why I don't think the 4GB issue is relevant (it's the next comment).  I do think it should be prioritised if there's nobody looking at it.

> As you say, if anything, the PCC should be 1.

Well, I don't think PCC should be used at all if the intention is to check equality.  PCC can theoretically be 1.0 (perfect linear correlation) with tensors that aren't equal.

> My suggestion is: keep the same PCC, skip the int32 tests with comment saying what PCC they return and link to an issue that tracks it.

I'm really just trying to move things forward with this PR.  I can disable the failing int32 tests and restore the PCC checks to the old values (even though they're all broken!) and link to the race condition issue.

**Comment by nvelickovicTT** [comment]
> I'm really just trying to move things forward with this PR. I can disable the failing int32 tests and restore the PCC checks to the old values (even though they're all broken!) and link to the race condition issue.

OK, so let's do the following:

1. Revert PCC value change.
2. Have a run of tests in CI which show int32 functionality has slightly reduced PCC.
3. Have a run which runs the same tests in CI but with the NOPs to show that it is really a race.
4. Link these runs in this PR.
5. Comment out those tests with description why it is done and a link to the issue that tracks the problem.

With that, I think everything will be well documented and understood, and we can continue with work on the race problem.
@jasondavies does that make sense?

**Comment by jasondavies** [comment]
@nvelickovicTT Sounds good!

I'm also wary of the fact there might be a hang issue as noted by @tt-rkim, but unable to reproduce locally so far.

**Comment by jasondavies** [comment]
@nvelickovicTT PCC changes are reverted, so this is ready for a CI run that shows int32 PCC failures now (and hopefully no hang on that other test this time).

**Comment by nvelickovicTT** [comment]
OK, CI started.

**Review by sjameelTT — COMMENTED** [review]
I'm going to pre-approve for the files I own — the python tests + the changes to validate.

**Review by sjameelTT — APPROVED** [review]

**Comment by jasondavies** [comment]
All failures in this run https://github.com/tenstorrent/tt-metal/actions/runs/15493207396 are related to slightly low PCC.

Unfortunately this stops at first failure (`pytest -x`), so doesn't list _all_ failures.

@nvelickovicTT Let me know how you want to proceed.  Move to step 3 or do we need to somehow run all tests without stopping on first failure?

**Comment by nvelickovicTT** [comment]
@jasondavies Let’s move to 3 then. I am not aware of a way to run CI so as not to stop on first failure.

**Comment by jasondavies** [comment]
@nvelickovicTT For step 3, will run all tests locally first for a better chance of CI passing first time with the NOPs.

**Comment by jasondavies** [comment]
Unfortunately I reproduced the hang, so will need to investigate:

```
tests/ttnn/unit_tests/operations/test_sampling.py::test_sampling_callback[seed=2024-p=[0.0, 0.3, 0.5, 0.7, 0.9, 0.0, 0.3, 0.5, 0.7, 0.9, 0.0, 0.3, 0.5, 0.7, 0.9, 0.0, 0.3, 0.5, 0.7, 0.9, 0.0, 0.3, 0.5, 0.7, 0.9, 0.0, 0.3, 0.5, 0.7, 0.9, 0.1, 0.8]-k=[10, 15, 20, 25, 30, 10, 15, 20, 25, 30, 10, 15, 20, 25, 30, 10, 15, 20, 25, 30, 10, 15, 20, 25, 30, 10, 15, 20, 25, 30, 10, 20]-shape=[1, 1, 32, 256]]
```

**Comment by jasondavies** [comment]
Similar to #22383, looks like _something_ causes `tests/ttnn/unit_tests/operations/test_sampling.py::test_sampling_callback` to hang after running a simple int32 transpose.

The issue occurs after running a simple int32 transpose (on this branch), followed by `tests/ttnn/unit_tests/operations/test_sampling.py::test_sampling_callback` (even on main branch).  Some state/config left over by int32 transpose is causing the hang.  It could be a semaphore issue.

Does anyone have any tips on how to locate exactly where the hang occurs?

**Comment by jasondavies** [comment]
Diagnosis and fix for hang is here: tenstorrent/tt-llk#340.

**Comment by jasondavies** [comment]
Interestingly, the 5000 NOP workaround doesn't seem to work when running on 3 threads (unpack/math/pack), but works great just on math.  Might be a clue to help resolve the issue.  Just pushed the 5000 NOP workaround for math only.  We should still see a hang for the sampling test.

**Comment by jasondavies** [comment]
@nvelickovicTT As expected, step 3 shows all permute/transpose tests pass with the workaround, except for sampling (for which we already have a fix in tt-llk).  The only other failures are:

1. [tests/ttnn/integration_tests/vit/test_ttnn_optimized_sharded_vit_wh.py](https://github.com/tenstorrent/tt-metal/actions/runs/15533605578/job/43729375563?pr=21270)

```
FAILED tests/ttnn/integration_tests/vit/test_ttnn_optimized_sharded_vit_wh.py::test_vit[sequence_size=224-image_channels=3-image_size=224-batch_size=8-model_name=google/vit-base-patch16-224] - RuntimeError: bad optional access
```

I don't have N150, and the test won't run on N300, so not sure if this is related or not.

2. [tt-train](https://github.com/tenstorrent/tt-metal/actions/runs/15533605578/job/43729383686?pr=21270) - looks like a timeout issue.  Again, not sure if related.

I pushed an update to pull in the tt-llk fix, so I guess we can retry and see if either of the above are affected.

**Comment by fvranicTT** [comment]
@jasondavies tt-train is a global one, nothing to do with your change: https://github.com/tenstorrent/tt-metal/pull/23276

File: tt_metal/include/compute_kernel_api/transpose_wh.h [hunk 5]
```diff
@@ -65,8 +94,23 @@ ALWI void transpose_wh_init_short(uint32_t icb) {
...
+    const std::uint32_t src_format = get_operand_src_format(icb);
+    const bool is_32bit = (src_format & 0xf) == (std::uint32_t)DataFormat::Int32;
+
+    if (is_32bit) {
+        UNPACK((llk_unpack_A<BroadcastType::NONE, false, EltwiseBinaryReuseDestType::NONE, UnpackToDestEn>(icb, itile, true)));
+        UNPACK((llk_unpack_set_srcb_dummy_valid()));
+        MATH((llk_math_eltwise_unary_datacopy<A2D, DST_ACCUM_MODE, BroadcastType::NONE, UnpackToDestEn>(idst)));
+        MATH((llk_math_transpose_dest<false, true>(idst)));
+	MATH({
+            for (int i = 0; i < 5000; ++i) TTI_NOP;
```
Comment (bbradelTT) [inline tt_metal/include/compute_kernel_api/transpose_wh.h]: Why is this needed? This is not in the PR description. Would be good to add there.

If this will be fixed at some point, there should be a comment with an issue number.

File: tt_metal/include/compute_kernel_api/transpose_wh.h [hunk 6]
```diff
@@ -65,8 +94,23 @@ ALWI void transpose_wh_init_short(uint32_t icb) {
  */
  // clang-format on
 ALWI void transpose_wh_tile(uint32_t icb, uint32_t itile, uint32_t idst) {
-    UNPACK((llk_unpack_A<BroadcastType::NONE, false>(icb, itile, false)));
-    MATH((llk_math_eltwise_unary_datacopy<A2D, DST_ACCUM_MODE, BroadcastType::NONE>(idst)));
+#if defined(TRISC_MATH) || defined(TRISC_UNPACK)
```
Comment (bbradelTT) [inline tt_metal/include/compute_kernel_api/transpose_wh.h:94]: nit:
Can this if be removed? For PACK the code should just be compiled out. Or is there an error or perf hit?

Makes me think that maybe there could be two helper functions. But that seems like it would make the code more complex.

**Review by bbradelTT — APPROVED** [review]

File: tt_metal/include/compute_kernel_api/transpose_wh.h (hunk 5 above)
Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h]: This is part of our plan to document the fact that the tests pass in CI with this workaround, and then remove it afterwards and disable the failing tests (with a link to the issue).  See [comment](https://github.com/tenstorrent/tt-metal/pull/21270#issuecomment-2949423946).

File: tt_metal/include/compute_kernel_api/transpose_wh.h (hunk 6 above)
Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h:94]: There is an error due to `const std::uint32_t src_format = get_operand_src_format(icb);`.  This uses `unpack_src_format` which is only available for unpack/math.

File: tt_metal/include/compute_kernel_api/transpose_wh.h (hunk 5 above)
Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h]: BTW the race condition issue is here: https://github.com/tenstorrent/tt-metal/issues/22298 and it affects bfloat16 too, though tricky to reproduce without restricting to single core.  So I guess the idea is that since the existing implementation suffers from the same problem, it probably shouldn't block this PR.

File: tt_metal/include/compute_kernel_api/transpose_wh.h (hunk 6 above)
Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h:94]: One idea could be to group into UNPACK/MATH e.g.

```cpp
UNPACK({
  if (get_operand_src_format(icb) & 0xf == (std::uint32_t)DataFormat::Int32) {
    llk_unpack_A<BroadcastType::NONE, false, EltwiseBinaryReuseDestType::NONE, UnpackToDestEn>(icb, itile, true);
    llk_unpack_set_srcb_dummy_valid();
  } else {
    llk_unpack_A<BroadcastType::NONE, false>(icb, itile, true);
  }
});
MATH({ ... });
```

Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h:94]: We would need to adjust the macro definitions for UNPACK/MATH to make this work though, e.g. `#define UNPACK(x) do { x } while(0)`

Comment (bbradelTT) [reply tt_metal/include/compute_kernel_api/transpose_wh.h:94]: It's ok to leave the code as is. If you group, then you're duplicating the if/else which is adding complexity.

Thanks.

File: tt_metal/include/compute_kernel_api/transpose_wh.h (hunk 5 above)
Comment (bbradelTT) [reply tt_metal/include/compute_kernel_api/transpose_wh.h]: Please add some info to the "What's Changed" section of the description.

**Comment by jasondavies** [comment]
Summary so far:

- without workaround, we have int32 failures due to slightly low PCC: https://github.com/tenstorrent/tt-metal/actions/runs/15493207396
- with 5000 NOPS (MATH) workaround, all green except tt-train (unrelated): https://github.com/tenstorrent/tt-metal/actions/runs/15536271366?pr=21270

Tracking issue for race condition is here: https://github.com/tenstorrent/tt-metal/issues/22298.

Next step is to remove the NOPs and disable the int32 tests with a link to the race condition issue.  Sound good?  /cc @nvelickovicTT

File: tt_metal/include/compute_kernel_api/transpose_wh.h (hunk 5 above)
Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h]: Updated the description, it was a bit out of date.  I've documented the CI runs, and I think the next step is to disable these failing int32 tests and remove the NOPs.

**Comment by nvelickovicTT** [comment]
@jasondavies that sounds good. Please go ahead, remove NOPs and disable the problematic tests (only for int32 data format).

**Comment by jasondavies** [comment]
@nvelickovicTT I disabled another couple of failing int32 tests (and merged with latest main).

**Comment by jasondavies** [comment]
@nvelickovicTT All tests are green!

File: tests/ttnn/unit_tests/operations/test_permute.py [hunk 7]
```diff
@@ -206,13 +225,11 @@ def test_permute_5d_width(shape, perm, memory_config, dtype, device):
 @pytest.mark.parametrize("shape", [(3, 65, 3, 3, 65), (1, 6, 256, 20, 50), (6, 20, 50, 1, 256)])
 @pytest.mark.parametrize("perm", [(4, 0, 3, 2, 1), (1, 3, 4, 0, 2), (3, 0, 4, 1, 2)])
 @pytest.mark.parametrize("memory_config", [ttnn.DRAM_MEMORY_CONFIG, ttnn.L1_MEMORY_CONFIG])
+# int32 fails due to possible race condition: https://github.com/tenstorrent/tt-metal/issues/22298
```
Comment (fvranicTT) [inline tests/ttnn/unit_tests/operations/test_permute.py]: Would this work instead?
```python
@pytest.mark.parametrize("dtype", [
    ttnn.bfloat16,
    ttnn.float32,
    pytest.param(
        ttnn.int32,
        marks=pytest.mark.skip(reason="int32 fails due to possible race condition: https://github.com/tenstorrent/tt-metal/issues/22298")
    ),
])
```
That way int32 is till collected and marked as skipped, and we provide a reason why.

Comment (jasondavies) [reply tests/ttnn/unit_tests/operations/test_permute.py]: Sounds good, thanks.

File: tt_metal/include/compute_kernel_api/transpose_wh.h [hunk 8]
```diff
@@ -65,8 +94,20 @@ ALWI void transpose_wh_init_short(uint32_t icb) {
...
+    const std::uint32_t src_format = get_operand_src_format(icb);
+    const bool is_32bit = (src_format & 0xf) == (std::uint32_t)DataFormat::Int32;
```
Comment (nvelickovicTT) [inline tt_metal/include/compute_kernel_api/transpose_wh.h]: `is_32bit` implies this covers all 32bit formats. Is that true?
If so, then we should check for FP32 and UInt32 as well.
If not, perhaps rename the flag to `is_int32`.

**Review by nvelickovicTT — APPROVED** [review]

File: tt_metal/include/compute_kernel_api/transpose_wh.h (hunk 8 above)
Comment (jasondavies) [reply tt_metal/include/compute_kernel_api/transpose_wh.h]: I believe this actually just checks both UInt32 and Int32 due to the `0xf` bitmask.

```cpp
Int32 = 8,
UInt32 = 24,
```

I wonder if it might cause too many issues if we expand this to include float32 at this stage, so we should probably just rename this to `is_int32`?

**Comment by jasondavies** [comment]
I see another int32 failure in the ongoing CI:

```
FAILED tests/ttnn/unit_tests/operations/test_permute.py::test_permute_8d_swapped[dtype=DataType.INT32-dims=(5, 4, 3, 2, 1, 0, 7, 6)-shape=[2, 2, 2, 2, 2, 2, 32, 32]] - AssertionError: 0.9998411879284664
```

I can disable this too.  Doesn't feel great knowing that some of the remaining int32 permute tests _might_ randomly fail.

**Comment by jasondavies** [comment]
@nvelickovicTT All green (again)!

**Comment by nvelickovicTT** [comment]
@jasondavies great! There are still a few more codeowners required to review.
@aagarwalTT, @abhullar-tt, @jbaumanTT, @nhuang-tt, @tt-aho could you please take a look?

**Comment by jasondavies** [comment]
and/or @tt-asaigal 👍

**Review by tt-aho — APPROVED** [review]
