### PR TITLE
Fix comment/doc typos.

### LINKED ISSUE #38761: Fix comment/doc typos.

### PR DESCRIPTION
**Pull request by jasondavies**
Closes https://github.com/tenstorrent/tt-metal/issues/38761

### Checklist

- [ ] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml?query=branch:{{branch_name}})
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:{{branch_name}})
- [ ] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:{{branch_name}})
- [ ] New/Existing tests provide coverage for changes

#### Model tests

If your changes cover model-related code, you should run tests corresponding to affected models and platforms (Single card, T3K, Galaxy). "Choose your pipeline" workflows facilitate running multiple kinds of tests in a single run. Each offers `models-mandatory` and `models-extended` presets.
The former includes a minimal set of tests, to be run always. The latter extends that with additional ones - use your best judgement in deciding which is the most appropriate for your PR.

- [ ] [(Single) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:{{branch_name}})
  - [ ] `models-mandatory` preset (runs: [Device perf regressions](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) and [Frequent model and ttnn tests](https://github.com/tenstorrent/tt-metal/actions/workflows/fast-dispatch-full-regressions-and-models.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(T3K) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:{{branch_name}})
  - [ ] `models-mandatory` preset (runs: [Unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-model-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(Galaxy) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:{{branch_name}})
  - [ ] `models-mandatory` preset (runs: [Quick tests](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]

**Review by handrewsTT — APPROVED** [review]

**Review by p1-0tr — APPROVED** [review]

**Review by nathan-TT — APPROVED** [review]
great cleanup!

**Review by rdraskicTT — APPROVED** [review]

**Review by cglagovichTT — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by ruizhangTT — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]

**Review by skhorasganiTT — APPROVED** [review]

**Review by nhuang-tt — APPROVED** [review]

**Review by dstoiljkovicTT — APPROVED** [review]

**Review by miacim — APPROVED** [review]

**Review by fvranicTT — APPROVED** [review]

**Review by mgajewskiTT — APPROVED** [review]

**Review by mdragulaTT — APPROVED** [review]

**Review by nvelickovicTT — APPROVED** [review]

**Review by mo-tenstorrent — APPROVED** [review]

**Review by atatuzunerTT — APPROVED** [review]

**Review by tt-aho — APPROVED** [review]

**Review by wenbinlyuTT — APPROVED** [review]

**Comment by fvranicTT** [comment]
@wilderfield could we please use some of your magic here? Any objection to that? As far as I could see, we have no functional changes, only typo fixes. Thanks!

**Review by riverwuTT — APPROVED** [review]
Thank you!

File: tt_metal/tools/profiler/fabric_event_profiler.hpp [hunk 1]
```diff
@@ -113,8 +114,8 @@ FORCE_INLINE void recordRoutingFields1D(uint32_t routing_fields) {
     kernel_profiler::timeStampedData<STATIC_ID, kernel_profiler::DoingDispatch::DISPATCH>(event_routing_fields.asU64());
 }
 
-// how slow is this? alternative is storing entire route buffer which isn't ideal either...
-template <uint32_t STATIC_ID = 12345>
+// how slow is this? alternative is sotring entire route buffer which isn't ideal either...
```
Comment (fvranicTT) [inline tt_metal/tools/profiler/fabric_event_profiler.hpp]: ?

**Review by jbakerTT — APPROVED** [review]
Approving as codeowner bypass.  This is documentation only, and I concur that this should be done ASAP.

**Review by blozano-tt — COMMENTED** [review]
Thanks for the thorough cleanup, @jasondavies! 🙏

I reviewed every change in this PR and verified that **none of the spelling corrections would break anything**. Here's a summary of my findings:

### Scope of changes (~380+ files)

1. **Code comments (vast majority)** — Fixes across C++ kernels, header files, Python source, and shell scripts. All changes are within comment blocks (`//`, `/* */`, `#`) and have zero impact on compiled code or runtime behavior.

2. **String literals in error/assertion messages** — Typos fixed in `TT_FATAL`, `log_debug`, and assertion messages (e.g. `"divisble" → "divisible"`, `"Atleast" → "At least"`, `"weigth" → "weight"`). These are display-only strings used for error reporting and are not matched against programmatically anywhere.

3. **Documentation strings / docstrings** — Fixes in nanobind `R"doc(...)doc"` strings and Python docstrings. These affect only generated documentation, not logic.

4. **Documentation files** — Fixes across `.md`, `.rst`, and `.ipynb` files in `docs/`, `tech_reports/`, `releases/`, and `ttnn/tutorials/`. Purely textual.

5. **Formatting in `test_autograd.py`** — One actual typo fix (`occurence → occurrence`) plus cosmetic reformatting (collapsing multi-line function call args to single lines). No logic changes.

6. **NoC overlay parameter headers** — All 100+ changes in `noc_overlay_parameters.{h,hpp,cpp}` files are exclusively in comments describing register fields. No `#define` names, values, or code were altered.

7. **Build script (`build_metal.sh`)** — Single comment-only fix (`eachother → each other`).

### Risk assessment: ✅ Zero risk

- **No variable names, function names, macros, or identifiers were changed**
- **No compile-time arguments or register definitions were modified**
- **No test assertions match against any of the corrected strings**
- All changes are confined to human-readable text (comments, docs, error messages)

One minor observation: in `adaptive_pool_utils.cpp`, the fix changes `"padds" → "pads"` but the adjacent typo `"tesnor"` (should be "tensor") in the same sentence was left unfixed. Very minor — just flagging in case you want to catch it in a follow-up.

Great contribution — this kind of cleanup improves code readability across the entire codebase!

**Comment by blozano-tt** [comment]
I swear I did not use AI.

**Review by blozano-tt — COMMENTED** [review]
**Updated review — now covering all 381 files** (my earlier review only covered ~200 due to API pagination; apologies for the incomplete first pass).

After reviewing the complete diff across all **381 files**, my assessment remains: **✅ Zero breakage risk**. Here's the updated and more detailed breakdown:

---

### Categories of changes

**1. Comments & documentation (~350+ files)** — The vast majority. Fixes in `//`, `/* */`, `#` comments, `.md`/`.rst` docs, Jupyter notebooks, changelogs, and tech reports. No impact on compiled code.

**2. String literals in error/log/doc messages (~50+ instances)** — Typos fixed in `TT_FATAL`, `TT_THROW`, `log_debug`, nanobind `R"doc()"`, Python docstrings, and assertion messages. These are display-only and not matched programmatically.

**3. Actual variable/identifier renames (3 cases — all safe):**
- `termiation_signal` → `termination_signal` in `test_tt_fabric_mux_bandwidth.cpp` — local variable; all 3 references updated in same scope.
- `cb_exp_sum_after_refuction` → `cb_exp_sum_after_reduction` in `cross_entropy_bw_program_factory.cpp`, `cross_entropy_fw_program_factory.cpp`, `softmax_program_factory.cpp` — local CB variables; each used only within its declaring scope.
- `is_nigthly_tt_train_tests_enabled` → `is_nightly_tt_train_tests_enabled` in `nano_gpt_test.cpp` — local `constexpr bool`; both declaration and its single usage updated together. The matching `"NIGTHLY_"` → `"NIGHTLY_"` string in `MEMORY_TRACKING.md` is documentation describing these test names.

**4. String data in `noc_overlay_parameters.{cpp,h,hpp}`** — These files contain string literal descriptions of hardware registers (e.g. `"// PARTIAL_SEND_WORDS_THR contols..."` → `"controls"`). While technically string data rather than comments, these strings are used purely for documentation/code-generation annotations and don't affect register definitions, addresses, or bit widths.

**5. Formatting in `test_autograd.py`** — One typo fix (`occurence` → `occurrence`) plus cosmetic reformatting (collapsing multi-line args to single lines). No logic changes.

### Risk assessment: ✅ Zero risk

- No `#define` names, macro values, register addresses, or bit widths were modified
- The 3 variable renames are self-contained local changes with all references updated
- No test assertions pattern-match against any of the corrected strings
- No API signatures, function names, or public interfaces were changed

Minor observation (same as before): in `adaptive_pool_utils.cpp`, the word `"tesnor"` in the same sentence as the `"padds" → "pads"` fix was left uncorrected.

**Comment by blozano-tt** [comment]
Who would have ever thought that correcting spelling in a comment would be the killer pattern that breaks our ccache setup.
