### PR TITLE
A couple small watcher fixes

### LINKED ISSUE #12957: Force a watcher poll on exit
So that we can pick up any anything that tripped between the last scheduled watcher poll and the devices closing. Need to do this before the first device detaches from watcher.

### LINKED ISSUE #14693: watcher needs to validate all device state before use
Some code has crept into watcher:
    uint32_t launch_msg_read_ptr = mbox_data->launch_msg_rd_ptr;
    bool enabled = (mbox_data->watcher.enable == WatcherEnabled);

Both launch_msg_read_ptr and watcher_enable need to be validated for legal state an throw an error if corrupt
(hit a case where a bug overwrite L1 and corrupted the rd_ptr)

### PR DESCRIPTION
**Pull request by tt-dma**
https://github.com/tenstorrent/tt-metal/issues/12957 and https://github.com/tenstorrent/tt-metal/issues/14693
CI: https://github.com/tenstorrent/tt-metal/actions/runs/16355653875

### CODE REVIEW

File: tt_metal/impl/debug/watcher_device_reader.cpp [hunk 1]
```diff
@@ -433,6 +433,14 @@ void WatcherDeviceReader::DumpCore(CoreDescriptor& logical_core, bool is_active_
     ValidateKernelIDs(virtual_core, &(mbox_data->launch[launch_msg_read_ptr]));
 
     // Whether or not watcher data is available depends on a flag set on the device.
+    if (mbox_data->watcher.enable != WatcherEnabled and mbox_data->watcher.enable != WatcherDisabled) {
+        TT_THROW(
+            "Watcher read invalid wathcer.enable on {}. Read {}, valid values are {} and {}.",
```
Comment (pgkeller) [inline tt_metal/impl/debug/watcher_device_reader.cpp]: typo

Comment (tt-dma) [reply tt_metal/impl/debug/watcher_device_reader.cpp]: Fixed

**Review by pgkeller — APPROVED** [review]

**Review by nhuang-tt — APPROVED** [review]
