### PR TITLE
Take `unpack_to_dest_mode` into account when computing for Kernel hash.

### LINKED ISSUE #22373: Wrong Cache Hit When unpack_to_dest_mode Is Used
### Describe the bug

When using `unpack_to_dest_mode`, which implicitly defines `unpack_src_format` and `unpack_dst_format` ([ref](https://github.com/tenstorrent/tt-metal/blob/9db65c24f94168528d1c31fc5df5f1d089bb890d/tt_metal/jit_build/genfiles.cpp#L326)), the kernel binary cache mechanism may result in incorrect cache hits.

The kernel compilation cache key is based on `KernelCompileHash`, which internally uses `ComputeKernel::config_hash()` ([ref](https://github.com/tenstorrent/tt-metal/blob/9db65c24f94168528d1c31fc5df5f1d089bb890d/tt_metal/impl/program/program.cpp#L1392)). However, `unpack_to_dest_mode` is **not** accounted for in `config_hash()` ([ref](https://github.com/tenstorrent/tt-metal/blob/9db65c24f94168528d1c31fc5df5f1d089bb890d/tt_metal/impl/kernels/kernel.cpp#L233)), which may lead to reuse of an incompatible kernel binary.

As a result, even when `unpack_to_dest_mode` varies across runs, the system might incorrectly hit a previously compiled kernel, causing functional mismatches.

### Steps to reproduce the issue

1. Run a kernel with `unpack_to_dest_mode` disabled.
2. Run the same kernel again with `unpack_to_dest_mode` enabled (e.g., using FP32 as `cb::param_in` format).
3. Observe that no new binary is generated due to cache hit.
4. Logs or outputs may reflect incorrect computation or precision due to using an outdated binary.

### Expected behavior

When `unpack_to_dest_mode` is used or changed, it should be included in the kernel configuration hash. A new kernel binary should be compiled when this mode changes.

### Please complete the following environment information

* `tt-metal` commit: `9db65c24f94168528d1c31fc5df5f1d089bb890d`
* Target hardware: WH

### PR DESCRIPTION
**Pull request by riverwuTT**
### Ticket
Closes #22373 

### Problem description
Current kernel hashing does not take into account `unpack_to_dest_mode`, which causes incorrect caching behavior.

### What's changed
Accounted in `unpack_to_dest_mode` in `ComputeKernel::config_hash` also added a new test case that verifies implementation.

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/runs/18023913141)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tests/tt_metal/tt_metal/api/test_kernel_creation.cpp [hunk 1]
```diff
@@ -150,4 +152,39 @@ TEST_F(CompileProgramWithKernelPathEnvVarFixture, TensixNonExistentKernel) {
...
+    auto kernel_handle_default = CreateKernel(program_default, kernel_file, CoreCoord(0, 0), config_default);
+    auto kernel_handle_fp32 = CreateKernel(program_fp32, kernel_file, CoreCoord(0, 0), config_fp32);
+
+    // Get the kernels from programs
+    const auto& kernels_default =
+        program_default.impl().get_kernels(static_cast<uint32_t>(HalProgrammableCoreType::TENSIX));
+    const auto& kernels_fp32 = program_fp32.impl().get_kernels(static_cast<uint32_t>(HalProgrammableCoreType::TENSIX));
+
+    // Direct hash comparison - this tests the actual Kernel::compute_hash() method
+    auto hash_default = kernels_default.at(kernel_handle_default)->compute_hash();
```
Comment (ruizhangTT) [inline tests/tt_metal/tt_metal/api/test_kernel_creation.cpp]: nit: is it possible to use `program_default.impl().get_kernel(kernel_handle_default)`?

File: tests/tt_metal/tt_metal/api/test_kernel_creation.cpp [hunk 2]
```diff
@@ -150,4 +152,39 @@ TEST_F(CompileProgramWithKernelPathEnvVarFixture, TensixNonExistentKernel) {
...
+    auto hash_fp32 = kernels_fp32.at(kernel_handle_fp32)->compute_hash();
+
+    // The hashes should be different across two kernels due to the difference in unpack_to_dest_mode
+    EXPECT_NE(hash_default, hash_fp32)
+        << "Kernels with different unpack_to_dest_mode should have different compute hashes. "
+        << "hash_default: " << hash_default << ", hash_fp32: " << hash_fp32 << ". "
```
Comment (ruizhangTT) [inline tests/tt_metal/tt_metal/api/test_kernel_creation.cpp]: nit: I think `EXPECT_NE` will print out the values if they don't match, so this is redundant.

File: tt_metal/api/tt-metalium/kernel_types.hpp [hunk 3]
```diff
@@ -70,7 +71,9 @@ struct ComputeConfig {
     MathFidelity math_fidelity = MathFidelity::HiFi4;
     bool fp32_dest_acc_en = false;
     bool dst_full_sync_en = false;
-    std::vector<UnpackToDestMode> unpack_to_dest_mode;
+    // This should be a std::array<UnpackToDestMode, NUM_CIRCULAR_BUFFERS>
```
Comment (abhullar-tt) [inline tt_metal/api/tt-metalium/kernel_types.hpp]: note in future archs, the number of dataflow buffers will depend on number of tile counters available (1 dataflow buffer may use several tile counters) whereas today we have 1:1 cb and tile counter. so it makes sense to keep this dynamic

**Review by abhullar-tt — APPROVED** [review]

File: tests/tt_metal/tt_metal/api/test_kernel_creation.cpp (hunk 1 above)
Comment (riverwuTT) [reply tests/tt_metal/tt_metal/api/test_kernel_creation.cpp]: Thanks for pointing this out! That would be a good improvement

File: tests/tt_metal/tt_metal/api/test_kernel_creation.cpp (hunk 2 above)
Comment (riverwuTT) [reply tests/tt_metal/tt_metal/api/test_kernel_creation.cpp]: Make sense.

File: tests/tt_metal/tt_metal/api/test_kernel_creation.cpp (hunk 1 above)
Comment (riverwuTT) [reply tests/tt_metal/tt_metal/api/test_kernel_creation.cpp]: Adopted

File: tests/tt_metal/tt_metal/api/test_kernel_creation.cpp (hunk 2 above)
Comment (riverwuTT) [reply tests/tt_metal/tt_metal/api/test_kernel_creation.cpp]: Adopted

File: tt_metal/api/tt-metalium/kernel_types.hpp (hunk 3 above)
Comment (riverwuTT) [reply tt_metal/api/tt-metalium/kernel_types.hpp]: This make sense, I've removed the comment.

File: tt_metal/api/tt-metalium/kernel_types.hpp [hunk 4]
```diff
@@ -13,6 +13,7 @@
 #include <tt-metalium/base_types.hpp>
 #include <tt-metalium/data_types.hpp>
 #include <tt-metalium/util.hpp>
+#include <tt-metalium/circular_buffer_constants.h>
```
Comment (ruizhangTT) [inline tt_metal/api/tt-metalium/kernel_types.hpp]: Is this header used?  If not then we can remove it as well.

Comment (riverwuTT) [reply tt_metal/api/tt-metalium/kernel_types.hpp]: good job checking

Comment (riverwuTT) [reply tt_metal/api/tt-metalium/kernel_types.hpp]: cleaned up

**Comment by riverwuTT** [comment]
APC failing, I broke something.

Edit: should have it fixed, waiting for APC rerun to confirm.
