### PR TITLE
Second attempt: add support for int32 to transpose_wh_tile.

### LINKED ISSUE #19950: Integer permute produces incorrect data
The following test will fail:
```
def test_integer_permute(device):

    torch_input = torch.randint(-10, 10, (1, 2, 1, 1))
    torch_output = torch.permute(torch_input, [0, 2, 3, 1])

    input_tensor = ttnn.from_torch(torch_input, layout=ttnn.TILE_LAYOUT, dtype=ttnn.int32, device=device)
    output_tensor = ttnn.permute(input_tensor, [0, 2, 3, 1])
    output_tensor = ttnn.to_torch(output_tensor)

    assert torch_output.shape == output_tensor.shape
    assert torch.all(torch_output == output_tensor)
```

If permute isn't intended to be supported for integer data types yet, an informative error should be thrown stating so instead.

### PR DESCRIPTION
**Pull request by jasondavies**
### Ticket

Second attempt at closing #19950.  First attempt was reverted due to failing BH tests.

### Problem description

ttnn.permute and ttnn.transpose don't work for int32.

The issue is that transpose_wh_tile uses `_llk_unpack_A_` for transpose, which relies on built-in unpacker support for transpose, but this path only supports 19-bit data.  When unpacking 32b data, unpack-to-dest is used, and the SrcA transpose functionality is not available for this path.

### What's changed

See https://github.com/tenstorrent/tt-llk/pull/135, which adds optional 32b support to `_llk_math_transpose_dest_`.  This works by splitting a 32b 16x16 face into two planes of high bits and low bits, and using the built-in transpose functionality of SrcB to transpose each plane separately before recombining in dest.

Additionally, we can swap the two middle faces when unpacking to dest, which avoids wasting cycles and bandwidth on swapping these faces using the FPU/SFPU.

tt-llk updates:

- `_llk_unpack_A_`: now supports `transpose_of_faces=true` for 32b data, to swap the two middle faces.
- `_llk_math_transpose_dest_`: now supports `{transpose_of_faces=false, is_32bit=true}` (also `{transpose_of_faces=true, is_32bit=true}` but not needed for transpose_wh_tile).

transpose_wh_tile:

- for int32, now uses the above changes to `_llk_unpack_A_` to perform transpose of faces on 32b data, followed by `_llk_math_transpose_dest_` with `{transpose_of_faces=false, is_32bit=true}`.

transpose_wh_dest:

- this API is not widely used, but it now also supports int32 via `_llk_math_transpose_dest_` with `{transpose_of_faces=true, is_32bit=true}`.

The transpose_wh_tile changes means int32 is now supported for permute/transpose for tile layouts and row major layouts.

Another change can be made separately to make float32 use the same 32b path.

### Notes

During implementation, a pre-existing potential race condition issue was found affecting WH only: https://github.com/tenstorrent/tt-metal/issues/22298 - which affects the existing bfloat16 transpose/permute implementation. This is difficult to reproduce reliably without restricting to a single core.  However, for int32, it seems to occur slightly more frequently, causing transpose/permute test failures.

Since this is a pre-existing issue, the decision was made to note the int32 CI failure here:

- https://github.com/tenstorrent/tt-metal/actions/runs/15493207396

Here is a successful int32 CI run with 5000 NOPs inserted in the MATH thread just after `transpose_wh_tile`:

- https://github.com/tenstorrent/tt-metal/actions/runs/15536271366

These tests have been disabled for int32 on WH until a fix is found for https://github.com/tenstorrent/tt-metal/issues/22298

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by jasondavies** [comment]
Fix for LLK transpose on BH is here: https://github.com/tenstorrent/tt-llk/pull/359

**Comment by jasondavies** [comment]
All tests _should_ pass on WH/BH -- these were done prior to merging the tt-llk BH fixes to be absolutely sure:

BH: https://github.com/tenstorrent/tt-metal/actions/runs/15701668996
WH: https://github.com/tenstorrent/tt-metal/actions/runs/15701660885

It would be nice to add float32 to the same path as int32 to support lossless transpose, but I think better to do it separately.

cc @nvelickovicTT

**Comment by nvelickovicTT** [comment]
> All tests _should_ pass on WH/BH -- these were done prior to merging the tt-llk BH fixes to be absolutely sure:
> 
> BH: https://github.com/tenstorrent/tt-metal/actions/runs/15701668996 WH: https://github.com/tenstorrent/tt-metal/actions/runs/15701660885
> 
> It would be nice to add float32 to the same path as int32 to support lossless transpose, but I think better to do it separately.
> 
> cc @nvelickovicTT

Agreed, definitely separately.

**Review by bbradelTT — APPROVED** [review]

**Review by rdjogoTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_op.cpp [hunk 1]
```diff
@@ -116,7 +116,7 @@ void Transpose::validate(const std::vector<Tensor>& input_tensors) const {
                 W * input_tensor.element_size(),
                 BUFFER_ALIGNMENT);
         }
-        TT_FATAL(input_tensor.dtype() == DataType::BFLOAT16 || input_tensor.dtype() == DataType::FLOAT32, "Error");
+        TT_FATAL(input_tensor.dtype() == DataType::BFLOAT16 || input_tensor.dtype() == DataType::FLOAT32 || input_tensor.dtype() == DataType::INT32, "Error");
```
Comment (nvelickovicTT) [inline ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_op.cpp]: Please make this error more descriptive. Instead of `Error` maybe `Unsupported data type for input tensor`.

**Review by nvelickovicTT — APPROVED** [review]

**Review by sjameelTT — APPROVED** [review]

**Review by abhullar-tt — APPROVED** [review]
