### PR TITLE
Fix for reductions ignoring explicit sharded output_mem_config

### LINKED ISSUE #41981: ttnn.sum ignores explicit sharded output_mem_config, returns interleaved
## Problem

`ttnn.sum` (and other reduce ops) returns inconsistent output `memory_config` depending on whether the output hint is omitted or explicitly provided:

- **No output hint**: Returns `WIDTH_SHARDED` — correct
- **Explicit output hint (same config)**: Returns `INTERLEAVED` — wrong

## Reproduction

```python
import torch, ttnn

device = ttnn.open_device(device_id=0)

shape = (1, 32, 4096)
ws_mem_config = ttnn.create_sharded_memory_config(
    shape=shape,
    core_grid=ttnn.CoreGrid(x=8, y=8),
    strategy=ttnn.ShardStrategy.WIDTH,
    use_height_and_width_as_shard_shape=False,
)
input_tensor = ttnn.from_torch(
    torch.randn(shape, dtype=torch.float32),
    dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT,
    device=device, memory_config=ws_mem_config,
)

# Call 1: no output hint → WIDTH_SHARDED ✓
out1 = ttnn.sum(input_tensor, dim=-1, keepdim=True)
mc1 = out1.memory_config()
print(mc1.memory_layout)  # WIDTH_SHARDED
print(mc1.shard_spec)     # ShardSpec{grid=8x8, shape=[32,32]}

# Call 2: explicit hint = same config → INTERLEAVED ✗
explicit = ttnn.MemoryConfig(
    memory_layout=mc1.memory_layout,
    buffer_type=mc1.buffer_type,
    shard_spec=mc1.shard_spec,
)
ttnn.deallocate(out1)
out2 = ttnn.sum(input_tensor, dim=-1, keepdim=True, memory_config=explicit)
mc2 = out2.memory_config()
print(mc2.memory_layout)  # INTERLEAVED — should be WIDTH_SHARDED
print(mc2.shard_spec)     # None
```

## Environment

- tt-metal commit: `aed2421dfe`
- Wormhole B0

### PR DESCRIPTION
**Pull request by fplavecTT**
### Summary
Reduction ops were ignoring sharded configuration provided through explicit `output_mem_config`.
This was root-caused to the code that was relying on presence of `nd_shard_spec` in `output_mem_config`, which may not always be present for sharded layouts (sometimes it's stored in `shard_spec`) 
This change:
- Switches to using `memory_layout` directly to determine whether the tensor is sharded.
- Adds missing handling for `BLOCK_SHARDED` layout.
- Copilot caught an issue in `TensorSpec::block_sharded`, which in turn revealed an issue in `ttnn::operations::data_movement::reshape_tiled`. Both issues are now addressed. The fix for the latter issue also resolves #35145
- Adds defensive asserts.
- Updates unit tests to cover various uncovered cases.

Closes #41981
Closes #35145

### CI Status
_Auto-generated on every push. Badges update live. Click a badge to filter runs by this branch._

- [](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:fplavec_41981_sharded)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:fplavec_41981_sharded)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:fplavec_41981_sharded)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/all-model-tests.yaml?query=branch:fplavec_41981_sharded)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:fplavec_41981_sharded)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:fplavec_41981_sharded)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:fplavec_41981_sharded)

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp [hunk 1]
```diff
@@ -57,16 +57,42 @@ ReduceDeviceOperation::spec_return_value_t ReduceDeviceOperation::compute_output
...
-        if (operation_attributes.output_mem_config.memory_layout() == TensorMemoryLayout::HEIGHT_SHARDED) {
-            return tensor_spec.height_sharded(nd_shard_spec.grid, nd_shard_spec.orientation);
+        if (mem_layout == TensorMemoryLayout::HEIGHT_SHARDED) {
+            return tensor_spec.height_sharded(grid, orientation);
         }
+        TT_FATAL(
+            grid.ranges().size() == 1,
+            "Block sharding requires a single CoreRange, got {} ranges",
+            grid.ranges().size());
+        return tensor_spec.block_sharded(grid.bounding_box(), orientation);
```
[the remark this answers is not in the document]
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp:104]: @copilot Isn't that really a bug in block_sharded()?

File: tests/ttnn/nightly/unit_tests/operations/reduction/test_reduction_ops.py [hunk 2]
```diff
@@ -396,12 +405,22 @@ def test_generic_ops_ndim_shard(device, shapes, keepdim, layout, op):
...
+@pytest.mark.parametrize("explicit_output_mem_config", [True, False])
+def test_generic_ops_wh_block_shard(
+    device, input_shape, shard_2d_shape, end_x, end_y, memory_layout, keepdim, layout, op, explicit_output_mem_config
+):
+    # To reduce the number of tests, we only test sum and var with explicit output mem_config.
+    # This exercises both known code paths where this could make a meaningful difference.
+    if explicit_output_mem_config and op not in ("sum", "var"):
+        pytest.skip("explicit output mem_config only tested for sum and var")
+
     dim = -2
```
[the remark this answers is not in the document]
Comment (fplavecTT) [reply tests/ttnn/nightly/unit_tests/operations/reduction/test_reduction_ops.py]: Done

File: ttnn/cpp/ttnn/operations/reduction/generic/device/welford_reduce_device_operation.cpp [hunk 3]
```diff
@@ -72,16 +72,42 @@ WelfordReduceDeviceOperation::spec_return_value_t WelfordReduceDeviceOperation::
...
-        if (operation_attributes.output_mem_config.memory_layout() == TensorMemoryLayout::HEIGHT_SHARDED) {
-            return tensor_spec.height_sharded(nd_shard_spec.grid, nd_shard_spec.orientation);
+        if (mem_layout == TensorMemoryLayout::HEIGHT_SHARDED) {
+            return tensor_spec.height_sharded(grid, orientation);
         }
+        TT_FATAL(
+            grid.ranges().size() == 1,
+            "Block sharding requires a single CoreRange, got {} ranges",
+            grid.ranges().size());
+        return tensor_spec.block_sharded(grid.bounding_box(), orientation);
```
[the remark this answers is not in the document]
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/welford_reduce_device_operation.cpp:119]: Fixed at source in `TensorSpec::block_sharded`

File: ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp:104]: Fixed at source in `TensorSpec::block_sharded`

File: ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp [hunk 4]
```diff
@@ -57,16 +57,63 @@ ReduceDeviceOperation::spec_return_value_t ReduceDeviceOperation::compute_output
...
+            }
+            if (input_legacy) {
+                return {input_legacy->grid, input_legacy->orientation};
+            }
+            TT_THROW(
+                "Sharded memory layout {} requires either nd_shard_spec or shard_spec to be set "
+                "on the output memory config or the input tensor",
+                mem_layout);
+        };
+        auto [grid, orientation] = get_grid_and_orientation();
```
[the remark this answers is not in the document]
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp]: Done

File: ttnn/cpp/ttnn/operations/reduction/generic/device/welford_reduce_device_operation.cpp [hunk 5]
```diff
@@ -72,16 +72,63 @@ WelfordReduceDeviceOperation::spec_return_value_t WelfordReduceDeviceOperation::
...
+            }
+            if (input_legacy) {
+                return {input_legacy->grid, input_legacy->orientation};
+            }
+            TT_THROW(
+                "Sharded memory layout {} requires either nd_shard_spec or shard_spec to be set "
+                "on the output memory config or the input tensor",
+                mem_layout);
+        };
+        auto [grid, orientation] = get_grid_and_orientation();
```
[the remark this answers is not in the document]
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/welford_reduce_device_operation.cpp]: Done.

**Review by bbradelTT — APPROVED** [review]
What is the reason for the checks for sum and var? Would other ops also work?

**Comment by fplavecTT** [comment]
> What is the reason for the checks for sum and var? Would other ops also work?

It was done to cover both regular reduce path (`ReduceDeviceOperation`) and Welford (`WelfordReduceDeviceOperation`), since they independently adjust for sharding and it's a good idea to check that they both work. Any other generic op could be used for the first path, and `std` could be used instead of `var`.

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 6]
```diff
@@ -285,12 +285,28 @@ ttnn::Tensor reshape_tiled(
...
+        // the correct shard spec.
+        auto shard_spec = updated_mem_config.shard_spec().value();
+        TensorSpec output_spec(
+            requested_shape_3d,
+            TensorLayout::fromPaddedShape(
+                tensor3d.dtype(),
+                PageConfig(tensor3d.layout()),
+                MemoryConfig(updated_mem_config.buffer_type()),
+                requested_shape_3d,
+                requested_padded_shape_3d));
```
Comment (awliu-TT) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp]: There's currently an effort to remove the use of `fromPaddedShape`. Could you please try replacing this with 
```
TensorLayout(tensor3d.dtype(),  PageConfig(tensor3d.layout()), updated_mem_config));
```
and see if that still works?

File: ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp [hunk 7]
```diff
@@ -57,16 +57,63 @@ ReduceDeviceOperation::spec_return_value_t ReduceDeviceOperation::compute_output
...
+        return tensor_spec.block_sharded(grid.bounding_box(), orientation);
+    }
 
-        auto nd_shard_spec_copy = nd_shard_spec;
+    // ND sharding: adjust per-logical-dimension shard shape for reduced dims.
+    // Fall back to the input tensor's nd_shard_spec when the output config omits it.
+    if (mem_layout == TensorMemoryLayout::ND_SHARDED) {
+        const auto& nd_shard_spec = operation_attributes.output_mem_config.nd_shard_spec();
+        const auto& input_nd_shard_spec = tensor_args.memory_config().nd_shard_spec();
+        TT_FATAL(
```
Comment (awliu-TT) [inline ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp]: This seems like a weird case. If the output's `memory_layout == TensorMemoryLayout::ND_SHARDED`, then it should have a `memory_config.nd_shard_spec()` value. Just curious, did you encounter a case like this where the output did not have an `nd_shard_spec`?

Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp]: Yes, the test `test_nd_sharded_reduce_h_no_output_shard_spec` I added in `tests/ttnn/nightly/unit_tests/operations/reduction/test_reduce.py` demonstrates how this can happen.

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 6 above)
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp]: Thanks for flagging that. Yes, the constructor works as you suggested. I just passed `MemoryConfig(updated_mem_config.buffer_type()` as the last argument to avoid any issues with alignment checks if all of `updated_mem_config` were used, given that we only need `buffer_type`.
Updated.

File: ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp (hunk 7 above)
Comment (awliu-TT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp]: Oh I see you are creating a `memory_config` instance and passing in a `memory_layout == TensorMemoryLayout::ND_SHARDED` but no `nd_shard_spec` is passed in. This should be illegal and just fail at `memory_config` creation with a `TT_FATAL`. Is there any reason you need to initialize the output ND-sharded `memory_config` the way you did here (without passing in an `nd_shard_spec`)? If we just `TT_FATAL` at the`memory_config` construction then this test case would become invalid.

Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp]: I have no special reason. Cursor flagged that this was possible, so I added a guard and a test to exercise it. If that case is made illegal then I can go back to hard assert if `nd_shard_spec` is not present, which is what I actually had in my first commit ( https://github.com/tenstorrent/tt-metal/pull/42120/changes/2f38f1960ca7ec38d6a670dd50379b10413420e8 ) and get rid of that test case.

Comment (awliu-TT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/reduce_op_device_operation.cpp]: Looks like we actually have a usecase for this in `ttnn/api/ttnn/types.hpp` where users can pass these sharded memory configs as keyword arguments and the op populates the shard spec. So we can't `TT_FATAL` it in the `memory_config` constructor. So we should keep this testcase then.

File: ttnn/cpp/ttnn/operations/reduction/generic/device/welford_reduce_device_operation.cpp [hunk 8]
```diff
@@ -72,16 +72,63 @@ WelfordReduceDeviceOperation::spec_return_value_t WelfordReduceDeviceOperation::
...
+                "on the output memory config or the input tensor",
+                mem_layout);
+        };
+        const auto& [grid, orientation] = get_grid_and_orientation();
+
+        // For width/height/block sharding modes, the output shard shape is fully determined
+        // by the output physical shape and the core grid. Just delegate to the
+        // appropriate TensorSpec builder.
+        if (mem_layout == TensorMemoryLayout::WIDTH_SHARDED) {
+            return tensor_spec.width_sharded(grid, orientation);
```
Comment (aliaksei-sala) [inline ttnn/cpp/ttnn/operations/reduction/generic/device/welford_reduce_device_operation.cpp]: During tensor spec creation, current grid and orientation may be taken from the input tensor, whose buffer type can differ from the output_mem_config specified by the user.
`tensor_spec` creation may use a DRAM type with L1 cores, and vice versa.

DRAM sharding uses a slightly different set of cores within the grid compare to L1 sharding, and these are not interchangeable.

Should we take this into account?

Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/welford_reduce_device_operation.cpp]: Thanks for flagging that. I think it's something we should definitely account for. Since these ops don't officially support DRAM sharding yet (as documented in nanobind files), I've recorded your feedback in the new Issue I've opened (#43050) so we don't forget to handle this case when the support is officially added.

Also, thanks to your comment, I've realized I had identical code in `welford_reduce_device_operation.cpp` and `reduce_op_device_operation.cpp`, so I've refactored common code.

**Review by itarabanTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 9]
```diff
@@ -285,21 +285,20 @@ ttnn::Tensor reshape_tiled(
...
-        // Synthesize TensorLayout from padded shape
-        auto synthetic_layout = tt::tt_metal::TensorLayout::fromPaddedShape(
+        // Synthesize a TensorLayout that reproduces the requested padded shape via an explicit alignment, but with an
+        // interleaved MemoryConfig (no shard_spec). Dropping the shard_spec is what lets the TensorSpec constructor
+        // below skip its shape-fits-shard-grid validation, which would otherwise apply the *input* shard_spec to the
+        // *output* shape and fatal. Pinning the alignment to requested_padded_shape_3d's last two dims (rather than
+        // relying on the page_config's default tile alignment) ensures synthetic_spec.physical_shape() exactly
+        // matches the requested padded shape, even if compute_padded_shape ever produced dims that exceed
+        // tile alignment (e.g., due to shard-aware padding).
+        auto synthetic_layout = TensorLayout(
```
Comment (aliaksei-sala) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp]: Custom alignment has been a source of multiple issues

tensor_spec mismatches where the only difference is alignment
This, in turn, leads to program cache misses, triggering new kernel compilations and blocking the use of Metal trace

Unless custom alignment is truly necessary, I’d suggest using the fromPaddedShape function here. I recently updated it to address these issues by using the default alignment for tile layouts when no overpadding is required.

File: ttnn/cpp/ttnn/operations/reduction/generic/device/common.cpp [hunk 10]
```diff
@@ -22,4 +22,89 @@ tt::tt_metal::ReduceOpParallelizationStrategy get_parallelization_strategy(
...
+                "on the output memory config or the input tensor",
+                mem_layout);
+        };
+        const auto& [grid, orientation] = get_grid_and_orientation();
+
+        // For width/height/block sharding modes, the output shard shape is fully determined
+        // by the output physical shape and the core grid. Just delegate to the
+        // appropriate TensorSpec builder.
+        if (mem_layout == TensorMemoryLayout::WIDTH_SHARDED) {
+            return tensor_spec.width_sharded(grid, orientation);
```
Comment (aliaksei-sala) [inline ttnn/cpp/ttnn/operations/reduction/generic/device/common.cpp:73]: If DRAM-sharded tensors aren’t supported, we could explicitly state that in validate_on_program_cache_miss within device_operation.

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 9 above)
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp]: I actually had `fromPaddedShape` in a previous revision, but @awliu-TT asked me to remove it because it is deprecated.

File: ttnn/cpp/ttnn/operations/reduction/generic/device/common.cpp (hunk 10 above)
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/reduction/generic/device/common.cpp:73]: Asserts added.

**Review by aliaksei-sala — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 9 above)
Comment (fplavecTT) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp]: Switched back to `fromPaddedShape` per offline discussion.

**Review by awliu-TT — APPROVED** [review]
