### PR TITLE
#33349: TopK general update and bug fix

### LINKED ISSUE #33349: TopK Slight Accuracy Drop with Qwen3-32B shapes
After the fix in this [PR](https://github.com/tenstorrent/tt-metal/pull/33287), the topk hang was resolved but locally on bh-51 with these shapes: 1,1,32,18992 k=32 I get slightly worse PCC than 0.99, with k=3000 all PCC passes, this issue tracks if the fix is potentially incorrectly handling the pair of tiles when there is odd number of tiles on each core or why this accuracy issue occurs.

Bad PCC observed with k=32:
```
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=True-sorted=True-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT16_B] - AssertionError: 0.9831419276403037
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=True-sorted=True-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT8_B] - AssertionError: 0.9805128217915379
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=True-sorted=False-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT16_B] - AssertionError: 0.9831419276403037
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=True-sorted=False-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT8_B] - AssertionError: 0.9805128217915379
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=False-sorted=True-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT16_B] - AssertionError: 0.980129021380807
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=False-sorted=True-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT8_B] - AssertionError: 0.9777846037433405
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=False-sorted=False-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT16_B] - AssertionError: 0.980129021380807
FAILED tests/ttnn/unit_tests/operations/reduce/test_topk.py::test_topk[sub_core_grids=None-largest=False-sorted=False-N=1-C=1-H=32-W=18992-dim=3-k=32-BFLOAT8_B] - AssertionError: 0.9777846037433405
```

On a model level output looks reasonable and no bad output. Some sample output from `Qwen3-32b`:
```
<think>
Okay, so I need to figure out how to answer this question about favorite condiments. The user is asking for personal preference, but since I'm anAI, I don't have actual tastes or favorites. Hmm. I should probably mention that I can't really have preferences, but then offer an informative response about condiments. Let me think... Maybe I can talk about popular condiments and why people like them. The user mentioned several examples like ketchup, mayonnaise, mustard, etc. I should cover some of those. Also, they want to knows if there's something exotic, like hoisin or Sriracha. I should highlight different types and uses. Maybe discuss how condiments enhance dishes. Also, perhaps mention cultural aspects. For example, how different regions have different favorites. Also, think about why people have favorites – it's about flavor, texture, memory, etc. Since I can't have personal experiences, I can't talk about personal favorites, but I can discuss common reasons people prefer certain condiments. Let me structure this. Start with acknowledging that I can't have favorites, but then go into an overview of popular condiments, why they are liked, and perhaps some examples of dishes they go with. Maybe mention how they add different elements like spice, tanginess, richness. Also, mention some global condiments to show diversity. Make sure to answer all parts of user's question even if I can't give personal preference. Check if I need to mention any health aspects? Maybe not unless it's part of why people like them. Also, think about texture – like how some people like thick vs. runny. Maybe include that. Alright, let me put this together in an organized way.
Okay, let me start drafting.

First, acknowledge that as anAI, I don't have personal preferences. Then, discuss popular condiments and why they are popular. Maybe start with ketchup, mayo, mustard as classics. Then move to others like Sriracha, hoisin, salsa, etc. Explain each's characteristics and uses. Maybe mention how they complement different dishes. Also, perhaps touch on how condiments can be tied to cultural or personal experiences. For example, someone's favorite condiment may remind them of home or family meals. Since I can't have personal experiences, I can talk about how people often form these associations. Also, note that some people enjoy mixing condiments to create unique flavors. Concluding that condiments are all about enhancing food and personal preference is key. Make sure to keep it engaging and informative. Avoid being too dry. Maybe use examples of dishes for each condiment. Let me check if I have all that. Yeah, I think that covers it. Now, structure it into paragraphs, making sure to flow from one idea to another. Start with introduction, then go into each condiment with examples, then wrap up with how they enhance meals and personal preferences.
Okay, let me write that out.
I need to make sure I don't mention any personal favorites but still answer why people love them. Also, check for any errors. Let me make sure I'm not missing any key points from user's question. They wanted to knows if it reminds of dish or meal. Since I can't have personal ones, I can say that for many people, condiments are tied to cherished meals or cultural traditions. For example, tartars sauce with fish and fries, or soy sauce with sushi. That should work. Alright, I think that's all. Let me put it all together.
Okay, done. Let me read through again to make sure it's clear and answers all parts of user's question.
Yes, I think that's good. Now, time to present it as an answer.
Okay, I think that's ready.
Wait, did I miss any of user's examples? They mentioned ketchup, mayo, mustard, Sriracha, hoisin, salsa, and garlic. I think I included all of those. Also, mentioned why people love them. Alright, I think that's all.
I think that's it. Let me go ahead and present this as an answer.
Okay, done.
Wait, in user's question, they also mention "maybe you enjoy..." and then examples. I should make sure to cover all those. Let me check again. Ketchup, mayo, mustard, Sriracha, hoisin, salsa, and garlic. Wait, in user's question, they said "the smooth and savory garlic of garlic." Wait, no, they said "the smooth and savory of garlic" but probably meant "aioli." Let me check. Original user message: "the smooth and savory of garlic" – probably they meant "aioli," which is garlic mayonnaise. So in response, I should mention that. Let me check if I included that. Yes, in second paragraph, I mentioned "aioli, which blends garlic and mayonnaise for..." So that's correct. So all examples are addressed. Good. Alright, I think that's all.
Okay, I think that's ready to go.
I think that's all. Let me present it.
Okay, done.
I think that's it. The answer is ready.
Okay, time to wrap up.
Alright, I think that's all. The answer is structured, covers all user's points, and is informative.
I think that's it. Let me go ahead and present it.
Okay, done.
```

To reproduce run:
`pytest tests/ttnn/unit_tests/operations/reduce/test_topk.py` with `1,1,32,18992 k=32`

### PR DESCRIPTION
**Pull request by mgajewskiTT**
### Ticket

#33349

### Problem description
TopK produced wrong results for some shapes from Qwen3-32b. Some of the functionality like - `indices_tensor` parameter were available only in Multicore version.

### What's changed
- General code cleanup and refactor,
- Unification of functionality in both program factories (some were available only to one or the other),
- Possibility to utilize the full number of cores for SingleCore approach processing - parallelization over Ht,
- Allowing the use of all tensor shapes and dim,
- Resolved issue with accuracy drop with Owen-32b shapes,
- Updated implementation docs,
- Removed redundant kernel.

### Checklist

- [x] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml?query=branch:mgajewskiTT/33349-topk-slight-accuracy-drop-with-qwen3-32b-shapes)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:mgajewskiTT/33349-topk-slight-accuracy-drop-with-qwen3-32b-shapes)  - OK, eltwise test fail not connected to this PR 
- [ ] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:mgajewskiTT/33349-topk-slight-accuracy-drop-with-qwen3-32b-shapes)
- [x] New/Existing tests provide coverage for changes

New implementation and Current implementation

#### Discovered issues 

#36329

#### Model tests

If your changes cover model-related code, you should run tests corresponding to affected models and platforms (Single card, T3K, Galaxy). "Choose your pipeline" workflows facilitate running multiple kinds of tests in a single run. Each offers `models-mandatory` and `models-extended` presets.
The former includes a minimal set of tests, to be run always. The latter extends that with additional ones - use your best judgement in deciding which is the most appropriate for your PR.

- [ ] [(Single) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:mgajewskiTT/33349-topk-slight-accuracy-drop-with-qwen3-32b-shapes)
  - [ ] `models-mandatory` preset (runs: [Device perf regressions](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) and [Frequent model and ttnn tests](https://github.com/tenstorrent/tt-metal/actions/workflows/fast-dispatch-full-regressions-and-models.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(T3K) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:mgajewskiTT/33349-topk-slight-accuracy-drop-with-qwen3-32b-shapes)
  - [ ] `models-mandatory` preset (runs: [Unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-model-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(Galaxy) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:mgajewskiTT/33349-topk-slight-accuracy-drop-with-qwen3-32b-shapes)
  - [ ] `models-mandatory` preset (runs: [Quick tests](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-model-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/reduction/topk/device/topk_single_core_program_factory.cpp [hunk 1]
```diff
@@ -16,193 +19,246 @@ namespace ttnn::prim {
...
+        total_number_of_cores,                // Total number of cores
+        static_cast<uint32_t>(uint16_output)  // Index format flag
+    };
     tt::tt_metal::TensorAccessorArgs(input_buffer).append_to(reader_compile_time_args);
+    if (tensor_args.indices.has_value()) {
+        tt::tt_metal::TensorAccessorArgs(tensor_args.indices->buffer()).append_to(reader_compile_time_args);
+    }
+    const std::map<std::string, std::string> reader_defines = {
+        {"GENERATE_INDICES", "1"},  // tensor_args.indices.has_value() ? "0" : "1" - GH issue: #36329
+    };
```
[the remark this answers is not in the document]
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/reduction/topk/device/topk_single_core_program_factory.cpp:152]: Described in GH issue.

File: ttnn/cpp/ttnn/operations/reduction/topk/device/topk_device_operation.cpp [hunk 2]
```diff
@@ -17,46 +14,104 @@
...
 
-    // for now multicore does not support uint32 output, so if uint16 is not
-    // supported, we default to single core
-    // multicore implementation only supports k <= 64
-    multicore_supported &= uint16_output;
+    // Apply requirement #2: Multi-core implementation constraint
+    // Multi-core only supports UInt16 indices (dimension size must fit in 16 bits)
+    multicore_supported &= (input_shape[args.dim] < std::numeric_limits<uint16_t>::max());
+    // Dimension size must be a power of two for bitonic sort
+    multicore_supported &= isPowerOfTwo(input_shape[args.dim]);
```
[the remark this answers is not in the document]
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/reduction/topk/device/topk_device_operation.cpp]: It requires to be a power of two because bitonic sort works on data size power of 2. Plan for the new algorithm that changes the multicore approach is being prepared. If there is a case where we now use multicore approach with data not being power of 2 we get a wrong result.

File: ttnn/cpp/ttnn/operations/reduction/topk/topk.cpp [hunk 3]
```diff
@@ -110,45 +186,86 @@ std::vector<Tensor> ExecuteTopK::invoke(
...
-        static_cast<int>(ttnn::prim::constants::min_dim_per_core) -
-            static_cast<int>(transformed_tensor.logical_shape()[-1]),
-        0);
-    const auto pad_val = largest ? std::numeric_limits<float>::min() : std::numeric_limits<float>::max();
+    const auto current_dim_size = static_cast<int>(transformed_tensor.logical_shape()[-1]);
+    const auto min_required_size = static_cast<int>(ttnn::prim::constants::min_dim_per_core);
+    const auto pad_amount = std::max(min_required_size - current_dim_size, 0);
+
+    // Choose padding value based on whether we want largest or smallest values
+    const auto pad_val = largest ? -std::numeric_limits<float>::infinity() : std::numeric_limits<float>::infinity();
```
[the remark this answers is not in the document]
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/reduction/topk/topk.cpp:232]: We use the same in `ttnn.sort` and it works.

File: ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.cpp [hunk 4]
```diff
@@ -44,7 +44,7 @@ void bind_reduction_topk_operation(nb::module_& mod) {
                 memory_config (ttnn.MemoryConfig, optional): Memory configuration for the operation. Defaults to `None`.
                 output_tensor (ttnn.Tensor, optional): Preallocated output tensor. Defaults to `None`.
                 sub_core_grids (ttnn.CoreRangeSet, optional): Core range set to run the operation on. Defaults to `None`.
-                indices_tensor (ttnn.Tensor, optional): Preallocated indices tensor. Defaults to `None`.
+                indices_tensor (ttnn.Tensor, optional): Preallocated indices tensor with filled values. Defaults to `None`.
```
Comment (nmauriceTT) [inline ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.cpp:47]: What "filled values" ? Should the `indices_tensor` be zero-initialized before the operation ? Or do you mean that topk() will fill that tensor with the indices of the top-k largest elements ?

File: ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.hpp [hunk 5]
```diff
@@ -1,4 +1,4 @@
-// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
+// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.hpp:1]: nit: I'm not sure of what the policy is for setting the year, but this file seems not to have changed otherwise.

**Review by bbradelTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/reduction/topk/device/topk_device_operation.cpp [hunk 6]
```diff
@@ -17,46 +14,104 @@
...
 
 namespace ttnn::prim {
-
+/**
+ * @brief Checks if a given unsigned integer is a power of two.
+ *
+ * @param n The unsigned integer to check
+ * @return true if n is a power of two (1, 2, 4, 8, 16, ...), false otherwise
+ */
+bool isPowerOfTwo(uint32_t n) { return n != 0 && (n & (n - 1)) == 0; }
```
Comment (nmauriceTT) [inline ttnn/cpp/ttnn/operations/reduction/topk/device/topk_device_operation.cpp]: Nitpick: We have `is_power_of_two` math.hpp in https://github.com/tenstorrent/tt-metal/blob/f1f5abc8598426186251ccb7b59fd8ca0a55b1c7/ttnn/cpp/ttnn/operations/math.hpp#L11

**Review by nmauriceTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.cpp (hunk 4 above)
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.cpp:47]: TBH I am a huge hater of this parameter. It was added in: https://github.com/tenstorrent/tt-metal/pull/25728 by different team. But this basically allows you to create indices tensor with whatever values you want and then in the reader kernel we do not create indices manually but just read from this tensor. Just added with filled values to point that output tensor will not be the same tensor as the one passed - different behavior to `output_tensors` parameter.

File: ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.hpp (hunk 5 above)
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/reduction/topk/topk_nanobind.hpp:1]: Good point, I just changed it here because I changed year for all files in the TopK directory and didn't want to leave the only one behind.

File: ttnn/cpp/ttnn/operations/reduction/topk/device/topk_device_operation.cpp (hunk 6 above)
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/reduction/topk/device/topk_device_operation.cpp]: Good catch! Changed.

**Review by nmauriceTT — APPROVED** [review]

File: models/demos/deepseek_v3/tests/unit/test_topk.py
Comment (johanna-rock-tt) [inline models/demos/deepseek_v3/tests/unit/test_topk.py:1]: Why are you changing a deepseek unit test? These unit tests should exactly reflect what we have in the model otherwise they are pointless. If you think we should change some parameters for that topk then we'll also need to change it in the model.

**Review by johanna-rock-tt — APPROVED** [review]
Please see comment about deepseek test. Otherwise looks good to me, but not reviewed in detail.

File: models/demos/deepseek_v3/tests/unit/test_topk.py
Comment (mgajewskiTT) [reply models/demos/deepseek_v3/tests/unit/test_topk.py:1]: This test uses SingleCore Program Factory approach. Previously it was truly single core, meaning that even though, we passed a subcoregrid of many cores it was only choosing the first one and the whole operation was running on this single core. Now we introduced Ht parallelism to speed up the OP. Without this change this test returns error:
```
FAILED models/demos/deepseek_v3/tests/unit/test_topk.py::test_topk_mesh_device[device_params0-False-DataType.BFLOAT16-shape0-mesh_device0] - RuntimeError: No core coordinate found at location: (8, 2, TENSIX, LOGICAL)
FAILED models/demos/deepseek_v3/tests/unit/test_topk.py::test_topk_mesh_device[device_params0-True-DataType.BFLOAT16-shape0-mesh_device0] - RuntimeError: No core coordinate found at location: (8, 2, TENSIX, LOGICAL)
```
because on WH it tries to dispatch the program on core that is not a compute core. This sub core grid is simply wrong for WH since we have 8x8 core grid and the sub core grid goes above 7th core both in x and y axis (7 because it starts indexing from 0). Please see: https://github.com/tenstorrent/tt-metal/actions/runs/21170043995/job/60885096271
