### PR TITLE
Fix topk_traces.py test failure

### LINKED ISSUE #22996: tests/sweep_framework/sweeps/reduction/traces/topk_traces.py failed
```
pytest   tests/sweep_framework/sweeps/reduction/traces/topk_traces.py
```
has failures when it shouldn't

### PR DESCRIPTION
**Pull request by rmillerTT**
### Ticket
#22996

### Problem description
- Test file was treating the tuple of output tensors ((values, indices)) from torch/ttnn as the output tensor of values
- The internal topk op requires the padded size of the last dimension of the input tensor to be 2 tiles (64). Small tensors had a padded size that was too small, raising an error

### What's changed
- Fixed the test file
- Pad the input tensor to the minimum required for topk (presently 64).

Ensured (locally) that the topk_traces.py tests pass through both pytest and through the sweeps framework.

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes https://github.com/tenstorrent/tt-metal/actions/runs/16119809817
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/reduction/topk/topk.cpp [hunk 1]
```diff
@@ -121,13 +122,27 @@ std::vector<Tensor> ExecuteTopK::invoke(
...
-    Tensor padded_tensor = ttnn::fill_implicit_tile_padding(
-        transformed_tensor, largest ? std::numeric_limits<float>::min() : std::numeric_limits<float>::max());
+
+    // pad the last dimension to satisfy the minimum size requirements
+    auto padded_tensor = transformed_tensor;
+    const auto pad_amount = std::max(
+        static_cast<int>(topk::constants::min_dim_per_core) - static_cast<int>(transformed_tensor.logical_shape()[-1]),
+        0);
+    if (pad_amount > 0) {
+        const auto pad_val = largest ? std::numeric_limits<float>::min() : std::numeric_limits<float>::max();
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/reduction/topk/topk.cpp]: Please move pad_val to before the if and then you can use it in the implicit pad below.

**Review by bbradelTT — APPROVED** [review]
Please update the description with info about your local testing via pytest and the sweep framework scripts.

File: ttnn/cpp/ttnn/operations/reduction/topk/topk.cpp (hunk 1 above)
Comment (rmillerTT) [reply ttnn/cpp/ttnn/operations/reduction/topk/topk.cpp]: Good catch, will do

**Review by nsorabaTT — APPROVED** [review]

**Comment by rmillerTT** [comment]
BH has a failing test that is also failing on main. Going to proceed with merge
