### PR TITLE
Fixing CCL Mesh Device Error

### LINKED ISSUE #26165: T3k ttnn tests failing on TT_FATAL @ /work/tt_metal/impl/dispatch/dispatch_query_manager.cpp:61: first_dispatch_core.has_value()
https://github.com/tenstorrent/tt-metal/actions/runs/16628938042/job/47053793681#step:5:12423

Test name: WorkerCclCommandProcessingKernelLocalMode.MultiInputReader_SinglePageTile

```
2025-07-30 17:21:54.045 | info     |           Metal | While initializing device 7, active ethernet dispatch core (x=25,y=16) detected as still running, issuing exit signal. (metal_context.cpp:581)
2025-07-30 17:21:54.122 | critical |          Always | Trying to re-initialize fabric context (assert.hpp:107)
2025-07-30 17:21:54.123 | critical |          Always | Could not find the dispatch core for 0 (assert.hpp:107)
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ /work/tt_metal/impl/dispatch/dispatch_query_manager.cpp:61: first_dispatch_core.has_value()
info:
Could not find the dispatch core for 0
backtrace:
 --- void tt::assert::tt_throw<unsigned char, unsigned char>(char const*, int, char const*, char const*, fmt::v11::fstring<unsigned char const&, unsigned char const&>::t, unsigned char const&, unsigned char const&)
 --- tt::tt_metal::DispatchQueryManager::get_dispatch_core(unsigned char) const
 --- tt::tt_metal::event_dispatch::issue_record_event_commands(tt::tt_metal::IDevice*, unsigned int, unsigned char, unsigned int, tt::tt_metal::SystemMemoryManager&, std::span<ttsl::StrongType<unsigned char, tt::tt_metal::SubDeviceIdTag> const, 18446744073709551615ul>, std::span<unsigned int const, 18446744073709551615ul>, bool, bool)

```

### PR DESCRIPTION
**Pull request by Riddy21**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/26165)

### Problem description
https://github.com/tenstorrent/tt-metal/pull/25687 removed support of IDevice* in Tensor. This broke some CCLs tests that relied on a collection of individual devices to run the op, as querying id() on IDevice returned chip_id_t, while MeshDevice returns a unique ID generated sequentially.

### What's changed

Used mesh device to create unit submeshes properly instead of creating new unit meshes.

### Checklist
- [x] [All commit test](https://github.com/tenstorrent/tt-metal/actions/runs/16733042818
)
- [x] [T3K Tests](https://github.com/tenstorrent/tt-metal/actions/runs/16790803258)

### CODE REVIEW

**Review by omilyutin-tt — APPROVED** [review]

File: tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp [hunk 1]
```diff
@@ -1539,16 +1539,22 @@ inline bool TestMultiInputReaderKernel(
...
+        devices.push_back(mesh_device->get_device(MeshCoordinate(0, i)));
     }
 
+    std::vector<std::shared_ptr<distributed::MeshDevice>> mesh_devices;
+    mesh_devices.reserve(devices.size());
+    for (size_t i = 0; i < devices.size(); i++) {
+        mesh_devices.push_back(mesh_device->create_submesh(MeshShape(1, 1), MeshCoordinate(0, i)));
+    }
+
+
```
Comment (Riddy21) [inline tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp]: @omilyutin-tt I didn't end up using the MeshWorkload properly, but I changed it to use unit submeshes correctly. Will this do?

File: tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp [hunk 2]
```diff
@@ -1539,16 +1539,22 @@ inline bool TestMultiInputReaderKernel(
...
     devices.reserve(fabric_num_devices);
     for (size_t i = 0; i < fabric_num_devices; i++) {
-        devices.push_back(view.get_device(MeshCoordinate(0, i)));
+        devices.push_back(mesh_device->get_device(MeshCoordinate(0, i)));
     }
 
+    std::vector<std::shared_ptr<distributed::MeshDevice>> mesh_devices;
+    mesh_devices.reserve(devices.size());
+    for (size_t i = 0; i < devices.size(); i++) {
+        mesh_devices.push_back(mesh_device->create_submesh(MeshShape(1, 1), MeshCoordinate(0, i)));
```
Comment (Riddy21) [inline tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp:1554]: Note, this only works on T3K up to 4 devices, didn't see any tests that used more than 4 devices, but if so need to change to use the second row

Comment (roseli-TT) [reply tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp:1554]: I thought T3k tests use 8 devices... Guess that's not the case? Which tests use 4?

**Review by roseli-TT — APPROVED** [review]

File: tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp (hunk 2 above)
Comment (Riddy21) [reply tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp:1554]: I think this test only uses a subset of the 8 devices. 

https://github.com/tenstorrent/tt-metal/blob/main/tests/ttnn/unit_tests/gtests/ccl/test_fabric_erisc_data_mover_loopback_with_workers.cpp#L425
https://github.com/tenstorrent/tt-metal/blob/main/tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp#L1694

**Review by cfjchu — APPROVED** [review]

File: tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp (hunk 1 above)
Comment (omilyutin-tt) [reply tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp]: Looks like there is a hang on `WorkerCclCommandProcessingKernelFabricUnicastMode.MultiInputReader_SinglePageTile_OneHop_PersistentFabric`?

Comment (Riddy21) [reply tests/ttnn/unit_tests/gtests/ccl/test_fabric_edm_common.hpp]: Working on it now, I thought that was a test that ran long when I was running locally.
