### PR TITLE
Increase generic pool kernel capacity to 32 sticks per tile

### LINKED ISSUE #14588: [Bug Report] Max Pool Fails with Large Kernels and 32 Row Reductions
**Describe the bug**
For some tensor shapes with large kernel sizes (>4x4), max pool fails the PCC assertion on wormhole if 32 row reductions are allowed.   Fixing the reductions to 16 rows alleviates the problem.

**To Reproduce**
1. Connect to an IRD reservation on a `Wormhole` machine
2. Checkout `wransom/Large32-bug`
3. Build the codebase
4. run the unit test `tests/ttnn/unit_tests/operations/test_maxpool2d.py`
5. Notice the test failures which pass if `max_rows_for_reduction` (line 66 of `max_pool2d_multi_core_program_factory.cpp)` is fixed to 16.

**Expected behavior**
Wormhole devices should be capable of using 32 row reductions, even for large kernel sizes.

### PR DESCRIPTION
**Pull request by pavlejosipovic**
Previously, max pool kernels were limited to 16 sticks per tile, forcing the use of the slower "large kernel" implementation when kernel height × width exceeded 16.

This change doubles capacity to 32 sticks per tile, which:
- Avoids using the inefficient large kernel implementation for moderate kernel sizes
- Significantly improves performance for kernels like the 5×5 used in YOLOv8 models
- Measured ~23x speedup for YOLOv8's pooling operations

Fixes #14588

### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/14588)

### Checklist
- [x] [Nightly tt-metal L2 tests BH](https://github.com/tenstorrent/tt-metal/actions/runs/15173003074) CI passes
- [x] [Nightly tt-metal L2 tests](https://github.com/tenstorrent/tt-metal/actions/runs/15172999214) CI with demo tests passes (if applicable)
- [x] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/runs/15163052702) CI passes (if applicable)
- [x] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/runs/15219396487) CI passes (if applicable)
- [x] [(Single-card) Frequent model and ttnn tests](https://github.com/tenstorrent/tt-metal/actions/runs/15148821919) CI passes

### CODE REVIEW

**Review by dstoiljkovicTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp [hunk 1]
```diff
@@ -25,6 +25,21 @@ ALWI bool fill_with_val(uint32_t begin_addr, uint32_t n, uint16_t val) {
...
+    const uint32_t num_tiles = get_local_cb_interface(cb_id).fifo_page_size / tile_size;
+    const uint64_t clear_value_addr = get_noc_addr(get_read_ptr(clear_value_cb_id));
+    uint64_t write_addr = get_noc_addr(get_write_ptr(cb_id));
+
+    for (uint32_t i = 0; i < num_tiles * num_pages; ++i) {
+        noc_async_read(clear_value_addr, write_addr, tile_size);
+        write_addr += tile_size;
+    }
+    noc_async_write_barrier();
+}
```
Comment (s-jovic) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp:41]: can we reuse this function in both kernels?

**Review by s-jovic — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp [hunk 2]
```diff
@@ -86,19 +84,32 @@ void MAIN {
...
     pack_untilize_dst_init_short<max_tiles_per_iter>(out_cb_id, num_out_rows, num_faces_in_tile);
 
+    // tilize reconfiguration is needed if we have more than one block and the number of tiles
+    // is not a multiple of MAX_TILES_PER_REDUCTION
+    constexpr bool tilize_reconfig_needed = in_nblocks_c > 1 && in_ntiles_c % MAX_TILES_PER_REDUCTION != 0;
     cb_wait_front(in_scalar_cb_id, 1);
     for (uint32_t i = 0; i < nsticks_per_core; ++i) {
         // perform the reduction over the first N - 1 whole chunks
+        if constexpr (tilize_reconfig_needed) {
+            UNPACK((llk_unpack_tilizeA_B_init<neginf_srca_maxpool, true, false, zero_srca_avgpool>(
```
Comment (wransom-TT) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp:99]: Why can't we tilize all 8 tiles and only reduce `num_output_tiles`?  I see even before your changes we were tilizing only `num_output_tiles`, and trying it in another branch I find that the call to `unpack_tilizeA_B_block ` hangs if I update it to `MAX_TILES_PER_REDUCTION`. But it would be good to understand why this doesn't work as it would eliminate the need for these re-inits and probably help performance

**Review by wransom-TT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp (hunk 2 above)
Comment (nkpatel-tt) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp:99]: If i am not wrong, this would execute on unpacker only.
Just curious, Does hardware take care of syncing between compute and unpacker that next reduce would execute only after this config change??

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp [hunk 3]
```diff
@@ -25,6 +25,21 @@ ALWI bool fill_with_val(uint32_t begin_addr, uint32_t n, uint16_t val) {
...
+    const uint32_t num_pages = get_local_cb_interface(cb_id).fifo_num_pages;
+    const uint32_t num_tiles = get_local_cb_interface(cb_id).fifo_page_size / tile_size;
+    const uint64_t clear_value_addr = get_noc_addr(get_read_ptr(clear_value_cb_id));
+    uint64_t write_addr = get_noc_addr(get_write_ptr(cb_id));
+
+    for (uint32_t i = 0; i < num_tiles * num_pages; ++i) {
+        noc_async_read(clear_value_addr, write_addr, tile_size);
+        write_addr += tile_size;
+    }
+    noc_async_write_barrier();
```
Comment (nkpatel-tt) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp:40]: do you mean `noc_async_read_barrier`???

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp [hunk 4]
```diff
@@ -25,6 +25,32 @@ ALWI bool fill_with_val(uint32_t begin_addr, uint32_t n, uint16_t val) {
...
+    const uint32_t num_pages = get_local_cb_interface(cb_id).fifo_num_pages;
+    const uint32_t num_tiles = get_local_cb_interface(cb_id).fifo_page_size / tile_size;
+    const uint64_t clear_value_addr = get_noc_addr(get_read_ptr(clear_value_cb_id));
+    uint64_t write_addr = get_noc_addr(get_write_ptr(cb_id));
+
+    for (uint32_t i = 0; i < num_tiles * num_pages; ++i) {
+        noc_async_read(clear_value_addr, write_addr, tile_size);
+        write_addr += tile_size;
+    }
+    noc_async_write_barrier();
```
Comment (nkpatel-tt) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp:40]: `noc_async_read_barrier` here and on line no 51??

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp (hunk 2 above)
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp:99]: It doesn't work correctly on LLK level if you sent in init num tiles than you have to use that number if "execution" call

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp [hunk 5]
```diff
@@ -25,6 +25,21 @@ ALWI bool fill_with_val(uint32_t begin_addr, uint32_t n, uint16_t val) {
     return true;
 }
 
+template <uint32_t cb_id, uint32_t clear_value_cb_id>
+FORCE_INLINE void clear_out_tiles() {
```
[the remark this answers is not in the document]
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp:29]: we can it's just few times slower to do it with a risc core

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp (hunk 3 above)
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp:40]: yeah thx I'll chage it.

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp (hunk 1 above)
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp:41]: 95% of code is duplicated, between the to we just need to remove one of them and make one that is a bit more generic.
I though about adding a common header utility but I think it's just better to have one reader kernel.

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp (hunk 4 above)
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp:40]: yes, thx

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp [hunk 6]
```diff
@@ -42,32 +68,47 @@ void kernel_main() {
     constexpr int32_t in_w = get_compile_time_arg_val(5);
 
     constexpr uint32_t in_c = get_compile_time_arg_val(6);
+    constexpr uint32_t in_nbytes_leftover = (in_c % (32 * 8)) * 2;
```
[the remark this answers is not in the document]
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp:71]: yes, thx

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp [hunk 7]
```diff
@@ -42,32 +68,47 @@ void kernel_main() {
...
     if (reader_id == 0) {
         cb_reserve_back(in_scalar_cb_id, 1);
         fill_with_val(get_write_ptr(in_scalar_cb_id), TILE_WIDTH, bf16_scalar >> 16);
         cb_push_back(in_scalar_cb_id, 1);
     }
 
+    constexpr uint32_t window_hw = window_h * window_w;
+    constexpr bool full_dest_width = in_c % (TILE_WIDTH * MAX_TILES_PER_REDUCTION) == 0;
+    constexpr uint32_t leftover_num_tiles = (in_c % (TILE_WIDTH * MAX_TILES_PER_REDUCTION)) / TILE_WIDTH;
+    if constexpr (window_hw > 16) {
```
[the remark this answers is not in the document]
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp:106]: makes sense I'll add a comment

File: ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp [hunk 8]
```diff
@@ -62,20 +62,18 @@ Pool2D::MultiCore::cached_program_t pool2d_multi_core_sharded_with_halo_v2_impl_
...
-        max_rows_for_reduction /= 2; */
-
-    // Hardware can do reduction of 8 tiles at a time.
-    // CB sizes can be restricted to this in case input channels are more than 256 to perform reduction iteratively.
     constexpr uint32_t MAX_TILES_PER_REDUCTION = 8;
-    const bool is_large_kernel = kernel_size_hw > max_rows_for_reduction;
     const bool is_wide_reduction = in_ntiles_c > MAX_TILES_PER_REDUCTION;
+    // Hardware can do reduction of 8 tiles at a time.
+    // CB sizes can be restricted to this in case input channels are more than 256 to perform reduction iteratively.
+    const bool is_large_kernel =
```
[the remark this answers is not in the document]
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp:71]: yeah I'll add a comment

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp (hunk 2 above)
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp:99]: compute needs input from unpacker to do any work (get data in SrcA/B registers)
and unpack won't be able to unpack before this executes (linear execution) so they are in sync

File: ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (pavlejosipovic) [reply ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp:71]: I've added a comment in compute kernel about face_r_dim where it's configured.
