### PR TITLE
Fixing 1D Mapping Algorithm in Mesh Device for flipped coords

### LINKED ISSUE #33426: # CCL Operations Fail with MGD 2x4 vs 4x2 Mesh Shape
## Problem

When testing a change to the T3K MGD to initialize FabricNodeIds as a 4x2 mesh shape (instead of 2x4), CCL operations (`all_gather_async`, `reduce_scatter_minimal_async`) fail with the following error:

```
RuntimeError: TT_FATAL @ /project/tt_metal/fabric/fabric.cpp:154: forwarding_direction.has_value()
info:
Could not find any forwarding direction from src (M0, D0) to dst (M0, D6)
```

## Expected Behavior

Since 4x2 and 2x4 represent the same physical mesh topology (just transposed), mesh device operations should be agnostic to the FabricNodeId ordering. The operations should work identically regardless of how the FabricNodeIds are initialized in the MGD.

## Actual Behavior

- **2x4 mesh shape**: Operations work correctly
  - CI run: https://github.com/tenstorrent/tt-metal/actions/runs/19771184380
- **4x2 mesh shape**: Operations fail with routing errors
  - CI run: https://github.com/tenstorrent/tt-metal/actions/runs/19744453444/job/56644693351

The test still opens a 2x4 MeshDevice ( I think??), just the underlying fabric node ids now look like this

Image

My changes should be modifying the system mesh, should not affect the MeshDevice shapes. Today, we do allow mapping 8x4, 4x8 MeshDevice onto the Galaxy. This infra should be working

### PR DESCRIPTION
**Pull request by Riddy21**
### Problem description
I isolated the mesh shape change ran this on a Flipped (2x4 vs 4x2) Mesh graph descriptor and got this error on few of the models
https://github.com/tenstorrent/tt-metal/actions/runs/19829710997/job/56813810402
It looks like these errors are happening in ring topologies:
MeshDevice(1x8 grid, 8 devices)

### What's changed
- [x] Changed mesh device shape mapping algorithm for 1D to use DFS instead of snake pattern

### Checklist
- [x] [APC](https://github.com/tenstorrent/tt-metal/actions/runs/19913537412)
- [x] [T3K](https://github.com/tenstorrent/tt-metal/actions/runs/19913490346)
- [x] [Galaxy](https://github.com/tenstorrent/tt-metal/actions/runs/19866657575)
- [x] [BH Multi-card](https://github.com/tenstorrent/tt-metal/actions/runs/19867931831)
- [x] [BH Galaxy Quick](https://github.com/tenstorrent/tt-metal/actions/runs/19868072553)
- [x] [WH Galaxy Quick](https://github.com/tenstorrent/tt-metal/actions/runs/19913523935/job/57087886325)

### CODE REVIEW

File: tt_metal/distributed/mesh_device_view.cpp [hunk 1]
```diff
@@ -191,19 +193,87 @@ std::vector<MeshCoordinate> MeshDeviceView::get_line_coordinates(
...
-        } else if (!left_to_right && col_index > 0) {
-            col_index--;
-        } else {
-            row_index++;
-            left_to_right = !left_to_right;
+    auto [start_row, start_col] = mesh_offset;
+
+    // If true, the line will loop back to the start coordinate as a ring.
+    // Keeping this as a constant for now, may make it configurable in the future.
+    const bool loop_back = true;
```
Comment (Riddy21) [inline tt_metal/distributed/mesh_device_view.cpp]: In order to not change the API interface, I've set this loopback to true by default. It will form a line topology that forms a loop, so that if 1D ring is used, no problems occur.

Comment (aliuTT) [inline tt_metal/distributed/mesh_device_view.cpp]: is this always true for all systems? I guess no harm in doing this, aside from potentially not returning a 1xN none-ring mesh if user doesn't care

Comment (Riddy21) [reply tt_metal/distributed/mesh_device_view.cpp]: I've changed it so it falls back on non-loopback if a loopback one wasn't found.

Comment (Riddy21) [reply tt_metal/distributed/mesh_device_view.cpp]: So this way, whenever cases like 1x8 or 1x32 happen, it will try form a loopback mesh first

File: tt_metal/distributed/mesh_device_view.cpp [hunk 2]
```diff
@@ -191,19 +193,87 @@ std::vector<MeshCoordinate> MeshDeviceView::get_line_coordinates(
...
+        if (line_coords.size() >= length) {
+            break;
+        }
+
+        // Explore neighbors in DFS order (push in reverse order to process in desired order)
+        auto neighbors = get_neighbors(current);
+        for (auto it = neighbors.rbegin(); it != neighbors.rend(); ++it) {
+            if (visited.find(*it) == visited.end()) {
+                stack.push(*it);
+            }
```
[the remark this answers is not in the document]
Comment (Riddy21) [reply tt_metal/distributed/mesh_device_view.cpp]: Algorithm has been changed

File: tt_metal/distributed/mesh_device_view.cpp [hunk 3]
```diff
@@ -191,19 +193,87 @@ std::vector<MeshCoordinate> MeshDeviceView::get_line_coordinates(
...
         }
     }
```
[the remark this answers is not in the document]
Comment (Riddy21) [reply tt_metal/distributed/mesh_device_view.cpp]: Algo has been changed

File: tt_metal/distributed/mesh_device_view.cpp [hunk 4]
```diff
@@ -191,24 +194,111 @@ std::vector<MeshCoordinate> MeshDeviceView::get_line_coordinates(
...
+    bool found_ring = dfs(line_coords, visited, /*require_ring=*/true);
+
+    // If ring not possible, fall back to any valid path
+    if (!found_ring) {
+        // Reset and try without ring requirement
+        line_coords.clear();
+        visited.clear();
+        visited.insert(start_coord);
+        line_coords.push_back(start_coord);
+        found_ring = dfs(line_coords, visited, /*require_ring=*/false);
```
Comment (amorrisonTT) [inline tt_metal/distributed/mesh_device_view.cpp]: is `found_ring` still the right variable name here?

Comment (Riddy21) [reply tt_metal/distributed/mesh_device_view.cpp]: Fixed

File: tt_metal/fabric/control_plane.cpp [hunk 5]
```diff
@@ -489,12 +489,11 @@ void ControlPlane::init_control_plane(
         // multi-host machines should be limited via rank bindings so should be ok
         if (cluster.is_ubb_galaxy() && !is_1d && board_size == 32 &&
             distributed_size == 1) {  // Using full board size for UBB Galaxy
-            int y_size = this->mesh_graph_->get_mesh_shape(MeshId{0})[1];
+            // Top left corner: index 0
             fixed_asic_position_pinnings.push_back({AsicPosition{1, 1}, FabricNodeId(MeshId{0}, 0)});
-            fixed_asic_position_pinnings.push_back({AsicPosition{1, 5}, FabricNodeId(MeshId{0}, 1)});
-            fixed_asic_position_pinnings.push_back({AsicPosition{1, 2}, FabricNodeId(MeshId{0}, y_size)});
+            // Bottom right corner: last device index
+            fixed_asic_position_pinnings.push_back({AsicPosition{4, 1}, FabricNodeId(MeshId{0}, board_size - 1)});
```
Comment (Riddy21) [inline tt_metal/fabric/control_plane.cpp:496]: Changing the pinning to first and last corner so that this pinning works for both 4x8 and 8x4

**Review by jvegaTT — COMMENTED** [review]
Please run Blackhole and Wormhole all post commit and Galaxy Quick to ensure there are no regressions with the other topologies. I am in particular worried about BH and WH Galaxy due to the new pinning and BH Loudbox which is also 2x4 but slightly different, seeing issues with this change.

**Review by aliuTT — APPROVED** [review]

**Review by jvegaTT — CHANGES_REQUESTED** [review]
Pipeline runs have revealed problems in N300 and galaxy that need to be addressed before merging

**Review by jvegaTT — APPROVED** [review]
Seems everything is solved now, lgtm
