### PR TITLE
Generalizing all_to_all_async by adding a composite implementation

### LINKED ISSUE #27780: all to all does not work on padded shapes
### Describe the bug

all to all reports an op assertion indicating incompatible shape sizes when we attempt to use a shape that doesn't evenly divide by 32Xnum_devices on the in or out dimension.

### Steps to reproduce the issue

Checkout jvega/unalligned_all_to_all_test
build metal and create/source venv
run pytest tests/ttnn/unit_tests/operations/ccl/blackhole_CI/nightly/test_all_to_all.py -k test_all_to_all_unaligned

### Expected behavior

The above should be functional with good PCC

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by scardozaTT**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/27780)

### Problem description
The all_to_all_async native implementation only handles very specific cases. We don't have a generic composite implementation to fall back on.

### What's changed
- Added a composite implementation for all_to_all_async, which will be used for all the unsupported cases by native implementation
- Added more T3K pytests for all_to_all_async
- Fixed bugs in pytest test logic for all_to_all_async

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes (https://github.com/tenstorrent/tt-metal/actions/runs/17957596259)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml) CI passes (if applicable)
- [ ] [Galaxy demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [x] T3000 frequent tests (https://github.com/tenstorrent/tt-metal/actions/runs/17957631916)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by scardozaTT** [comment]
Some pytests fail due to a bug in `all_broadcast_async`, I've filed a separate [issue](https://github.com/tenstorrent/tt-metal/issues/29183) for that

**Comment by jvegaTT** [comment]
> Some pytests fail due to a bug in `all_broadcast_async`, I've filed a separate [issue](https://github.com/tenstorrent/tt-metal/issues/29183) for that

Are those failing tests being skipped with a message specifying the relevant issue so the pytest itself passes?

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp [hunk 1]
```diff
@@ -159,6 +159,36 @@ bool use_composite_all_gather(
     return false;
 }
 
+bool use_composite_all_to_all(
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp:162]: Why is this in common.cpp? Seems specific just for all to all

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp [hunk 2]
```diff
@@ -232,4 +262,85 @@ std::vector<ttnn::Tensor> composite_all_gather(
     return output_tensors;
 }
 
+ttnn::Tensor composite_all_to_all(
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp:265]: Same comment as above, this should not be in common

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp [hunk 3]
```diff
@@ -232,4 +262,85 @@ std::vector<ttnn::Tensor> composite_all_gather(
...
+    bool is_sharded = input_tensor.is_sharded();
+    auto input_memory_config = input_tensor.memory_config();
+    auto interim_memory_config = is_sharded ? ttnn::DRAM_MEMORY_CONFIG : input_memory_config;
+    auto output_memory_config = memory_config.value_or(input_memory_config);
+
+    // Convert to row major
+    if (is_tiled_and_not_tile_aligned) {
+        // If input is tiled bfloat8_b, convert to bfloat16 to do the all_broadcast_async + concat
+        if (convert_to_bfloat16_for_composite) {
+            input_tensor = ttnn::typecast(input_tensor, ttnn::DataType::BFLOAT16);
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: Assign it to a temporary buffer and deallocate the input

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp [hunk 4]
```diff
@@ -232,4 +262,85 @@ std::vector<ttnn::Tensor> composite_all_gather(
...
+        }
+        input_tensor = ttnn::to_layout(input_tensor, ttnn::Layout::ROW_MAJOR);
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: Assign it to a temporary buffer and deallocate the input

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp [hunk 5]
```diff
@@ -232,4 +262,85 @@ std::vector<ttnn::Tensor> composite_all_gather(
...
+    }
+
+    // Sharded input is challenging to work with, because we perform slice and concat separately
+    // and the user can't give us intermediate shard specs. So the most foolproof solution is
+    // to simply undo sharding by converting to DRAM interleaved storage.
+    if (is_sharded) {
+        input_tensor = ttnn::to_memory_config(input_tensor, interim_memory_config);
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: Can you specify the output memory config for all_broadcast_async to give it the interim_memory_config? If not this is fine but it would improve perf to not have to do an extra op

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp [hunk 6]
```diff
@@ -232,4 +262,85 @@ std::vector<ttnn::Tensor> composite_all_gather(
...
+    }
+
+    // Step 1: make every device have a copy of every tensor
+    std::vector<ttnn::Tensor> broadcasted_tensors = ttnn::operations::experimental::ccl::all_broadcast_async(
+        input_tensor,
+        num_links,
+        interim_memory_config,
+        ttnn::ccl::Topology::Linear,
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp:324]: Does all broadcast async only work in linear? If not you should allow the option for ring. For reference perf in ring is often nearly double that of linear.

**Comment by scardozaTT** [comment]
> > Some pytests fail due to a bug in `all_broadcast_async`, I've filed a separate [issue](https://github.com/tenstorrent/tt-metal/issues/29183) for that
> 
> Are those failing tests being skipped with a message specifying the relevant issue so the pytest itself passes?

Yes, I added a pyskip and the Issue number for those

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 1 above)
Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp:162]: There was a recent refactor which put all the composite functions in a single file, I kept my code consistent with that structure. Not sure about the rationale behind it.

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 3 above)
Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: If you notice this code block assigns back to the same variable, so I wanted to check if the original object gets destroyed.
I added some prints to the code: (inside tensor.cpp as well)
```
std::cout << ">> doing to_memory_config" << std::endl;
input_tensor = ttnn::to_memory_config(input_tensor, interim_memory_config);
std::cout << "<< done to_memory_config" << std::endl;
```
And got:
```
>> doing to_memory_config
called destructor
called destructor
called destructor
called destructor
called destructor
called destructor
called destructor
<< done to_memory_config
```
Not sure why there's 7 destructor calls to this object, but I'm hoping the original buffer is being deallocated.

What do you think? Do you want me to explicitly call deallocate()? (I'll need to add 2 lines of code after every op invocation)

Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: Ok after adding more prints I don't think the input tensor is being deallocated. These prints might be coming from other tensors being temporarily created during op execution.
I'll add the explicit deallocate() calls.

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 6 above)
Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp:324]: not sure tbh, the all_gather composite hardcoded this to linear, so I followed the same and didn't want to get too creative.
I'll leave this as is for now, and if there are complaints about performance we can revisit this again.

File: tests/nightly/t3000/ccl/test_all_to_all.py [hunk 7]
```diff
@@ -342,8 +343,184 @@ def test_all_to_all(
...
+    layout,
+    mem_config,
+    num_iters,
+    do_check,
+    reuse_inputs,
+):
+    if layout == ttnn.ROW_MAJOR_LAYOUT and input_dtype == ttnn.bfloat8_b:
+        pytest.skip("Row-major layout is not supported for bfloat8_b")
+
+    # The below fails because of a bug in all_broadcast_async (Issue #29183)
```
[the remark this answers is not in the document]
Comment (scardozaTT) [reply tests/nightly/t3000/ccl/test_all_to_all.py]: done

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp [hunk 8]
```diff
@@ -159,6 +159,36 @@ bool use_composite_all_gather(
...
+    bool is_tiled_and_tile_aligned = input_tensor.layout() == ttnn::Layout::TILE &&
+                                     (input_shape[2] % tile_height == 0 && input_shape[3] % tile_width == 0);
+
+    // the current native implementation works for very specific cases
+    if (input_tensor.layout() == ttnn::Layout::TILE && input_tensor.buffer()->buffer_type() == ttnn::BufferType::DRAM &&
+        input_tensor.memory_config().memory_layout() == ttnn::TensorMemoryLayout::INTERLEAVED &&
+        (!memory_config.has_value() ||
+         memory_config.value().memory_layout() == ttnn::TensorMemoryLayout::INTERLEAVED) &&
+        (in_dim == 2 || in_dim == 3) && (out_dim == 2 || out_dim == 3) && is_tiled_and_tile_aligned) {
+        return false;
```
[the remark this answers is not in the document]
Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: fixed

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 3 above)
Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: done

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 4 above)
Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: done

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 6 above)
Comment (jvegaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp:324]: Can you make an issue about this. I get that functionality is the most important metric but we can't just throw away perf. It really bothers me as well that the all gather is this way

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 3 above)
Comment (jvegaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp]: Thanks

**Review by jvegaTT — APPROVED** [review]
I am approving this to unblock but there are a few things I am unhappy about which I think we should create an issue for to track and tackle when we can

We should not be hardcoding to linear in the composite ops, the user should specify this parameter at a python level and it should be fed down

We shouldn't have all the composites done in the common folder. They should be in the same base folder as the op. This unnecessarily pollutes the common folder so it ends up not being used. Only things that are done in common by multiple ops should be there

**Comment by scardozaTT** [comment]
> I am approving this to unblock but there are a few things I am unhappy about which I think we should create an issue for to track and tackle when we can
> 
> We should not be hardcoding to linear in the composite ops, the user should specify this parameter at a python level and it should be fed down
> 
> We shouldn't have all the composites done in the common folder. They should be in the same base folder as the op. This unnecessarily pollutes the common folder so it ends up not being used. Only things that are done in common by multiple ops should be there

I've created a separate Issue to track this: https://github.com/tenstorrent/tt-metal/issues/29332

File: ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp (hunk 6 above)
Comment (scardozaTT) [reply ttnn/cpp/ttnn/operations/experimental/ccl/common.cpp:324]: Created a separate Issue to track this: https://github.com/tenstorrent/tt-metal/issues/29332
