### PR TITLE
Fix worker <-> teardown by adding separate worker connection teardown semaphore

### LINKED ISSUE #16634: Fix Worker <-> fabric EDM connection teardown race
A race condition was recently discovered that can sometimes lead to hangs. This race condition occurs during connection teardown between workers and fabric EDM endpoints.

A bandaid has been created in this PR: https://github.com/tenstorrent/tt-metal/pull/16636

The general problem is that there is aliasing between the flow control and teardown. The worker only has one semaphore for both but it should have two. At the moment, there is a possibility of double increment from EDM -> worker.

Image

There likely a few options to address this problem but the simplest is probably to just add a new semaphore on the worker side and store it in the `ttnn/cpp/ttnn/operations/ccl/kernels/edm_fabric/edm_fabric_worker_adapters.hpp`. 
- Device side can by updated by extending `WorkerToFabricEdmSender::build_from_args` to read in the runtime args. 
- Host side can be updated by extending `append_worker_to_fabric_edm_sender_rt_args` in `ttnn/cpp/ttnn/operations/ccl/erisc_datamover_builder.cpp` to pass the semaphore as well as `FabricEriscDatamoverBuilder::build` to create the semaphore.

### PR DESCRIPTION
**Pull request by SeanNijjar**
Submitting on behalf of @tt-aho who did the work for this fix.

### Ticket
https://github.com/tenstorrent/tt-metal/issues/16634

### Problem description
See issue for more details. There was a bug in the worker connection teardown logic that would lead to non-deterministic and unsafe worker <-> edm fabric teardown, possibly leading to hangs.

### What's changed
Added a dedicated worker teardown semaphore on the worker that removes the (bug) aliasing between flow control logic and worker connection teardown logic. Note that this doesn't appear to resolve all hangs as another hang now appears after running several hundred iterations after applying this fix.

### Checklist
- [x] Post commit CI: https://github.com/tenstorrent/tt-metal/actions/runs/12933571901
- [x] T3K frequent, nightly, unit: https://github.com/tenstorrent/tt-metal/actions/runs/12961369175
- same failures as main 
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/ccl/kernels/edm_fabric/fabric_erisc_datamover_channels.hpp [hunk 1]
```diff
@@ -219,7 +219,14 @@ struct EdmChannelWorkerInterface {
 
     // Connection management methods
     //
-    FORCE_INLINE void teardown_connection() const { increment_worker_semaphore(); }
+    FORCE_INLINE void teardown_connection() const {
+        auto const &worker_info = *worker_location_info_ptr;
+        uint64_t worker_semaphore_address = get_noc_addr(
+            (uint32_t)worker_info.worker_xy.x, (uint32_t)worker_info.worker_xy.y, worker_info.worker_teardown_semaphore_address);
+
+        DPRINT << "EDM ntf trdn sem @" << (uint64_t)worker_semaphore_address << "\n";
```
Comment (SeanNijjar) [inline ttnn/cpp/ttnn/operations/ccl/kernels/edm_fabric/fabric_erisc_datamover_channels.hpp:227]:
```suggestion
```

File: ttnn/cpp/ttnn/operations/ccl/kernels/edm_fabric/edm_fabric_worker_adapters.hpp [hunk 2]
```diff
@@ -173,7 +179,7 @@ struct WorkerToFabricEdmSender {
         // A proper fix requires for example adding an additional teardown semaphore on the
         // worker side that the EDM writes to to acknowledge teardown. The problem here
         // is that the flow control aliases the teardown.
```
Comment (tt-aho) [inline ttnn/cpp/ttnn/operations/ccl/kernels/edm_fabric/edm_fabric_worker_adapters.hpp:181]: Remove comment

**Review by tt-aho — APPROVED** [review]
