### PR TITLE
Let ttnn.reshape support 0 volume tensors

### LINKED ISSUE #15284: Support empty tensor in reshape/view ops
This two input variation appeared in `retinanet_resnet50_fpn` model
```
    [
        ["Tensor<[0, 1, 4]> self = ?", "List[int] size = [0, 4]"],
        ["Tensor<[0, 2, 2]> self = ?", "List[int] size = [0, 4]"],
    ]
```
And if it convert to `ttnn.reshape`, it will cause this error msg

```
Failed to run. Raised exception: TT_FATAL @ /tmp/build-via-sdist-ywnpie0n/metal_libs-0.53.0rc41+wormhole.b0/ttnn/cpp/ttnn/tensor/tensor_utils.cpp:475: shape[index] > 0
```

Now I avoid convert it by

https://github.com/tenstorrent/pytorch2.0_ttnn/blob/cc697a9e552c43754a36586edc3dd06750f37928/torch_ttnn/passes/lowering/to_tt_pass.py#L739-L744

Does `ttnn.reshape` need to support these input variation? if not, then `retinanet_resnet50_fpn`  cannot end-to-end compile

### PR DESCRIPTION
**Pull request by swimdi**
### Ticket
#15284 

### Problem description
torch.reshape support cases with zero element. For example:
```
torch_input_tensor = torch.ones([0, 5])
reshape_tensor = torch.reshape(torch_input_tensor, [0, 0, 5])
print(reshape_tensor.shape)
# torch.Size([0, 0, 5])
```

Similarly, in torch_ttnn, there are scenarios involving zero-element tensors where operations are lowered from a torch operation to ttnn.reshape.

This PR adds support for such cases.

### What's changed
 - Let ttnn.reshape support 0 element
 - Add zero element unittest

### Checklist
- [x] [Post commit CI](https://github.com/tenstorrent/tt-metal/actions/runs/12310606570)
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 1]
```diff
@@ -167,6 +167,15 @@ ttnn::Tensor ReshapeViewOperation::invoke(const ttnn::Tensor& tensor, const ttnn
     if (tensor_shape == shape) {
         return tensor;
     }
+
+    // Just edit shape if shape has a 0 dimension
+    for (auto index = 0; index < shape.rank(); ++index) {
+        if (shape[index] == 0) {
+            std::cout << "!!! 0 dimension !!!" << std::endl;
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:174]: Pleaseremove

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 2]
```diff
@@ -167,6 +167,15 @@ ttnn::Tensor ReshapeViewOperation::invoke(const ttnn::Tensor& tensor, const ttnn
     if (tensor_shape == shape) {
         return tensor;
     }
+
+    // Just edit shape if shape has a 0 dimension
+    for (auto index = 0; index < shape.rank(); ++index) {
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:172]: if tensor.volume() == 0

File: ttnn/cpp/ttnn/tensor/tensor_utils.cpp [hunk 3]
```diff
@@ -473,10 +474,20 @@ const ttnn::SimpleShape infer_dims_for_reshape(const Tensor& tensor, tt::stl::Sp
...
             new_volume *= shape[index];
         }
     }
+    if (has_zero && index_of_negative_1 != -1) {
+        std::string error_msg = "cannot reshape tensor of 0 elements into shape [";
+        for(auto & s: shape) {
+            error_msg += std::to_string(s) + ",";
+        }
+        error_msg += "] because the unspecified dimension size -1 can be any value and is ambiguous";
+        TT_THROW("{}", error_msg);
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/tensor/tensor_utils.cpp:489]: TT_THROW("Cannot reshape tensor of 0 elements into shape () because the unspecified dimension size -1 can be any value and is ambiguous", shape);

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 1 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp]: Oh.. I removed

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 2 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp]: okok, Edited

File: ttnn/cpp/ttnn/tensor/tensor_utils.cpp (hunk 3 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:489]: cannot convert `shape` to string directly, so I remain the origin code

Comment (ayerofieiev-tt) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:489]: What error do you get?

Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:489]: The compiled err is
```
/home/ubuntu/tt-metal/.cpmcache/fmt/73b5ec45edbd92babfd91c3777a9e1ab9cac8238/include/fmt/base.h:2657:45: error: implicit instantiation of undefined template 'fmt::detail::type_is_unformattable_for<tt::stl::Span<const int>, char>'
 2657 |     type_is_unformattable_for<T, char_type> _;
```

File: tests/ttnn/unit_tests/test_reshape.py [hunk 4]
```diff
@@ -384,3 +384,39 @@ def test_fp32_support(input_shape, output_shape, device):
...
+    [ttnn.ROW_MAJOR_LAYOUT, ttnn.TILE_LAYOUT],
+)
+@pytest.mark.parametrize(
+    "ttnn_reshape",
+    [True, False],
+)
+@pytest.mark.parametrize(
+    "use_device, memory_config",
+    [(True, None), (True, ttnn.L1_MEMORY_CONFIG), (False, None)],
+)
```
Comment (jvegaTT) [inline tests/ttnn/unit_tests/test_reshape.py:409]: Do we need 48 different testing iterations for this case? I worry it increases test time too much

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 5]
```diff
@@ -167,6 +167,12 @@ ttnn::Tensor ReshapeViewOperation::invoke(const ttnn::Tensor& tensor, const ttnn
     if (tensor_shape == shape) {
         return tensor;
     }
+
+    // Just edit shape if shape has a 0 dimension
+    if tensor.volume() == 0 {
+        return tensor.reshape(shape);
+    }
+
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:175]: We should also check shape.volume which should be 0 if and only if tensor.volume is 0. Otherwise we can hit errors down the road

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp [hunk 6]
```diff
@@ -374,7 +374,9 @@ Tensor tensor_reshape(const Tensor& input_tensor, const ttnn::Shape& new_shape)
                     if (tensor.memory_config().memory_layout != TensorMemoryLayout::HEIGHT_SHARDED) {
                         DeviceStorage device_storage = std::get<T>(tensor.get_storage());
                         DeviceBuffer device_buffer = device_storage.get_buffer();
-                        device_buffer->set_page_size(new_shape[-1] * tensor.element_size());
+                        if (new_shape[-1] != 0) {
+                            device_buffer->set_page_size(new_shape[-1] * tensor.element_size());
+                        }
```
Comment (jvegaTT) [inline ttnn/cpp/ttnn/tensor/tensor_ops.cpp:379]: Should we set the page size to some default value in this case? I wonder if by minimizing it we can reduce unnecessary memory allocation on device later. Also will help reduce strange edge cases

**Review by jvegaTT — CHANGES_REQUESTED** [review]
I have left a few comments. Please address before merging. Thanks

File: tests/ttnn/unit_tests/test_reshape.py (hunk 4 above)
Comment (swimdi) [reply tests/ttnn/unit_tests/test_reshape.py:409]: I think it's all zero element won't spend too much time, or I'll reduce the cases

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 5 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:175]: Ok I'll check

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp (hunk 6 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:379]: Actually I don't know what page_size mean(could you give some doc link of page_size?), if it mean num of tiles then I think set 0 make sense, but set 0 will hang the machine. I'll double check why set 0 not work

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp [hunk 7]
```diff
@@ -387,7 +389,7 @@ Tensor tensor_reshape(const Tensor& input_tensor, const ttnn::Shape& new_shape)
 
                         uint32_t mul_div = new_shape[-1] > shard_shape[1] ?
                                         (new_shape[-1] / shard_shape[1]) :
-                                        (shard_shape[1] / new_shape[-1]);
+                                        (new_shape[-1] != 0 ? (shard_shape[1] / new_shape[-1]) : 0);
```
[the remark this answers is not in the document]
Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:392]: yes... I'll double check what codes will be effected

File: tests/ttnn/unit_tests/test_reshape.py (hunk 4 above)
Comment (jvegaTT) [reply tests/ttnn/unit_tests/test_reshape.py:409]: Can you profile how long that component of the test takes in seconds by running it? Pytest has a lot of overhead

Comment (swimdi) [reply tests/ttnn/unit_tests/test_reshape.py:409]: The origin `test_reshape.py` spent `23.784s`, after added these 48 cases it spent `23.814s`, but I think I'll reduce it to about 8 case

Comment (jvegaTT) [reply tests/ttnn/unit_tests/test_reshape.py:409]: Oh then that's fine. FYI for the future you can use -k 'name of function' in pytest to run just that function and not the whole file.

Comment (swimdi) [reply tests/ttnn/unit_tests/test_reshape.py:409]: okok, thank you

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp (hunk 6 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:379]: Oh it's not num of tiles, its tile's size if TILE_LAYOUT(https://github.com/tenstorrent/tt-metal/blob/main/tech_reports/tensor_layouts/tensor_layouts.md#3-tensor-layout)

If set 0 the case of `input_shape, output_shape = [0], [1, 0]` will hang
and I print its value is
```
tensor.element_size(): 2
device_buffer->page_size(): 4
```
So currently I set page size to `2 * tensor.element_size()`

I try to figure out why its page_size is 4, I trace the code to here
https://github.com/tenstorrent/tt-metal/blob/61420b06c3fbc0d4e50e13e7aff0f60fb2f7714e/ttnn/cpp/ttnn/tensor/tensor_ops.cpp#L42
inside the `populate_buffers_and_metadata` the print is
```
other.element_size(): 2
other device_buffer->page_size(): 4
```
but in `tensor_to` I cannot print `async_safe_tensor`'s `page_size`, so I don't know why its page size is 2

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp]: I edited this part to set 0 if either `new_shape[-1]` or `shard_shape[1]` is 0

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 5 above)
Comment (jvegaTT) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:179]: Could you also add:
TT_ASSERT(shape.volume() != 0 && "tensor's volume is not 0, but shape's volume is 0");
Right after the if just to cover us in both directions?

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp (hunk 6 above)
Comment (jvegaTT) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:379]: This part is not that important, it seems a bit more involved so maybe just keep it as it is unless we find an issue down the road. The fact view doesn't work with your changes (below) is much more important

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp (hunk 5 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:180]: okok I added, thank you

**Review by jvegaTT — APPROVED** [review]
Looks good to merge

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 8]
```diff
@@ -167,6 +167,17 @@ ttnn::Tensor ReshapeViewOperation::invoke(const ttnn::Tensor& tensor, const ttnn
     if (tensor_shape == shape) {
         return tensor;
     }
+
+    // Just edit shape if shape has a 0 dimension
+    if (tensor.volume() == 0) {
+        TT_ASSERT(shape.volume() == 0 && "tensor's volume is 0, but shape's volume is not 0");
+        TT_ASSERT((tensor.storage_type() != StorageType::MULTI_DEVICE &&
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:174]: Please use `TT_FATAL`

`TT_ASSERT` is only really hit in debug mode, and not run on CI by default.

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 9]
```diff
@@ -167,6 +167,17 @@ ttnn::Tensor ReshapeViewOperation::invoke(const ttnn::Tensor& tensor, const ttnn
     if (tensor_shape == shape) {
         return tensor;
     }
+
+    // Just edit shape if shape has a 0 dimension
+    if (tensor.volume() == 0) {
+        TT_ASSERT(shape.volume() == 0 && "tensor's volume is 0, but shape's volume is not 0");
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:173]:
```suggestion       
        TT_FATAL(shape.volume() == 0 , "Tensor volume is 0, but shape's volume is not");
```

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 10]
```diff
@@ -167,6 +167,17 @@ ttnn::Tensor ReshapeViewOperation::invoke(const ttnn::Tensor& tensor, const ttnn
...
+        TT_ASSERT((tensor.storage_type() != StorageType::MULTI_DEVICE &&
+                   tensor.storage_type() != StorageType::MULTI_DEVICE_HOST) &&
+                   "Reshaping a multi-device tensor with 0 volume is not supported");
+        return tensor.reshape(shape);
+    }
+    TT_ASSERT(shape.volume() != 0 && "tensor's volume is not 0, but shape's volume is 0");
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:179]:
```suggestion
    TT_FATAL(shape.volume() != 0, "Tensor volume is not 0, but shape volume is 0");
```

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 11]
```diff
@@ -167,6 +167,17 @@ ttnn::Tensor ReshapeViewOperation::invoke(const ttnn::Tensor& tensor, const ttnn
     if (tensor_shape == shape) {
         return tensor;
     }
+
+    // Just edit shape if shape has a 0 dimension
+    if (tensor.volume() == 0) {
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:172]: Please use `TT_FATAL`

`TT_ASSERT` is only really hit in debug mode, and not run on CI by default.

**Review by swimdi — COMMENTED** [review]
Use `TT_FATAL` instead of `TT_ASSERT`

File: ttnn/cpp/ttnn/tensor/tensor_utils.cpp (hunk 3 above)
Comment (sminakov-tt) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:495]: @ayerofieiev-tt `shape` here is `tt::stl::Span<const int32_t>`, not `ttnn::SimpleShape`, so it can't be easily printed

Comment (sminakov-tt) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:495]: I would suggest to extract error message printing code into a lambda and call it twice

Comment (ayerofieiev-tt) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:495]: Can we pleace accept a SimpleShape here instead?

**Comment by jvegaTT** [comment]
Since I re-wrote reshape, I just merged this PR with my new stuff but to get full generality we need this pushed in ASAP.

**Review by ntarafdar — APPROVED** [review]

**Comment by ntarafdar** [comment]
@swimdi please rebase and address all comments, we want to get this in ASAP
CC: @ayerofieiev-tt

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp [hunk 12]
```diff
@@ -391,7 +391,12 @@ Tensor tensor_reshape(const Tensor& input_tensor, const ttnn::Shape& new_shape)
                     if (tensor.memory_config().memory_layout != TensorMemoryLayout::HEIGHT_SHARDED) {
                         DeviceStorage device_storage = std::get<T>(tensor.get_storage());
                         DeviceBuffer device_buffer = device_storage.get_buffer();
-                        device_buffer->set_page_size(new_shape[-1] * tensor.element_size());
+                        if (new_shape[-1] != 0) {
+                            device_buffer->set_page_size(new_shape[-1] * tensor.element_size());
+                        }
+                        else {
+                            device_buffer->set_page_size(2 * tensor.element_size());
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/tensor/tensor_ops.cpp:398]: nit: 2 is a magic number. Would be good to replace with a meaningful variable/constant.

**Review by bbradelTT — APPROVED** [review]

**Comment by swimdi** [comment]
> @swimdi please rebase and address all comments, we want to get this in ASAP
> CC: @ayerofieiev-tt

I've rebased, please take a look

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp [hunk 13]
```diff
@@ -391,7 +391,12 @@ Tensor tensor_reshape(const Tensor& input_tensor, const ttnn::Shape& new_shape)
                     if (tensor.memory_config().memory_layout != TensorMemoryLayout::HEIGHT_SHARDED) {
                         DeviceStorage device_storage = std::get<T>(tensor.get_storage());
                         DeviceBuffer device_buffer = device_storage.get_buffer();
-                        device_buffer->set_page_size(new_shape[-1] * tensor.element_size());
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/tensor/tensor_ops.cpp:394]: Please replace with 
```
const auto& tensor_spec = tensor.tensor_spec();
auto page_size_bytes = tensor_spec.compute_page_size_bytes();
device_buffer->set_page_size(page_size_bytes);
```

@sminakov-tt , right?

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp [hunk 14]
```diff
@@ -402,10 +407,16 @@ Tensor tensor_reshape(const Tensor& input_tensor, const ttnn::Shape& new_shape)
                         auto shard_spec = shard_spec_buffer.tensor_shard_spec;
                         auto shard_shape = shard_spec.shape;
 
-                        uint32_t mul_div = new_shape[-1] > shard_shape[1] ? (new_shape[-1] / shard_shape[1])
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/tensor/tensor_ops.cpp:405]: No need to calculate it all. Please just ask tensor spec.
```
const auto& tensor_spec = tensor.tensor_spec();
auto shard_spec_buffer = tensor_spec.compute_shard_spec_buffer();
device_buffer-> set_shard_spec(shard_spec_buffer);
```

Comment (ayerofieiev-tt) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:405]: @TT-BrianLiu , look how handy :)

File: ttnn/cpp/ttnn/tensor/tensor_utils.cpp (hunk 3 above)
Comment (ayerofieiev-tt) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:660]: Still like a lot of complication to me. 
We could attempt to create a `new_shape = ttnn::SimpleShape(std::move(new_shape));`
We could ask `new_shape.volume`, we could check things within it, instead of doing all the shenanigans to validate and print. wdyt?

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp (hunk 13 above)
Comment (sminakov-tt) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:394]: Yes, I think this should be the correct way

File: ttnn/cpp/ttnn/tensor/tensor_utils.cpp (hunk 3 above)
Comment (sminakov-tt) [reply ttnn/cpp/ttnn/tensor/tensor_utils.cpp:660]: We can't create a SimpleShape out of a vector here. SimpleShape contains uint32_t, but the input numbers are int32_t with a special treatment of -1. The whole reason for this function is to replace -1 with a proper value.

File: ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp [hunk 15]
```diff
@@ -370,6 +370,17 @@ ttnn::Tensor ReshapeViewOperation::invoke(
 
     const uint32_t shape_second_last_dim = shape.rank() >= 2 ? shape[-2]:1;
     const uint32_t tensor_shape_second_last_dim = tensor_shape.rank() >= 2 ? tensor_shape[-2]:1;
+
+    // Just edit shape if shape has a 0 dimension
+    if (tensor.volume() == 0) {
```
Comment (sminakov-tt) [inline ttnn/cpp/ttnn/operations/data_movement/reshape_view/reshape.cpp:375]: Actually `tensor.volume()` refers to physical volume, not logical volume. You can use either `tensor.get_logical_volume()` or `tensor.logical_shape().volume()`
cc @ayerofieiev-tt

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp (hunk 13 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:394]: okok, I replaced with `compute_page_size_bytes`

File: ttnn/cpp/ttnn/tensor/tensor_ops.cpp (hunk 14 above)
Comment (swimdi) [reply ttnn/cpp/ttnn/tensor/tensor_ops.cpp:405]: I try to replaced with `compute_shard_spec_buffer`, but the `test_reshape_sharded_rm` failed@@
```
# origin
page_shape is {1, 32}
tensor2d_shape is {128, 1}
# use compute_shard_spec_buffer
page_shape is {1, 64}
tensor2d_shape is {4096, 1}

E       RuntimeError: TT_FATAL @ /home/ubuntu/tt-metal/ttnn/cpp/ttnn/operations/data_movement/transpose/device/transpose_op.cpp:57: shard_spec.shape[1] == W
```

so I kept the origin code

**Review by ayerofieiev-tt — APPROVED** [review]
