### PR TITLE
Mpise/22336 4gb tensor gets filled with zeros

### LINKED ISSUE #22336: 4GB tensor gets filled with zeros
### Describe the bug

A 4GB host tensor filled with 1.0 gets replaced with 0.0 when sent to the device.

### Steps to reproduce the issue

The following creates a tensor with 2**31 2-byte elements = 4GB total.  The same occurs for float32 (4 bytes per element) if the tensor is reduced to 2**30 elements.  Reducing the tensor size to below 4GB passes the test.

Suspected problem with `uint32_t` being incorrectly used somewhere in the code path.

```python
import ttnn
import torch

device = ttnn.open_device(device_id=0)

def test_large_tensor(device):
    shape = (2**5, 2**13, 2**13)
    torch_input = torch.full(shape, 1).bfloat16()
    torch_output = torch_input

    input_tensor = ttnn.from_torch(torch_input, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat16, device=device)
    output_tensor = ttnn.from_device(input_tensor)
    output_tensor = ttnn.to_torch(output_tensor).bfloat16()

    print("shapes", torch_output.shape, output_tensor.shape)
    print("tensors", torch_output, output_tensor)

    assert torch_output.shape == output_tensor.shape
    assert torch.all(torch_output == output_tensor)

try:
    test_large_tensor(device)
finally:
    ttnn.close_device(device)
```

### Expected behavior

Tensor should not be filled with zeros.

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by mpiseTT**
### Ticket
[22336](https://github.com/tenstorrent/tt-metal/issues/22336)

### What's changed
Investigate the call flows, identify the problematic codes and fix them (could be by accumulating intermediate results in `uint64_t` or increasing the integer type width from `uint32_t` to `uint64_t`).

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-quick-trigger.yaml) CI passes (if applicable)
- [ ] [TG demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [x] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp [hunk 1]
```diff
@@ -923,47 +932,50 @@ uint32_t process_relay_linear_cmd(uint32_t cmd_ptr, uint32_t& downstream_data_pt
...
 
     // First step - read into DB0
     uint32_t scratch_read_addr = scratch_db_top[0];
-    uint32_t amt_to_read = (scratch_db_half_size > read_length) ? read_length : scratch_db_half_size;
+    uint32_t amt_to_read = (scratch_db_half_size > wlength) ? wlength : scratch_db_half_size;
     uint64_t noc_addr = get_noc_addr_helper(noc_xy_addr, read_addr);
     noc_async_read(noc_addr, scratch_read_addr, amt_to_read);
     read_addr += amt_to_read;
-    noc_async_read_barrier();
+    wlength -= amt_to_read;
```
Comment (jbaumanTT) [inline tt_metal/impl/dispatch/kernels/cq_prefetch.cpp:948]: If wlength is now == to 0, then the loop below will be skipped and tehre will be no async_read_barrier performed before the write_pages_to_dispatcher

File: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp [hunk 2]
```diff
@@ -923,47 +932,50 @@ uint32_t process_relay_linear_cmd(uint32_t cmd_ptr, uint32_t& downstream_data_pt
...
-        db_toggle ^= 1;
-        scratch_read_addr = scratch_db_top[db_toggle];
-        scratch_write_addr = scratch_db_top[db_toggle ^ 1];
+    constexpr uint32_t max_batch_size = ~(scratch_db_half_size - 1);
+    while (wlength != 0) {
+        uint32_t read_length = (wlength > max_batch_size) ? max_batch_size : wlength;
+        wlength -= read_length;
+        while (read_length != 0) {
+            // TODO(pgk); we can do better on WH w/ tagging
+            noc_async_read_barrier();
```
Comment (jbaumanTT) [inline tt_metal/impl/dispatch/kernels/cq_prefetch.cpp]: This needs to be at the end of the loop, or else there won't be a read barrier after the last read and before the last write.

Comment (mpiseTT) [reply tt_metal/impl/dispatch/kernels/cq_prefetch.cpp]: Good catch, thanks!

File: tt_metal/api/tt-metalium/mesh_command_queue.hpp [hunk 3]
```diff
@@ -114,7 +114,7 @@ class MeshCommandQueue {
     virtual void enqueue_read(
         const std::shared_ptr<MeshBuffer>& mesh_buffer,
         DistributedHostBuffer& host_buffer,
-        const std::optional<std::unordered_set<MeshCoordinate>>& shards,
+        const std::optional<std::set<MeshCoordinate>>& shards,
```
Comment (pgkeller) [inline tt_metal/api/tt-metalium/mesh_command_queue.hpp]: curious why the change?  maybe add a comment about why ordered set is needed?

File: tt_metal/impl/dispatch/device_command.cpp [hunk 4]
```diff
@@ -153,12 +153,13 @@ void DeviceCommand<hugepage_write>::add_dispatch_wait_with_prefetch_stall(
...
 
 template <bool hugepage_write>
-void DeviceCommand<hugepage_write>::add_prefetch_relay_linear(uint32_t noc_xy_addr, uint32_t lengthB, uint32_t addr) {
+void DeviceCommand<hugepage_write>::add_prefetch_relay_linear(uint32_t noc_xy_addr, DeviceAddr lengthB, uint32_t addr) {
     uint32_t increment_sizeB = tt::align(sizeof(CQPrefetchCmd), this->pcie_alignment);
     auto initialize_relay_linear_cmd = [&](CQPrefetchCmd* relay_linear_cmd) {
         relay_linear_cmd->base.cmd_id = CQ_PREFETCH_CMD_RELAY_LINEAR;
         relay_linear_cmd->relay_linear.noc_xy_addr = noc_xy_addr;
         relay_linear_cmd->relay_linear.length = lengthB;
+        relay_linear_cmd->relay_linear.length_hi = (lengthB >> 32) & 0xff;
```
Comment (pgkeller) [inline tt_metal/impl/dispatch/device_command.cpp:162]: this looks like an assumption about how large an address we can use.  ideally this would go behind the hal.  if not behind the hal, at least use a named constexpr and a TODO: move behind hal.

File: tt_metal/impl/dispatch/device_command.hpp [hunk 5]
```diff
@@ -57,7 +57,7 @@ class DeviceCommand {
 
     void add_dispatch_wait_with_prefetch_stall(uint32_t flags, uint32_t address, uint32_t stream, uint32_t count);
 
-    void add_prefetch_relay_linear(uint32_t noc_xy_addr, uint32_t lengthB, uint32_t addr);
+    void add_prefetch_relay_linear(uint32_t noc_xy_addr, DeviceAddr lengthB, uint32_t addr);
```
Comment (pgkeller) [inline tt_metal/impl/dispatch/device_command.hpp:60]: length isn't an addr?

File: tt_metal/impl/dispatch/device_command.cpp (hunk 4 above)
Comment (pgkeller) [reply tt_metal/impl/dispatch/device_command.cpp:162]: oh, I see, the cmd itself adds an extra byte, in which case the constexpr should be in cq_commands.h and used here

**Review by pgkeller — COMMENTED** [review]
only got part way through, submitting what I have for now

File: tt_metal/impl/dispatch/device_command.hpp (hunk 5 above)
Comment (mpiseTT) [reply tt_metal/impl/dispatch/device_command.hpp:60]: We use `DeviceAddr` type in all such applications in the host code. I continued with it for consistency. I did have a new type defined, but it just got confusing and eventually I abandoned it and fell in line with this. In fact I don't see why we cannot just use plain old `uint64_t`. Maybe DeviceAddressWidth might have been a more suitable name for this category, a bit wordier, but I guess it could have avoided this question.

File: tt_metal/api/tt-metalium/mesh_command_queue.hpp (hunk 3 above)
Comment (mpiseTT) [reply tt_metal/api/tt-metalium/mesh_command_queue.hpp]: An earlier version of the distributed host buffer + mesh buffer read back test I wrote used this `enqueue_read` method with a `DistributedHostBuffer::shard_coords()` argument, which is defined as returning a `std::set`.  Using it as the argument to this method seemed like the convenient thing to do, so I had to either change this argument to be a `std::set` or change that return type to be a `std::unordered_set`. There were only a couple of places in code that use this method, and those places pass in `std::nullopt` for this argument. `DistributedHostBuffer::shard_coords()` on the other is used more extensively in the code. So changing the argument type of this method to `std::set` was the lesser change. But now, the test I wrote no longer uses distributed host buffers and we can revert this change. I left it in because from experience this type seems more usable.

File: ttnn/api/ttnn/tensor/tensor_impl.hpp [hunk 6]
```diff
@@ -223,8 +223,6 @@ Tensor unpad(const Tensor& tensor, const ttnn::Shape& output_tensor_start, const
 //                                         Print
 // ======================================================================================
 
-std::ostream& operator<<(std::ostream& os, const DataType& dtype);
```
Comment (jbaumanTT) [inline ttnn/api/ttnn/tensor/tensor_impl.hpp]: Why remove this code?

File: tests/tt_metal/distributed/test_large_mesh_buffer.cpp [hunk 7]
```diff
@@ -0,0 +1,397 @@
...
+        shard_shape,
+        page_shape,
+        page_size >> 10,
+        reflect::enum_name(tensor_layout));
+
+    uint32_t device_rows = mesh_device_->num_rows();
+    uint32_t device_cols = mesh_device_->num_cols();
+    uint32_t num_devices = device_rows * device_cols;
+    uint64_t tensor_size = num_devices * device_tensor_size;
+#if 0
```
Comment (jbaumanTT) [inline tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: Remove?

File: ttnn/api/ttnn/tensor/tensor_impl.hpp (hunk 6 above)
Comment (mpiseTT) [reply ttnn/api/ttnn/tensor/tensor_impl.hpp]: I had added a bunch of `std::out << ` to understand the callflow in `tensor_impl.cpp`, and this was flagged by the compiler as a redefinition of the same function somewhere else. Now I don't remember, but I just searched the codebase and found a definition in ttnn/core/tensor/types.cpp line 10, which must have been it. It is not necessary for this PR, but since I found an issue, I kept the fix in.

**Review by jbaumanTT — APPROVED** [review]

**Review by nhuang-tt — APPROVED** [review]

File: .github/workflows/t3000-unit-tests-impl.yaml [hunk 8]
```diff
@@ -23,7 +23,7 @@ jobs:
       fail-fast: false
       matrix:
         test-group: [
-          { name: "t3k ttmetal tests", arch: wormhole_b0, cmd: run_t3000_ttmetal_tests, timeout: 35, owner_id: ULMEPM2MA}, #Sean Nijjar
+          { name: "t3k ttmetal tests", arch: wormhole_b0, cmd: run_t3000_ttmetal_tests, timeout: 120, owner_id: ULMEPM2MA}, #Sean Nijjar
```
Comment (ttmchiou) [inline .github/workflows/t3000-unit-tests-impl.yaml]: whoa, this is a massive increase to t3k unit test timeouts.
What are we adding that requires a 1.5 hours of extra testing?

This should be moved to nightly or frequent if tests run this long

Comment (ttmchiou) [reply .github/workflows/t3000-unit-tests-impl.yaml]: @mpiseTT please provide a test run in CI explaining such a drastic increase.

File: tt_metal/api/tt-metalium/mesh_command_queue.hpp (hunk 3 above)
Comment (omilyutin-tt) [reply tt_metal/api/tt-metalium/mesh_command_queue.hpp]: > An earlier version of the distributed host buffer + mesh buffer

Do you use this anywhere now? I would change this back, this is not intended to be used with `shard_coords()`. There is a look up in this second map, which is algorithmically slower than unordered set

File: ttnn/api/ttnn/tensor/tensor_impl.hpp (hunk 6 above)
Comment (omilyutin-tt) [reply ttnn/api/ttnn/tensor/tensor_impl.hpp]: I don't get it - is this dead code? How does your temporary `std::out << ` affect this?

File: tt_metal/impl/data_format/bfloat16.cpp [hunk 9]
```diff
@@ -114,11 +114,11 @@ void print_golden_metalium_vectors(std::vector<bfloat16>& golden_vec, std::vecto
 }
 
 std::vector<std::uint32_t> create_random_vector_of_bfloat16(
-    uint32_t num_bytes, int rand_max_float, int seed, float offset) {
+    size_t num_bytes, int rand_max_float, int seed, float offset) {
     auto rand_float = std::bind(std::uniform_real_distribution<float>(0, rand_max_float), std::mt19937(seed));
 
     std::vector<std::uint32_t> vec(num_bytes / sizeof(std::uint32_t), 0);
-    for (int i = 0; i < vec.size(); i++) {
+    for (auto i = 0; i < vec.size(); i++) {
```
Comment (omilyutin-tt) [inline tt_metal/impl/data_format/bfloat16.cpp]: When you say `auto i = 0;`, `auto` is `int`. What is the goal of this change here?

**Review by omilyutin-tt — CHANGES_REQUESTED** [review]
Trying to understand the purpose of some diffs in this PR

File: tt_metal/impl/data_format/bfloat16.cpp (hunk 9 above)
Comment (mpiseTT) [reply tt_metal/impl/data_format/bfloat16.cpp]: dang, you are right! I intended for it to be the type of `vec.size()`!

File: ttnn/api/ttnn/tensor/tensor_impl.hpp (hunk 6 above)
Comment (mpiseTT) [reply ttnn/api/ttnn/tensor/tensor_impl.hpp]: It is not dead code. If you try to use this overload, the compiler might complain that this function was redefined or it is ambiguous whether to use this or the one in `types.cpp` (I think the compiler error must have been "redefined" because both places the signature is the same).

Thanks for the offline discussion. I'll revert this here and propose this with a new "cleanup" PR next week.

File: .github/workflows/t3000-unit-tests-impl.yaml (hunk 8 above)
Comment (mpiseTT) [reply .github/workflows/t3000-unit-tests-impl.yaml]: I am working with @roseli-TT for this one. We estimated from testing that the timeout needs to be 45 mins for the new tests I added in `tests/tt_metal/distributed/test_large_mesh_buffer.cpp`, however with 45 it still timed out. I've restarted the T3000 unit tests and will measure how much would be a suitable increase (with some modest margin).
Btw, most of the time in this test goes to initializing a 12 GB size random vector (see `tests/tt_metal/distributed/test_large_mesh_buffer.cpp` lines 54-55). This is initialized just once for all the tests in this file. A desirable change maybe to have a once initialized large random vector globally available for any test that needs random vector (can take requisite slices from the global random vector). That might save a lot of time across several tests, but out of the scope of this PR.

Comment (mpiseTT) [reply .github/workflows/t3000-unit-tests-impl.yaml]: The measurement test run to finalize this number is here: https://github.com/tenstorrent/tt-metal/actions/runs/17335477441.

Earlier with @roseli-TT 's help we had measured the new tests would add about 8 mins (this: https://github.com/tenstorrent/tt-metal/actions/runs/17302943632), based on which originally we changed the timeout from 35 to 45 mins. However, that was inadequate (failed run with 45 here: https://github.com/tenstorrent/tt-metal/actions/runs/17331525196/job/49209109175)

File: ttnn/api/ttnn/tensor/tensor_impl.hpp (hunk 6 above)
Comment (mpiseTT) [reply ttnn/api/ttnn/tensor/tensor_impl.hpp]: This change was reverted. Will readd with a new "cleanup" PR.

File: tt_metal/api/tt-metalium/mesh_command_queue.hpp (hunk 3 above)
Comment (mpiseTT) [reply tt_metal/api/tt-metalium/mesh_command_queue.hpp]: This change is reverted

File: .github/workflows/t3000-unit-tests-impl.yaml (hunk 8 above)
Comment (mpiseTT) [reply .github/workflows/t3000-unit-tests-impl.yaml]: The T3000 unit tests completed in 40 mins this time. There seems to be run to run timing variation, which perhaps needs its own separate investigation. I've changed this timeout to 60 mins now, which should be high enough to ensure no timeout yet it is not too loose a bound.

**Review by omilyutin-tt — APPROVED** [review]

File: .github/workflows/t3000-unit-tests-impl.yaml [hunk 10]
```diff
@@ -23,7 +23,7 @@ jobs:
       fail-fast: false
       matrix:
         test-group: [
-          { name: "t3k ttmetal tests", arch: wormhole_b0, cmd: run_t3000_ttmetal_tests, timeout: 35, owner_id: ULMEPM2MA}, #Sean Nijjar
+          { name: "t3k ttmetal tests", arch: wormhole_b0, cmd: run_t3000_ttmetal_tests, timeout: 60, owner_id: ULMEPM2MA}, #Sean Nijjar
```
Comment (tt-rkim) [inline .github/workflows/t3000-unit-tests-impl.yaml]: What? 35 -> 60?

Comment (mpiseTT) [reply .github/workflows/t3000-unit-tests-impl.yaml]: We think 45 mins should be adequate most of the times, but with that timeout 1 out of 1 run of ttmetal tests failed. Based on measurement of just the added tests, we thought we need an extra 8 mins, so 45 should've been adequate. 50 mins might work an acceptably high percentage of times, but I skipped that step! I figured 60 is definitely loose enough without being really too much (requirement is 45 < x <= 60).
Also ref convo on same topic with @ttmchiou above https://github.com/tenstorrent/tt-metal/pull/26571#discussion_r2311528673

File: .github/workflows/t3000-unit-tests-impl.yaml (hunk 8 above)
Comment (ttmchiou) [reply .github/workflows/t3000-unit-tests-impl.yaml]: I think this is an extremely strong argument for running in t3k frequent or nightly.
In theory, unit tests should be running on the order of under a minute or two.

If we have every following PR for t3k unit tests workflow necessitating a 15 minute increase in unit tests, our workflow would blow up.

Currently our T3K unit test workflow takes just shy of 1 hr (55min) and 36m of which is for t3k unit tests test suite assuming there is no queue.

Adding this battery of tests which requires an extra 25 minutes of CI time compounded by the high frequency that this workflow runs a lot means a very significant increase in feedback for devs to finish their CI runs.

Suggestions:
I would argue that CI time always falls in the scope of any dev's PR.
Would suggest looking into caching this large 12 GB random vector.
Move this test into t3k frequent/nightly.


I'd also look into the variable runtime. Why is this the case? is it bounded by device limitations? all Runners should have the same compute resources.

**Review by bbradelTT — APPROVED** [review]

File: .github/workflows/t3000-unit-tests-impl.yaml (hunk 8 above)
Comment (mpiseTT) [reply .github/workflows/t3000-unit-tests-impl.yaml]: The 12 GB vector is generated just once and subsequently reused for all 24 tests. I'll move this into nightly, makes sense.

**Review by tt-rkim — APPROVED** [review]

File: tests/tt_metal/distributed/test_large_mesh_buffer.cpp [hunk 11]
```diff
@@ -0,0 +1,380 @@
...
+
+    // Create test data - use uint16_t for easy verification
+    auto num_elements = tensor_size / ElementSize;
+    ASSERT_TRUE(num_elements <= max_num_elements_);
+    std::vector<ElementType> src_vec(src_vec_.begin(), src_vec_.begin() + num_elements);
+
+    distributed::MeshCoordinateRange coord_range(mesh_device_->shape());
+    std::vector<MeshCommandQueue::ShardDataTransfer> input_shards = {};
+    for (auto& coord : coord_range) {
+        input_shards.push_back({coord, src_vec.data()});
```
Comment (amahmudTT) [inline tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: Please reserve first before pushing back to avoid exponential overhead of recopying. General comment.

File: tests/tt_metal/distributed/test_large_mesh_buffer.cpp [hunk 12]
```diff
@@ -0,0 +1,380 @@
...
+    constexpr auto tile_height{constants::TILE_HEIGHT};
+    constexpr auto tile_width{constants::TILE_WIDTH};
+    constexpr auto tile_area{tile_height * tile_width};
+    // Ensure buffer dimensions are divisible by tile dimensions
+    ASSERT_TRUE(device_tensor_shape.height() % tile_height == 0);
+    ASSERT_TRUE(device_tensor_shape.width() % tile_width == 0);
+
+    auto test_helper_factor_area = [](uint32_t area, int32_t& height, int32_t& width) {
+        // Find all factors of area
+        std::vector<uint32_t> factors{1};
```
Comment (amahmudTT) [inline tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: Same as above.

**Comment by mpiseTT** [comment]
I made a mistake actually in claiming that the tests are moved out of t3000 unit tests - they are not. I've only added them to nightly. I've disabled auto merge until I fix it. @ttmchiou @tt-rkim

File: tests/tt_metal/distributed/test_large_mesh_buffer.cpp (hunk 12 above)
Comment (mpiseTT) [reply tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: This lambda is finding number of factors, which are not known at the beginning. Also, pushing back integers, which is fast. So please reconsider this request.

Comment (amahmudTT) [reply tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: There are multiple cases , I made a general comment. Are all of them like this ?

Comment (mpiseTT) [reply tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: The other place you commented, it is pushing a structure, but not a big one, not many of them (number of devices on which this test will run), and this is a test file, so I took care of the really blatant item (the one time creation and initialization of the large data vector) but these places I did the convenient thing. This imho will barely move the needle if at all.

Comment (amahmudTT) [reply tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: I meant there are other places in the code where i did not comment and vectors are pushed back into, hence I mentioned it is a general comment. If they do not matter it is fine.

Comment (amahmudTT) [reply tests/tt_metal/distributed/test_large_mesh_buffer.cpp]: Anyway resolving in advance. And approving.

**Review by amahmudTT — APPROVED** [review]

**Comment by mpiseTT** [comment]
> I made a mistake actually in claiming that the tests are moved out of t3000 unit tests - they are not. I've only added them to nightly. I've disabled auto merge until I fix it. @ttmchiou @tt-rkim

In the last push I properly addressed this. Now the new large buffer tests are in `unit_tests_dispatch_slow`. The new tests only were added to t3000 nightly testing yaml.

**Review by abhullar-tt — APPROVED** [review]
