### PR TITLE
0D, 1D and 0 volume support for argmax

### LINKED ISSUE #16720: argmax returns incorrect shape
Run pytest
```
import pytest

import torch

import ttnn
from tests.ttnn.utils_for_testing import assert_with_pcc
from models.utility_functions import torch_random


@pytest.mark.parametrize("batch_size", [1, 32])
@pytest.mark.parametrize("h", [32])
@pytest.mark.parametrize("w", [64000])
@pytest.mark.parametrize("dim", [-1])
def test_argmax(device, batch_size, h, w, dim):

    torch.manual_seed(0)


    torch_input_tensor = torch.randn((1, 1, h, w), dtype=torch.bfloat16)
    torch_output_tensor = torch.argmax(torch_input_tensor, dim=3)
    input_tensor = ttnn.from_torch(torch_input_tensor, device=device)
    output_tensor = ttnn.argmax(input_tensor, dim=3, use_multicore=False if batch_size > 1 else True)
    output_tensor = ttnn.to_torch(output_tensor)
    assert_with_pcc(torch_output_tensor, output_tensor)
```

Expected:
- Everything passes

Actual:
```
FAILED test_argmax.py::test_argmax[-1-64000-32-1] - AssertionError: list(expected_pytorch_result.shape)=[1, 1, 32] vs list(actual_pytorch_result.shape)=[1, 1, 1, 32]
FAILED test_argmax.py::test_argmax[-1-64000-32-32] - AssertionError: list(expected_pytorch_result.shape)=[1, 1, 32] vs list(actual_pytorch_result.shape)=[1, 1, 1, 32]
```

Adding in a reshape fixes the problem, but argmax should set the shapes properly by itself.

### LINKED ISSUE #16986: argmax returns incorrect shape when no dim specified
Needs to be split off from https://github.com/tenstorrent/tt-metal/issues/16720

Reproduce:
add None to dim in tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_argmax_int.py and run pytest

Expected:
the shape for None should be []

Actual:
the shape for None is [1,1,1,1] instead of []

Blocked by 0 rank and 0D/1D tensor work.

### PR DESCRIPTION
**Pull request by nsorabaTT**
### Ticket
This PR addresses the following issues:
https://github.com/tenstorrent/tt-metal/issues/16986
https://github.com/tenstorrent/tt-metal/issues/16720
https://github.com/tenstorrent/tt-metal/issues/19576

### Problem description
This PR addresses 3 key shortcomings in the existing argmax implementation:
1. `keepdim`
To ensure torch compatibility, we need to drop the reduction dimension from the output shape by default. An optional parameter `keepdim` (false by default) can be set if the reduction dimension is to be retained in the output.
**NOTE**: The current argmax implementation does not have this option and the implementation is equivalent to keeping `keepdim` true. In that sense, it is a breaking change.

2. 0D, 1D, 0V inputs
This PR adds logic to handle argmax where the rank of the tensor < 2 or when one of the input dimension is 0.

3. Remove assumption of Rank 4 tensor
To pave way for rank 2 and rank 3 support in future PRs, this one also simplifies how all dimensions except the reduction dimension in handled and treated in the argmax device kernel. Specifically, we move to a rank independent implementation that can be extended to other ranks in future.

#### Summary

| Rank | All dims supported | Matches Torch?  |  0 volume supported  | Shape requirement |
|------|--------------------|------------------|----------------------|---------------------|
|    0    |                Y                |               Y             |           Y                        |           None              |
|    1    |                Y                |                Y             |           Y                        |           None              |
|    2    |               N                |                Y             |           Y                        |           [1, 1]               |
|    3   |                N                |                Y            |            Y                        |           [1, X, Y]          |
|    4   |                N                |                Y             |            Y                       |          [1, 1, X, Y]      |

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) [CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/14316052291)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [x] New/Existing tests provide coverage for changes (Sweeps added)

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/reduction/argmax/device/kernels/reader_argmax_interleaved.cpp [hunk 1]
```diff
@@ -7,66 +7,66 @@
 #include "dataflow_api.h"
 #include "utils/bfloat16.h"
 
+#define NEG_INF_BFLOAT16 0xFF80  // Representation of negative infinity in bfloat16
```
Comment (nsorabaTT) [inline ttnn/cpp/ttnn/operations/reduction/argmax/device/kernels/reader_argmax_interleaved.cpp:10]: We need to find a good home for this define, since there is a use case for its reuse. Current candidate:
`tt_metal/hw/inc/utils/bfloat16.h`

**Review by jdesousa-TT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/reduction/argmax/device/argmax_op.cpp [hunk 2]
```diff
@@ -44,8 +81,11 @@ void ArgMax::validate_with_output_tensors(
     }
 
     auto input_shape = input_tensor_a.get_padded_shape();
-    TT_FATAL(input_shape[0] == 1, "dim 0 must be 1");
-    TT_FATAL(input_shape[1] == 1, "dim 1 must be 1");
+    auto rank = input_shape.rank();
+
+    // This is a limitation in the present implementation
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/reduction/argmax/device/argmax_op.cpp:86]: if torch supports this and we don't have an issue yet, please create an issue.

**Review by bbradelTT — APPROVED** [review]

**Review by vsureshTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/reduction/argmax/device/argmax_op.cpp (hunk 2 above)
Comment (nsorabaTT) [reply ttnn/cpp/ttnn/operations/reduction/argmax/device/argmax_op.cpp:86]: Covered by an existing issue: https://github.com/tenstorrent/tt-metal/issues/18241
