### PR TITLE
ttnn round op fix

### LINKED ISSUE #22209: ttnn round args mismatches with torch round args
### Describe the bug

The current implementation of ttnn.round requires the decimal parameter to be explicitly provided

### Steps to reproduce the issue

```
import torch
import ttnn

x = torch.tensor([1.2345, 2.5678])
torch.round(x)            # Works without `decimal`
ttnn.round(x)             # Throws error: missing required argument `decimal`
```

### Expected behavior

both should work

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by Aswinmcw**
### Ticket
#22209 

### Problem description
ttnn round op requires decimal parameter to be provided

### What's changed
Make argument as optional and add test case for it

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
https://github.com/tenstorrent/tt-metal/actions/runs/15177790951
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
https://github.com/tenstorrent/tt-metal/actions/runs/15177789893
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp [hunk 1]
```diff
@@ -568,7 +568,7 @@ void bind_unary_operation_with_int_parameter(
                 return self(queue_id, input_tensor, parameter, memory_config, output_tensor);
             },
             py::arg("input_tensor"),
-            py::arg(parameter_name.c_str()),
+            py::arg(parameter_name.c_str()) = 0,
```
Comment (KalaivaniMCW) [inline ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp:571]: should be a kwarg decimals=0,

Comment (KalaivaniMCW) [reply ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp:571]: below py::kw_only(),

Comment (Aswinmcw) [reply ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp:571]: if it is keyword argument, it expects like ttnn.round(tensor, decimal=1), instead of ttnn.round(tensor, 1)

**Review by KalaivaniMCW — APPROVED** [review]

File: tests/ttnn/unit_tests/operations/eltwise/test_round.py [hunk 2]
```diff
@@ -19,7 +19,7 @@
         torch.Size([1, 3, 320, 384]),
     ),
 )
-@pytest.mark.parametrize("decimal", [-3, 6, -1])
+@pytest.mark.parametrize("decimal", [-3, 6, -1, ""])
```
Comment (fvranicTT) [inline tests/ttnn/unit_tests/operations/eltwise/test_round.py:22]: You could pass None instead of an empty string. It's a more Pythonic way of handling absence of value.
In that case, the below code would be:

```python
if decimal is None:  # Check for None instead of ""
    torch_output_tensor = golden_function(torch_input_tensor)
    output_tensor = ttnn.round(input_tensor)
else:
    torch_output_tensor = golden_function(torch_input_tensor, decimals=decimal)
    output_tensor = ttnn.round(input_tensor, decimals=decimal)
```

File: ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp [hunk 3]
```diff
@@ -568,8 +568,8 @@ void bind_unary_operation_with_int_parameter(
                 return self(queue_id, input_tensor, parameter, memory_config, output_tensor);
             },
             py::arg("input_tensor"),
-            py::arg(parameter_name.c_str()),
             py::kw_only(),
+            py::arg(parameter_name.c_str()) = 0,
```
Comment (fvranicTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.hpp:572]: how about making parameter optional instead?

**Review by VirdhatchaniKN — APPROVED** [review]

**Review by mcw-anasuya — APPROVED** [review]

**Review by patrickroberts — APPROVED** [review]

**Review by omilyutin-tt — APPROVED** [review]

**Review by dchenTT — APPROVED** [review]
