### PR TITLE
#33250: Add missing ops to docs.

### LINKED ISSUE #23507: Online documentation is missing for certain OPs
Enumerate all ttnn OPs that are missing any entires in the online documentation.
https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api.html#operations

Off hand, bcast isn't documented.

Should experimental OPs be documented?

Moreh OPs should be removed.

### LINKED ISSUE #30274: HTML documentation of some ttnn API functions is missing
### Describe the documentation issue

Some functions in the ttnn API are missing from the https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api.html page. Such functions are mentioned and used elsewhere, (e.g. in the [AdvancedPerformanceOptimizationsForModels](https://github.com/tenstorrent/tt-metal/blob/main/tech_reports/AdvancedPerformanceOptimizationsForModels/AdvancedPerformanceOptimizationsForModels.md) technical report). A non-exhaustive list of such functions is as follows:
- `ttnn.record_event`
- `ttnn.wait_for_event`
- `ttnn.allocate_tensor_on_device`
- `ttnn.copy_host_tensor_to_device`

### Describe the documentation solution you want to see

The API reference page should contain documentation for these functions, and they should be present in the function list in the navigation sidebar.

### Describe the diagrams or screenshots (if any) that the documentation should have

_No response_

### LINKED ISSUE #33250: Add missing ops to docs
### Problem

Many existing TTNN operations are missing from the documentation. They do not appear on the operations list at [https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api.html#operations](https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api.html#operations), and they also lack example entries in `examples_mapping.py`.

### Task

Conduct an audit to identify all TTNN operations that exist in the codebase but are not included in the documentation. Add the missing operations to the appropriate sections in `api.rst` so they appear on the docs site. For each operation, also provide example usage and include it in `examples_mapping.py`.

Example python script to:

```python
#!/usr/bin/env python3
"""
Script to find operations that are missing from docs/source/ttnn/ttnn/api.rst
compared to what's registered in ttnn.query_registered_operations()
"""

import ttnn
from pathlib import Path

def get_registered_operations():
    """Get all registered operations from ttnn.query_registered_operations()"""
    registered_ops = set()
    
    all_ops = ttnn.query_registered_operations()
    for op in all_ops:
        registered_ops.add(op.python_fully_qualified_name)
    
    return registered_ops

def extract_ops_from_api_rst(api_rst_path):
    """Extract all ttnn operations from api.rst file by checking each line"""
    api_ops = set()
    
    with open(api_rst_path, 'r') as f:
        for line in f:
            # Remove leading and trailing spaces
            stripped_line = line.strip()
            
            # Check if the line starts with ttnn. (after stripping)
            if stripped_line.startswith('ttnn.'):
                api_ops.add(stripped_line)
    
    return api_ops

def find_missing_operations():
    """Main function to find operations missing from api.rst"""
    
    # Define file path
    script_dir = Path(__file__).parent
    api_rst_path = script_dir / "docs/source/ttnn/ttnn/api.rst"
    
    # Check if file exists
    if not api_rst_path.exists():
        print(f"Error: Could not find api.rst at {api_rst_path}")
        return
    
    print("Analyzing operations...")
    print("=" * 60)
    
    # Get registered operations from ttnn
    print("Getting registered operations from ttnn...")
    registered_ops = get_registered_operations()
    
    # Extract operations from api.rst
    print("Extracting operations from api.rst...")
    api_ops = extract_ops_from_api_rst(api_rst_path)
    
    print(f"Registered operations in ttnn: {len(registered_ops)}")
    print(f"Operations found in api.rst: {len(api_ops)}")
    print()
    
    # Find operations that are registered but missing from api.rst
    # For each registered operation, check if it exists in api_ops
    missing_ops = set()
    for registered_op in registered_ops:
        if registered_op not in api_ops:
            missing_ops.add(registered_op)
    
    if missing_ops:
        print(f"Operations missing from api.rst ({len(missing_ops)}):")
        print("-" * 40)
        for op in sorted(missing_ops):
            print(f"  {op}")
        print()
    else:
        print("✅ All registered operations are documented in api.rst!")
    
    # Also show operations that are in api.rst but not registered
    extra_ops = api_ops - registered_ops
    if extra_ops:
        print(f"Operations in api.rst but not registered ({len(extra_ops)}):")
        print("-" * 40)
        for op in sorted(extra_ops):
            print(f"  {op}")
        print()
    
    # Show some statistics
    print("Summary:")
    print(f"  Total registered operations: {len(registered_ops)}")
    print(f"  Total operations in api.rst: {len(api_ops)}")
    print(f"  Missing from api.rst: {len(missing_ops)}")
    print(f"  Extra in api.rst: {len(extra_ops)}")
    print(f"  Common operations: {len(api_ops & registered_ops)}")
    
    # Save detailed results to a file
    output_file = script_dir / "missing_operations_report.txt"
    with open(output_file, 'w') as f:
        f.write("TTNN Operations Analysis Report\n")
        f.write("=" * 50 + "\n\n")
        
        f.write(f"Analysis Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"API RST file: {api_rst_path}\n")
        f.write(f"Source: ttnn.query_registered_operations()\n\n")
        
        f.write("SUMMARY:\n")
        f.write(f"  Total registered operations: {len(registered_ops)}\n")
        f.write(f"  Total operations in api.rst: {len(api_ops)}\n")
        f.write(f"  Missing from api.rst: {len(missing_ops)}\n")
        f.write(f"  Extra in api.rst: {len(extra_ops)}\n")
        f.write(f"  Common operations: {len(api_ops & registered_ops)}\n\n")
        
        if missing_ops:
            f.write(f"OPERATIONS MISSING FROM API.RST ({len(missing_ops)}):\n")
            f.write("-" * 50 + "\n")
            for op in sorted(missing_ops):
                f.write(f"  {op}\n")
            f.write("\n")
        
        if extra_ops:
            f.write(f"OPERATIONS IN API.RST BUT NOT REGISTERED ({len(extra_ops)}):\n")
            f.write("-" * 50 + "\n")
            for op in sorted(extra_ops):
                f.write(f"  {op}\n")
            f.write("\n")
        
        # Show all registered operations for reference
        f.write("ALL REGISTERED OPERATIONS:\n")
        f.write("-" * 50 + "\n")
        for op in sorted(registered_ops):
            f.write(f"  {op}\n")
    
    print(f"\n📝 Detailed report saved to: {output_file}")

if __name__ == "__main__":
    find_missing_operations()
```

### PR DESCRIPTION
**Pull request by mgajewskiTT**
### Ticket

#33250
Also solving: #30274, #23507

### Problem description
Many existing TTNN operations are missing from the documentation. They do not appear on the operations list at https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api.html#operations, and they also lack example entries in `examples_mapping.py`.

### What's changed
- Compared list of operations from `ttnn.query_registered_operations()` and in `api.rst`,
- Added missing OPs to `api.rst` file,
- Corrected bindings of operations that caused docs crash,
- Updated document https://docs.google.com/spreadsheets/d/1Z3nduLHMEJqLs2VveyULptdOAaaLlbKnhD-U4sgISu8/edit?usp=sharing,
- Sorted operations alphabetically,

Note: Skipped all experimental and Moreh operations.

### Next steps

- Create tickets for individual teams based on findings from spreadsheet under #32364 - Done, ready to assign,
- Add check to pipeline (preferably `.pre-commit-config.yaml`) to check if new OP was added and is not in docs for new operations. #34667

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes https://github.com/tenstorrent/tt-metal/actions/runs/20333850243

### CODE REVIEW

**Review by gwangTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/reduction/sampling/sampling_nanobind.cpp [hunk 1]
```diff
@@ -19,28 +19,28 @@ namespace ttnn::operations::reduction::detail {
...
-          Currently, this operation supports inputs and outputs with specific memory layout and data type constraints.
+        Currently, this operation supports inputs and outputs with specific memory layout and data type constraints.
 
-          Equivalent PyTorch code:
-              .. code-block:: python
+        Equivalent PyTorch code:
+            .. code-block:: python
 
-                  return torch.sampling(
+               return torch.sampling(
```
[the remark this answers is not in the document]
Comment (mgajewskiTT) [reply ttnn/cpp/ttnn/operations/reduction/sampling/sampling_nanobind.cpp:43]: Examples will be removed from bindings to files.

File: docs/source/ttnn/ttnn/api.rst [hunk 2]
```diff
@@ -560,9 +641,22 @@ Pooling
    :nosignatures:
    :template: function.rst
 
+   ttnn.adaptive_avg_pool2d
+   ttnn.adaptive_max_pool2d
+   ttnn.avg_pool2d
    ttnn.global_avg_pool2d
+   ttnn.grid_sample
```
[the remark this answers is not in the document]
Comment (mgajewskiTT) [reply docs/source/ttnn/ttnn/api.rst]: Grouping is based on file placement in tt-metal.

**Review by dchenTT — APPROVED** [review]

**Review by dstoiljkovicTT — APPROVED** [review]

File: docs/source/ttnn/ttnn/api.rst (hunk 2 above)
Comment (dstoiljkovicTT) [inline docs/source/ttnn/ttnn/api.rst]: Might be good idea to put grid_sample right beside upsample op in the Vision section since it is not a pool op

File: docs/source/ttnn/ttnn/api.rst
Comment (ayerofieiev-tt) [inline docs/source/ttnn/ttnn/api.rst:1]: I wish all bw ops were grouped together somewhere in the bottom.
Not ops we are most proud about :)

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by edwinleeTT — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]

File: docs/source/ttnn/ttnn/api.rst (hunk 2 above)
Comment (mgajewskiTT) [reply docs/source/ttnn/ttnn/api.rst]: Good point! Changed.

File: docs/source/ttnn/ttnn/api.rst
Comment (mgajewskiTT) [reply docs/source/ttnn/ttnn/api.rst:1]: You ask and you have it :) All `_bw` operations got their own section at the bottom.

**Review by ntarafdar — APPROVED** [review]
