### PR TITLE
#38711: Update pack_scalar_runtime_arg

### LINKED ISSUE #38711: addcmul scalar bit-cast bug: integer value treated as float bit-pattern for bfloat16/float32 tensors
### Nightly CI failure
https://github.com/tenstorrent/tt-metal/actions/runs/22430389826

Failing tests:
- `test_composite.py::test_run_eltwise_composite_test[addcmul-input_shapes2]` (wormhole_b0 N150)
- `test_composite.py::test_run_eltwise_composite_test[addcmul-input_shapes4]` (blackhole P150, N300)

### Root cause
PR #38011 ("Add int32 support for addcmul") changed the `value` parameter from `float` to `ScalarVariant` (`std::variant<float, int32_t, uint32_t>`). This causes two interacting problems:

1. **Nanobind overload resolution change**: Before #38011, Python `int` was auto-converted to `float`. Now nanobind matches Python `int` to the `int32_t` variant alternative.

2. **Incorrect scalar packing for float tensors**: In `pack_scalar_runtime_arg()` at `ttnn/cpp/ttnn/operations/eltwise/ternary/device/ternary_op_utils.cpp:341`, the `int32_t`/`uint32_t` branch does `std::bit_cast<uint32_t>(v)` regardless of the output tensor dtype. When tensors are bfloat16/float32, the SFPU kernel interprets these bits as a float. So integer `42` (`0x0000002A`) becomes ~`5.88e-44` (essentially zero), making the result degenerate to `output ≈ input_a` instead of `input_a + 42 * input_b * input_c`.

This explains the PCC of 0.41 — the result is just `input_a` correlated against the full formula.

### Suggested fix
In `pack_scalar_runtime_arg`, when the output dtype is floating-point, convert the integer scalar to float before bit-casting:

```cpp
if (dtype != DataType::INT32 && dtype != DataType::UINT32) {
    return std::bit_cast<uint32_t>(static_cast<float>(v));
}
return std::bit_cast<uint32_t>(v);
```

### PR DESCRIPTION
**Pull request by mouliraj-mcw**
### Ticket
Link to Github Issue #38711 

### What's changed
Fix addcmul scalar bit-cast bug by converting integer scalars to float when packing for float/bfloat16 tensors (ternary and unary), and add addcmul dtype checks so only BFLOAT16, FLOAT32, INT32, and BFLOAT8_B are allowed.
### Checklist

- [ ] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml?query=branch:mouliraj/bit-cast_bug)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:mouliraj/bit-cast_bug)
- [ ] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:mouliraj/bit-cast_bug)
- [ ] New/Existing tests provide coverage for changes
- [ ] (Optional) Ran [clang-tidy code analysis](https://github.com/tenstorrent/tt-metal/actions/workflows/code-analysis.yaml) on the PR branch to catch linting errors early

#### Model tests

If your changes cover model-related code, you should run tests corresponding to affected models and platforms (Single card, T3K, Galaxy). "Choose your pipeline" workflows facilitate running multiple kinds of tests in a single run. Each offers `models-mandatory` and `models-extended` presets.
The former includes a minimal set of tests, to be run always. The latter extends that with additional ones - use your best judgement in deciding which is the most appropriate for your PR.

- [ ] [(Single) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:mouliraj/bit-cast_bug)
  - [ ] `models-mandatory` preset (runs: [Device perf regressions](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) and [Frequent model and ttnn tests](https://github.com/tenstorrent/tt-metal/actions/workflows/fast-dispatch-full-regressions-and-models.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(T3K) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:mouliraj/bit-cast_bug)
  - [ ] `models-mandatory` preset (runs: [Unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-model-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

- [ ] [(Galaxy) Choose your pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:mouliraj/bit-cast_bug)
  - [ ] `models-mandatory` preset (runs: [Quick tests](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml))
  - [ ] `models-extended` preset (runs: the mandatory tests, plus [Demo](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) and [Model perf](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-perf-tests.yaml) tests)
  - [ ] other selection - specify runs

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/eltwise/unary/common/unary_op_utils.cpp [hunk 1]
```diff
@@ -1011,10 +1011,18 @@ std::uint32_t pack_scalar_runtime_arg_impl(float param, DataType dtype) {
     return std::bit_cast<std::uint32_t>(param);
 }
 
-std::uint32_t pack_scalar_runtime_arg_impl(std::uint32_t param, DataType /*dtype*/) { return param; }
+std::uint32_t pack_scalar_runtime_arg_impl(std::uint32_t param, DataType dtype) {
```
Comment (KalaivaniMCW) [inline ttnn/cpp/ttnn/operations/eltwise/unary/common/unary_op_utils.cpp:1017]: could you add one test case covering this change ?

**Review by KalaivaniMCW — APPROVED** [review]

File: tests/ttnn/unit_tests/operations/eltwise/test_unary.py [hunk 2]
```diff
@@ -1077,7 +1077,7 @@ def test_unary_atanh_ttnn(input_shapes, torch_dtype, ttnn_dtype, low, high, devi
 )
 @pytest.mark.parametrize(
     "param",
-    (0.65, 7.7, 36.49, 58.6, 97.2),
```
Comment (mateusznowakTT) [inline tests/ttnn/unit_tests/operations/eltwise/test_unary.py:1080]: Why change here? Seems unrelated.

Comment (mouliraj-mcw) [reply tests/ttnn/unit_tests/operations/eltwise/test_unary.py:1080]: Just to verify float tensors with integer scalars, instead of introducing two new values, I modified the float value to an integer.

**Review by mateusznowakTT — APPROVED** [review]
