### PR TITLE
[DM] Fix noc_inline_dw_write_with_state issue and add DM tests to cover it

### LINKED ISSUE #26532: [DM] Add tests for inline dw APIs
Need to add data movement tests for stateful and stateless inline direct write APIs:

- `noc_inline_dw_write`
- `noc_inline_dw_write_set_state`
- `noc_inline_dw_write_with_state`

fyi @vvukomanovicTT

### PR DESCRIPTION
**Pull request by nstamatovicTT**
### Ticket
[Github Issue](https://github.com/orgs/tenstorrent/projects/135/views/10?pane=issue&itemId=123522028&issue=tenstorrent%7Ctt-metal%7C26532)

### Problem description
In `noc_inline_dw_write_with_state`, the `NOC_AT_LEN_BE` register was not being updated. As a result, in certain scenarios, the actual write address differed from the one provided as a method parameter.

### What's changed
**This is a reopened PR because the [previous one](https://github.com/tenstorrent/tt-metal/pull/27905) failed the APC after merging.**

I've added the fix in both blackhole and wormhole. However, as mentioned in the [docs](https://github.com/tenstorrent/tt-isa-documentation/blob/main/BlackholeA0/NoC/MemoryMap.md), on blackhole, this call should be avoided. The fix consists of updating the `NOC_AT_LEN_BE` every time both `update_addr_lo` and `update_be_on_addr_lo` are set. This is done this way because the fabric team is changing the lower part of the address but the offset stays the same. To make sure they don't lose performance on the unnecessary register writes, we added `update_be_on_addr_lo ` which can be disabled if needed. The `NOC_AT_LEN_BE` is updated with the corresponding mask, which is calculated based on the last 5 bits of the address. See [documentation](https://github.com/tenstorrent/tt-isa-documentation/blob/main/WormholeB0/NoC/MemoryMap.md#noc_at_len_be).
I've also added the data movement tests for this api.

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes [results](https://github.com/tenstorrent/tt-metal/actions/runs/19033730995)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [x] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [x] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [x] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml) CI passes (if applicable)
- [ ] [Galaxy demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by jbaumanTT — APPROVED** [review]

**Review by mpiseTT — APPROVED** [review]

File: tests/tt_metal/tt_metal/data_movement/direct_write/kernels/sender_non_stateful.cpp [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+    const uint32_t packed_receiver_coords = get_compile_time_arg_val(8);
+    const uint32_t noc_id = get_compile_time_arg_val(9);
+
+    // Extract receiver coordinates
+    uint32_t receiver_x = (packed_receiver_coords >> 16) & 0xFFFF;
+    uint32_t receiver_y = packed_receiver_coords & 0xFFFF;
+
+    {
+        DeviceZoneScopedN("RISCV0");
+        if (same_destination) {
```
Comment (atatuzunerTT) [inline tests/tt_metal/tt_metal/data_movement/direct_write/kernels/sender_non_stateful.cpp]: One point of improvement is that you can make all compile time args `constexpr`, and subsequently this `if` statement an `if constexpr` statement. This will save you space in the binary (not that you need it in this case) and time in execution (depending on the variable, the if clause or the else clause will get compiled away so that you save time in runtime).

File: tests/tt_metal/tt_metal/data_movement/direct_write/kernels/sender_non_stateful.cpp [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+            // Case 1: All writes to same destination - non-stateful reconfigures each time
+            uint64_t dest_noc_addr = get_noc_addr(receiver_x, receiver_y, dest_l1_addr);
+
+            for (uint32_t i = 0; i < num_writes; i++) {
+                uint32_t write_value = same_value ? write_value_base : (write_value_base + i);
+                if (use_posted_writes) {
```
Comment (atatuzunerTT) [inline tests/tt_metal/tt_metal/data_movement/direct_write/kernels/sender_non_stateful.cpp]: Same with this `if` statement

File: tests/tt_metal/tt_metal/data_movement/direct_write/kernels/sender_stateful.cpp [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+    const uint32_t noc_id = get_compile_time_arg_val(9);
+
+    // Extract receiver coordinates
+    uint32_t receiver_x = (packed_receiver_coords >> 16) & 0xFFFF;
+    uint32_t receiver_y = packed_receiver_coords & 0xFFFF;
+
+    {
+        DeviceZoneScopedN("RISCV0");
+
+        if (same_destination) {
```
Comment (atatuzunerTT) [inline tests/tt_metal/tt_metal/data_movement/direct_write/kernels/sender_stateful.cpp]: Same as above here

File: tt_metal/hw/inc/blackhole/noc_nonblocking_api.h [hunk 4]
```diff
@@ -1296,6 +1298,10 @@ inline __attribute__((always_inline)) void noc_fast_write_dw_inline_with_state(
 
     if constexpr (update_addr_lo) {
         NOC_CMD_BUF_WRITE_REG(noc, cmd_buf, NOC_TARG_ADDR_LO, dest_addr);
+        if constexpr (update_be_on_addr_lo) {
+            uint32_t be32 = 0xF << (dest_addr & (NOC_WORD_BYTES - 1));
+            NOC_CMD_BUF_WRITE_REG(noc, cmd_buf, NOC_AT_LEN_BE, be32);
+        }
```
Comment (yugaoTT) [inline tt_metal/hw/inc/blackhole/noc_nonblocking_api.h]: seems like we don't need to update NOC_AT_LEN_BE on fabric because we are writing to stream register, not L1 with this api. Can you instead of making a bool to disable `update_be_on_addr_lo`, use `InlineWriteDst dst_typ`e to differentiate ?

Comment (yugaoTT) [reply tt_metal/hw/inc/blackhole/noc_nonblocking_api.h]: if I understand it correctly, this field should always be updated when writing to L1, but not needed when writing to MMIO,

Comment (nstamatovicTT) [reply tt_metal/hw/inc/blackhole/noc_nonblocking_api.h]: `InlineWriteDst dst_type` isn't present in the `noc_fast_write_dw_inline_with_state`. Do you think we should add that? Also, I think that in that case we would also have to add _spoof_ for the with_state api

Comment (nstamatovicTT) [reply tt_metal/hw/inc/blackhole/noc_nonblocking_api.h]: @yugaoTT pinging for visibility

Comment (rtawfik01) [reply tt_metal/hw/inc/blackhole/noc_nonblocking_api.h]: @TT-BrianLiu @tt-aho can you guys check that the above change is alright as well?

**Review by rtawfik01 — APPROVED** [review]

File: tt_metal/hw/inc/blackhole/noc_nonblocking_api.h (hunk 4 above)
Comment (yugaoTT) [reply tt_metal/hw/inc/blackhole/noc_nonblocking_api.h]: @nstamatovicTT IMO dst_type is a clearer arg than another bool (it reflects how the hardware limitations on this). maybe for now spoof for with_state can just leave blank, and just have a ASSERT(false) there, since we are not using it.

Comment (nstamatovicTT) [reply tt_metal/hw/inc/blackhole/noc_nonblocking_api.h]: @yugaoTT can you review

**Review by yugaoTT — APPROVED** [review]
approving under the assumption that fabric related pipelines passed
