### PR TITLE
Watcher to catch noc_inline_dw_write's to DRAM

### LINKED ISSUE #20881: [Bug Report] `noc_inline_dw_write` doesn't work on DRAM write.
**Overview**
 While i was testing the functionality of`noc_inline_dw_write` api, i found that this api does not work on DRAM write.
I want for the api to work on DRAM write so that developers can try more methods to optimize kernel.

**Describe the bug**  
 
 I observed several facts with some experiments.
1. 
`noc_inline_dw_write` to DRAM writes local DRAM address(LSB 36-bits) encoded in noc_addr.
The code tries writing a value '0xBADF00D' to first 4-byte of DRAM using `noc_inline_dw_write`.
```cpp
uint32_t val = 0xBADF00D;
InterleavedAddrGenFast<true> dst_addr_gen = {
	.bank_base_address = dst_addr, 
	.data_format = get_dataformat(cb_print) // int32 data format
};

// noc address given by address generator
uint64_t noc_addr1 = get_noc_addr(0, dst_addr_gen);
DPRINT << "noc_addr1 - 0x" << noc_addr1 << ENDL();

// 1. noc_inline_dw_write with noc_addr1
DPRINT << "Case 1 - noc_inline_dw_write on noc address to dram" << ENDL();

DPRINT << "Before-write : " << ENDL();
check_dram_status(noc_addr1, cb_print); // this is a function to print dram with given address. the source of it is included in reproduce step. 

noc_inline_dw_write(noc_addr1, val, 0xF, noc_index);
noc_async_write_barrier(noc_index);

DPRINT << "After-write : " << ENDL();
check_dram_status(noc_addr1, cb_print);
```
The print result shows first row of a tile.
As you can see, the written value is not`0xBADF00D`, but `0x1020` which is local dram address of `noc_addr1` .
From the print outputs, it seems that the header of NoC packet is being handled as data payload. 
Therefore, the local dram address(0x1020) was written into first 4-byte of given DRAM address.
```
0:(x=0,y=0):BR: ----- Kernel Start ----
0:(x=0,y=0):BR: noc_addr1 - 0x2c0000001020
0:(x=0,y=0):BR: Case 1 - noc_inline_dw_write on noc address to dram
0:(x=0,y=0):BR: Before-write : 
0:(x=0,y=0):BR: 0 --READ--cin1-- 40005020 40102c00 40100040 40004051 1070d400 f77ffd10 a5d005dd 4041 50501000 1505000 10005500 50005000 51545000 51145000 50500051 501450 <TileSlice data truncated due to exceeding max count (16)>
0:(x=0,y=0):BR: After-write : 
0:(x=0,y=0):BR: 0 --READ--cin1-- 1020 40102c00 40100040 40004051 1070d400 f77ffd10 a5d005dd 4041 50501000 1505000 10005500 50005000 51545000 51145000 50500051 501450 <TileSlice data truncated due to exceeding max count (16)>
```

2. 
Additionally, i tested the full mask of be32('0xFFFFFFFF') by customizing `noc_fast_write_dw_inline` function.
Modifications included in the custom function are : 
- Add `NOC_CMD_WR_BE` flag to noc_cmd_filed
- dprint be32 as binary format
```cpp
template <uint8_t noc_mode = DM_DEDICATED_NOC>
inline __attribute__((always_inline)) void noc_fast_write_dw_inline_moreh(
    uint32_t noc,
    uint32_t cmd_buf,
    uint32_t val,
    uint64_t dest_addr,
    uint32_t be32,
    uint32_t static_vc,
    bool mcast,
    bool posted = false) {
   ...
    bool static_vc_alloc = true;
    uint32_t noc_cmd_field = (static_vc_alloc ? NOC_CMD_VC_STATIC : 0x0) | NOC_CMD_STATIC_VC(static_vc) | NOC_CMD_CPY |
                             NOC_CMD_WR | NOC_CMD_WR_INLINE | NOC_CMD_WR_BE |  // add NOC_CMD_WR_BE flag.
                             (mcast ? (NOC_CMD_PATH_RESERVE | NOC_CMD_BRCST_PACKET) : 0x0) |
                             (posted ? 0x0 : NOC_CMD_RESP_MARKED);
    dprint_be_binary(be32); // print be32 as binary format
    ...
}

void kernel_main() {
  DPRINT << "Case 3 - custom noc_inline_dw_write on noc address to dram with full be mask" << ENDL();
  uint32_t be32 = 0xFFFFFFFF; // 32 bytes enabled
  noc_fast_write_dw_inline_moreh(
      noc_index, write_at_cmd_buf, val, noc_addr1, be32, NOC_UNICAST_WRITE_VC, /*mcast*/false,
      /*posted*/false);
  noc_async_write_barrier(noc_index);
  check_dram_status(noc_addr1, cb_print);
}
```
The execution of above code outputs below logs.
We can observe the value '0x0BADF00D' is written into local DRAM address after 25th bytes.
With 4-byte sized datum, `1020(4byte) 40002c00(4byte) 0(4byte) 41(4byte) 309e00(4byte) ffffff00(4byte) adf00d(3byte)ff(1byte) b(4byte)`
```
0:(x=0,y=0):BR: Case 3 - custom noc_inline_dw_write on noc address to dram with full be mask
0:(x=0,y=0):BR: Before-write : 
0:(x=0,y=0):BR: 0 --READ--cin1-- 40005130 40102c00 40000040 40004051 70d400 f77ffd00 a5d005dd 4041 10501000 505000 10005500 50005000 50100000 50145000 50500001 500050 <TileSlice data truncated due to exceeding max count (16)>
0:(x=0,y=0):BR: 
0:(x=0,y=0):BR: byte enable mask : 11111111111111111111111111111111
0:(x=0,y=0):BR: After-write : 
0:(x=0,y=0):BR: 0 --READ--cin1-- 1020 40002c00 0 41 309e00 ffffff00 adf00dff b 10501000 505000 10005500 50005000 50100000 50145000 50500001 500050 <TileSlice data truncated due to exceeding max count (16)>
```

**To Reproduce**  
I modified exist 'examples' operation in ttnn dir.  
To see main changes on the example program, please check out [a test kernel](https://github.com/tenstorrent/tt-metal/blob/yechan/noc_inline_dw_write/ttnn/cpp/ttnn/operations/examples/example/device/kernels/dataflow/noc_inline_dw_write_test.cpp) and [pytest script](https://github.com/tenstorrent/tt-metal/blob/yechan/noc_inline_dw_write/tests/ttnn/unit_tests/operations/test_examples.py)
1.  Go to [yechan/noc_inline_dw_write](https://github.com/tenstorrent/tt-metal/tree/yechan/noc_inline_dw_write) branch
2. Build with debug and setup python venv following tt-metal installation guide.
3. Enable dprint by running `export TT_METAL_DPRINT_CORES=0,0`
4. Run a command 'pytest tests/ttnn/unit_tests/operations/test_examples.py'  
5. See both DPRINT result and pytest result  

Be sure to reset your device through tt-smi before running example program.

**Expected behavior**  
You may see the print output as below.
Image

 
**Please complete the following environment information:**  
- OS: Ubuntu 22.04.4 LTS  
- Version of software : 
  - base branch (main) : [16e07](https://github.com/tenstorrent/tt-metal/commit/16e07839fa45bad63d1079697edc68b6daf04098)
  - working branch : [c70f47](https://github.com/tenstorrent/tt-metal/commit/c70f47d1d42633b22f7851693f19b9c130c26b7b)
- Arch: wormhole_b0 n300s
 
**Additional context**  
N/A

### PR DESCRIPTION
**Pull request by nhuang-tt**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/20881)

### Problem description
Community members reported that this API doesn't work when writing to DRAM. Confirmed with hardware engineers that noc_inline_dw_write to DRAM addresses is not supported. The documentation in `dataflow_api.h` is incorrect.

### What's changed
- Update docstring in `dataflow_api.h`
- Sanitize calls to `noc_inline_dw_write` to make sure they aren't DRAM addresses
- Add Idle/Active/Tensix test cases

### Checklist
APC
https://github.com/tenstorrent/tt-metal/actions/runs/14630221711
T3K
https://github.com/tenstorrent/tt-metal/actions/runs/14630221870
TG
https://github.com/tenstorrent/tt-metal/actions/runs/14630222007
Single Card TTNN
https://github.com/tenstorrent/tt-metal/actions/runs/14630222200
BH
https://github.com/tenstorrent/tt-metal/actions/runs/14630222413

### CODE REVIEW

File: tt_metal/impl/debug/watcher_device_reader.cpp [hunk 1]
```diff
@@ -585,6 +585,10 @@ void WatcherDeviceReader::DumpNocSanitizeStatus(
             error_msg = get_noc_target_str(device_id, core, noc, san);
             error_msg += " (mixing virtual and virtual coordinates in Mcast).";
             break;
+        case DebugSanitizeInlineWriteDramUnsupported:
+            error_msg = get_noc_target_str(device_id, core, noc, san);
+            error_msg += " (inline dw writes does not support DRAM destination addresses).";
```
Comment (tt-dma) [inline tt_metal/impl/debug/watcher_device_reader.cpp:590]: Nit: "inline dw writes do not support"

File: tests/tt_metal/tt_metal/debug_tools/watcher/test_noc_sanitize.cpp [hunk 2]
```diff
@@ -50,9 +51,43 @@ typedef enum sanitization_features {
...
+
+CoreCoord get_core_coord_for_test(const std::shared_ptr<tt::tt_metal::Buffer>& buffer) {
+    if (buffer->is_l1()) {
+        return buffer->device()->worker_core_from_logical_core(buffer->allocator()->get_logical_core_from_bank_id(0));
+    } else {
+        return buffer->device()->logical_core_from_dram_channel(0);
+    }
+}
+
 void RunTestOnCore(WatcherFixture* fixture, IDevice* device, CoreCoord &core, bool is_eth_core, watcher_features_t feature, bool use_ncrisc = false) {
```
Comment (nhuang-tt) [inline tests/tt_metal/tt_metal/debug_tools/watcher/test_noc_sanitize.cpp:91]: I removed references of "l1_*" in this file. The buffers can be DRAM or L1.

**Review by tt-dma — APPROVED** [review]

**Review by blozano-tt — APPROVED** [review]

**Review by afuller-TT — APPROVED** [review]
