### PR TITLE
Fix uniform sfpu in BH

### LINKED ISSUE #20699: BH TTNN Unit failure in test for uniform
https://github.com/tenstorrent/tt-metal/actions/runs/14417681705/job/40436423449
```
FAILED tests/ttnn/unit_tests/operations/test_uniform.py::test_uniform[seed=2024-dtype=bfloat16-rand_range=[0, 1]-shape=[32, 32]] - RuntimeError: TT_THROW @ /work/tt_metal/impl/program/program.cpp:113: tt::exception
info:
Failed to generate binaries for compute_uniform TT_THROW @ /work/tt_metal/jit_build/build.cpp:67: tt::exception
info:
trisc1 build failed. Log: In file included from /work/ttnn/cpp/ttnn/operations/uniform/device/kernels/compute_uniform.cpp:7,
                 from ../chlkc_math.cpp:3,
                 from /work/.ttnn_runtime_artifacts/tt_metal/hw/ckernels/blackhole/metal/common/chlkc_list.h:21,
                 from /work/.ttnn_runtime_artifacts/tt_metal/hw/firmware/src/trisck.cc:14:
/work/.ttnn_runtime_artifacts/tt_metal/include/compute_kernel_api/eltwise_unary/rand.h:9:10: fatal error: llk_math_eltwise_unary_sfpu_rand.h: No such file or directory
    9 | #include "llk_math_eltwise_unary_sfpu_rand.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I think this is similar to other eltwise ops.

Needs to be fixed.

### PR DESCRIPTION
**Pull request by Aswinmcw**
### Ticket
#20699 

### Problem description
BH TTNN Unit failure in test for uniform

### What's changed
eltwise rand sfpu missed in BH

Screenshot 2025-04-16 at 4 33 35 PM

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
https://github.com/tenstorrent/tt-metal/actions/runs/14491183316
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable)
https://github.com/tenstorrent/tt-metal/actions/runs/14491185481
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by nvelickovicTT — APPROVED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_rand.h [hunk 1]
```diff
@@ -39,14 +39,12 @@ inline void rand(uint32_t from, uint32_t scale) {
...
         TTI_SFPADDI(0xbf80 /*-1*/, p_sfpu::LREG0, 0);
-        TTI_SFPNOP;
 
         // Scale the float from [0, 1) to [from, from + scale)
         // lreg0 = lreg0 * scale + from
         TTI_SFPMAD(p_sfpu::LREG0, p_sfpu::LREG1, p_sfpu::LREG2, p_sfpu::LREG0, 0);
-        TTI_SFPNOP;
 
-        TTI_SFPSTORE(0, 3, 7, 0);
+        TTI_SFPSTORE(p_sfpu::LREG0, p_sfpu::LREG3, ADDR_MOD_7, 0);
```
Comment (nvelickovicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_rand.h:47]: 3 -> p_sfpu::LREG3 is nto correct. Please take a look at https://github.com/tenstorrent/tt-llk/blob/b18f26b2a3bc3be7c8ed6c75f5a4da04f4647aa3/tt_llk_blackhole/instructions/assembly.yaml#L2339C6-L2339C25. The 3 represents instruction modifier of the instruction. Take a look at and use https://github.com/tenstorrent/tt-llk/blob/b18f26b2a3bc3be7c8ed6c75f5a4da04f4647aa3/tt_llk_blackhole/llk_lib/llk_defs.h#L139

**Review by nvelickovicTT — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]
