### PR TITLE
#14010: fix caching issues with moreh_adam and moreh_adamw

### LINKED ISSUE #14010: [Bug Report] Moreh_adamw program is not properly cached
**Describe the bug**
While using `moreh_adamw` we saw that cache grows a little bit with every iteration. After review, we see that `steps` is cached inside program cache that triggers recreation of program for every new call. 

**To Reproduce**
* `enable_program_cache`
* Run `moreh_adamw` with same parameters except steps (1, 2, 3, 4, 5)
* Cache size grows 

**Expected behavior**
`steps` should not be part of caching mechanism

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: main

### PR DESCRIPTION
**Pull request by o2buzzle**
### Ticket
Closes #14010 

### Problem description
`adam` and `adamw` specified the `step` operation attribute that is provided at runtime as a non-cacheable argument. As such when the `step` changes the cache is always regenerated even though the cache item is valid if the argument is overriden accordingly

### What's changed
- Override `compute_program_hash` with custom hash implementation that does not use the `step` argument
- Update `override_runtime_arguments` with new item for `step`

### Checklist
- [x] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by o2buzzle** [comment]
CI run: https://github.com/tenstorrent/tt-metal/actions/runs/11434570794

File: ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp [hunk 1]
```diff
@@ -156,4 +156,14 @@ std::tuple<MorehAdamOperation::operation_attributes_t, MorehAdamOperation::tenso
             max_exp_avg_sq_in,
             {param_out, exp_avg_out, exp_avg_sq_out, max_exp_avg_sq_out}}};
 }
+auto MorehAdamOperation::compute_program_hash(
+    const MorehAdamOperation::operation_attributes_t& operation_attributes,
+    const MorehAdamOperation::tensor_args_t& tensor_args) -> tt::stl::hash::hash_t {
+    // For hash we'll set `step` to 0
+    auto operation_attributes_without_step = operation_attributes;
+    operation_attributes_without_step.step = 0;
```
Comment (rfurko-tt) [inline ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp:164]: wdyt about not caching `learning_rate` as well? Once we start using LRScheduler we will same issue.

Comment (o2buzzle) [reply ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp]: I think 305e5fd should cover it. You should double check if the rewrite of `compute_program_hash` is acceptable as well

File: ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp [hunk 2]
```diff
@@ -156,4 +157,35 @@ std::tuple<MorehAdamOperation::operation_attributes_t, MorehAdamOperation::tenso
...
             {param_out, exp_avg_out, exp_avg_sq_out, max_exp_avg_sq_out}}};
 }
+auto MorehAdamOperation::compute_program_hash(
+    const MorehAdamOperation::operation_attributes_t& operation_attributes,
+    const MorehAdamOperation::tensor_args_t& tensor_args) -> tt::stl::hash::hash_t {
+    // // For hash we'll set `step` to 0
+    // auto operation_attributes_without_step = operation_attributes;
+    // operation_attributes_without_step.step = 0;
+
+    // return tt::stl::hash::hash_objects_with_default_seed(operation_attributes_without_step, tensor_args);
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp:167]: Please delete commented out code.

**Review by bbradelTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp (hunk 2 above)
Comment (o2buzzle) [reply ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_device_operation.cpp]: Done

File: ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_program_factory.cpp [hunk 3]
```diff
@@ -277,6 +298,8 @@ void MorehAdamOperation::ProgramFactory::override_runtime_arguments(
             if (max_exp_avg_sq_in_buffer != nullptr) {
                 runtime_args[4] = max_exp_avg_sq_in_buffer->address();
             }
+            runtime_args[5] = f2u_lr.u;
+            runtime_args[10] = operation_attributes.step;
```
Comment (rfurko-tt) [inline ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_program_factory.cpp:302]: just curious, why step index is 10 in `runtime_args`?

**Review by rfurko-tt — APPROVED** [review]
LGTM, thank you @o2buzzle for fixing the issue!

File: ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_program_factory.cpp (hunk 3 above)
Comment (o2buzzle) [reply ttnn/cpp/ttnn/operations/moreh/moreh_adam/device/moreh_adam_program_factory.cpp:302]: I wish I have a hint of an idea what went through my colleague's minds when they wrote these ops

**Review by razorback3 — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/experimental/matmul/group_attn_matmul/device/group_attn_matmul_device_operation.cpp [hunk 4]
```diff
@@ -3,8 +3,9 @@
 // SPDX-License-Identifier: Apache-2.0
```
Comment (mrshaw01) [inline ttnn/cpp/ttnn/operations/experimental/matmul/group_attn_matmul/device/group_attn_matmul_device_operation.cpp:3]: Should not change this file.

**Review by mrshaw01 — APPROVED** [review]

**Comment by o2buzzle** [comment]
CI is OK: https://github.com/tenstorrent/tt-metal/actions/runs/11478694436/

I will proceed with merging
