### PR TITLE
#13707: Replace LegacyShape with SimpleShape

### LINKED ISSUE #13707: Change compute_output_shapes in all_gather from LegacyShape to SimpleShape
**Describe the bug**
We tried changing but learned that operation and potentially its consumers need to adjust.

The expected new behavior is that an op must return a logical shape as SimpleShape.
Downstream infra will figure out what padding should be added depending on the rest of params like dtype, layout, (strides, tile size, etc).

### PR DESCRIPTION
**Pull request by Aswinmcw**
Tracking Issue : #13707 

Replace LegacyShape with SimpleShape

### Checklist
- [x] Post commit CI passes - https://github.com/tenstorrent/tt-metal/actions/runs/11341230160
- [x] T3K Pipelines - https://github.com/tenstorrent/tt-metal/actions/runs/11341265809
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by SeanNijjar — APPROVED** [review]
Thanks @Aswinmcw!

**Review by bbradelTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp [hunk 1]
```diff
@@ -165,10 +165,10 @@ void AllGather::validate(const std::vector<Tensor> &input_tensors) const {
     }
 }
 
-std::vector<tt::tt_metal::LegacyShape> AllGather::compute_output_shapes(const std::vector<Tensor> &input_tensors) const {
-    auto shape = input_tensors[0].get_legacy_shape();
+std::vector<ttnn::SimpleShape> AllGather::compute_output_shapes(const std::vector<Tensor> &input_tensors) const {
+    auto shape = input_tensors[0].get_padded_shape(); // TODO: Replace with get_logical_shape()
```
Comment (TT-BrianLiu) [inline ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: This might hide more bugs later. Why does switching to `logical_shape` not work here?

Comment (Aswinmcw) [reply ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: using logical shape throws error in layernorm op due to padding

Comment (TT-BrianLiu) [reply ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: What's the padding? I think it would be good to fix both in this PR. The workaround here only works because allgather itself doesn't have padded tests (i am assuming)

Comment (TT-BrianLiu) [reply ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: What's the test to repro? I can take a look at this as well

Comment (Aswinmcw) [reply ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: `tests/ttnn/unit_tests/operations/test_distributed_layernorm.py`
This is the test file that is failing if we use logical shape

Comment (SeanNijjar) [reply ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: The problem is:
1) All-gather doesn't support padding properly yet and when distributed layernorm was implemented it knew this and as a sort of hack - it accounted for this behaviour.
2) Fixing this properly in all-gather (with acceptable perf) is a non-trivial amount of work. Until then, this PR will migrate us to new tensor without regressing on old functionality.

Comment (TT-BrianLiu) [reply ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: Ok merge it for now. Would distributed layernorm be safe to flip to `SimpleShape` as well? Or does it depend on some behaviour in all gather?

Comment (SeanNijjar) [reply ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op.cpp:169]: it's the same problem - it was built knowing this limitation of all-gather there so when we fix it in all-gather we need to make sure to flip it there too.

**Review by TT-BrianLiu — APPROVED** [review]

**Review by sminakov-tt — APPROVED** [review]
