### PR TITLE
Fix on-host to_dtype op

### LINKED ISSUE #21915: Make on-host to_dtype op nicer
1. Needs to be moved to .cpp
2. Poor test coverage
3. Some duplicated code from what I can see.

### PR DESCRIPTION
**Pull request by aliaksei-sala**
### Ticket
[Fix on-host to_dtype op](https://github.com/tenstorrent/tt-metal/issues/21915)

### Problem description
- The implementation should be moved to the .cpp file.
- Improve test coverage.
- Duplicate code needs to be removed.
- Investigate and fix the bug where BF4/BF8 inputs are not utilized.

### What's changed
Refactored the implementation to address the concerns outlined in the problem description.

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes. [Results](https://github.com/tenstorrent/tt-metal/actions/runs/16209340536)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable). [Results](https://github.com/tenstorrent/tt-metal/actions/runs/16209352604)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        switch (dst_type) {
+            case DataType::BFLOAT4_B: return &transform_type<SrcType, bfloat4_b>;
+            case DataType::BFLOAT8_B: return &transform_type<SrcType, bfloat8_b>;
+            case DataType::BFLOAT16: return &transform_type<SrcType, bfloat16>;
+            case DataType::FLOAT32: return &transform_type<SrcType, float>;
+            case DataType::UINT8: return &transform_type<SrcType, uint8_t>;
+            case DataType::UINT16: return &transform_type<SrcType, uint16_t>;
+            case DataType::UINT32: return &transform_type<SrcType, uint32_t>;
+            case DataType::INT32: return &transform_type<SrcType, int32_t>;
+            default: TT_THROW("Unsupported data type conversion requested. Destination type is invalid!");
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: I'm not sure how often you expect this case to be reached. Maybe print the data type.

**Review by bbradelTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp (hunk 1 above)
Comment (omilyutin-tt) [reply ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: Can we use this pattern (here and below):
1. Enumerate all cases explicitly - this way, when a new enum is added, compilation fails, which forces developers to update the processing code accordingly.
2. Add `TT_THROW("Unreachable");` after the switch block, as some compilers (with additional checks on) don't recognize the switch is exhaustive and complain "non void function doesn't return a value".

```cpp
switch (dst_type) {
  case DataType::BFLOAT4_B:
  ...
  case DataType::Invalid: TT_THROW("Invalid data type!");
}    
TT_THROW("Unreachable"); 
```

File: ttnn/cpp/ttnn/operations/core/to_dtype/transform_type.hpp
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/core/to_dtype/transform_type.hpp:1]: Is it possible to move this whole thing in to_dtype_op.cpp?

File: ttnn/cpp/ttnn/operations/core/to_dtype/transform_type.hpp [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+
+template <typename SrcType, typename DstType>
+tt::tt_metal::Tensor transform_type(const tt::tt_metal::Tensor& input_tensor, const DataType dst_type) {
+    using namespace tt::tt_metal;
+
+    TT_FATAL(is_cpu_tensor(input_tensor), "transform_type(...) function only supports host tensors!");
+    auto input_dtype = input_tensor.dtype();
+    auto storage = preprocess_tensor<SrcType>(input_tensor);
+
+    using intm_src_t =
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/core/to_dtype/transform_type.hpp]: nit: spell `IntermediateSrcType` and add a comment, might be unclear for unfamiliar readers what we are doing here

File: ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+
+}  // namespace detail
+
+Tensor ToDtype::invoke(const ttnn::Tensor& input_tensor, const ttnn::DataType& dtype) {
+    if (input_tensor.dtype() == dtype) {
+        return input_tensor;
+    }
+
+    const auto& transform_type = detail::get_dtype_conversion_function(input_tensor.dtype(), dtype);
+    return transform_type(input_tensor, dtype);
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: Is it possible instead of returning `transform_type` from this function, move the lambdas here in `invoke`, capture `input_tensor` along with `dtype`, and then dispatch to `transform directly? Something like

```cpp

auto transform_tensor = [&input_tensor, dst_type = dtype]<typename SrcType>() {
        switch (dst_type) {
            case DataType::BFLOAT4_B: return transform_tensor<SrcType, bfloat4_b>(input_tensor, dtype);
            case DataType::BFLOAT8_B: return transform_tensor<SrcType, bfloat8_b>(input_tensor, dtype);
            case DataType::BFLOAT16: return transform_tensor<SrcType, bfloat16>(input_tensor, dtype);
            case DataType::FLOAT32: return transform_tensor<SrcType, float>(input_tensor, dtype);
            ...
        }
    };

switch (src_type) {
        case DataType::BFLOAT4_B: return transform_tensor.operator()<bfloat4_b>();
        case DataType::BFLOAT8_B: return transform_tensor.operator()<bfloat8_b>();
        case DataType::BFLOAT16: return transform_tensor.operator()<bfloat16>();
        ...
    }
```

wdyt?

**Review by omilyutin-tt — COMMENTED** [review]
Looks good!

File: ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp (hunk 1 above)
Comment (aliaksei-sala) [reply ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: For case 1, I didn't handle DataType::Invalid enum now and don't have any warnings or errors
Adding -Wswitch -Wswitch-enum flags will break the build. Do we want to address that issue later?

I'll add `case DataType::Invalid`

Comment (omilyutin-tt) [reply ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: > Adding -Wswitch -Wswitch-enum flags will break the build. Do we want to address that issue later?

Can you clarify? Do you mean that enumerating all cases exhaustively and explicitly won't work with these flags? I think our default build already breaks if you try to do something like this, if not default definitely on one of CI variants.

Comment (aliaksei-sala) [reply ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: These flags enforce exhaustive enumeration of all cases, but since we don’t use them, this isn’t enforced and CI checks passed even though the DataType::Invalid case was unhandled.

Results of CI runs in the PR description

Comment (omilyutin-tt) [reply ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: Yes, but you include `default: ` branch, which is why CI run you linked passes, I think. `default: ` makes it "exhaustive".

Unless I misunderstand something, but I think the PR run is based on the change that has `default: ` :)

**Review by nsextonTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp (hunk 1 above)
Comment (aliaksei-sala) [reply ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: You’re right, I checked what happens if we remove `default:`, and clang-tidy does fail as expected. 
What do you think about removing `default:` to catch missing enum values during static analysis?

in that case we will get nice message:
`error: enumeration value 'INVALID' not handled in switch [clang-diagnostic-switch]`

Comment (aliaksei-sala) [reply ttnn/cpp/ttnn/operations/core/to_dtype/to_dtype_op.cpp]: Actually, I think it’s better to keep the default case. 
We don’t want to require developers to update every switch statement when a new type is added.

**Review by omilyutin-tt — APPROVED** [review]
