### PR TITLE
#6315: Fix dprint tests for T3000

### LINKED ISSUE #6315: Test dprint/watcher on T3000
We have unit tests under `tests/tt_metal/tt_metal/unit_tests_common` (see specifically `DPrintFixture` and `WatcherFixture` tests), but they only run on n300 on CI. Hypothetically all dprint/watcher features should extend to >2 chips, but we should test it out to be sure. CI does not have T3000s, so can't add to CI runs yet.

To run a unit test: `./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=*{Test Name}`

Per Mo, we should also test running all-gather test since it's exercising more of the features together than just the unit tests.

### PR DESCRIPTION
**Pull request by ihamer-tt**
- Update WaitForPrintsFinished to allow dprint server thread to make progress
- Update test_print_before_finish to run on one device only as closing some devices causes the test to fail on other devices.

### CODE REVIEW

**Comment by ihamer-tt** [comment]
The one test that still fails is DPrintFixture.TestPrintEthCores:
```
| Test Error: Line 3 of gtest_dprint_log.txt did not match expected:
        1010@0.122559
        101-1.618@0.122559
tests/tt_metal/tt_metal/unit_tests_common/dprint/test_eth_cores.cpp:70: Failure
Value of: FilesMatchesString( DPrintFixture::dprint_file_name, golden_output )
  Actual: false
Expected: true
```
This sounds similar to #6378. @tt-dma, what do you think we should do with this?

**Comment by ihamer-tt** [comment]
Tests: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8360542152

**Comment by tt-dma** [comment]
Looks good to me, so I guess what we were suspecting (await called before first iteration is finished) was the culprit?

For the TestPrintEthCores, it does appear to be the same problem as #6378, while unexpected since we had a fix for n300 for that, the issue crops up again in #6424. Why don't we disable this test on t3000 for now and I will investigate this week

File: tests/tt_metal/tt_metal/unit_tests_common/dprint/test_print_before_finish.cpp [hunk 1]
```diff
@@ -58,11 +58,7 @@ static void RunTest(DPrintFixture* fixture, Device* device) {
...
 
 TEST_F(DPrintFixture, TestPrintFinish) {
-    // Iterate devices in reverse for this test. Since the test closes the devices early, avoid
-    // closing L chip before R chip.
     auto devices = this->devices_;
-    std::reverse(devices.begin(), devices.end());
-    for (Device* device : devices) {
-        this->RunTestOnDevice(RunTest, device);
-    }
+    // Run only on the first device
```
Comment (tt-dma) [inline tests/tt_metal/tt_metal/unit_tests_common/dprint/test_print_before_finish.cpp:62]: Can we just comment here that we run only on first device because the test closes devices as it goes, and that causes problems for multi-chip?

**Review by tt-dma — APPROVED** [review]
