### PR TITLE
#38643: Replace composite gelu_bw(approximate=none) with fused polynomial kernel

### LINKED ISSUE #38643: [TTNN]: ttnn.gelu_bw(approximate="none") composite decomposition has severe ULP errors (Max ULP = 32,460)
### Component / Area

TTNN / Eltwise Operations / Unary Backward / GELU Backward

### Issue Type

Bad Outputs

### Observed

`ttnn.gelu_bw(approximate="none")` — the main (non-experimental) API — has severe accuracy issues affecting approximately 50% of the BF16 input range:

1. **Wrong sign outputs** at x ≈ -3.7: derivative should be negative but returns positive
2. **High ULP errors** in deep negative (x < -5) and large positive (x > 5) regions
3. **10.69% of all BF16 values have ULP > 1000**
4. **Max ULP = 32,460** (expected: ≤ 1)

This is the **same mathematical bug** as issue #35971, but in a different code path.

### Implementation Details

The main API `ttnn.gelu_bw(approximate="none")` is implemented as a **composite host-side decomposition** in `ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward.cpp` (lines ~1613-1632). It dispatches approximately 10 separate TTNN sub-operations:

```cpp
float kAlpha = M_SQRT1_2;
float kBeta = M_2_SQRTPI * M_SQRT1_2 * 0.5;
Tensor cdf = ttnn::multiply(
    (ttnn::add(
        ttnn::erf(ttnn::multiply(input, kAlpha, ...)),
        1, ...)),
    0.5);
Tensor pdf = ttnn::multiply(
    ttnn::exp(ttnn::multiply(ttnn::multiply(input, input), -0.5), ...),
    kBeta, ...);
ttnn::multiply(grad, ttnn::add(cdf, ttnn::multiply(input, pdf)), ...);
```

**Root cause:** The formula `cdf = 0.5 * (1 + erf(x/√2))` suffers from catastrophic cancellation when `erf(x/√2)` approaches -1 for large negative x. The SFPU `erf()` implementation saturates, and `1 + (-1)` loses all significant digits. This cannot be fixed by rearranging the composite ops — the fundamental limitation is in the erf/erfc SFPU functions.

### Distinction from Issue #35971

Issue #35971 covers `ttnn.experimental.gelu_bw()` — a **fused device kernel** implementation (`eltwise_bw_gelu_approx_none.cpp`) that computes the entire GELU derivative in a single kernel. That was fixed by PR #36366 using piecewise polynomial approximation (Max ULP = 1).

This issue covers `ttnn.gelu_bw()` — the **main public API** that uses composite host-side decomposition. These are independent code paths. The main API does NOT call the experimental API.

| API | Implementation | Code Path | Status |
|-----|---------------|-----------|--------|
| `ttnn.experimental.gelu_bw()` | Fused device kernel | `ttnn/cpp/ttnn/operations/experimental/unary_backward/gelu_backward/device/kernels/compute/eltwise_bw_gelu_approx_none.cpp` | **Fixed** (PR #36366) |
| `ttnn.gelu_bw()` | Composite decomposition | `ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward.cpp` | **This issue** |

### Note on tanh mode

Both APIs also support `approximate="tanh"`, which uses the tanh-based GELU approximation matching PyTorch's `torch.nn.functional.gelu(approximate='tanh')`. The tanh mode is a distinct mathematical formulation and is **not affected** by this bug.

### Expected

GELU backward should compute `GELU'(x) = Φ(x) + x·φ(x)` where Φ is the standard normal CDF and φ is the standard normal PDF. Results should match the fp64 reference within 1 ULP for BF16.

### Reproducer

```python
import ttnn
import torch
import math

device = ttnn.open_device(0)

x_val = -3.7  # Wrong sign occurs here
input_tensor = ttnn.from_torch(
    torch.full((1, 1, 32, 32), x_val, dtype=torch.bfloat16),
    layout=ttnn.TILE_LAYOUT, device=device
)
grad_tensor = ttnn.from_torch(
    torch.full((1, 1, 32, 32), 1.0, dtype=torch.bfloat16),
    layout=ttnn.TILE_LAYOUT, device=device
)

# Main API (NOT experimental)
result = ttnn.gelu_bw(grad_tensor, input_tensor, approximate="none")
actual = ttnn.to_torch(result[0])[0, 0, 0, 0].item()

# Reference
SQRT2 = math.sqrt(2.0)
INV_SQRT_2PI = 1.0 / math.sqrt(2.0 * math.pi)
cdf = 0.5 * math.erfc(-x_val / SQRT2)
pdf = math.exp(-0.5 * x_val * x_val) * INV_SQRT_2PI
expected = cdf + x_val * pdf

print(f"x = {x_val}")
print(f"Expected: {expected:.6e} (NEGATIVE)")
print(f"Actual:   {actual:.6e} (POSITIVE - WRONG SIGN!)")

ttnn.close_device(device)
```

### Proposed Fix

Create a new fused device kernel under `ttnn/cpp/ttnn/operations/eltwise/unary_backward/` that calls `gelu_derivative_tile()` — the same polynomial SFPU function used by the experimental fix (PR #36366). This replaces the composite decomposition with a single device kernel while keeping the main API independent of the experimental namespace.

The shared SFPU infrastructure (`ckernel_sfpu_gelu.h`, `gelu.h`) provides the polynomial math. Only a new compute kernel and program factory need to be created under the main op.

### Frequency

100% reproducible. Affects all BF16 values in the broken regions.

### Priority

P2 (P1 consumer tt-train already uses the fixed experimental path)

### Impact

- Any user calling `ttnn.gelu_bw()` directly (not through tt-train) gets wrong gradients
- Wrong sign causes gradients to flow in the wrong direction during backpropagation
- The moderate negative region [-5, -2] contains commonly encountered activation values

### Related Issues

- #35971: Same bug in `ttnn.experimental.gelu_bw()` (fixed by PR #36366)
- #35290: ttnn.gelu() ULP errors (forward GELU, similar erf precision issue)

### PR DESCRIPTION
**Pull request by epam-iaroslav-voitovych**
### Ticket
Fixes #38643

### Problem description
`ttnn.gelu_bw(approximate="none")` uses a composite host-side decomposition (~4 ttnn sub-ops) that computes `cdf = 0.5 * (1 + erf(x/sqrt(2)))`. This suffers from catastrophic cancellation when `erf()` saturates to -1 for large negative x, producing **Max ULP = 32,460** and wrong-sign outputs at x ~ -3.7.

This is the same mathematical bug as #35971 (experimental API), but in the main public API code path (`unary_backward.cpp`).

### What's changed
Replace the composite decomposition for `approximate="none"` with a fused device kernel that calls `gelu_derivative_tile<false>()` — the shared SFPU polynomial primitive from `ckernel_sfpu_gelu.h`. The `approximate="tanh"` mode is unchanged (no precision issue there).

#### New device operation (6 files)
Independent device operation under `ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/`:

| File | Lines | Purpose |
|------|-------|---------|
| `gelu_bw_device_operation_types.hpp` | 23 | `GeluBwParams` + `GeluBwInputs` type definitions |
| `gelu_bw_device_operation.hpp` | 42 | `GeluBwDeviceOperation` struct + `launch_gelu_bw()` declaration |
| `gelu_bw_device_operation.cpp` | 138 | validate, compute_output_specs, create_output_tensors, program hash |
| `gelu_bw_program_factory.hpp` | 31 | Program factory declaration with shared_variables_t |
| `gelu_bw_program_factory.cpp` | 192 | CB setup, kernel creation, work distribution, runtime args |
| `kernels/compute/eltwise_bw_gelu_poly.cpp` | 60 | Compute kernel: `gelu_derivative_tile<false>()` + `mul_binary_tile()` |

#### Modified files (2 files)
- **`unary_backward.cpp`**: Replace the buggy composite `else` branch (17 lines) with a call to `launch_gelu_bw()` (5 lines)
- **`CMakeLists.txt`**: Add kernel file set and new source files

#### Design decisions
- **Independent of experimental API**: Lives in `ttnn::operations::unary_backward::gelu_bw` namespace (not `ttnn::prim`). Either the main or experimental implementation can be deleted without affecting the other.
- **Shared SFPU math, not duplicated**: The polynomial coefficients and `gelu_derivative_tile<false>()` function live in `ckernel_sfpu_gelu.h` (shared infrastructure). Only the compute kernel, program factory, and device operation are new.
- **Shared data movement kernels**: Uses existing `reader_binary_interleaved_start_id.cpp` and `writer_unary_interleaved_start_id.cpp` from binary/unary ops.

#### Performance (host-side timing, Wormhole n150)

[Benchmark script](https://gist.github.com/epam-iaroslav-voitovych/12355c6e51d0907a5a37d67cff6bd8be). A/B measured in the same session, kernel cache cleared between phases (main `8071cf40e1`, 2026-04-01).

| Shape | Tiles | Composite (us) | Fused (us) | Speedup |
|-------|------:|---------------:|-----------:|--------:|
| [1,1,32,32] | 1 | 2,301 | 172 | **13.4x faster** |
| [1,1,256,256] | 64 | 2,491 | 158 | **15.8x faster** |
| [1,1,1024,1024] | 1,024 | 2,470 | 157 | **15.7x faster** |
| [1,1,4096,4096] | 16,384 | 5,059 | 2,376 | **2.1x faster** |

The composite dispatches ~4 separate ttnn ops (erf, multiply, add, exp) through the host. The fused kernel does everything in a single device dispatch with a polynomial SFPU kernel. At dispatch-dominated shapes (1-1024 tiles) the speedup is 13-16x. At compute-dominated (16K tiles) the gap narrows to 2.1x.

#### Accuracy results (Wormhole n150, hardware-verified exhaustive BF16 sweep)

Per-segment analysis across the natural regions of the GELU derivative function. "Before" numbers measured on main (`8071cf40e1`) composite implementation, "After" from this PR's fused kernel — same device, same session.

| Region | Count | Before Max ULP | After Max ULP |
|--------|------:|---------------:|--------------:|
| x <= -13.375 (saturates to 0) | 15,681 | 0 | 0 |
| (-13.375, -5] exp-based | 181 | 503 | **1** |
| [-5, -3) transition | 96 | 29,868 | **1** |
| [-3, 3.17) core | 32,655 | 14,959 | **1** |
| x >= 3.17 (saturates to 1) | 15,947 | 1 | 0 |
| **OVERALL** | **64,560** | **29,868** | **1** |

The worst composite errors occur in the [-5, -3) transition region (Max ULP = 29,868 at x = -3.72) due to catastrophic cancellation in `1 + erf(x/√2)` when `erf` saturates to -1. 100% of BF16 values are within 1 ULP after the fix.

#### Tests (adapted from experimental API tests for main API return type)
- **C++ (`test_gelu_bw_main_ulp.cpp`)**: 11 tests — ULP analysis, segment analysis, exp-based region, saturation thresholds, special values
- **Python (`test_gelu_bw_main_ulp.py`)**: 33 tests — derivative at zero, positive/negative values, near-zero, local minimum, gradient scaling, summary
- All 44 tests pass. Additionally, the experimental API tests (11 C++ + 33 Python) pass as a regression check, confirming the shared kernel works through both paths.

### Checklist

- [x] [Sanity tests](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:ivoitovych%2Fissue-38643-gelu-bw-composite-fused-kernel-pr)
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:ivoitovych%2Fissue-38643-gelu-bw-composite-fused-kernel-pr)
- [x] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:ivoitovych%2Fissue-38643-gelu-bw-composite-fused-kernel-pr)
- [x] New/Existing tests provide coverage for changes
- [ ] (Optional) Ran [clang-tidy code analysis](https://github.com/tenstorrent/tt-metal/actions/workflows/code-analysis.yaml) on the PR branch to catch linting errors early

### CI Status
_Auto-generated on every push. Badges update live. Click a badge to filter runs by this branch._

- [](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:ivoitovych/issue-38643-gelu-bw-composite-fused-kernel-pr)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:ivoitovych/issue-38643-gelu-bw-composite-fused-kernel-pr)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:ivoitovych/issue-38643-gelu-bw-composite-fused-kernel-pr)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/all-model-tests.yaml?query=branch:ivoitovych/issue-38643-gelu-bw-composite-fused-kernel-pr)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:ivoitovych/issue-38643-gelu-bw-composite-fused-kernel-pr)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:ivoitovych/issue-38643-gelu-bw-composite-fused-kernel-pr)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:ivoitovych/issue-38643-gelu-bw-composite-fused-kernel-pr)

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/kernels/compute/eltwise_bw_gelu_poly.cpp [hunk 1]
```diff
@@ -0,0 +1,60 @@
+// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/kernels/compute/eltwise_bw_gelu_poly.cpp]: 2026

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_device_operation.cpp [hunk 2]
```diff
@@ -0,0 +1,138 @@
+// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_device_operation.cpp]: 2026

File: tests/ttnn/unit_tests/operations/eltwise/test_gelu_bw_main_ulp.py [hunk 3]
```diff
@@ -0,0 +1,408 @@
...
+        expected = gelu_derivative_expected_bf16_daz(x)
+        ulp = ulp_distance_bf16_daz(actual, expected)
+
+        if ulp > max_ulp:
+            max_ulp = ulp
+            worst_x = x
+
+        logger.info(f"{desc:>20} | {x:>10.4f} | {expected:>12.6f} | {actual:>12.6f} | {ulp:>8}")
+
+    logger.info("-" * 70)
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/eltwise/test_gelu_bw_main_ulp.py]: Should be debug to not fill up logs?

**Review by bbradelTT — COMMENTED** [review]
How long do all the tests take?
If they take too long maybe they should be moved to nightly.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/kernels/compute/eltwise_bw_gelu_poly.cpp (hunk 1 above)
Comment (epam-iaroslav-voitovych) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/kernels/compute/eltwise_bw_gelu_poly.cpp]: Thank you — fixed. Updated copyright to 2026 in all new files.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_device_operation.cpp (hunk 2 above)
Comment (epam-iaroslav-voitovych) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_device_operation.cpp]: Fixed along with all other new files in this PR.

File: tests/ttnn/unit_tests/operations/eltwise/test_gelu_bw_main_ulp.py (hunk 3 above)
Comment (epam-iaroslav-voitovych) [reply tests/ttnn/unit_tests/operations/eltwise/test_gelu_bw_main_ulp.py]: Good point, thank you. Changed all informational `logger.info` calls to `logger.debug`. Error conditions use pytest assertions rather than logging, so no error-level messages were affected.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 4]
```diff
@@ -87,10 +171,178 @@ inline void calculate_gelu() {
...
+// =============================================================================
+// GELU Derivative - Polynomial Approximation (NEW)
+// =============================================================================
+// GELU'(x) = Φ(x) + x*φ(x) where Φ is CDF, φ is PDF of standard normal
+// Uses piecewise polynomials for high accuracy
+// =============================================================================
+
+// Degree-16 polynomial for GELU'(x) over [-3, 3]
+// Coefficients from Sollya fpminimax
+constexpr float GELU_DERIV_CORE_C0 = 0.49999025f;
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: ## Change 1: Core polynomial - odd-function decomposition
### Proposed change

The degree-16 polynomial over [-3, 3.1719] (17 coefficients `GELU_DERIV_CORE_C0`
through `GELU_DERIV_CORE_C16`) was replaced by a degree-8 polynomial in u = x^2 (9 coefficients
`GELU_DERIV_H0` through `GELU_DERIV_H8`) using the decomposition:

```
GELU'(x) = 0.5 + x * h(x^2)
```

### Why it works

GELU'(x) = Φ(x) + x·φ(x), and the identity **GELU'(x) + GELU'(-x) = 1** holds
exactly (provable from Φ(x) + Φ(-x) = 1 and φ(x) = φ(-x)). This means
GELU'(x) − 0.5 is an **odd function** of x, so it can be written as x · h(x^2)
for some function h. The polynomial h(u) only needs degree 8 in u to achieve
max ULP = 1 in BF16 over the entire [-3, 3.1719] range.

### Before vs After

| Metric | Before | After |
|---|---|---|
| Coefficients | 17 (`C0`–`C16`) | 9 (`H0`–`H8`) |
| Horner operations | ~32 (degree-16 in x) | ~11 (degree-8 in u, plus u=x^2, x·h, +0.5) |
| Conditionals for sign | None | None (odd form handles sign automatically) |
| Accuracy at x = 0 | ≈ 0.49999 | Exactly 0.5 (structural: 0 · h(0) = 0) |
| Max ULP (BF16, DAZ+FTZ) | 1 | 1 |

**Before:**

```cpp
// 17 coefficients, degree 16 in x
constexpr float GELU_DERIV_CORE_C0  = 0.49999025f;
constexpr float GELU_DERIV_CORE_C1  = 0.79791743f;
constexpr float GELU_DERIV_CORE_C2  = 1.7774066e-4f;
constexpr float GELU_DERIV_CORE_C3  = -0.26595619f;
constexpr float GELU_DERIV_CORE_C4  = -4.5130015e-4f;
constexpr float GELU_DERIV_CORE_C5  = 5.9655134e-2f;
constexpr float GELU_DERIV_CORE_C6  = 4.1692785e-4f;
constexpr float GELU_DERIV_CORE_C7  = -9.2725726e-3f;
constexpr float GELU_DERIV_CORE_C8  = -1.8569338e-4f;
constexpr float GELU_DERIV_CORE_C9  = 1.0372815e-3f;
constexpr float GELU_DERIV_CORE_C10 = 4.4518791e-5f;
constexpr float GELU_DERIV_CORE_C11 = -8.0475649e-5f;
constexpr float GELU_DERIV_CORE_C12 = -5.8852397e-6f;
constexpr float GELU_DERIV_CORE_C13 = 3.8346534e-6f;
constexpr float GELU_DERIV_CORE_C14 = 4.0404797e-7f;
constexpr float GELU_DERIV_CORE_C15 = -8.3111068e-8f;
constexpr float GELU_DERIV_CORE_C16 = -1.1251415e-8f;

// Evaluation: straight Horner on x
v_elseif(x >= -3.0f) {
    result = PolynomialEvaluator::eval(
        x,
        GELU_DERIV_CORE_C0,  GELU_DERIV_CORE_C1,  GELU_DERIV_CORE_C2,
        GELU_DERIV_CORE_C3,  GELU_DERIV_CORE_C4,  GELU_DERIV_CORE_C5,
        GELU_DERIV_CORE_C6,  GELU_DERIV_CORE_C7,  GELU_DERIV_CORE_C8,
        GELU_DERIV_CORE_C9,  GELU_DERIV_CORE_C10, GELU_DERIV_CORE_C11,
        GELU_DERIV_CORE_C12, GELU_DERIV_CORE_C13, GELU_DERIV_CORE_C14,
        GELU_DERIV_CORE_C15, GELU_DERIV_CORE_C16);
}
```

**After:**

```cpp
// 9 coefficients, degree 8 in u = x^2
constexpr float GELU_DERIV_H0 = 7.9788309336e-01f;
constexpr float GELU_DERIV_H1 = -2.6593554020e-01f;
constexpr float GELU_DERIV_H2 = 5.9766173363e-02f;
constexpr float GELU_DERIV_H3 = -9.4142099842e-03f;
constexpr float GELU_DERIV_H4 = 1.1061388068e-03f;
constexpr float GELU_DERIV_H5 = -9.7448595625e-05f;
constexpr float GELU_DERIV_H6 = 6.0921474869e-06f;
constexpr float GELU_DERIV_H7 = -2.3764030743e-07f;
constexpr float GELU_DERIV_H8 = 4.2734988881e-09f;

// Evaluation: Horner on u = x^2, then reconstruct via odd-function identity
v_elseif(x >= -3.0f) {
    sfpi::vFloat u = x * x;
    sfpi::vFloat h = PolynomialEvaluator::eval(
        u,
        GELU_DERIV_H0, GELU_DERIV_H1, GELU_DERIV_H2,
        GELU_DERIV_H3, GELU_DERIV_H4, GELU_DERIV_H5,
        GELU_DERIV_H6, GELU_DERIV_H7, GELU_DERIV_H8);
    result = 0.5f + x * h;
}
```

## Change 2: Elimination of the LEFT polynomial
### Proposed change

The degree-8 shifted polynomial for x ∈ [-5, -3] (9 coefficients
`GELU_DERIV_LEFT_C0` through `C8`, evaluated at t = x + 4) was removed entirely.
The asymptotic tail region was extended from (-13.375, -5] to (-13.375, -3).

### Why it works

The asymptotic formula GELU'(x) ≈ φ(x) · (x − 1/x + 1/x^3) with Mills ratio
correction (1 − 1/x^2 + 1/x^4) already achieves **max ULP ≤ 1** across the
full [-5, -3] range in accurate mode. The `x_times_exp_negative_tail` helper
does Cody-Waite range reduction yielding |r| < 0.5 for any negative t, so it
works identically at x = -3 (t = -4.5, |r| = 0.34) as at x = -13 (t = -84.5).

The LEFT polynomial was simply redundant, the tail formula it was bridging
already covers both sides with ULP ≤ 1.

### Before vs After

| Metric | Before | After |
|---|---|---|
| LEFT coefficients | 9 (`LEFT_C0`–`C8`) | 0 (removed) |
| Piecewise branches | 4 (saturate-1, core, left, tail) | 3 (saturate-1, core, tail) |

**Removed code:**

```cpp
// These 9 coefficients were removed
constexpr float GELU_DERIV_LEFT_C0 = -5.03619085066020488739013671875e-4f;
constexpr float GELU_DERIV_LEFT_C1 = -1.872996450401842594146728515625e-3f;
constexpr float GELU_DERIV_LEFT_C2 = -3.2110414467751979827880859375e-3f;
constexpr float GELU_DERIV_LEFT_C3 = -3.30785498954355716705322265625e-3f;
constexpr float GELU_DERIV_LEFT_C4 = -2.20105494372546672821044921875e-3f;
constexpr float GELU_DERIV_LEFT_C5 = -8.814539178274571895599365234375e-4f;
constexpr float GELU_DERIV_LEFT_C6 = -9.72292109508998692035675048828125e-5f;
constexpr float GELU_DERIV_LEFT_C7 = 9.22545223147608339786529541015625e-5f;
constexpr float GELU_DERIV_LEFT_C8 = 3.57478638761676847934722900390625e-5f;

// This entire branch was removed
v_elseif(x >= -5.0f) {
    sfpi::vFloat t = x + 4.0f;
    result = PolynomialEvaluator::eval(
        t,
        GELU_DERIV_LEFT_C0, GELU_DERIV_LEFT_C1, GELU_DERIV_LEFT_C2,
        GELU_DERIV_LEFT_C3, GELU_DERIV_LEFT_C4, GELU_DERIV_LEFT_C5,
        GELU_DERIV_LEFT_C6, GELU_DERIV_LEFT_C7, GELU_DERIV_LEFT_C8);
}
```

The existing tail branch (`v_elseif(x > -13.375f)`) now directly follows the
core branch, naturally absorbing the [-5, -3] range.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_program_factory.cpp [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+
+    for (uint32_t i = 0, num_tiles_written = 0; i < num_cores; i++) {
+        CoreCoord core = {i / num_cores_y, i % num_cores_y};
+        uint32_t num_tiles_per_core = 0;
+        if (core_group_1.contains(core)) {
+            num_tiles_per_core = num_tiles_per_core_group_1;
+        } else if (core_group_2.contains(core)) {
+            num_tiles_per_core = num_tiles_per_core_group_2;
+        } else {
+            TT_ASSERT(false, "Core not in specified core ranges");
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_program_factory.cpp]: Please do not use TT_ASSERT. Use TT_FATAL or TT_THROW instead. Here would be TT_FATAL.

**Review by bbradelTT — APPROVED** [review]
Looks ok assuming comments by @fvranicTT are addressed.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_program_factory.cpp (hunk 5 above)
Comment (epam-iaroslav-voitovych) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_program_factory.cpp]: Thank you! Applied — both `TT_ASSERT(false, ...)` replaced with `TT_FATAL(false, ...)` in `gelu_bw_program_factory.cpp` (in `create()` and `override_runtime_arguments()`).

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 4 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you for the detailed proposals, Filip! Both implemented:

**1. Odd-function decomposition (CORE):** Replaced degree-16 in x (17 coefficients, ~32 ops) with degree-8 in u=x² (9 coefficients, ~12 ops) using GELU'(x) = 0.5 + x·h(x²). Also gives GELU'(0) = 0.5 exactly (structural).

**2. LEFT polynomial elimination:** Removed the [-5, -3) shifted polynomial entirely (9 coefficients, ~10 ops + 1 branch). The asymptotic tail with Mills ratio correction already covers (-13.375, -3) at Max ULP ≤ 1. Reduces from 4 to 3 piecewise regions.

Combined result: **16K tiles: 2,376 → 1,388 us (42% faster)**. Max ULP = 1 unchanged. All 96 tests pass (30 C++ + 66 Python across both main and experimental APIs).

Note: after the 2026-04-01 rebase, these changes apply to the shared kernel `ckernel_sfpu_gelu.h` on main (merged via PR #36366), benefiting both APIs through the shared `gelu_derivative_tile<false>()` primitive.

**Review by fvranicTT — APPROVED** [review]

**Review by dgomezTT — APPROVED** [review]

**Review by williamlyTT — APPROVED** [review]

**Review by amahmudTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_device_operation.cpp [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+    const auto& input_tensor = tensor_args.input;
+    const auto& grad_output = tensor_args.grad_output;
+    const auto& input_shape = input_tensor.padded_shape();
+    operation::Hash hash = operation::hash_operation<GeluBwDeviceOperation>(
+        args,
+        input_tensor.dtype(),
+        input_tensor.memory_config(),
+        grad_output.dtype(),
+        grad_output.memory_config(),
+        input_shape.volume());
```
Comment (dchenTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/gelu_bw_device_operation.cpp:115]: Hash on input shape volume is an overkill and may be unsafe. But it has been like that for a while. The new unary_infra has addressed that. Probably OK for this PR.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/kernels/compute/eltwise_bw_gelu_poly.cpp [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+#include "api/compute/eltwise_unary/eltwise_unary.h"
+#include "api/compute/eltwise_binary_sfpu.h"
+#include "api/compute/binary_bitwise_sfpu.h"
+#include "api/compute/binary_shift.h"
+#include "api/compute/compute_kernel_api.h"
+#include "api/compute/eltwise_unary/gelu.h"
+
+void kernel_main() {
+    uint32_t per_core_block_cnt = get_arg_val<uint32_t>(0);
+    uint32_t per_core_block_size = get_arg_val<uint32_t>(1);
```
Comment (dchenTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/gelu_bw/device/kernels/compute/eltwise_bw_gelu_poly.cpp:22]: FYI there will be more visible perf gain when per_core_block_size is more than 1. Probably not this PR. Up to you.

**Review by mateusznowakTT — APPROVED** [review]

**Comment by azaytsev-epam** [comment]
bug has been created
https://github.com/tenstorrent/tt-metal/issues/42677
