### PR TITLE
#24823: Add isin operation to TTNN Python and C++ APIs

### LINKED ISSUE #26065: Add torch.isin OP
### Describe the bug

Based on missing functionality, add torch.isin OP
https://docs.pytorch.org/docs/stable/generated/torch.isin.html

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by jbbieniekTT**
### Ticket
#26065

### Problem description
provide support for ttnn's equivalent of `torch.isin` - base algorithm that is subject to optimisation

### What's changed
implement multi-core isin

### Support
- OP arguments: any two tensors of any arbitrary size that fit in DRAM, together with the uint32 output tensor
- output dtype: uint32
- layouts: row-major or tile
- dtypes: int32, uint32
- shapes: any as long as it fits in chip's DRAM
- only interleaved
- scalars: to be supported

### Theory of operation
Presentation: https://docs.google.com/presentation/d/1t6KABlgzMuTBWJ8DK4nAV8KfUIJ0dQfaySce9POgMTY/edit?usp=sharing
#### TL;DR:
- convert `elements` and `test_elements` into row-major 1D,
- split them into chunks (big enough to fill the whole L1 of each core with elements + test_elements + output chunks),
- for each input chunk, scan for its values inside each of test_elements chunks,
- output UINT32 `0x00000000` and `0xFFFFFFFF`
**Complexity: `O(input_volume^2/num_cores)`**

### Perf graph (from [1024, 1] till [1024, 1024]):
output_plot

### Perf graph (from [16384, 1] till [16384, 1024]):
output_plot_2

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy quick](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-quick-trigger.yaml) CI passes (if applicable)
- [ ] [TG demo tests, for Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-demo-tests.yaml) CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml) CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by cmaryanTT** [comment]
Can you please update the description to state what is and what isn’t supported. OP arguments/variants, shapes, layouts, dtypes, etc. Every commit of a new OP should have these details in the PR description.

**Comment by jbbieniekTT** [comment]
> Can you please update the description to state what is and what isn’t supported. OP arguments/variants, shapes, layouts, dtypes, etc. Every commit of a new OP should have these details in the PR description.

done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+        ttnn::experimental::isin,
+        doc,
+        ttnn::pybind_overload_t{
+            [](const OperationType& self,
+               const Tensor& elements,
+               const Tensor& test_elements,
+               const bool& assume_unique,
+               const bool& invert,
+               const std::optional<MemoryConfig>& memory_config,
+               const std::optional<Tensor>& opt_out,
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: "opt out" means you are not taking part in something. Please change the name. Something like:
- opt_output
- optional_out
- optional_output
Preferably the last one.

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+               const QueueId& queue_id = DefaultQueueId) -> Tensor {
+                return self(queue_id, elements, test_elements, assume_unique, invert, memory_config, opt_out);
+            },
+            py::arg("elements").noconvert(),
+            py::arg("test_elements").noconvert(),
+            py::kw_only(),
+            py::arg("assume_unique") = false,
+            py::arg("invert") = false,
+            py::arg("memory_config") = std::nullopt,
+            py::arg("out") = std::nullopt,
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Should this be the same as the parameter (opt_out or what it might be changed to)?

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+#include "isin.hpp"
+
+#include <optional>
+
+namespace ttnn::operations::experimental::isin::detail {
+
+using namespace ttnn;
+
+void bind_isin_operation(py::module& module) {
+    auto doc = "";
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Please add the doc string.

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+#include "ttnn/tensor/tensor.hpp"
+
+namespace ttnn::operations::experimental::isin::common {
+
+using namespace tt;
+using namespace tt_metal;
+
+constexpr int32_t FIRST_DIMENSION = 0;
+
+// constexpr auto INDEX_HINT_TENSOR_DATA_TYPE = DataType::INT32;
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp]: Should be removed?

File: tests/ttnn/unit_tests/operations/test_isin.py [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+    assert torch_isin_result.count_nonzero() == ttnn.to_torch(ttnn_isin_result).count_nonzero()
+
+
+@pytest.mark.parametrize(
+    "elements_shape, test_elements_shape, expected_num_program_cache_entries",
+    [
+        ([10], [20], 1),
+        ([20], [10], 1),
+        ([10, 10], [20, 20], 4),
+        # (
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/test_isin.py]: Remove?

File: tests/ttnn/unit_tests/operations/test_isin.py [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+                [[[i ^ j ^ k ^ l for i in range(0, 10)] for j in range(0, 10)] for k in range(0, 10)]
+                for l in range(0, 10)
+            ],
+            [28 * i for i in range(0, 20)],
+            ttnn.int32,
+            ttnn.TILE_LAYOUT,
+        ),
+    ],
+)
+def test_isin_normal(elements, test_elements, dtype, layout, device):
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/test_isin.py]: Please consider renaming.
I don't know what you mean by normal. That makes me think of a normal distribution.

File: tests/ttnn/unit_tests/operations/test_isin.py [hunk 7]
```diff
@@ -0,0 +1,140 @@
...
+    test_elements_torch = torch.tensor(test_elements, dtype=torch_dtype)
+
+    elements_ttnn = ttnn.from_torch(elements_torch, device=device, layout=layout)
+    test_elements_ttnn = ttnn.from_torch(test_elements_torch, device=device, layout=layout)
+
+    torch_isin_result = torch.isin(elements_torch, test_elements_torch)
+    ttnn_isin_result = ttnn.experimental.isin(elements_ttnn, test_elements_ttnn)
+
+    assert torch_isin_result.shape == ttnn_isin_result.shape
+    assert torch_isin_result.count_nonzero() == ttnn.to_torch(ttnn_isin_result).count_nonzero()
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/test_isin.py]: Is there a reason to not test that the two results are identical?

File: tests/ttnn/unit_tests/operations/test_isin.py [hunk 8]
```diff
@@ -0,0 +1,140 @@
...
+        ([10], [20], 1),
+        ([20], [10], 1),
+        ([10, 10], [20, 20], 4),
+        # (
+        #     [10, 100, 2, 10, 50], [20, 10, 20, 10], 5
+        # ),
+        ([5, 10, 5, 1, 1, 1, 1, 1, 1, 5], [20], 3),
+    ],
+)
+def test_isin_callback_random(elements_shape, test_elements_shape, expected_num_program_cache_entries, device):
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/test_isin.py]: Please consider renaming.
I don't know what you mean by callback. That makes me think of callback functions.

File: tests/ttnn/unit_tests/operations/test_isin.py [hunk 9]
```diff
@@ -0,0 +1,140 @@
...
+# SPDX-License-Identifier: Apache-2.0
+
+import pytest
+import torch
+import ttnn
+
+from tests.ttnn.utils_for_testing import assert_allclose
+
+
+def select_torch_dtype(ttnn_dtype):
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/test_isin.py:12]: Should this be common somewhere?

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp [hunk 10]
```diff
@@ -0,0 +1,98 @@
...
+    if (tensor_args.optional_out) {
+        TT_FATAL(
+            tensor_args.optional_out->dtype() == OUTPUT_TENSOR_DATA_TYPE,
+            "Preallocated output should be of uint8 dtype");
+        return *tensor_args.optional_out;
+    }
+    return create_device_tensor(compute_output_specs(args, tensor_args), tensor_args.elements_tensor.device());
+}
+
+operation::Hash IsInDeviceOperation::compute_program_hash(
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp]: Would it be possible to not specify this method and use the default program hash?

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp [hunk 11]
```diff
@@ -0,0 +1,193 @@
...
+#include "tt-metalium/work_split.hpp"
+#include "ttnn/operations/experimental/isin/device/isin_device_op.hpp"
+#include "ttnn/operations/experimental/isin/isin_cbs.hpp"
+
+namespace ttnn::operations::experimental::isin {
+
+using namespace common;
+
+namespace {
+constexpr uint32_t BIT_MASK_32 = 32 - 1;
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: Please do something like
```
constexpr CEIL32_BIT_MASK = 0x1f;
```

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp [hunk 12]
```diff
@@ -0,0 +1,193 @@
...
+
+inline uint64_t ceil32(const uint64_t& number) {
+    return ((number & BIT_MASK_32) == 0) ? number : ((number | BIT_MASK_32) + 1);
+}
+
+inline bool is_pow2_min32(const uint64_t& number) { return ((number & (number - 1)) == 0) && number >= 32; }
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: Is this unused?

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp [hunk 13]
```diff
@@ -0,0 +1,193 @@
...
+#include "ttnn/operations/experimental/isin/isin_cbs.hpp"
+
+namespace ttnn::operations::experimental::isin {
+
+using namespace common;
+
+namespace {
+constexpr uint32_t BIT_MASK_32 = 32 - 1;
+
+inline uint64_t ceil32(const uint64_t& number) {
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: Is this unused?

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp [hunk 14]
```diff
@@ -0,0 +1,193 @@
...
+    return ((number & BIT_MASK_32) == 0) ? number : ((number | BIT_MASK_32) + 1);
+}
+
+inline bool is_pow2_min32(const uint64_t& number) { return ((number & (number - 1)) == 0) && number >= 32; }
+
+// inline std::vector<CoreCoord> get_worker_cores(const CoreCoord& compute_grid_size) {
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: Please delete commented out code, here and below.

If it is needed, consider using log_debug or in kernels
`#ifdef DEBUG`

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp [hunk 15]
```diff
@@ -0,0 +1,193 @@
...
+        static_cast<uint32_t>(IsInCB::OUTPUT),
+        elements_tensor.logical_volume(),
+        test_elements_tensor.logical_volume(),
+        single_fetch_subchunk_size,
+        static_cast<uint32_t>(invert)};
+    TensorAccessorArgs(*elements_buffer).append_to(compile_time_args);
+    TensorAccessorArgs(*test_elements_buffer).append_to(compile_time_args);
+    TensorAccessorArgs(*output_buffer).append_to(compile_time_args);
+
+    const uint32_t subchunks_num =
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp:77]: Please add an explanatory comment.

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp [hunk 16]
```diff
@@ -0,0 +1,54 @@
...
+using namespace tt::tt_metal;
+
+struct IsInProgramFactory {
+    struct shared_variables_t {
+        KernelHandle reader_kernel_id;
+        KernelHandle writer_kernel_id;
+        std::vector<CoreCoord> cores;
+    };
+
+    static constexpr const char* READER_KERNEL_PATH =
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp]: Unless this is used in multiple places in the code base, this should not be in the header / struct. Just have it near or in CreateKernel.

**Review by bbradelTT — COMMENTED** [review]
Please add high level descriptions of what the code is doing, especially in the kernels.

**Comment by bbradelTT** [comment]
For Support in the description, what about interleaved and sharding?

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp (hunk 12 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: Redundant artifact

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp (hunk 13 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: Redundant artifact

File: tests/ttnn/unit_tests/operations/test_isin.py (hunk 5 above)
Comment (jbbieniekTT) [reply tests/ttnn/unit_tests/operations/test_isin.py]: Yeah, this case is too big for DRAM

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp (hunk 4 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 3 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 2 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: This is in accordance with Torch, and this parameter is optional

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 1 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Went with `optional_out`

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp (hunk 14 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: For now, it is unnecessary and can be removed

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp (hunk 15 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp:77]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp (hunk 16 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp]: Done

File: tests/ttnn/unit_tests/operations/test_isin.py (hunk 9 above)
Comment (jbbieniekTT) [reply tests/ttnn/unit_tests/operations/test_isin.py:12]: Perhaps yes, I just usually define it

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp (hunk 11 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.cpp]: Removed

File: tests/ttnn/unit_tests/operations/test_isin.py (hunk 6 above)
Comment (jbbieniekTT) [reply tests/ttnn/unit_tests/operations/test_isin.py]: renamed to "typical"

File: tests/ttnn/unit_tests/operations/test_isin.py (hunk 7 above)
Comment (jbbieniekTT) [reply tests/ttnn/unit_tests/operations/test_isin.py]: this is a comparison of torch's BoolTensor and ttnn's uint32 tensor - uint32 is enforced by default ttnn integer compatibility across its ops

File: tests/ttnn/unit_tests/operations/test_isin.py (hunk 8 above)
Comment (jbbieniekTT) [reply tests/ttnn/unit_tests/operations/test_isin.py]: this tests program cache and is run with randomly generated data

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp (hunk 10 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp]: yeah, done

**Comment by jbbieniekTT** [comment]
> For Support in the description, what about interleaved and sharding?

interleaved only

File: ttnn/cpp/ttnn/operations/experimental/isin/isin.cpp [hunk 17]
```diff
@@ -0,0 +1,142 @@
...
+        is_in_preprocessing_result.preprocessed_elements_tensor.layout();
+    is_in_preprocessing_result.elements_size = is_in_preprocessing_result.preprocessed_elements_tensor.logical_volume();
+    is_in_preprocessing_result.test_elements_size =
+        is_in_preprocessing_result.preprocessed_test_elements_tensor.logical_volume();
+    is_in_preprocessing_result.single_fetch_elements_number = calculate_max_fetch_size(
+        is_in_preprocessing_result.preprocessed_elements_tensor,
+        is_in_preprocessing_result.preprocessed_test_elements_tensor);
+
+    if (is_in_preprocessing_result.preprocessed_elements_tensor.layout() != OUTPUT_TENSOR_LAYOUT) {
+        is_in_preprocessing_result.preprocessed_elements_tensor =
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin.cpp:80]: Shouldn't the new TensorAccessor make it easy to iterate through all locations without having to change the input to suit some specific requirements?

Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin.cpp:80]: this is because the input tensor is flattened to 1D (because the search space is global for both tensor arguments) and if it is row-major, then it avoids the enforced tile padding overhead, the algorithm also depends on the fact that it should be straightforward to access as many continuously located data bytes as possible to reduce the amount of DRAM swaps

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp [hunk 18]
```diff
@@ -0,0 +1,119 @@
...
+    const uint32_t subchunks_per_core = get_arg_val<uint32_t>(2);
+    const uint32_t subchunks_offset = get_arg_val<uint32_t>(3);
+
+    const auto elements_addr_gtor =
+        TensorAccessor{ctas.elements_accessor_args, elements_buffer_address, ctas.elements_size * 4};
+    const auto test_elements_addr_gtor =
+        TensorAccessor{ctas.test_elements_accessor_args, test_elements_buffer_address, ctas.test_elements_size * 4};
+
+    /*
+        for every subchunk (part of a stick) of the elements tensor - to wchi an analogous output chunk
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp]: typo: wchi

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp [hunk 19]
```diff
@@ -0,0 +1,22 @@
...
+#include <type_traits>
+
+namespace ttnn::operations::experimental::isin {
+
+using namespace tt;
+
+enum class IsInCB : std::underlying_type_t<CBIndex> {
+    ELEMENTS = CBIndex::c_0,
+    TEST_ELEMENTS = CBIndex::c_1,
+    // INDEX_HINT = CBIndex::c_2,
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp]: Should be removed?

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 2 above)
Comment (bbradelTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Ok, I'm just not sure if having different names will work. Which pytest uses optional_out? If currently there isn't one, please add one.

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+               const bool& invert,
+               const std::optional<MemoryConfig>& memory_config,
+               const std::optional<Tensor>& optional_out,
+               const QueueId& queue_id = DefaultQueueId) -> Tensor {
+                return self(queue_id, elements, test_elements, assume_unique, invert, memory_config, optional_out);
+            },
+            py::arg("elements").noconvert(),
+            py::arg("test_elements").noconvert(),
+            py::kw_only(),
+            py::arg("assume_unique") = false,
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp:61]: Does assume_unique help with performance currently, or will it in the future?

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp [hunk 21]
```diff
@@ -0,0 +1,119 @@
...
+                output_subchunk_ptr[elements_index] = 0xFFFFFFFF;
+                break;
+            }
+        }
+    }
+}
+
+/*
+    When a core begins processing of a given chunk, the output chunk is fully erased with zeroes
+    (or filled with ones, if the invert flag is set) - this makes sure that the output chunk is properly filled
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp:47]: Where is the logic for that?

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp [hunk 22]
```diff
@@ -0,0 +1,119 @@
...
+    volatile tt_l1_ptr elements_number_type* elements_subchunk_ptr =
+        reinterpret_cast<volatile tt_l1_ptr elements_number_type*>(elements_l1_read_addr);
+    volatile tt_l1_ptr elements_number_type* test_elements_subchunk_ptr =
+        reinterpret_cast<volatile tt_l1_ptr elements_number_type*>(test_elements_l1_read_addr);
+    volatile tt_l1_ptr output_number_type* output_subchunk_ptr =
+        reinterpret_cast<volatile tt_l1_ptr output_number_type*>(output_l1_write_addr);
+    for (uint32_t elements_index = 0; elements_index < elements_subchunk_size; ++elements_index) {
+        for (uint32_t test_elements_index = 0; test_elements_index < test_elements_subchunk_size;
+             ++test_elements_index) {
+            if (elements_subchunk_ptr[elements_index] == test_elements_subchunk_ptr[test_elements_index]) {
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp:37]: What if invert is true?

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 23]
```diff
@@ -0,0 +1,58 @@
...
+            py::arg("invert") = false,
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp:62]: Please add a test for invert=True

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 24]
```diff
@@ -0,0 +1,58 @@
...
+            py::arg("memory_config") = std::nullopt,
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Please add a test for memory_config

**Review by sjameelTT — APPROVED** [review]
Approving for the changes to TM comments

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 20 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp:61]: this *might* do increase performance, but i am not sure if it is the case on our HW architecture, however i place it here for compatibility with Torch's API

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp (hunk 18 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp (hunk 19 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp (hunk 22 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp:37]: Fixed

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 23 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp:62]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 24 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp (hunk 21 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_reader.cpp:47]: Logic applied

**Comment by jbbieniekTT** [comment]
@bbradelTT i noted that actually `torch.isin` doesn't support optional out tensors, so i removed this from here as well

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 25]
```diff
@@ -22,11 +22,14 @@ void bind_isin_operation(py::module& module) {
...
             Parameters:
-                * `elements` (Tensor): integers to be masked with 0s or 1s depending no their extence in test_elements
+                * `elements` (Tensor): integers to be masked with 0s or 1s depending no their existence in test_elements and the invert flag
                 * `test_elements` (Tensor): all integers
 
             Keyword Arguments:
                 * `invert` (bool): invert nonzero output with zeroes and vice versa
+
+            Notes:
+                * `assume_unique` (bool): does nothing for the time being, but is originally intended to be an optimization technique copied from Torch
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Please do not say "copied from Torch"

Maybe something like "but is reserved for potential future optimizations"

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 26]
```diff
@@ -0,0 +1,61 @@
...
+        module,
+        ttnn::experimental::isin,
+        doc,
+        ttnn::pybind_overload_t{
+            [](const OperationType& self,
+               const Tensor& elements,
+               const Tensor& test_elements,
+               const bool& assume_unique,
+               const bool& invert,
+               const std::optional<MemoryConfig>& memory_config,
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: If this has requirements (e.g. needs to be row major, or has to be DRAM) then the doc string should list them.

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 25 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Corrected

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 26 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Applied

Comment (bbradelTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Based on an off-line discussion, memory_config is always DRAM interleaved. It's better to not have it as a parameter then.

**Review by bbradelTT — APPROVED** [review]

**Review by aczajkowskiTT — APPROVED** [review]
Thanks for adding the perf graphs

**Comment by cmaryanTT** [comment]
Can you please mention the theory of operation in the PR description. Is this sort + N * binary search based?

**Comment by jbbieniekTT** [comment]
> Can you please mention the theory of operation in the PR description. Is this sort + N * binary search based?

added, this could be nlogn sort + linear search, however kernel processing is done in reader in L1 and i don't want to rely on an L1 write pointer being accessible for both reading and writing - this is counterintuitive to the CB design. 2 optimisations are planned for this:
- implementation of a heuristic allowing for effective cost-based splitting of row-major tensors for processing, balancing the chunk sizes, utilised core numbers and DRAM swaps;
- own implementation of LLKs not only for isin, but for scatter, unique, etc. as well to avoid reader kernel-only dependence and to fully utilise compute engine

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 2 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: this parameter has been removed, because even though Torch often provides an optional `out` parameter, it is not the case here

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp [hunk 27]
```diff
@@ -0,0 +1,49 @@
+// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
+//
+// SPDX-License-Identifier: Apache-2.0
+
+#pragma once
+
+#include "../isin_common.hpp"
```
Comment (sminakov-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp:7]: Please avoid include paths with `../`

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_writer.cpp [hunk 28]
```diff
@@ -0,0 +1,34 @@
...
+//
+// SPDX-License-Identifier: Apache-2.0
+
+#include "dataflow_api.h"
+
+#include "../isin_common.hpp"
+
+namespace {
+
+}
```
Comment (sminakov-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_writer.cpp]: Pls remove

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_common.hpp [hunk 29]
```diff
@@ -0,0 +1,123 @@
...
+    using std_type = uint16_t;
+};
+
+template <>
+struct df_to_std<DataFormat::UInt8> {
+    using std_type = uint8_t;
+};
+
+template <DataFormat df>
+using std_type_t = typename df_to_std<df>::std_type;
```
Comment (sminakov-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_common.hpp:44]: Do you really need this std_type_t and df_to_std?
It seems like the only usage you have of it is `sizeof(std_type_t<...>)`. You can just have a constexpr function to get the size based on DataFormat, we may even have one to do this already

**Review by sminakov-tt — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_common.hpp (hunk 29 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_common.hpp:44]: i switched to using them as types, actually, as it should be :D

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_writer.cpp (hunk 28 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/dataflow/isin_writer.cpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp (hunk 27 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_program_factory.hpp:7]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.hpp [hunk 30]
```diff
@@ -0,0 +1,50 @@
...
+#include "isin_device_op_types.hpp"
+#include "isin_program_factory.hpp"
+
+#include "ttnn/decorators.hpp"
+
+namespace ttnn::operations::experimental::isin {
+
+using namespace common;
+using namespace tt;
+using namespace tt::tt_metal;
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.hpp]: Remove `using` from headers

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp [hunk 31]
```diff
@@ -0,0 +1,77 @@
...
+    }
+    return create_device_tensor(compute_output_specs(args, tensor_args), tensor_args.elements_tensor.device());
+}
+
+IsInDeviceOperation::invocation_result_t IsInDeviceOperation::invoke(
+    const Tensor& elements_tensor,
+    const Tensor& test_elements_tensor,
+    const uint32_t& single_fetch_subchunk_size,
+    const bool& assume_unique,
+    const bool& invert,
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp]: Pass primitive types by value

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op_types.hpp [hunk 32]
```diff
@@ -0,0 +1,34 @@
...
+
+#include "ttnn/tensor/tensor.hpp"
+
+#include <optional>
+
+namespace ttnn::operations::experimental::isin {
+
+using namespace common;
+using namespace ttnn;
+using namespace tt::tt_metal;
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op_types.hpp]: Same here - remove aliases from headers

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 33]
```diff
@@ -0,0 +1,58 @@
...
+
+            Parameters:
+                * `elements` (Tensor): integers to be masked with 0s or 1s depending no their existence in test_elements and the invert flag
+                * `test_elements` (Tensor): all integers
+
+            Keyword Arguments:
+                * `invert` (bool): invert nonzero output with zeroes and vice versa
+
+            Notes:
+                * `assume_unique` (bool): does nothing for the time being, but is reserved for potential future optimizations
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp:32]: What is the point of adding this now then?

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp [hunk 34]
```diff
@@ -0,0 +1,20 @@
...
+//
+// SPDX-License-Identifier: Apache-2.0
+
+#pragma once
+
+#include "ttnn/tensor/tensor.hpp"
+
+namespace ttnn::operations::experimental::isin::common {
+
+using namespace tt;
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp]: Ditto

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp [hunk 35]
```diff
@@ -0,0 +1,21 @@
...
+
+#pragma once
+
+#include "hostdevcommon/kernel_structs.h"
+
+#include <type_traits>
+
+namespace ttnn::operations::experimental::isin {
+
+using namespace tt;
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp:13]: Ditto

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp [hunk 36]
```diff
@@ -0,0 +1,58 @@
...
+        R"doc(
+            This operator returns a uint32 tensor of the same specification as
+            the elements tensor with those of the elements filled out with nonzero
+            values (this rule can be inverted with the invert flag) that correspond
+            to those of the values from the elements tensor that are contained in the
+            test_elements tensor.
+
+            Parameters:
+                * `elements` (Tensor): integers to be masked with 0s or 1s depending no their existence in test_elements and the invert flag
+                * `test_elements` (Tensor): all integers
```
Comment (omilyutin-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: This description is very hard to parse. Is it possible to provide an example?

**Review by omilyutin-tt — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 36 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp (hunk 35 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_cbs.hpp:13]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp (hunk 34 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_common.hpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp (hunk 33 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin_pybind.cpp:32]: This is so as to reserve the keyword to preserve compatibility with Torch

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op_types.hpp (hunk 32 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op_types.hpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp (hunk 31 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.cpp]: Fixed

File: ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.hpp (hunk 30 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/isin_device_op.hpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin.cpp [hunk 37]
```diff
@@ -0,0 +1,138 @@
...
+void validate_inputs(const Tensor& elements, const Tensor& test_elements) {
+    TT_FATAL(
+        elements.dtype() == test_elements.dtype(),
+        "elements.dtype: {}, test_elements.dtype: {}, they must be equal",
+        enchantum::to_string(elements.dtype()),
+        enchantum::to_string(test_elements.dtype()));
+}
+
+uint32_t calculate_max_fetch_size(const Tensor& elements, const Tensor& test_elements) {
+    const auto l1_size_per_core = elements.device()->l1_size_per_core();
```
Comment (rfurko-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/isin.cpp:52]: I think there is a better way to estimate L1 memory capacity

i've seen something like: `device->l1_size_per_core() - device->allocator()->get_base_allocator_addr(tt::tt_metal::HalMemType::L1);`. That way if for some reason there are another allocated sharded tensors and this operation is called it will not OOM 

```
 a = ttnn.tensor() # large sharded tensor that takes 800kb of memory per core
 b, d = ttnn.tensor() # DRAM tensors that are used in operation itself
 ttnn.isin(b, d) -> will need to use less L1 memory due to `a` being allocated beforehand 
```

File: ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/compute/isin_sorter.cpp [hunk 38]
```diff
@@ -0,0 +1,21 @@
...
+#include "../isin_common.hpp"
+
+#include "ckernel_sfpu.h"
+
+#include <cstdint>
+
+namespace NAMESPACE {
+
+void MAIN {
+    constexpr auto ctas = get_ctas();
```
Comment (rfurko-tt) [inline ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/compute/isin_sorter.cpp]: remove this file?

Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/device/kernels/compute/isin_sorter.cpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/isin/isin.cpp (hunk 37 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/isin/isin.cpp:52]: Gotcha, this is a very interesting finding

File: ttnn/cpp/ttnn/operations/experimental/isin/CMakeLists.txt [hunk 39]
```diff
@@ -0,0 +1,23 @@
...
+
+target_sources(
+    ttnn_op_experimental_isin
+    PRIVATE
+        device/isin_device_op.cpp
+        device/isin_program_factory.cpp
+        isin.cpp
+)
+
+target_include_directories(ttnn_op_experimental_isin PRIVATE ${FixmeOpIncDirs})
```
Comment (tt-rkim) [inline ttnn/cpp/ttnn/operations/experimental/isin/CMakeLists.txt:15]: @cmaryanTT When is this being fixeD?

**Review by tt-rkim — APPROVED** [review]
How much more time do your tests add to the jobs?

**Comment by jbbieniekTT** [comment]
> How much more time do your tests add to the jobs?

they take around 80 seconds for the time being

**Comment by jbbieniekTT** [comment]
reduced them to almost 70 seconds

**Review by blozano-tt — APPROVED** [review]
Some file in this PR must have a singular owner. If you could hunt that down, and update CODEOWNERS, that would be appreciated.

**Comment by jbbieniekTT** [comment]
> Some file in this PR must have a singular owner. If you could hunt that down, and update CODEOWNERS, that would be appreciated.

I realized I touched `reshape_device_operation.cpp`, which is not owned by any of the people who had approved my PR before @blozano-tt did
