### PR TITLE
#33581: update ternary device operation

### LINKED ISSUE #33581: Fix program cache hashing for sharded tensors in Ternary device operation

### LINKED ISSUE #34398: Ternary op sharding performance optimization
Reference: #34132

### LINKED ISSUE #37632: WhereOp program cache collision when operands are implicitly broadcasted
### Component / Area

ops

### Issue Type (optional)

Bad Outputs

### Observed

When `ttnn.where` op is being executed two consecutive times, first time implicitly broadcasting the `true_value` tensor, and the second time implicitly broadcasting the `false_value` tensor, the outputs of the second op invocation are incorrect.

It appears that there's a program cache collision - if the program cache is cleared between the two invocations, the outputs are correct.

### Expected

Program cache should differentiate between the two variants of implicit broadcasting.

### 1. Steps (exact commands)

Minimal reproducer: [repro_where_bug.py](https://github.com/user-attachments/files/25237659/repro_where_bug.py)

### 2. Input data / link or description

N/A

### 3. Frequency

always

### 1. Software Versions

tt-metal commit: [430d1f4d95d8401df010d0d932807258e8605ab1](https://github.com/tenstorrent/tt-metal/commit/430d1f4d95d8401df010d0d932807258e8605ab1)

### 2. Hardware Details

N300

### Is this a regression?

Unknown

### Regression Details

_No response_

### Logs & Diagnostics

_No response_

### Priority

None

### Impact

_No response_

### PR DESCRIPTION
**Pull request by mouliraj-mcw**
### Ticket
Link to Github Issue #33581 

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist

- [ ] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml?query=branch:mouliraj/ternary_cache_issues)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:mouliraj/ternary_cache_issues)
- [ ] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:mouliraj/ternary_cache_issues)

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/eltwise/ternary/device/ternary_device_operation.cpp [hunk 1]
```diff
@@ -147,51 +198,115 @@ static ttnn::Shape compute_broadcasted_output_binary(const ttnn::Shape& a_shape,
...
+        auto height_padded = tt::round_up(tensor_height, grid_size.y * tt::constants::TILE_HEIGHT);
+        auto shard_height = tt::round_up(tt::div_up(height_padded, grid_size.y), tt::constants::TILE_HEIGHT);
+        auto shard_width = tt::round_up(tt::div_up(tensor_width, grid_size.x), tt::constants::TILE_WIDTH);
+        shard_shape = {shard_height, shard_width};
+    }
+    log_debug(tt::LogOp, "TernaryDeviceOperation: Generated shard spec using all {} worker cores", num_cores);
+    return ShardSpec(all_cores, shard_shape, ShardOrientation::ROW_MAJOR);
+}
+
+static MemoryConfig resolve_mem_config_actual(
```
Comment (KalaivaniMCW) [inline ttnn/cpp/ttnn/operations/eltwise/ternary/device/ternary_device_operation.cpp:175]: Test case : to verify resolve_mem_config 
3 inputs - each with diff no of cores and verify output mem config

File: ttnn/cpp/ttnn/operations/eltwise/ternary/device/ternary_device_operation.cpp [hunk 2]
```diff
@@ -147,51 +198,115 @@ static ttnn::Shape compute_broadcasted_output_binary(const ttnn::Shape& a_shape,
...
-        output_shard_spec =
-            adjust_to_shape(*input_b_shard_spec, tensor_args.input_tensor_b->padded_shape(), padded_output_shape);
-    } else if (input_c_shard_spec.has_value()) {
-        // C has a spec (either inherited from C or fallback to C) → adjust from C
-        TT_FATAL(tensor_args.input_tensor_c.has_value(), "Cannot adjust from input_c when tensor_c is not present");
-        auto padded_output_shape =
-            tensor_args.input_tensor_c->tensor_spec().tensor_layout().compute_padded_shape(output_shape);
-        output_shard_spec =
-            adjust_to_shape(*input_c_shard_spec, tensor_args.input_tensor_c->padded_shape(), padded_output_shape);
+static ShardSpec generate_shard_spec_all_cores(
```
Comment (KalaivaniMCW) [inline ttnn/cpp/ttnn/operations/eltwise/ternary/device/ternary_device_operation.cpp:143]: Say for TTT variant, all 3 inputs passed with Shard strategy , w/o core grid details or shard_shape. - a case that with test this

File: ttnn/cpp/ttnn/operations/eltwise/ternary/device/ternary_op_utils.cpp [hunk 3]
```diff
@@ -11,6 +12,127 @@
...
+    const auto rank = shape.rank();
+    uint64_t volume_except_last = 1;
+    for (int i = 0; i < static_cast<int>(rank) - 1; ++i) {
+        volume_except_last *= shape[i];
+    }
+    return (volume_except_last % shard[0]) != 0 or (shape[-1] % shard[1]) != 0;
+}
+
+// Check based on input specs and output memory config (two tensors, same shape and memory config).
+static bool is_native_L1_sharding_two(const TensorSpec& a, const TensorSpec& b, const tt::tt_metal::MemoryConfig& c) {
```
Comment (KalaivaniMCW) [inline ttnn/cpp/ttnn/operations/eltwise/ternary/device/ternary_op_utils.cpp]: You can name this fn `is_native_L1_sharding` as well.
function overloading should take care of the rest since the signatures are different

**Review by KalaivaniMCW — APPROVED** [review]

File: tests/ttnn/unit_tests/operations/eltwise/test_ternary_sharding.py [hunk 4]
```diff
@@ -1715,3 +1720,310 @@ def test_where_ttt_height_bcast_mixed_strategy_mixed_L1(device, dtype_pt, dtype_
...
+        shape=(192, 64),  # 768/4
+        core_grid=ttnn.CoreGrid(y=2, x=2),
+        strategy=ttnn.ShardStrategy.HEIGHT,
+        orientation=ttnn.ShardOrientation.ROW_MAJOR,
+        use_height_and_width_as_shard_shape=True,
+    )
+    # B: 12 cores, 2 ranges (row 0: 6 cores, row 1: 6 cores) -> grid.size() == 2, most cores
+    grid_2_ranges = ttnn.CoreRangeSet(
+        {
+            ttnn.CoreRange((0, 0), (0, 5)),  # 6 cores
```
Comment (mateusznowakTT) [inline tests/ttnn/unit_tests/operations/eltwise/test_ternary_sharding.py:1987]: There is https://github.com/tenstorrent/tt-umd/issues/2129 - I'm not sure when UMD submodule is updated in metal to pull fix, please make sure to test pairs that previously had conflicting hash (which was making binary cache to fail, see https://github.com/tenstorrent/tt-metal/issues/33910 )

Comment (mouliraj-mcw) [reply tests/ttnn/unit_tests/operations/eltwise/test_ternary_sharding.py:1987]: The issue appears to be fixed. I’ve also added a test case to verify it in the ternary.

**Review by mateusznowakTT — APPROVED** [review]
