### PR TITLE
Replace assert()/TT_ASSERT() with reliable checks in tests

### LINKED ISSUE #35592: Tests rely on assert() / TT_ASSERT() that are compiled out in Release builds
# Problem Statement

While working on PR #35587, I noticed a broader pattern across the tests/ directory:
many tests rely on assert() or TT_ASSERT() for test-critical precondition checks.

In Release builds, these assertions may be compiled out or disabled, which means:
	•	tests can continue execution with invalid assumptions
	•	failures may silently turn into false positives
	•	test behavior can differ between Debug and Release configurations

This makes test results less trustworthy, especially for CI configurations that run tests in Release mode.

Concrete Example

In tests/tt_metal/fabric/test_basic_1d_fabric.cpp, the following issues were observed:
	•	assert(...) used to validate topology + fabric config assumptions
	•	TT_ASSERT(...) used to enforce an expected device count

In Release builds, these checks do not reliably fire, allowing the test to proceed in an invalid state.
This was addressed in PR #35587 by replacing them with gtest assertions (ASSERT_TRUE, ASSERT_EQ), which are always active.

# Why This Matters

Tests should:
	•	fail deterministically
	•	enforce preconditions independent of build type
	•	provide actionable diagnostics when assumptions are violated

Relying on assert() / TT_ASSERT() in tests undermines all three.

# Scope of the Issue

This does not appear to be isolated to a single file.
A quick scan suggests similar patterns across multiple files under tests/, where:
	•	assert() is used instead of ASSERT_*
	•	TT_ASSERT() is used for conditions that should hard-fail the test

This indicates a systemic issue in test authoring conventions, rather than a local bug.

### Final Assessment: Problematic Runtime Assertions in `tests/`

**`assert()` - 21 usages across 7 files:**

| File | Count |
|------|-------|
| `data_movement/interleaved/test_interleaved.cpp` | 4 |
| `data_movement/multi_interleaved/test_multi_interleaved.cpp` | 3 |
| `llrt/test_libs/conv_pattern.hpp` | 10 |
| `test_dram_copy_sticks_multi_core.cpp` | 1 |
| `test_dataflow_cb.cpp` | 1 |
| `perf_microbenchmark/ethernet/test_ethernet_bidirectional_bandwidth_no_edm.cpp` | 1 |
| `perf_microbenchmark/ethernet/test_ethernet_link_ping_latency_no_edm.cpp` | 1 |

**`TT_ASSERT` - 103 usages across 34 files**

| File | Count |
|------|-------|
| `perf_microbenchmark/3_pcie_transfer/test_pull_from_pcie.cpp` | 14 |
| `api/test_tilize_untilize.cpp` | 14 |
| `perf_microbenchmark/1_compute_mm/test_compute_mm.cpp` | 10 |
| `dispatch/dispatch_event/test_EnqueueWaitForEvent.cpp` | 7 |
| `perf_microbenchmark/6_dram_offchip/test_dram_offchip.cpp` | 6 |
| `gtests/ccl/test_erisc_data_mover_with_workers.cpp` | 5 |
| `perf_microbenchmark/ethernet/test_ethernet_bidirectional_bandwidth_no_edm.cpp` | 4 |
| `test_utils/bfloat_utils.hpp` | 4 |
| `tt_eager/tensors/test_raw_host_memory_pointer.cpp` | 4 |
| `gtests/udm/test_udm_utils.hpp` | 3 |
| `perf_microbenchmark/9_dram_adjacent_read_remote_l1_write/test_dram_read_l1_write.cpp` | 3 |
| `dispatch/dispatch_program/test_EnqueueProgram.cpp` | 3 |
| `perf_microbenchmark/dispatch/test_bw_and_latency.cpp` | 2 |
| `perf_microbenchmark/8_dram_adjacent_core_read/test_dram_read.cpp` | 2 |
| `perf_microbenchmark/dispatch/common.h` | 2 |
| `gtests/ccl/test_fabric_edm_common.hpp` | 2 |
| `gtests/udm/reduction/sharded/test_udm_reduction.cpp` | 1 |
| `perf_microbenchmark/11_remote_cb_sync_matmul_single_core/test_remote_cb_sync_matmul.cpp` | 1 |
| `debug_tools/watcher/test_assert.cpp` | 1 |
| `distributed/test_mesh_socket.cpp` | 1 |
| `perf_microbenchmark/noc/test_noc_unicast_vs_multicast_to_single_core_latency.cpp` | 1 |
| `perf_microbenchmark/dispatch/benchmark_rw_buffer.cpp` | 1 |
| `perf_microbenchmark/ethernet/test_all_ethernet_links.cpp` | 1 |
| `perf_microbenchmark/3_pcie_transfer/test_rw_buffer.cpp` | 1 |
| `perf_microbenchmark/10_dram_read_remote_cb_sync/test_dram_read_remote_cb.cpp` | 1 |
| `eth/test_eth_multi_txq_rxq.cpp` | 1 |
| `eth/test_erisc_app_direct_send.cpp` | 1 |
| `api/test_runtime_args.cpp` | 1 |
| `tt_fabric/fabric_router/test_fabric_builder_local_connections.cpp` | 1 |
| `tt_eager/ops/test_eltwise_unary_op.cpp` | 1 |
| `dispatch/dispatch_program/test_kernel_config_buffer.cpp` | 1 |
| `perf_microbenchmark/common/util.hpp` | 1 |
| `data_movement/pcie_read_bw/test_pcie_read_bw.cpp` | 1 |
| `test_compile_args.cpp` | 1 |

---

**Grand Total: 124 assertions that silently pass in Release mode**

All of these should be converted to gtest macros (`ASSERT_TRUE`, `ASSERT_EQ`, `EXPECT_TRUE`, etc.) to ensure they actually fire regardless of build configuration.

### PR DESCRIPTION
**Pull request by blozano-tt**
### Ticket
Fixes #35592

### Problem description
Tests in the `tests/` directory rely on `assert()` and `TT_ASSERT()` for test-critical precondition checks. In Release builds, these assertions are compiled out or disabled, which means:
- Tests can continue execution with invalid assumptions
- Failures may silently turn into false positives
- Test behavior differs between Debug and Release configurations

This makes test results less trustworthy, especially for CI configurations that run tests in Release mode.

### What's changed
Replaced all uses of `assert()` and `TT_ASSERT()` in the `tests/` directory with checks that work reliably in Release builds:

**For gtest files:** Use gtest macros (`ASSERT_TRUE`, `ASSERT_EQ`, `ASSERT_NE`, `ASSERT_GE`, etc.)
**For non-gtest files and helper functions:** Use `TT_FATAL` with descriptive error messages

**Summary of changes across 43 files:**
- Converted 21 `assert()` usages to `ASSERT_*`/`TT_FATAL`
- Converted 103 `TT_ASSERT()` usages to `ASSERT_*`/`TT_FATAL`
- Removed unused `#include <cassert>` from 2 files
- Added descriptive error messages where they were missing

This ensures:
- Assertions fire reliably in Release mode
- Better failure diagnostics (especially with gtest macros that show expected vs actual values)
- Consistent test behavior across all build configurations

### Checklist

- [x] [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml?query=branch:fix/replace-asserts-with-reliable-checks-issue-35592)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:fix/replace-asserts-with-reliable-checks-issue-35592)
- [ ] [cpp-unit-tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:fix/replace-asserts-with-reliable-checks-issue-35592)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: tests/ttnn/unit_tests/gtests/ccl/test_erisc_data_mover_with_workers.cpp [hunk 1]
```diff
@@ -466,9 +466,9 @@ bool RunWriteBWTest(
 
     const uint32_t num_bytes_per_send = local_chip_edm_builder.get_eth_buffer_size_bytes();
     const uint32_t pages_per_send = num_bytes_per_send / page_size;
-    TT_ASSERT(num_bytes_per_send > 0);
-    TT_ASSERT(num_bytes_per_send >= page_size);
-    TT_ASSERT(num_bytes_per_send >= page_size);
+    TT_FATAL(num_bytes_per_send > 0, "num_bytes_per_send must be greater than 0");
+    TT_FATAL(num_bytes_per_send >= page_size, "num_bytes_per_send must be at least page_size");
+    TT_FATAL(num_bytes_per_send >= page_size, "num_bytes_per_send must be at least page_size");
```
Comment (blozano-tt) [inline tests/ttnn/unit_tests/gtests/ccl/test_erisc_data_mover_with_workers.cpp]:
```suggestion
```

**Review by atatuzunerTT — APPROVED** [review]

**Review by jvegaTT — APPROVED** [review]
TM files look good

**Review by aliuTT — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Review by nhuang-tt — APPROVED** [review]

**Review by yugaoTT — APPROVED** [review]
