### PR TITLE
#26044: Fix ct args passed to element wise kernel after TensorAccessor refactoring

### LINKED ISSUE #26044: ttnn tensor add has no effects
### Describe the bug

Image
, where the first view into `xqkv_fused_sharded` shows the values before the add operation on line 423 and the second view into `xqkv_fused_sharded` shows the results of the add operation. It is clear that the results is wrong -- e.g., the very first element of the result is wrong: `1.07031 + (-0.12500) != 1.07031`. 

- I was able to bisect the commits and narrow the problem down to this PR: #25976.
   - the test fails with the commit; test code is on [branch](https://github.com/tenstorrent/tt-metal/tree/gongyu/bisect_fail)
  - the test works with the commit that is right before (PR: #25756); test code is on [branch](https://github.com/tenstorrent/tt-metal/tree/gongyu/temp_test)

### Steps to reproduce the issue

1. Check out https://github.com/tenstorrent/tt-metal/tree/gongyu/for_stas
2. `./build_metal.sh`, `./create_venv.sh`, and `source python_env/bin/activate`
3. `pip install -r models/demos/qwen25_vl/reference/requirements.txt`
4. `TT_METAL_HOME=$(pwd) PYTHONPATH=$(pwd) MESH_DEVICE=N150 CI=true HF_MODEL=/proj_sw/user_dev/Qwen/Qwen2.5-VL-3B-Instruct TT_CACHE_PATH=<some where on fast disk, e.g., /localdev/gwang/.cache/qwen/2.5-VL-3b> pytest models/demos/qwen25_vl/demo/demo.py -k ci-only-repeated-batch`
5. See error in above screenshot with a breakpoint
6. See the ML model output garbage text:
Image

### Expected behavior

1. Expect `1.07031 + (-0.12500) = 0.94531`
2. Expect the test to succeed and show PASSED at the end
3. Expect the ML model to output something like this: 

Image

### Please complete the following environment information

The above was run on `aus-wh-*` IRD machines (with the [metal dev docker image](ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-22.04-dev-amd64:latest)), which already has the weights at `HF_MODEL=/proj_sw/user_dev/Qwen/Qwen2.5-VL-3B-Instruct`, though downloading the weights is pretty fast -- needs to change the env var: `HF_MODEL=Qwen/Qwen2.5-VL-3B-Instruct`

### PR DESCRIPTION
**Pull request by sminakov-tt**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/26044

### Problem description
During the TensorAccessor migration (https://github.com/tenstorrent/tt-metal/pull/25976) there was a bug causing incorrect compile time arguments being passed for elementwise kernel in some cases

### What's changed
Fixed the compile time arguments passed to `element_wise_multi_core_program_factory.cpp` kernel
Updated the defines handling in the kernel to be more consistent

### Checklist
- [x] [All post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/16644433957)
- [x] Manually verified the fix with the custom branch and steps in the ticket 
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by gwangTT — APPROVED** [review]
Thanks, Stas!

**Review by patrickroberts — APPROVED** [review]

**Review by ntarafdar — APPROVED** [review]

**Review by sjameelTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/eltwise/binary/device/element_wise_multi_core_program_factory.cpp [hunk 1]
```diff
@@ -137,21 +137,22 @@ BinaryDeviceOperation::ElementWiseMultiCore::cached_program_t BinaryDeviceOperat
     auto cb_output = tt_metal::CreateCircularBuffer(program, all_device_cores, cb_output_config);
 
     std::map<std::string, std::string> reader_defines;
+    std::vector<uint32_t> reader_compile_time_args = {(std::uint32_t)block_or_width_sharded};
     if (src0_sharded) {
         reader_defines["IN0_SHARDED"] = "1";
+    } else {
+        TensorAccessorArgs(*src0_buffer).append_to(reader_compile_time_args);
```
Comment (dchenTT) [inline ttnn/cpp/ttnn/operations/eltwise/binary/device/element_wise_multi_core_program_factory.cpp:144]: A general question. Since src0_buffer is added as compile arg, does it mean every time when input tensor changes,  kernel will be re-compiled? Shall it be runtime arg?

Comment (sminakov-tt) [reply ttnn/cpp/ttnn/operations/eltwise/binary/device/element_wise_multi_core_program_factory.cpp:144]: Those arguments include whether the tensor is in l1/dram, interleaved/sharded, and sharding parameters. It doesn't include buffer address or page size, which are always passed separately. The arguments should remain compile time

**Review by dchenTT — APPROVED** [review]
