### PR TITLE
#35885: Fix tanh_bw ULP precision with fused sech²(x) kernel (Max ULP 15,140 → 1)

### LINKED ISSUE #35885: [TTNN]: ttnn::tanh_bw has catastrophic ULP errors
### Component / Area

TTNN / Eltwise Backward Operations / tanh_bw

### Issue Type (optional)

Bad Outputs

### Observed

`ttnn::tanh_bw` produces Max ULP = 15,139 with mean ULP = 155.59.

The `ttnn::tanh_bw` operation produces catastrophically incorrect results in the transition and saturation regions, with **Max ULP = 15,139** compared to the mathematically correct reference. This is an implementation bug, not a BF16 format limitation.

**Proof**: The forward `ttnn::tanh` operation achieves **Max ULP = 1** across the entire BF16 range using the same testing methodology, demonstrating that correct implementation is achievable.

Per-segment analysis:

```
TANH_BW PER-SEGMENT ULP ANALYSIS
================================

Segment                  Count   Max ULP    Mean ULP     ULP=0    ULP<=1    ULP<=2   Worst Input
------------------------------------------------------------------------------------------------
x < -10                  15967     12666      136.48     98.3%     98.3%     98.3%      -10.0625
-10 <= x < -5              128     14515    13738.42      0.0%      0.0%      0.0%       -5.0312
-5 <= x < -4                32     14886    14709.56      0.0%      0.0%      0.0%       -4.0312
-4 <= x < -3.5              32     15080    14988.47      0.0%      0.0%      0.0%       -3.5156
-3.5 <= x < -3              32     15139     5225.31      0.0%      0.0%      3.1%       -3.3438
-3 <= x < -2                64        95       22.30      4.7%      4.7%      7.8%       -3.0000
-2 <= x < -1               128        17        3.67     12.5%     39.8%     54.7%       -1.7734
-1 <= x < -0.5             128         3        1.04     16.4%     81.2%     98.4%       -0.9336
-0.5 <= x < 0            16001         1        0.08     91.9%    100.0%    100.0%       -0.5000
x == 0                       1         0        0.00    100.0%    100.0%    100.0%        0.0000
0 < x < 0.5              16000         1        0.08     91.9%    100.0%    100.0%        0.0002
0.5 <= x < 1               128         3        1.04     16.4%     81.2%     98.4%        0.8984
1 <= x < 2                 128        17        3.68     11.7%     39.8%     54.7%        1.7734
2 <= x < 3                  64        90       20.81      6.2%      6.2%      9.4%        2.9844
3 <= x < 3.5                32     15139     4756.81      0.0%      0.0%      3.1%        3.3438
3.5 <= x < 4                32     15087    14994.44      0.0%      0.0%      0.0%        3.5000
4 <= x < 5                  32     14896    14721.09      0.0%      0.0%      0.0%        4.0000
5 <= x < 10                128     14527    13752.80      0.0%      0.0%      0.0%        5.0000
x >= 10                  15968     12686      137.27     98.3%     98.3%     98.3%       10.0000
------------------------------------------------------------------------------------------------
```

Specific failure examples:

| Input x | Expected Output | Actual Output | ULP Error |
|---------|-----------------|---------------|-----------|
| -3.3438 | 0.0049 | 0.0000 | 15,139 |
| -5.0312 | 0.0002 | 0.0000 | 14,515 |
| 3.3438 | 0.0049 | 0.0000 | 15,139 |
| 4.0000 | 0.0013 | 0.0000 | 14,896 |

**Note**: Values like 0.0049, 0.0013, 0.0002 are perfectly representable in BF16. The implementation is producing incorrect zeros.

### Expected

`ttnn::tanh_bw` should achieve precision comparable to `ttnn::tanh` (Max ULP <= 2).

The forward `ttnn::tanh` achieves Max ULP = 1:

```
TANH (FORWARD) PER-SEGMENT ULP ANALYSIS
=======================================

Segment                  Count   Max ULP    Mean ULP     ULP=0    ULP<=1    ULP<=2   Worst Input
------------------------------------------------------------------------------------------------
x < -10                  15967         0        0.00    100.0%    100.0%    100.0%        0.0000
-10 <= x < -5              128         1        0.88     12.5%    100.0%    100.0%       -9.0000
-5 <= x < -4                32         1        1.00      0.0%    100.0%    100.0%       -5.0000
-4 <= x < -3                64         1        0.75     25.0%    100.0%    100.0%       -4.0000
-3 <= x < -2                64         1        0.45     54.7%    100.0%    100.0%       -2.7656
-2 <= x < -1               128         1        0.52     47.7%    100.0%    100.0%       -2.0000
-1 <= x < -0.5             128         1        0.41     58.6%    100.0%    100.0%       -1.0000
-0.5 <= x < 0            16001         1        0.07     92.5%    100.0%    100.0%       -0.4980
x == 0                       1         0        0.00    100.0%    100.0%    100.0%        0.0000
0 < x < 0.5              16000         1        0.07     92.5%    100.0%    100.0%        0.0000
0.5 <= x < 1               128         1        0.41     59.4%    100.0%    100.0%        0.5078
1 <= x < 2                 128         1        0.52     47.7%    100.0%    100.0%        1.0000
2 <= x < 3                  64         1        0.47     53.1%    100.0%    100.0%        2.0000
3 <= x < 4                  64         1        0.73     26.6%    100.0%    100.0%        3.0469
4 <= x < 5                  32         1        1.00      0.0%    100.0%    100.0%        4.0000
5 <= x < 10                128         1        0.88     11.7%    100.0%    100.0%        5.0000
x >= 10                  15968         0        0.00    100.0%    100.0%    100.0%        0.0000
------------------------------------------------------------------------------------------------
```

| Operation | Max ULP | Mean ULP | % Within 1 ULP | % Within 2 ULP |
|-----------|---------|----------|----------------|----------------|
| tanh (forward) | **1** | **0.047** | **100%** | **100%** |
| tanh_bw (backward) | 15,139 | 155.59 | 97.97% | 98.11% |

This demonstrates that correct BF16 implementation IS achievable for tanh-family functions.

Mathematical background:
```
Forward:  tanh(x)
Backward: d/dx tanh(x) = 1 - tanh(x)^2 = sech^2(x)
```

**Root cause** (verified in source code):

The TTNN implementation (`ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward.cpp:287-301`) chains high-level ops:

```cpp
Tensor tanh_res = ttnn::tanh(input, output_mem_config);      // BF16 tanh saturates to ±1.0 for |x| > ~3.4
tanh_res = ttnn::square(tanh_res, output_mem_config);        // 1.0² = 1.0
tanh_res = ttnn::rsub(tanh_res, 1.0f, ...);                  // 1.0 - 1.0 = 0.0 ← PRECISION LOSS
ttnn::multiply(grad, tanh_res, ...);                         // grad * 0 = 0
```

Note: An SFPU kernel for tanh derivative exists (`tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h`) but has the same bug at line 29:
```cpp
val = val * (-val) + vConst1;  // 1 - tanh(x)² - same precision loss
```

When `tanh(x)` saturates to exactly ±1.0 in BF16, the `1 - tanh²` computation yields exactly 0, even though the true derivative (e.g., 0.0013 at x=4) is representable in BF16.

**Why forward tanh works**: The forward tanh (`ckernel_sfpu_tanh.h:47-77`) uses a **polynomial approximation** (Sollya-generated coefficients) that directly computes tanh(x) without intermediate saturation, achieving Max ULP = 1.

**Suggested fix**: Create a similar polynomial or continued fraction approximation for sech²(x) that directly computes the derivative without relying on `1 - tanh(x)²`.

### 1. Steps (exact commands)

```bash
# Prerequisites: tt-metal already cloned and built from https://github.com/tenstorrent/tt-metal

cd <your-tt-metal-directory>

# Fetch the test branch and apply changes without committing
git remote add ivoitovych https://github.com/ivoitovych/tt-metal.git
git fetch ivoitovych ivoitovych/tanh-bf16-ulp-diagnostic-tests
git merge --no-commit --squash ivoitovych/ivoitovych/tanh-bf16-ulp-diagnostic-tests

# Build only the affected target
# (if build fails with "mpfr not found", run: sudo apt-get install libmpfr-dev libgmp-dev)
cmake --build build_Debug --target unit_tests_ttnn -j$(nproc)

# Run tanh ULP diagnostic tests
./build_Debug/test/ttnn/unit_tests_ttnn --gtest_filter="*TanhUlp*:*TanhBwUlp*"
```

Test files (included in the merge):
- C++ tests: `tests/ttnn/unit_tests/gtests/test_tanh_bw_ulp_diagnostic.cpp`
- Python tests: `tests/ttnn/unit_tests/operations/eltwise/backward/test_tanh_bw_ulp_diagnostic.py`

### 2. Input data / link or description

-

### 3. Frequency

100% reproducible - affects all values in the transition/saturation region (|x| > 3).

### 1. Software Versions

- tt-metal base: https://github.com/tenstorrent/tt-metal commit `78fc90f44b`
- Test branch: https://github.com/ivoitovych/tt-metal/tree/ivoitovych/tanh-bf16-ulp-diagnostic-tests
- OS: Ubuntu 22.04.5 LTS, Kernel 5.15.0-164-generic
- Python: 3.10.12

### 2. Hardware Details

- Device: Blackhole P150a
- Driver: TT-KMD 2.6.1-pre
- Firmware: 19.1.0

### Is this a regression?

Unknown

### Regression Details

Note: Prior tanh_bw tests (`tests/ttnn/nightly/unit_tests/operations/eltwise/backward/test_backward_tanh.py`) use PCC comparison and only test the narrow range `[-1.45, 1.45]`, avoiding the saturation region where this bug manifests.

### Logs & Diagnostics

_No response_

### Priority

P1

### Impact

Incorrect gradients during backpropagation for any model using tanh activation. This can cause:
- Slower or failed convergence during training
- Incorrect weight updates
- Degraded model quality

### PR DESCRIPTION
**Pull request by epam-iaroslav-voitovych**
### Ticket

Fixes #35885

### Problem description

`ttnn::tanh_bw` produces catastrophically incorrect gradients with **Max ULP = 15,140** across the BFloat16 range. The root cause is the composite `1 - tanh^2(x)` formula in `unary_backward.cpp`: when `tanh(x)` saturates to +/-1.0 in BF16 for |x| > ~3.4, `tanh^2 = 1.0` exactly, so `1 - 1 = 0`. The true sech^2(x) values (e.g., 0.0013 at x=4) are perfectly representable in BF16, so the implementation returns 0 where the answer should be non-zero. This produces incorrect gradients during backpropagation for any model using tanh activation.

For comparison, forward `ttnn::tanh` achieves Max ULP = 1 using a polynomial approximation, proving correct BF16 precision is achievable for tanh-family functions.

#### Approach

Replace the 4-op composite decomposition (`tanh -> square -> rsub -> multiply`) with a fused SFPU kernel computing sech^2(x) directly. This eliminates all intermediate BF16 rounding and the catastrophic cancellation.

The implementation follows the 5-layer `DeviceOperationConcept` pattern (same as PR #39303 for gelu_bw), creating a binary device operation (2 inputs: grad + input) under `ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/`.

#### SFPU kernel: 2 piecewise regions + zero saturation

| Region | Range | Formula | Rationale |
|--------|-------|---------|-----------|
| Core | \|x\| < 3 | Degree-10 minimax polynomial in t = (2/9)*x^2 - 1 | Scaling to [-1,1] keeps powers bounded; ~12 MAD ops via Horner |
| Tail | 3 <= \|x\| < 45 | Inline Cody-Waite exp(-2\|x\| + ln4) | Asymptotic formula exact to 1 BF16 ULP for \|x\| >= 3; ~16 ops |
| Saturation | \|x\| >= 45 | 0 | sech^2(45) < BF16 min normal |

Region boundaries are named constants (`CORE_REGION_LIMIT = 3.0`, `TAIL_REGION_LIMIT = 45.0`) describing the piecewise structure: polynomial → exp → zero saturation.

Exploits even symmetry: sech^2(-x) = sech^2(x), so the polynomial operates on x^2 (equivalent to degree-20 in x with only 11 coefficients). The tail uses degree-4 Cody-Waite Taylor expansion — degree-5 term contributes < 0.0001 BF16 ULP because 2^k attenuation (k = -7 to -125) shrinks the error far below BF16 precision. No external function calls (`_sfpu_exp_f32_accurate_`, `_sfpu_reciprocal_`) — only Horner evaluation and inline arithmetic.

#### Key insight: FP32 FTZ underflow avoidance

The ln4 trick folds the x4 multiplication into the exp argument: `4 * exp(-2|x|) = exp(-2|x| + ln4)`. At x = 43.75, `exp(-87.5) ~ 9.8e-39` is below FP32 min normal and flushes to 0 under hardware FTZ, but `exp(-87.5 + ln4) = exp(-86.114) ~ 3.9e-38` stays representable. This extends valid coverage from |x| = 43.75 to |x| = 45.

#### Results (all ~65,026 valid BF16 values, Wormhole n150 L)

| Metric | Before (composite) | After (fused kernel) |
|--------|-------------------:|--------------------:|
| Max ULP | 15,140 | **1** |
| Mean ULP | 155.55 | **0.07** |
| % within 1 ULP | 98.05% | **100.00%** |
| Values with ULP > 100 | 952 | **0** |

#### Per-segment ULP analysis (post-fix)

| Region | Count | Mean ULP | Max ULP |
|--------|------:|---------:|--------:|
| x < -10 | 15,967 | 0.01 | 1 |
| [-10, -5) | 128 | 0.57 | 1 |
| [-5, -4) | 32 | 0.47 | 1 |
| [-4, -3) | 64 | 0.45 | 1 |
| [-3, -2) | 64 | 0.47 | 1 |
| [-2, -1) | 128 | 0.47 | 1 |
| [-1, 0) | 16,129 | 0.13 | 1 |
| x == 0 | 2 | 0.00 | 0 |
| (0, 1) | 16,128 | 0.13 | 1 |
| [1, 2) | 128 | 0.46 | 1 |
| [2, 3) | 64 | 0.47 | 1 |
| [3, 4) | 64 | 0.45 | 1 |
| [4, 5) | 32 | 0.50 | 1 |
| [5, 10) | 128 | 0.56 | 1 |
| x >= 10 | 15,968 | 0.01 | 1 |
| **OVERALL** | **65,026** | **0.07** | **1** |

##### New files (8)

| File | Purpose |
|------|---------|
| `tt_metal/hw/inc/api/compute/eltwise_unary/tanh_derivative.h` | Compute API: `tanh_derivative_tile_init<>()` + `tanh_derivative_tile<>()` |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation_types.hpp` | `TanhBwParams` + `TanhBwInputs` types |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.hpp` | `TanhBwDeviceOperation` struct + `launch_tanh_bw()` |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp` | Validation, output specs, program hash |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.hpp` | `TanhBwProgramFactory` declaration |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp` | 3 CBs, kernel creation, work distribution |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/kernels/compute/eltwise_bw_tanh_deriv.cpp` | Compute kernel |

##### Modified files (4)

| File | Change |
|------|--------|
| `tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h` | Added `calculate_tanh_derivative_sech2()` with polynomial + degree-4 inline exp; named region constants |
| `tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h` | Same (byte-identical pair) |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward.cpp` | Replaced 4-op composite with `launch_tanh_bw()` |
| `ttnn/cpp/ttnn/operations/eltwise/unary_backward/CMakeLists.txt` | Added kernel file set + 2 source files |

##### Test files (4, from earlier commits on this branch)

| File | Purpose |
|------|---------|
| `tests/ttnn/unit_tests/gtests/test_tanh_bw_ulp.cpp` | 10 exhaustive ULP tests for tanh_bw (MPFR-256 reference) |
| `tests/ttnn/unit_tests/gtests/test_tanh_fw_ulp.cpp` | 9 exhaustive ULP tests for tanh forward (regression baseline) |
| `tests/ttnn/unit_tests/gtests/sources.cmake` | Registered test files |
| `tests/ttnn/unit_tests/gtests/CMakeLists.txt` | Added mpfr/gmp link for precision reference |

#### How to test

```bash
# Build
cmake --build build_Debug --target unit_tests_ttnn -j$(nproc)

# Clear kernel cache (required after SFPU kernel changes)
rm -rf ~/.cache/tt-metal-cache/*

# Run tanh_bw tests (10 tests)
./build_Debug/test/ttnn/unit_tests_ttnn --gtest_filter="*TanhBwUlp*"

# Run tanh forward regression tests (9 tests)
./build_Debug/test/ttnn/unit_tests_ttnn --gtest_filter="*TanhFwUlp*"
```

#### Test duration

All 19 tests (10 TanhBwUlp + 9 TanhFwUlp) complete in ~5 seconds on Wormhole n150 L. The exhaustive sweep tests process all ~65,026 valid BF16 values in a single batched tensor operation per test.

#### A/B revert verification (Wormhole n150 L, 2026-03-09)

Full A/B test performed on hardware using the **same test code** against both implementations. All non-test files were reverted to the merge base (`1c22985943`) for Phase A, then restored to branch HEAD (`d77beb31e6`) for Phase B. Each phase included a clean rebuild + kernel cache clear.

**Methodology:**
1. `git checkout <merge-base> -- <all non-test files>` (reverts implementation to composite `1 - tanh^2(x)`)
2. Rebuild `unit_tests_ttnn`, clear `~/.cache/tt-metal-cache/`
3. Run `--gtest_filter="*TanhBwUlp*"` → Phase A results
4. `git checkout HEAD -- <all non-test files>` (restores fused sech^2 kernel)
5. Rebuild `unit_tests_ttnn`, clear `~/.cache/tt-metal-cache/`
6. Run `--gtest_filter="*TanhBwUlp*"` → Phase B results

**Phase A — merge base (composite `1 - tanh^2(x)`):**

| Test | Result | Key failure |
|------|--------|-------------|
| DerivativeAtZero | PASSED | |
| DerivativeAtPositiveValues | **FAILED** | sech^2(3) ULP=94, sech^2(5) ULP=14527, sech^2(10) ULP=12687 |
| DerivativeAtNegativeValues | **FAILED** | sech^2(-3) ULP=94, sech^2(-5) ULP=14527, sech^2(-10) ULP=12687 |
| DerivativeNearZero | PASSED | |
| WithGradientScaling | PASSED | |
| PerSegmentULPAnalysis | **FAILED** | Max ULP=15140 in exhaustive BF16 sweep |
| CumulativeULPDistribution | **FAILED** | 97.97% within 1 ULP (threshold: 99%) |
| ReferenceImplementationVerification | PASSED | |
| SaturationRegionAnalysis | **FAILED** | Max ULP=15140 at x=-3.34375 |
| PlatinumReferenceVerification | PASSED | |
| **Total** | **5 PASSED, 5 FAILED** | |

**Phase B — branch HEAD (fused sech^2 kernel):**

| Test | Result |
|------|--------|
| DerivativeAtZero | PASSED |
| DerivativeAtPositiveValues | PASSED |
| DerivativeAtNegativeValues | PASSED |
| DerivativeNearZero | PASSED |
| WithGradientScaling | PASSED |
| PerSegmentULPAnalysis | PASSED |
| CumulativeULPDistribution | PASSED |
| ReferenceImplementationVerification | PASSED |
| SaturationRegionAnalysis | PASSED |
| PlatinumReferenceVerification | PASSED |
| **Total** | **10 PASSED, 0 FAILED** |

**Revert path:** reverting the single-line change in `unary_backward.cpp` (replacing `launch_tanh_bw()` with the original 4-line composite) restores Phase A behavior. The `tanh_bw/` device operation directory becomes dead code with no other callers.

#### Performance (host-side timing, Wormhole n150)

[Benchmark script](https://gist.github.com/epam-iaroslav-voitovych/b032c77d978a0b8571a5cb01e41a3583). A/B measured in the same session, kernel cache cleared between phases (main `462e9aefd1`, 2026-04-06).

| Shape | Tiles | Composite (us) | Fused (us) | Speedup |
|-------|------:|---------------:|-----------:|--------:|
| [1,1,32,32] | 1 | 876 | 152 | **5.76x** |
| [1,1,256,256] | 64 | 916 | 140 | **6.57x** |
| [1,1,1024,1024] | 1,024 | 901 | 158 | **5.69x** |
| [1,1,4096,4096] | 16,384 | 1,591 | 1,067 | **1.49x** |

The composite dispatches 4 separate ttnn ops (tanh, square, rsub, multiply) through the host. The fused kernel does everything in a single device dispatch with a polynomial SFPU kernel. At dispatch-dominated shapes (1-1024 tiles) the speedup is 5.7-6.6x. At compute-dominated (16K tiles) the gap narrows to 1.49x.

### Checklist

 - [x] [Sanity tests](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml)
 - [x] [Nightly tt-metal L2 tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml)

### CODE REVIEW

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h [hunk 1]
```diff
@@ -50,5 +53,157 @@ inline void tanh_derivative_init() {
...
+    // Cody-Waite range reduction: t = k·ln(2) + r
+    sfpi::vFloat z = t * INV_LN2;
+    sfpi::vInt k_int;
+    sfpi::vFloat k = _sfpu_round_nearest_int32_(z, k_int);
+
+    sfpi::vFloat r = k * LN2_HI + t;  // Extended precision subtraction
+    r = k * LN2_LO + r;
+
+    // Degree-5 Taylor for exp(r)
+    sfpi::vFloat poly = PolynomialEvaluator::eval(r, 1.0f, 1.0f, C2, C3, C4, C5);
```
Comment (nmauriceTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h]: The following should save a few `SFPLOADI`
```suggestion
    // Degree-5 Taylor for exp(r)
    sfpi::vFloat poly = PolynomialEvaluator::eval(r, sfpi::vConst1, sfpi::vConst1, C2, C3, C4, C5);
```

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h [hunk 2]
```diff
@@ -50,5 +53,157 @@ inline void tanh_derivative_init() {
...
+        v_elseif(a < 45.0f) {
+            // Tail region: inline exp(-2|x| + ln4) = 4·exp(-2|x|)
+            // Asymptotic formula exact to 1 BF16 ULP for |x| >= 3.
+            // For |x| >= 45, result stays 0 (sech²(45) ≈ 5.5e-39 < BF16 min normal).
+            result = inline_exp_sech2_tail(a);
+        }
+        v_endif;
+
+        sfpi::dst_reg[0] = result;
+        sfpi::dst_reg++;
```
Comment (nmauriceTT) [inline tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:213]: (Nitpick for training if you use `is_fp32_dest_acc_en=True`)

Since `SFPSTORE` rounds towards 0 by default, we should round-to-nearest explicitly before storing to dst if  `is_fp32_dest_acc_en = False`.
```suggestion
        if constexpr (!is_fp32_dest_acc_en) {
                result = sfpi::reinterpret<sfpi::vFloat>(sfpi::float_to_fp16b(result, 0));
        }
        sfpi::dst_reg[0] = result;
        sfpi::dst_reg++;
```

File: tests/ttnn/unit_tests/operations/eltwise/analyze_sech2_bf16_saturation.py [hunk 3]
```diff
@@ -0,0 +1,382 @@
...
+    sign = (bits >> 15) & 1
+    magnitude = bits & 0x7FFF
+    if sign == 0:
+        return magnitude
+    else:
+        return -magnitude
+
+
+def main():
+    print("=" * 80)
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/eltwise/analyze_sech2_bf16_saturation.py]: Please use logger.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+
+    for (uint32_t i = 0, num_tiles_written = 0; i < num_cores; i++) {
+        CoreCoord core = {i / num_cores_y, i % num_cores_y};
+        uint32_t num_tiles_per_core = 0;
+        if (core_group_1.contains(core)) {
+            num_tiles_per_core = num_tiles_per_core_group_1;
+        } else if (core_group_2.contains(core)) {
+            num_tiles_per_core = num_tiles_per_core_group_2;
+        } else {
+            TT_ASSERT(false, "Core not in specified core ranges");
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp]: TT_THROW

**Review by bbradelTT — APPROVED** [review]

File: tests/ttnn/unit_tests/gtests/TANH_BW_BASELINE_ULP_REPORT.md
Comment (fvranicTT) [inline tests/ttnn/unit_tests/gtests/TANH_BW_BASELINE_ULP_REPORT.md:1]: Please don't add this to the PR.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h [hunk 5]
```diff
@@ -50,5 +53,157 @@ inline void tanh_derivative_init() {
...
+//   |x| < 3:    Degree-10 polynomial in t = (2/9)·a² - 1 (~12 MAD ops)
+//   |x| >= 3:   Inline exp(-2|x| + ln4) with FTZ (~17 ops)
+//               (zero saturation at |x| >= 45 via guard)
+//
+// Accuracy: Max ULP = 1 across all 65,026 valid BF16 values (FP32 sim).
+// Performance: ~14 ops (core) or ~19 ops (tail) vs ~40-50 ops (old version).
+// =============================================================================
+template <bool APPROXIMATION_MODE, int ITERATIONS = 8>
+inline void calculate_tanh_derivative_sech2() {
+    for (int d = 0; d < ITERATIONS; d++) {
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:173]: have you tested different #pragma GCC unroll values?

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h [hunk 6]
```diff
@@ -50,5 +53,157 @@ inline void tanh_derivative_init() {
...
+
+    // Cody-Waite range reduction: t = k·ln(2) + r
+    sfpi::vFloat z = t * INV_LN2;
+    sfpi::vInt k_int;
+    sfpi::vFloat k = _sfpu_round_nearest_int32_(z, k_int);
+
+    sfpi::vFloat r = k * LN2_HI + t;  // Extended precision subtraction
+    r = k * LN2_LO + r;
+
+    // Degree-5 Taylor for exp(r)
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h]: Degree-4 might be enough in our case. Have you checked it?

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h (hunk 1 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h]: Thank you — applied. Both `1.0f` constants replaced with `sfpi::vConst1` to avoid unnecessary `SFPLOADI` instructions.

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h (hunk 2 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:213]: Thank you for catching this — applied. Added explicit `float_to_fp16b(result, 0)` guarded by `if constexpr (\!is_fp32_dest_acc_en)`, and threaded `DST_ACCUM_MODE` through via `SFPU_TWO_PARAM_KERNEL` in the compute API header.

File: tests/ttnn/unit_tests/operations/eltwise/analyze_sech2_bf16_saturation.py (hunk 3 above)
Comment (epam-iaroslav-voitovych) [reply tests/ttnn/unit_tests/operations/eltwise/analyze_sech2_bf16_saturation.py]: This file has been removed from the PR — it was an offline analysis script, not a test. Moved to [gist](https://gist.github.com/epam-iaroslav-voitovych/219a88e37e5040075d9bd5156ba7b87c) for reference.

File: tests/ttnn/unit_tests/gtests/TANH_BW_BASELINE_ULP_REPORT.md
Comment (epam-iaroslav-voitovych) [reply tests/ttnn/unit_tests/gtests/TANH_BW_BASELINE_ULP_REPORT.md:1]: Agreed — removed. Moved to [gist](https://gist.github.com/epam-iaroslav-voitovych/905fdd92ef6dd60e2a66d00fa052393a) for reference.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward.cpp [hunk 7]
```diff
@@ -293,12 +294,11 @@ std::vector<std::optional<Tensor>> ExecuteUnaryBackwardTanh::invoke(
     std::optional<Tensor> input_grad) {
```
[the remark this answers is not in the document]
Comment (epam-iaroslav-voitovych) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/unary_backward.cpp]: Fixed — the signature was changed to `const std::optional<Tensor>& input_grad` as part of the implementation refactor.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp (hunk 4 above)
Comment (epam-iaroslav-voitovych) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp]: Thank you — applied. Both occurrences of `TT_ASSERT(false, ...)` replaced with `TT_THROW(...)` to ensure the check fires in Release builds as well, matching the dominant codebase convention.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h (hunk 6 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h]: Good call — degree-4 is indeed sufficient. The degree-5 term (r⁵/120) contributes less than 0.0001 BF16 ULP to the final sech² result because the 2^k exponent scaling in the tail region (k ranges from -7 to -125) attenuates the polynomial error by at least 128x. Applied and hardware verified: Max ULP = 1 preserved across all 65,026 valid BF16 values.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h (hunk 5 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:173]: Tested four variants on Wormhole n150 L bare-metal: no pragma (current), `unroll 0`, `unroll 4`, `unroll 8`. Each variant: clear kernel cache, run [perf benchmark](https://gist.github.com/epam-iaroslav-voitovych/be61d0f30af5c13beb24ac4822c1145c) (100 iterations + 10 warmup), run all 10 ULP tests.

**Accuracy:** All variants pass 10/10 ULP tests (Max ULP = 1). Unrolling does not affect correctness.

**Host-side timing (us, lower is better):**

| Shape | Tiles | no pragma | unroll 0 | unroll 4 | unroll 8 |
|-------|------:|----------:|---------:|---------:|---------:|
| [1,1,32,32] | 1 | 190 | 141 | 146 | 138 |
| [1,1,256,256] | 64 | 142 | 131 | 133 | 133 |
| [1,1,1024,1024] | 1,024 | 142 | 144 | 124 | 131 |
| [1,1,4096,4096] | 16,384 | 1,067 | 1,067 | 1,116 | 1,068 |

**Throughput (M tiles/sec, higher is better):**

| Shape | Tiles | no pragma | unroll 0 | unroll 4 | unroll 8 |
|-------|------:|----------:|---------:|---------:|---------:|
| [1,1,1024,1024] | 1,024 | 7.43 | 7.11 | 8.19 | 7.04 |
| [1,1,4096,4096] | 16,384 | 15.26 | 15.29 | 14.67 | 15.30 |

All variants are within measurement noise (~10% jitter at dispatch-dominated shapes, <1% at compute-dominated). No unroll value produces a statistically significant improvement. Keeping the current code (no pragma) — the compiler's default heuristic is fine here.

Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:173]: Could you benchmark against code in main? I'm interested in the diff.

Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:173]: Thank you for the suggestion! Benchmarked after rebasing onto main (`6ff3e0d0ba`, 2026-03-30):

| Shape | Tiles | Composite (us) | Fused sech² (us) | Speedup |
|-------|------:|---------------:|------------------:|--------:|
| [1,1,32,32] | 1 | 772 | 133 | 5.8x faster |
| [1,1,256,256] | 64 | 806 | 136 | 5.9x faster |
| [1,1,1024,1024] | 1,024 | 739 | 136 | 5.4x faster |
| [1,1,4096,4096] | 16,384 | 1,597 | 1,066 | 1.5x faster |

A/B measured in the same session, kernel cache cleared between phases. 19/19 ULP tests pass, Max ULP = 1.

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h [hunk 8]
```diff
@@ -50,5 +53,170 @@ inline void tanh_derivative_init() {
...
+
+        // sech²(x) is an even function: sech²(-x) = sech²(x)
+        sfpi::vFloat a = sfpi::abs(val);
+
+        v_if(a < CORE_REGION_LIMIT) {
+            // Core region: degree-10 polynomial in t = (2/9)·u - 1, u = a²
+            // Scaling u ∈ [0, 9) → t ∈ [-1, 1) keeps powers bounded.
+            sfpi::vFloat u = a * a;
+            sfpi::vFloat t = u * (2.0f / 9.0f) + (-1.0f);
+            result = PolynomialEvaluator::eval(
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:185]: For bf16, this might be an overkill and we might be able to get away with less coefficients. However, since these are not coefficients of a Taylor polynomial, we can't just truncate in case of !is_fp32_dest_acc_en, and we'd need to refit the polynomials offline using the above mentioned script.

Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:185]: Thank you for the suggestion! Investigated reducing the polynomial degree for BF16:

| Degree | FP32 sim Max ULP | Hardware Max ULP |
|--------|-----------------|-----------------|
| 10 (current) | 1 | **1** |
| 9 | 1 | 3 |
| 8 | 1 | 3 |
| 7 | 9 | — |

Degree-9 and degree-8 pass in FP32 simulation (Max ULP = 1) but fail on hardware (Max ULP = 3) — the SFPU intermediate rounding introduces errors that the simulation doesn't capture. The refitting used iterative weighted least-squares with Remez-style refinement on the BF16 grid. Degree-10 remains the minimum that achieves Max ULP = 1 on hardware.

Comment (fvranicTT) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:185]: I meant that for FP16B, 10-degree might be an overkill. For FP32, 10-degree is OK. 
For FP16B that has 7 bits of mantissa, e.g. 7-degree or 6-degree might improve performance without loss of precession.

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp [hunk 9]
```diff
@@ -0,0 +1,134 @@
...
+    if (preallocated_input_grad.has_value()) {
+        out_memory_config = preallocated_input_grad->memory_config();
+        output_datatype = preallocated_input_grad->dtype();
+    }
+
+    TT_FATAL(
+        output_datatype == input_tensor.dtype(),
+        "TANH_BW operation requires input and output data types to match. Input data type: {}, Output data type: {}",
+        static_cast<int>(input_tensor.dtype()),
+        static_cast<int>(output_datatype));
```
Comment (nmauriceTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp]: Nitpick: It should be possible to print DataType directly. This should print the type name rather than a code (i.e. easier troubleshooting for users)
```suggestion
    TT_FATAL(
        output_datatype == input_tensor.dtype(),
        "TANH_BW operation requires input and output data types to match. Input data type: {}, Output data type: {}",
        input_tensor.dtype(),
        output_datatype);
```

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp [hunk 10]
```diff
@@ -0,0 +1,134 @@
...
+
+    TT_FATAL(
+        input_tensor.buffer() != nullptr,
+        "Operands to TANH_BW need to be allocated in buffers on the device. Buffer is null.");
+
+    TT_FATAL(
+        input_tensor.memory_config().memory_layout() == out_memory_config.memory_layout(),
+        "TANH_BW operation requires Input and Output memory layout to match. Input layout: {}, Output layout: {}",
+        static_cast<int>(input_tensor.memory_config().memory_layout()),
+        static_cast<int>(out_memory_config.memory_layout()));
```
Comment (nmauriceTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp]:
```suggestion
    TT_FATAL(
        input_tensor.memory_config().memory_layout() == out_memory_config.memory_layout(),
        "TANH_BW operation requires Input and Output memory layout to match. Input layout: {}, Output layout: {}",
        input_tensor.memory_config().memory_layout(),
        out_memory_config.memory_layout());
```

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp [hunk 11]
```diff
@@ -0,0 +1,134 @@
...
+
+    TT_FATAL(!input_tensor.is_sharded(), "TANH_BW operation does not support sharded input tensor.");
+
+    TT_FATAL(
+        input_tensor.layout() == Layout::TILE,
+        "TANH_BW operation requires tensor to be in Tile layout when working with non-sharded input tensor. Input "
+        "tensor layout: {}",
+        static_cast<int>(input_tensor.layout()));
```
Comment (nmauriceTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp]:
```suggestion
    TT_FATAL(
        input_tensor.layout() == Layout::TILE,
        "TANH_BW operation requires tensor to be in Tile layout when working with non-sharded input tensor. Input "
        "tensor layout: {}",
        input_tensor.layout());
```

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp [hunk 12]
```diff
@@ -0,0 +1,192 @@
...
+    const auto& grad_output = tensor_args.grad_output;
+    auto* src0_buffer = grad_output.buffer();
+    auto* src1_buffer = input.buffer();
+    auto* dst_buffer = output.buffer();
+
+    auto& reader_runtime_args = GetRuntimeArgs(program, reader_kernel_id);
+    auto& compute_runtime_args = GetRuntimeArgs(program, compute_kernel_id);
+    auto& writer_runtime_args = GetRuntimeArgs(program, writer_kernel_id);
+
+    uint32_t num_tiles = input.physical_volume() / tt::constants::TILE_HW;
```
Comment (nmauriceTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp]: Nitpick:
```suggestion
    uint32_t num_tiles = input.physical_volume() / input.tensor_spec().tile().get_tile_size();
```

**Review by nmauriceTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp (hunk 12 above)
Comment (azaytsev-epam) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_program_factory.cpp]: used input.tensor_spec().tile().get_tile_hw(); it is the same thing

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp (hunk 9 above)
Comment (azaytsev-epam) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp]: addressed

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp (hunk 10 above)
Comment (azaytsev-epam) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp]: addressed

File: ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp (hunk 11 above)
Comment (azaytsev-epam) [reply ttnn/cpp/ttnn/operations/eltwise/unary_backward/tanh_bw/device/tanh_bw_device_operation.cpp]: addressed

**Review by mateusznowakTT — APPROVED** [review]

File: tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h (hunk 8 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:185]: Thank you for the suggestion, Filip. We're already significantly faster than the original composite code (1.5–6.4x depending on shape), so as an incremental upgrade this should be in good shape.

I'd prefer not to relax the Max ULP = 1 precision in this PR — once we ship ULP > 1, there's a risk of needing to fix it back later. For a milestone, the current code achieves the best possible BF16 accuracy (Max ULP = 1) while already being faster than what it replaces.

Happy to create a follow-up ticket for further performance optimization — we could apply the full spectrum of techniques we used on the GELU forward kernel (Moroz exp, v_if/v_and narrowing, constant folding, etc.) and potentially explore the `is_fp32_dest_acc_en` branching you're suggesting. But that would be a separate focused optimization pass rather than mixing precision trade-offs into this correctness fix.

What do you think?

Comment (fvranicTT) [reply tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_tanh_derivative.h:185]: Sure, we can try this in a follow-up.

**Review by fvranicTT — APPROVED** [review]

File: tests/ttnn/unit_tests/gtests/CMakeLists.txt [hunk 13]
```diff
@@ -45,12 +45,19 @@ add_library(TTNN::Test::Basic ALIAS unit_tests_ttnn_basic)
 TT_ENABLE_UNITY_BUILD(unit_tests_ttnn_basic)
 target_sources(unit_tests_ttnn_basic PRIVATE ${UNIT_TESTS_TTNN_BASIC_SOURCES})
 target_include_directories(unit_tests_ttnn_basic PRIVATE ${PROJECT_SOURCE_DIR}/tests)
+find_library(MPFR_LIBRARY mpfr)
```
Comment (dgomezTT) [inline tests/ttnn/unit_tests/gtests/CMakeLists.txt]: @wilderfield is it ok to add new libraries here?

**Review by dgomezTT — APPROVED** [review]

File: tests/ttnn/unit_tests/gtests/CMakeLists.txt (hunk 13 above)
Comment (williamlyTT) [reply tests/ttnn/unit_tests/gtests/CMakeLists.txt]: @blozano-tt see question above ^

Comment (blozano-tt) [reply tests/ttnn/unit_tests/gtests/CMakeLists.txt]: This looks sketchy.

You are adding a dependency on a system library that appears hidden away in tests?

We try to define all our dependencies in third_party/CMakeLists.txt where we also provide means to download them through CPM.

The only exceptions to the CPM path are numa, hwctl, and openmpi - which are guaranteed to be installed via “install_dependencies.sh”.

If you incur a dependency, you have to do the due diligence to ensure that dep is present for all platforms we need to support.

**Review by blozano-tt — DISMISSED** [review]
Raising an objection, because it is not clear to me where mpfr or gmp are coming from. We assume they are on the system?

File: tests/ttnn/unit_tests/gtests/CMakeLists.txt (hunk 13 above)
Comment (epam-iaroslav-voitovych) [reply tests/ttnn/unit_tests/gtests/CMakeLists.txt]: Thanks for catching this — you're right that a `find_library()` for a system lib hidden in test CMakeLists is not the right pattern, even with graceful degradation.

I've migrated the high-precision golden-reference verification (formerly `PlatinumReferenceVerification` in the C++ tests) to companion Python tests using `mpmath` at 256-bit precision: `tests/ttnn/unit_tests/operations/eltwise/test_tanh_bw_ulp.py` and `test_tanh_fw_ulp.py`. `mpmath` is a transitive dependency of `torch` (via `sympy`), so it's already in every tt-metal CI Python environment — no system package, no Dockerfile change, no `install_dependencies.sh` change.

The Python tests also exercise the operation through the public Python binding (`ttnn.from_torch → ttnn.tanh_bw → ttnn.to_torch`), so they add a layer of coverage the direct-C++ tests can't provide. Test composition follows the same template as the merged PR #36366: 7 classes for tanh_bw (45 sample points) and 6 classes for tanh_fw (44 sample points), all asserting per-point ULP ≤ 2 against the mpmath reference. Results: 89/89 passing on Wormhole n150 L.

The C++ side now contains zero MPFR/GMP references — `find_library` calls, `HAVE_MPFR` define, and `#ifdef HAVE_MPFR` blocks all removed. Pushed as `398a94a856`.

**Review by kstevensTT — APPROVED** [review]
