### PR TITLE
16942: ttnn.experimental.scatter_

### LINKED ISSUE #16942: Missing interface - scatter
**Describe the bug**
The values_out tensor is set to the values_in tensor with data modified as follows: data from the input tensor is inserted at the positions specified by the indices tensor. N is the number of batches, W the number of indices in each batch, K the range of each index and C the number data channels for each index. It is not permitted to repeat the same output index within a single SCATTER operation and so each output index occurs at most once. It follows that K >= W. In use cases that require multiple updates to the same output position, these must be decomposed into multiple SCATTER operations.

**To Reproduce**

**Expected behavior**

```
// The following array is used to check compliance that an output position
// is modified at most once.
bool_t output_modified[N,K,C];

// Copy the values_in tensor to the values_out tensor.
// Values not written by the scatter operation are unchanged in the output.
for_each(0 <= n < N, 0 <= k < K, 0 <= c < C) {
    in_out_t value = tensor_read<in_out_t>(values_in, [N,K,C], [n,k,c]);
    tensor_write<in_out_t>(values_out, [N,K,C], [n, k, c], value);
    output_modified[n,k,c]=false;
}

// Now perform the SCATTER operation, modifying the positions from the indices tensor
for_each(0 <= n < N, 0 <= w < W, 0 <= c < C) {
    index_t k = tensor_read<index_t>(indices, [N,W], [n,w]);
    REQUIRE(0 <= k && k < K);
    REQUIRE(output_modified[n,k,c] == false);
    in_out_t value = tensor_read<in_out_t>(input, [N,W,C], [n,w,c]);
    tensor_write<in_out_t>(values_out, [N,K,C], [n, k, c], value);
    output_modified[n,k,c] = true;
}

```

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

### PR DESCRIPTION
**Pull request by jbbieniekTT**
### Ticket
#16942 

### Problem description
Provide `ttnn.experimental.scatter_` to work for input tensors of the size required by the client. For now, long input and index tensors cause excessive execution time, and this is to be covered by the issue #22926.

### What's changed
- Implemented `ttnn.experimental.scatter_`.

### Checklist
- [ ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI with demo tests passes (if applicable)
- [ ] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [ ] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml) CI passes (if applicable) See [recommended dev flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by bbradelTT — COMMENTED** [review]
We're all really pressed for time. Please try to have your PRs in a finished state before sending them out. For getting a first opinion, consider a draft PR and request a preliminary review from one person.

My main feedback:
- Don't have ???
- Have issue numbers next to TODOs
- Remove commented out code
- Remove dprints unless they're within a debug block
Also
- tile_guts_gen seems strange
- I can't tell what "memory_config testing!!!!!!!!!!" means. My best guess is that you're trying to remind yourself to add tests

**Comment by jbbieniekTT** [comment]
@bbradelTT Hey, I apologise, I should have done as you said. I actually forgot to put it into draft state. I am working on cleaning all the stuff.

File: ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/dataflow/reader_scatter.cpp [hunk 1]
```diff
@@ -0,0 +1,136 @@
+// SPDX-FileCopyrightText: © 2025 Tenstorrent Inc.
```
[the remark this answers is not in the document]
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/dataflow/reader_scatter.cpp:1]: Done

File: ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+        get_compile_time_arg_val(9),
+        get_compile_time_arg_val(10),
+        get_compile_time_arg_val(11),
+        get_compile_time_arg_val(12),
+        get_compile_time_arg_val(13),
+        get_compile_time_arg_val(14),
+        get_compile_time_arg_val(15),
+        get_compile_time_arg_val(16),
+        get_compile_time_arg_val(17),
+        get_compile_time_arg_val(18)};
```
Comment (bbradelTT) [inline ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp:144]: Would this benefit in any way from https://github.com/tenstorrent/tt-metal/pull/18379 ?

**Review by bbradelTT — APPROVED** [review]

File: ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp (hunk 2 above)
Comment (bbradelTT) [reply ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp:141]: I looked into this. Doesn't seem to be a good way to not enumerate through all arg vals.

File: ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+    const uint32_t& face_x,
+    const uint32_t& face_y,
+    const uint32_t& scalar_x,
+    const uint32_t& scalar_y) {
+    return l1_ptr[calc_offset_inside_tile(face_x, face_y, scalar_x, scalar_y)];
+}
+
+FORCE_INLINE uint32_t
+get_width_scalar_index(const uint32_t& tile_id, const uint32_t& face_x, const uint32_t& scalar_x) {
+    return tile_id * tt::constants::TILE_WIDTH + face_x * (tt::constants::TILE_WIDTH >> 1) + scalar_x;
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp:84]: tile height and width and not constants since ~6 months ago (the feature was called tiny tiles and was added to improve perf in some cases)
most of old code uses constants and so does not handle things right.

instead you should be fetching tile size from the tensor spec.

File: ttnn/cpp/ttnn/operations/experimental/scatter/scatter.hpp [hunk 4]
```diff
@@ -0,0 +1,36 @@
+// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
+//
+// SPDX-License-Identifier: Apache-2.0
+
+#pragma once
+
+#include "scatter_enums.hpp"
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/experimental/scatter/scatter.hpp:7]: using `ScatterReductionType` from this include makes sense, but this include also leaks lower level things. I am not a fan of this

File: tests/ttnn/unit_tests/operations/test_scatter.py [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+@pytest.mark.parametrize(
+    "input_shape, dim, index_and_source_shape, input_dtype",
+    [
+        ([100], -1, [80], ttnn.float32),
+        ([50, 200], -1, [50, 100], ttnn.bfloat16),
+        ([2, 30, 200], -1, [2, 30, 200], ttnn.float32),
+        ([1, 1, 20, 20, 200], -1, [1, 1, 20, 20, 20], ttnn.bfloat16),
+        ([2, 2, 2, 2, 2, 2, 2, 2], -1, [2, 2, 2, 2, 2, 2, 2, 2], ttnn.float32),
+        ([10, 1, 10, 1, 10], -1, [10, 1, 10, 1, 1], ttnn.bfloat16),
```
Comment (cmaryanTT) [inline tests/ttnn/unit_tests/operations/test_scatter.py:31]: Please include large shapes, including the client shapes. Part of the claim of this PR is support for tensors of any size.

**Review by cmaryanTT — CHANGES_REQUESTED** [review]

**Review by ayerofieiev-tt — COMMENTED** [review]
Current tests might be insufficient and I recommend to extend tests to include:
* All dimensions (dim=0,1,2,-1,-2,-3)
* Edge cases (empty tensors, boundary indices)
* Error conditions (invalid dimensions, out-of-bounds indices)
* Data Types (integer, bfloat8_b)

File: ttnn/cpp/ttnn/operations/experimental/scatter/scatter.hpp (hunk 4 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/scatter/scatter.hpp:7]: Moved to `scatter_program_factory.hpp`

File: ttnn/cpp/ttnn/operations/experimental/scatter/device/scatter_device_operation.cpp [hunk 6]
```diff
@@ -0,0 +1,177 @@
...
+        TT_FATAL(
+            static_cast<int32_t>(dim) >= -static_cast<int32_t>(output_rank),
+            "dim cannot be lower than output shape's negative rank (dim: {}, rank: {}).",
+            dim,
+            -static_cast<int32_t>(output_rank));
+        TT_FATAL(
+            static_cast<int32_t>(dim) < static_cast<int32_t>(output_rank),
+            "dim must be lower than output shape's positive rank (dim: {}, rank: {}).",
+            dim,
+            static_cast<int32_t>(output_rank));
```
[the remark this answers is not in the document]
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/scatter/device/scatter_device_operation.cpp]: Done

File: ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp (hunk 3 above)
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/scatter_common.hpp:84]: Done

File: ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/dataflow/reader_scatter.cpp [hunk 7]
```diff
@@ -0,0 +1,169 @@
...
+                                break;
+                            }
+
+                            // get scatter info
+                            volatile index_type& index_value =
+                                tile_guts<index_type>(index_l1_ptr, face_x, face_y, scalar_x, scalar_y);
+                            // check if index value targets currently chosen input tile (tile_input)
+                            const uint32_t dest_tile_id_in_row = index_value >> 5;
+                            if (dest_tile_id_in_row != tile_input) {
+                                ASSERT(dest_tile_id_in_row == tile_input);
```
[the remark this answers is not in the document]
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/scatter/device/kernels/dataflow/reader_scatter.cpp]: Fixed the assert itself als

**Review by rfurko-tt — CHANGES_REQUESTED** [review]
```
const Tensor transposed_tensor = reduction_common::perform_transpose(input_tensor, is_dim_last_idx, dim, -1);
```

i really don't like this approach, we should use transpose really careful with TILED layout. 

Imagine, that you need to perform transpose on tensor with shape [1, 2, N, M] (-3 and -1), now shape of the new tensor is [1, M, N, 2], but actually it is [1, M, N, 2[32]] as last dimension will be tiled. As you can see, now tensor volume increased 16x. I don't think it is expected behavior of the scatter operation and potentially a problem which will be hard to debug/understand.

**Comment by rfurko-tt** [comment]
"this approach enables easy and cache-friendly implementation"

* I agree that it simplifies implementation of the operation, but it does not cover use-cases when it should work as well
* "cache-friendly implementation" program cache? are we optimizing by this criteria? 

"the size may either increase or decrease (depending whether dim1 > dim2 or dim1 < dim2 between 1x and 32x times"
the problem when it increases 32x times

**Comment by jbbieniekTT** [comment]
> Would it be possible to transpose the data only when processing each tile in the kernel? That would avoid the size increase.

actually if the difference between dims is more than one, then e.g. consider the following situation:
we have a shape `(31, 1, 1)` and we want to transpose the first axis with the last one so that it would look like `(1, 1, 31)` - the shape prior is padded to `(31, 32, 32)` while the latter one to `(1, 32, 32)`, and if we were to scatter along the first dim in the first case, then we would need to take just one scalar from one tile and keep swapping tiles from different regions of memory as opposed to when scatter is performed along the last axis (fetching 31 values contained in one tile), transposing inside a kernel would only for the `dim1 == -2 && dim1 == -1` case

File: tests/ttnn/unit_tests/operations/test_scatter.py (hunk 5 above)
Comment (jbbieniekTT) [reply tests/ttnn/unit_tests/operations/test_scatter.py:31]: @cmaryanTT @bbradelTT @aczajkowskiTT i have managed to reduce execution time to under one minute for BH

**Comment by aczajkowskiTT** [comment]
> ```
> const Tensor transposed_tensor = reduction_common::perform_transpose(input_tensor, is_dim_last_idx, dim, -1);
> ```
> 
> i really don't like this approach, we should use transpose really careful with TILED layout.
> 
> Imagine, that you need to perform transpose on tensor with shape [1, 2, N, M] (-3 and -1), now shape of the new tensor is [1, M, N, 2], but actually it is [1, M, N, 2[32]] as last dimension will be tiled. As you can see, now tensor volume increased 16x. I don't think it is expected behavior of the scatter operation and potentially a problem which will be hard to debug/understand.

@rfurko-tt I don't think it's wise from a software engineering point of view to be planning around a specific OP's bugs and implementation errors.  Transpose is the correct operation to use in this case no?  If there is a corner case that transpose cannot handle in L1, it should have an exit case to DRAM, or should be fixed; rather than our unrelated OP keeping track of transpose bugs.  Am I wrong on this?

On another note, for the customer shape we are interested in, I understand the transpose issue does not occur.

**Comment by rfurko-tt** [comment]
@aczajkowskiTT 

"I don't think it's wise from a software engineering point of view to be planning around a specific OP's bugs and implementation errors." - it's not specific bug in the transpose operation... that's how tiling works

Imagine two tensors: 
tensor A: [1, 2, 16384, 16384] -> fits in DRAM (way less < 12 GB)
tensor B: [16384, 2, 16384, 1] -> does not fit in DRAM (more than 12 GB) 

please review discussion in the `ttnn::sum` issue i've shared

**Comment by aczajkowskiTT** [comment]
> @aczajkowskiTT
> 
> "I don't think it's wise from a software engineering point of view to be planning around a specific OP's bugs and implementation errors." - it's not specific bug in the transpose operation... that's how tiling works
> 
> Imagine two tensors: tensor A: [1, 2, 16384, 16384] -> fits in DRAM (way less < 12 GB) tensor B: [16384, 2, 16384, 1] -> does not fit in DRAM (more than 12 GB)
> 
> please review discussion in the `ttnn::sum` issue i've shared

Right so based on a specific input shape into transpose, wouldn't it be cleaner from a usability and developer perspective for transpose to handle that corner case?  Then if transpose returns an error code you default to another approach (your preferred alternative)?

**Comment by aczajkowskiTT** [comment]
> > @aczajkowskiTT
> > "I don't think it's wise from a software engineering point of view to be planning around a specific OP's bugs and implementation errors." - it's not specific bug in the transpose operation... that's how tiling works
> > Imagine two tensors: tensor A: [1, 2, 16384, 16384] -> fits in DRAM (way less < 12 GB) tensor B: [16384, 2, 16384, 1] -> does not fit in DRAM (more than 12 GB)
> > please review discussion in the `ttnn::sum` issue i've shared
> 
> Right so based on a specific input shape into transpose, wouldn't it be cleaner from a usability and developer perspective for transpose to handle that corner case? Then if transpose returns an error code you default to another approach (your preferred alternative)?

Also, having to read a discussion on `ttnn:sum` to understand what is happening with transpose is exactly the spaghetti code of dependencies we're trying to avoid...

**Comment by rfurko-tt** [comment]
"wouldn't it be cleaner from a usability and developer perspective for transpose to handle that corner case?" 

with all due respect, it's not issue of transpose. It is expected that transpose will use that much memory. you are creating tensor that padded shape requires 17 GB. The issue is that scatter calls transpose.

transpose will return error code, to be precise - throw exception "tensor does not fit in DRAM"

**Comment by rfurko-tt** [comment]
"Also, having to read a discussion on ttnn:sum to understand what is happening with transpose is exactly the spaghetti code of dependencies we're trying to avoid..."

i've mentioned reading the issue, because it seems like you didn't understand the underlying issue and wanted to provide more context

**Comment by aczajkowskiTT** [comment]
> "wouldn't it be cleaner from a usability and developer perspective for transpose to handle that corner case?"
> 
> with all due respect, it's not issue of transpose. It is expected that transpose will use that much memory. you are creating tensor that padded shape requires 17 GB. The issue is that scatter calls transpose.
> 
> transpose will return error code, to be precise - throw exception "tensor does not fit in DRAM"

Okay, so catch the error code, and use a different approach, L1 cache/number of cores will change with architectures, so shapes that transpose can or cannot handle is hardware dependent, thus it is below the abstraction layer of what the op does.

**Comment by rfurko-tt** [comment]
"Okay, so catch the error code, and use a different approach"

this makes no sense, imagine that you need to try/catch every operation in python? 

"L1 cache/number of cores will change with architectures, so shapes that transpose can or cannot handle is hardware dependent" 

with newer versions of hardware we will want to support larger models. just from usage perspective, would you expect that any random operation takes 32x memory of the tensor you pass? (if it's not inherent to the operation) 

"so shapes that transpose can or cannot handle is hardware dependent" 
imagine if our tensor is exactly 12GB DRAM, and we want to perform this transpose, when do you expect our new hardware to have 384GB (12x32) of DRAM?

File: tests/ttnn/unit_tests/operations/test_scatter.py (hunk 5 above)
Comment (philei-tt) [reply tests/ttnn/unit_tests/operations/test_scatter.py:31]: @jbbieniekTT  Here: https://github.com/tenstorrent/tt-metal/pull/22731 I will add @pytest.mark.slow marker, so that slow tests are not ran by default, and you can run them with --runslow 

Maybe that will be useful for you

**Comment by rfurko-tt** [comment]
How I would handle this issue: create a separate program factories that would handle different dimensions, have three different kernels for three different cases: (dim = -1, -2 or any other dimension)

**Comment by aczajkowskiTT** [comment]
> How I would handle this issue: create a separate program factories that would handle different dimensions, have three different kernels for three different cases: (dim = -1, -2 or any other dimension)

Regarding exception, I think our current version of Python should support zero-cost exceptions, so there is no cost if no exception is raised.  

@rfurko-tt I think we're having a philosophical discussion at this point, which is where the disagreement is.  I think optimizing for perf with more PRs is totally valid, as you suggest.

**Comment by rfurko-tt** [comment]
"Regarding exception, I think our current version of Python should support zero-cost exceptions, so there is no cost if no exception is raised.

you are trying to prove why it's okay to release half-baked operation... which is not acceptable for providing to our customers. 

i would never use hardware which require me to write code like this 
```
    try:
      f0 = x + y
    catch:
      raise Exception("Unfortunately our operation takes more memory than needed")

    try:
      f1 = y + x
    catch:
      raise Exception("Unfortunately our operation takes more memory than needed")
```

"@rfurko-tt I think we're having a philosophical discussion at this point, which is where the disagreement is. I think optimizing for perf with more PRs is totally valid, as you suggest." 

this is not philosophical discussion, I am trying to show you that operation has unexpected behavior which results in 32x more memory consumption and it's not an issue of any other operation other than this one.

**Comment by aczajkowskiTT** [comment]
> "Regarding exception, I think our current version of Python should support zero-cost exceptions, so there is no cost if no exception is raised.
> 
> you are trying to prove why it's okay to release half-baked operation... which is not acceptable for providing to our customers.
> 
> i would never use hardware which require me to write code like this
> 
> ```
>     try:
>       f0 = x + y
>     catch:
>       raise Exception("Unfortunately our operation takes more memory than needed")
> 
>     try:
>       f1 = y + x
>     catch:
>       raise Exception("Unfortunately our operation takes more memory than needed")
> ```
> 
> "@rfurko-tt I think we're having a philosophical discussion at this point, which is where the disagreement is. I think optimizing for perf with more PRs is totally valid, as you suggest."
> 
> this is not philosophical discussion, I am trying to show you that operation has unexpected behavior which results in 32x more memory consumption and it's not an issue of any other operation other than this one.

God forbid we throw and catch exceptions...

**Comment by aczajkowskiTT** [comment]
@rfurko-tt @ayerofieiev-tt @jbbieniekTT After offline discussion, we decided that for problematic tensor shapes that can cause a significant increase in memory usage, this implementation will need to be amended with another PR to detect these shapes and handle them explicitly.

@jbbieniekTT Please create a ticket against this PR for the shapes @rfurko-tt is concerned about.  Include performance profiling as part of that.

**Comment by ayerofieiev-tt** [comment]
Sharing the wider context on what we aligned on in the offline discussion

## Feedback
As a user I think of my tensor of shape + datatype and expect it to fit. Same for compiler.
Operation uses transpose inside which for some cases will explode used memory.
We don't like it, because it violates the "minimal surprise rule" for users.

## Guidance
It is on the right level of abstraction for OP team to think deeply about such things, to strive to never do this and to avoid bringing such negative surprises to consumers of the framework.
At the same time it is fair that we might not be able to always implement things perfectly, specially when a more junior engineer introduces a new operations.
* It is fair for the feedback to be acknowledged as important and to be incorporated and learned from.
* We don't think transpose must be removed right here right now, but I recommend an action based on below
* We expect OP developers to think about these things and avoid such decisions whenever possible.
* It is acceptable to make conscious decision to use transpose (or any other trick like using composite operation or squeeze/unsqueeze or..) but it must be conscious. 
  * The behavior must be well documented. Warning message is recommended to inform users of this behavior (to follow the minimal surprise principle). 
  * Such decisions must be weighted. It is very often easier to make things right when OP is introduced instead of "later". 
  * The more often such things are done and not followed up on - the more our junior engineers copy bad decisions and less valuable know-how our organization builds.

@rfurko-tt @aczajkowskiTT @jbbieniekTT

File: tests/ttnn/unit_tests/operations/test_scatter.py (hunk 5 above)
Comment (cmaryanTT) [reply tests/ttnn/unit_tests/operations/test_scatter.py:31]: I am ok with the large shape being left out or marked as slow as Pavlo suggested. Next improvement to the OP should be focused on large shape support.

**Review by cmaryanTT — APPROVED** [review]
Approving to get an MVP of this OP committed. Performant support for larger shapes can follow in the next PR, which should get a new issue opened; tests for the larger shape of interest can be either in this PR and marked as slow, or left out for the next PR. Longer term followup changes to improve behaviour around or remove transpose should be tracked in a separate issue.

**Comment by dmakoviichuk-tt** [comment]
HI @cmaryanTT and @jbbieniekTT  I suggest to throw exception for the case where transpose would work 10x slower and/or use much more memory:
When we are transposing and one of two last dimensions is not divisible by TILE.  
And please create ticket  with high priority to support.
We saw similar decision with other ops. As result we wasted couple of days debugging the issue because we could not expect **ttnn::sum** can be so slow. Anyway no one is going to use this op for these cases. It might throw exception or just be too slow. In our case ttnn::sum with the same issue was as slow as a half of gpt2s :)
It will save a lot of debugging time for the customers.

I will approve this pr immediately once I see:
1) a link to the created ticket.
2) Exception for these really bad cases to save customers time.
3) updated pr description for the op behavior.

Screenshot 2025-06-02 at 7 40 36 PM

According to the description it should work with any tensor sizes which is not true.
It should not take a lot of time to do it
Thanks

**Comment by cmaryanTT** [comment]
@dmakoviichuk-tt that's reasonable. @jbbieniekTT - can you please add a TT_FATAL for whatever size approximately exceeds ~5 seconds of execution time (unusably long, but not so long that it's annoying for isolated usage), and another for
- for last two dims not divisible by tile size
- AND we are transposing
- AND the transposed tensor size would be > 200KB larger than its original size (i.e. for small tensors, the transpose is fine, because the absolute increase is reasonable)

**Comment by dmakoviichuk-tt** [comment]
@cmaryanTT  thanks!

File: tests/ttnn/unit_tests/operations/test_scatter.py (hunk 5 above)
Comment (jbbieniekTT) [reply tests/ttnn/unit_tests/operations/test_scatter.py:31]: @philei-tt that's excellent, i am very happy to mark my test with this as soon as the PR gets merged, if not in this PR, then in the PR that will follow immediately after, the one focusing on optimising unfortunate input shapes
@bbradelTT i will as well create a sweep test in this PR, i think
@cmaryanTT @aczajkowskiTT i am going to refactor the last thing from @ayerofieiev-tt today and merge the PR asap, the issue has been created (#22926)

File: ttnn/cpp/ttnn/operations/experimental/scatter/scatter.hpp [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+struct ScatterOperation {
+    static Tensor invoke(
+        const Tensor& input_tensor,
+        const int32_t& dim,
+        const Tensor& index_tensor,
+        const Tensor& source_tensor,
+        const std::optional<MemoryConfig>& opt_out_memory_config,
+        const std::optional<scatter::ScatterReductionType>& opt_reduction,
+        std::optional<Tensor>& opt_output,
+        const QueueId& queue_id = DefaultQueueId);
```
[the remark this answers is not in the document]
Comment (jbbieniekTT) [reply ttnn/cpp/ttnn/operations/experimental/scatter/scatter.hpp]: Okay, it's fixed

**Comment by jbbieniekTT** [comment]
> @dmakoviichuk-tt that's reasonable. @jbbieniekTT - can you please add a TT_FATAL for whatever size approximately exceeds ~5 seconds of execution time (unusably long, but not so long that it's annoying for isolated usage), and another for
> 
> * for last two dims not divisible by tile size
> * AND we are transposing
> * AND the transposed tensor size would be > 200KB larger than its original size (i.e. for small tensors, the transpose is fine, because the absolute increase is reasonable)

Done

**Review by rfurko-tt — APPROVED** [review]
LGTM, thanks for the changes

Please add ticket to fix program cache as discussed offline. thanks in advance
