### PR TITLE
Use optimised fp32→bf16 typecast with RNE; fp32_to_[u]int32; uint16_to_uint32.

### LINKED ISSUE #30147: ttnn.typecast rounds away from 0 on ties rather than to even
### Describe the bug

When casting tensors from float32 to bfloat16, ttnn.typecast rounds away from 0 on ties, whereas torch, ttnn.to_dtype, ttnn.from_torch all round to even on ties. 

For instance:

| x | 128.5 | 
| - | - |
| `torch.to(x, bfloat16)` | 128 |
| `ttnn.from_torch(x)` | 128 |
| `ttnn.to_dtype(x)` | 128 |
| `ttnn.typecast(x)` | 129 | 

### Steps to reproduce the issue

Running `python -m pytest` on the following code

```python
import ttnn
import pytest
import torch

from tests.ttnn.utils_for_testing import assert_with_ulp, assert_equal


@pytest.mark.parametrize("val", [128.5, -128.5])
def test_from_torch_typecast(device):
    ttnn_dtype = ttnn.bfloat16

    shape = [20,20]
    # torch_input_fp32 = torch.arange(shape[0] * shape[1], dtype=torch.float32)
    
    torch_input_fp32 = torch.full(shape, val, dtype=torch.float32)
    torch_input_fp32 = torch.reshape(torch_input_fp32, shape)
    torch_golden_bf16 = torch_input_fp32.to(torch.bfloat16)


    ttnn_input_fp32 = ttnn.from_torch(torch_input_fp32, device=device, layout=ttnn.TILE_LAYOUT)
    ttnn_input_bf16 = ttnn.typecast(ttnn_input_fp32, dtype=ttnn_dtype)

    torch_calculated_bf16 = ttnn.to_torch(ttnn_input_bf16)

    assert_with_ulp(torch_golden_bf16, torch_calculated_bf16, ulp_threshold=0)
    
@pytest.mark.parametrize("val", [128.5, -128.5])
def test_from_torch_to_dytpe(val, device):
    ttnn_dtype = ttnn.bfloat16

    shape = [20,20]
    # torch_input_fp32 = torch.arange(shape[0] * shape[1], dtype=torch.float32)
    
    torch_input_fp32 = torch.full(shape, val, dtype=torch.float32)
    torch_input_fp32 = torch.reshape(torch_input_fp32, shape)
    torch_golden_bf16 = torch_input_fp32.to(torch.bfloat16)


    ttnn_input_fp32 = ttnn.from_torch(torch_input_fp32, layout=ttnn.TILE_LAYOUT)
    ttnn_input_bf16 = ttnn.to_dtype(ttnn_input_fp32, dtype=ttnn_dtype)

    torch_calculated_bf16 = ttnn.to_torch(ttnn_input_bf16)

    assert_with_ulp(torch_golden_bf16, torch_calculated_bf16, ulp_threshold=0)
    

@pytest.mark.parametrize("val", [128.5, -128.5])
def test_from_torch_with_dtype(device, val):
    torch_dtype = torch.float32
    ttnn_dtype = ttnn.bfloat16

    shape = [20,20]
    # torch_input_fp32 = torch.arange(shape[0] * shape[1], dtype=torch.float32)
    torch_input_fp32 = torch.full(shape, 128.5, dtype=torch.float32)
    torch_input_fp32 = torch.reshape(torch_input_fp32, shape)
    torch_golden_bf16 = torch_input_fp32.to(torch.bfloat16)

    ttnn_calculated_bf16 = ttnn.from_torch(torch_input_fp32, dtype=ttnn_dtype, device=device, layout=ttnn.TILE_LAYOUT)
    torch_calculated_bf16 = ttnn.to_torch(ttnn_calculated_bf16)

    assert_with_ulp(torch_golden_bf16, torch_calculated_bf16, ulp_threshold=0)
```

will have a FAILED test on `test_from_torch.py::test_from_torch_typecast` with a ULP error of 1 (128 rounded to 129 instead of 128). 

### Expected behavior

ttnn.typecast should round-to-nearest-tie-to-even and be consistent with torch and other ttnn rounding operations.
ttnn.typecast(128.5) should return 128.

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by jasondavies**
### Ticket

Closes https://github.com/tenstorrent/tt-metal/issues/30147

Part of typecast LLK revamp: https://github.com/tenstorrent/tt-metal/issues/33976

### Problem description

- Unlike PyTorch, typecasting fp32→bf16 currently uses round-to-nearest with ties away from zero.
- fp32_to_[u]int32 LLKs were also in need of optimisation.

### What's changed

- Use optimised fp32→bf16 typecast LLK with round-to-nearest-even.
- This requires calling an init function to set up SFPLOADMACRO and constants.
- Modified `typecast_tile_init` to use `<in, out>` template params, matching `typecast_tile`.
- Add fp32_to_bf16 typecast init call.
- Add fp32_to_[u]int32 (renamed from fp16b_to_[u]int32).

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/runs/20463722805) CI passes
- [x] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/runs/20463720109) CI with demo tests passes (if applicable)
- [x] [L2 Nightly](https://github.com/tenstorrent/tt-metal/actions/runs/20463716712) CI passes
- [x] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/runs/20463705625) CI passes

### CODE REVIEW

**Comment by jasondavies** [comment]
@fvranicTT Updated.  Looks like I missed an init.

**Comment by jasondavies** [comment]
@fvranicTT Rolled in two more typecast functions, and fixed the errors.

**Comment by fvranicTT** [comment]
BH PC: https://github.com/tenstorrent/tt-metal/actions/runs/20197422537
Nightly C++: https://github.com/tenstorrent/tt-metal/actions/runs/20197429699

Note that we have a few known failures in these pipelines.

**Comment by jasondavies** [comment]
Really getting into the weeds here.  Reasons for current test failures:

typecast_tile_init, typecast_tile get put into `PROCESS_POST_ACTIVATIONS`.  The problem is that the new typecast_init overwrites two constants that are used by the binary op.

```cpp
for (uint32_t i = 0; i < num_tiles_per_cycle; ++i) {
    copy_tile(cb_post_rhs, i, i * 2 + 1);

    BINARY_SFPU_OP(i * 2, i * 2 + 1, i * 2);
    PROCESS_POST_ACTIVATIONS(i * 2);
}
tile_regs_commit();
```

**Comment by jasondavies** [comment]
Adding this fix everywhere could be a bit time consuming:

```diff
--- a/ttnn/cpp/ttnn/operations/eltwise/binary_ng/device/kernels/compute/eltwise_binary_sfpu_no_bcast.cpp
+++ b/ttnn/cpp/ttnn/operations/eltwise/binary_ng/device/kernels/compute/eltwise_binary_sfpu_no_bcast.cpp
@@ -44,7 +44,7 @@ void MAIN {
     PACK((llk_pack_relu_config(ReluType::ZERO_RELU)));
 #endif

-#if not(HAS_ACTIVATIONS(LHS) or HAS_ACTIVATIONS(RHS))
+#if not(HAS_ACTIVATIONS(LHS) or HAS_ACTIVATIONS(RHS) or HAS_ACTIVATIONS(POST))
     BINARY_SFPU_INIT
 #endif

@@ -57,7 +57,7 @@ void MAIN {

         cb_reserve_back(cb_out, num_tiles_per_cycle);

-#if HAS_ACTIVATIONS(LHS) or HAS_ACTIVATIONS(RHS)
+#if (HAS_ACTIVATIONS(LHS) or HAS_ACTIVATIONS(RHS)) and not(HAS_ACTIVATIONS(POST))
         BINARY_SFPU_INIT
 #endif
         tile_regs_acquire();
@@ -69,6 +69,9 @@ void MAIN {
         for (uint32_t i = 0; i < num_tiles_per_cycle; ++i) {
             copy_tile(cb_post_rhs, i, i * 2 + 1);

+#if HAS_ACTIVATIONS(POST)
+            BINARY_SFPU_INIT
+#endif
             BINARY_SFPU_OP(i * 2, i * 2 + 1, i * 2);
             PROCESS_POST_ACTIVATIONS(i * 2);
         }
```

**Comment by jasondavies** [comment]
@fvranicTT This should fix the issue but it may well appear elsewhere if init functions are not properly respected.

**Comment by jasondavies** [comment]
@fvranicTT Fixed silly typo

**Comment by fvranicTT** [comment]
> @fvranicTT Fixed silly typo

Ah I only saw this now @jasondavies .
I think that explains a lot of llk test failures [here](https://github.com/tenstorrent/tt-metal/actions/runs/20197429699/job/57983594400). Let me rerun the pipelines.

**Comment by fvranicTT** [comment]
BH PC: https://github.com/tenstorrent/tt-metal/actions/runs/20205044385
Nightly C++ tests: https://github.com/tenstorrent/tt-metal/actions/runs/20205052002

**Comment by jasondavies** [comment]
I can reproduce this failure, but unclear if related to my changes:

> python -m pytest 'tests/tt_eager/python_api_testing/unit_testing/misc/test_distributed_layernorm_post_allgather.py::test_layernorm_part_2_with_program_cache[fp32_disabled-layernorm-4-inp_shape0-BFLOAT16]'

Doesn't seem to use any typecasting.

Otherwise things are looking good.  Let me know if you see any errors that I should look into.

**Comment by fvranicTT** [comment]
> I can reproduce this failure, but unclear if related to my changes:
> 
> 
> 
> > python -m pytest 'tests/tt_eager/python_api_testing/unit_testing/misc/test_distributed_layernorm_post_allgather.py::test_layernorm_part_2_with_program_cache[fp32_disabled-layernorm-4-inp_shape0-BFLOAT16]'
> 
> 
> 
> Doesn't seem to use any typecasting.
> 
> 
> 
> Otherwise things are looking good.  Let me know if you see any errors that I should look into.

This is one of the known failures. It was reported last week.

**Comment by fvranicTT** [comment]
New set of runs:
BH PC: https://github.com/tenstorrent/tt-metal/actions/runs/20223708284
Nightly: https://github.com/tenstorrent/tt-metal/actions/runs/20223718722

I reran a few of the failed jobs. I haven't checked all of them, but some look like they are failing for some time.

**Comment by fvranicTT** [comment]
It seems we're ok. The remaining failures are already known issues.

File: ttnn/cpp/ttnn/operations/copy/typecast/device/typecast_program_factory.cpp [hunk 1]
```diff
@@ -87,6 +87,10 @@ TypecastProgramFactory::cached_program_t TypecastProgramFactory::create(
     bool math_approx_mode = false;
 
     std::map<std::string, std::string> unary_defines;
+    unary_defines["TYPECAST_LLK_INIT"] = fmt::format(
+        "typecast_tile_init<{0}u, {1}u>",
+        (uint32_t)datatype_to_dataformat_converter(input_dtype),
```
Comment (fvranicTT) [inline ttnn/cpp/ttnn/operations/copy/typecast/device/typecast_program_factory.cpp]:
```suggestion
        static_cast<uint32_t>(datatype_to_dataformat_converter(input_dtype)),
```

nitpick comment. We should really move away from C-style casts.

**Comment by jasondavies** [comment]
> It seems we're ok. The remaining failures are already known issues.

Thanks.  I have the remainder of the typecast ops to complete, but I thought it would be better to merge this in parts to make it easier to catch any possible problems further down the line.  So I'll do the remainder in a "part 2" at some point.  This PR helped ensure proper init is in place.

**Comment by fvranicTT** [comment]
> > It seems we're ok. The remaining failures are already known issues.
> 
> Thanks. I have the remainder of the typecast ops to complete, but I thought it would be better to merge this in parts to make it easier to catch any possible problems further down the line. So I'll do the remainder in a "part 2" at some point. This PR helped ensure proper init is in place.

Yeah, let's merge part1 first. North America is still in bed, waiting for the ttnn code owners to approve, and I'll try to streamline the llk->metal part after that.

**Review by dchenTT — APPROVED** [review]

**Comment by KalaivaniMCW** [comment]
I have triggered Nightly L2 Eltwise here : https://github.com/tenstorrent/tt-metal/actions/runs/20326771652

**Review by KalaivaniMCW — APPROVED** [review]

**Review by Aswinmcw — APPROVED** [review]

**Comment by nvelickovicTT** [comment]
@jasondavies tis PR needs to be merged in lockstep with the tt-llk one, but has conflicts. Can you update to resolve them?

**Comment by jasondavies** [comment]
@nvelickovicTT Done - it was just conflicting on the tt-llk ref.

**Review by nvelickovicTT — APPROVED** [review]

**Comment by nvelickovicTT** [comment]
@jasondavies I think you need to rebase to latest tt-metal main as well. A PR with folder path changes went in in the meantime.

**Comment by jasondavies** [comment]
@nvelickovicTT Done.  Both tt-llk and tt-metal PRs should now be up-to-date.

**Comment by jasondavies** [comment]
@nvelickovicTT All green

**Review by blozano-tt — APPROVED** [review]
✅ CodeOwners bypass approval granted by @dpopovTT (metalium-developers-infra team)

**Comment by nvelickovicTT** [comment]
Thanks Jason. I've triggered the tt-llk part merge process.
Once that is done, can you please retarget llk submodule here to point to the latest tt-llk main.
In the meantime I am pursuing to get the final approves needed.
And then we will merge this part.

**Comment by jasondavies** [comment]
@fvranicTT @nvelickovicTT Updated

**Comment by fvranicTT** [comment]
APC: https://github.com/tenstorrent/tt-metal/actions/runs/20463722805
BH PC: https://github.com/tenstorrent/tt-metal/actions/runs/20463720109
Nightly C++ tests: https://github.com/tenstorrent/tt-metal/actions/runs/20463716712
Device perf regression tests: https://github.com/tenstorrent/tt-metal/actions/runs/20463705625
