### PR TITLE
Enable and fix readability-inconsistent-declaration-parameter-name clang-tidy check

### LINKED ISSUE #34339: Function parameter names inconsistent between declaration and definition
Our code base, particularly `ttnn` has a vast number of occurrences where function parameter names in declarations do not match the names used in the definition.

In some cases this is quite serious: for example parameters that appear to be swapped between declaration and definition, or parameters that are just entirely incorrectly named in the declaration - this would be misleading to anyone reading the header file - and could in fact be bugs.

Apparent swap of parameters:
Declaration:
https://github.com/tenstorrent/tt-metal/blob/f79a0b1ab89aa8cac98b3af53f90f484e4472c9f/ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_async_op.hpp#L290-L291
Definition:
https://github.com/tenstorrent/tt-metal/blob/f79a0b1ab89aa8cac98b3af53f90f484e4472c9f/ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_async_op.cpp#L512-L513

Incorrect parameter name in declaration:

Image

To surface all such problems you can use clang-tidy:
https://clang.llvm.org/extra/clang-tidy/checks/readability/inconsistent-declaration-parameter-name.html

Edit `.clang-tidy` to contain:
```
Checks: >
  -*,
  readability-inconsistent-declaration-parameter-name,

CheckOptions:
  - key: readability-function-cognitive-complexity.IgnoreMacros
    value: true
  - key: readability-function-cognitive-complexity.Threshold
    value: 339
  - key: portability-simd-intrinsics.Suggest
    value: true
  # May enable later; for now activate the check with a lighter touch
  - key: readability-simplify-boolean-expr.SimplifyDeMorgan
    value: false
  - key: performance-unnecessary-copy-initialization.AllowedTypes
    value: "^MemoryPin$"

FormatStyle: 'file'

HeaderFilterRegex: '.*'
```

Run:
```
cmake --preset clang-tidy
cmake --build --preset clang-tidy
```

### PR DESCRIPTION
**Pull request by pavlejosipovic**
### Ticket
Closes [Issue 34339](https://github.com/tenstorrent/tt-metal/issues/34339)

### Problem description
Function parameter names inconsistent between declaration and definition

### What's changed
Enable clang-tidy check for this and fix instances of this problem

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/runs/20367762108)
- [ ] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/runs/20367766866) (same as main)
- [x] [Merge gate](https://github.com/tenstorrent/tt-metal/actions/runs/20371352841/job/58538539463)

### CODE REVIEW

File: tt_metal/api/tt-metalium/mesh_device.hpp [hunk 1]
```diff
@@ -153,7 +153,7 @@ class MeshDevice : public IDevice, public std::enable_shared_from_this<MeshDevic
 
 public:
     MeshDevice(
-        std::shared_ptr<ScopedDevices> scoped_devices,
+        std::shared_ptr<ScopedDevices> mesh_handle,
```
Comment (dstoiljkovicTT) [inline tt_metal/api/tt-metalium/mesh_device.hpp:156]: IMO scoped_devices is a better fit for a name to this parameter, so maybe we could change the definition to fit the declaration version

File: ttnn/cpp/ttnn/operations/eltwise/binary_ng/device/binary_ng_device_operation.hpp [hunk 2]
```diff
@@ -71,13 +71,13 @@ struct BinaryNgDeviceOperation {
         static cached_program_t create(
             const operation_attributes_t& operation_attributes,
             const tensor_args_t& tensor_args,
-            tensor_return_value_t& output);
+            tensor_return_value_t& c);
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/eltwise/binary_ng/device/binary_ng_device_operation.hpp:74]: Same here, this naming is not very informative

File: ttnn/cpp/ttnn/operations/eltwise/unary/unary_composite.hpp [hunk 3]
```diff
@@ -54,32 +54,32 @@ struct ExecuteUnaryCompositeOpWithFloats {
...
+        const Tensor& input_a,
         std::optional<std::variant<float, int32_t>> min = std::nullopt,
         std::optional<std::variant<float, int32_t>> max = std::nullopt,
-        const std::optional<MemoryConfig>& memory_config = std::nullopt,
+        const std::optional<MemoryConfig>& output_mem_config = std::nullopt,
         const std::optional<Tensor>& output_tensor = std::nullopt);
 
     static Tensor invoke(
-        const Tensor& input_tensor,
+        const Tensor& a,
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/eltwise/unary/unary_composite.hpp:64]: Again not fan of one letter variables, but less of a fan of inconsistent naming throughout different invoke functions

File: ttnn/cpp/ttnn/operations/experimental/bcast_to/device/bcast_to_device_operation.hpp [hunk 4]
```diff
@@ -54,7 +54,7 @@ struct BcastToOperation {
             cached_program_t& cached_program,
             const operation_attributes_t& operation_attributes,
             const tensor_args_t& tensor_args,
-            tensor_return_value_t& output);
+            tensor_return_value_t& c);
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/experimental/bcast_to/device/bcast_to_device_operation.hpp:57]: Same here

File: ttnn/cpp/ttnn/operations/experimental/ccl/llama_all_gather_matmul_async/llama_all_gather_matmul_async.hpp [hunk 5]
```diff
@@ -14,7 +14,7 @@ namespace operations::experimental::ccl {
 
 struct ExecuteAllGatherMatmulAsync {
     static ttnn::Tensor invoke(
-        const ttnn::Tensor& input0,
+        const ttnn::Tensor& input_tensor,
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/experimental/ccl/llama_all_gather_matmul_async/llama_all_gather_matmul_async.hpp]: Can we have these two sequential parameters both match the naming convention?

File: ttnn/cpp/ttnn/operations/experimental/slice_write/slice_write.hpp [hunk 6]
```diff
@@ -12,8 +12,8 @@ struct SliceWriteOperation {
     static ttnn::Tensor invoke(
         const ttnn::Tensor& input_tensor,
         ttnn::Tensor& output_tensor,
-        const ttnn::SmallVector<uint32_t>& output_tensor_start,
-        const ttnn::SmallVector<uint32_t>& output_tensor_end,
+        const ttnn::SmallVector<uint32_t>& begins,
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/experimental/slice_write/slice_write.hpp:15]: These previous two seemed more descriptive

File: ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/moreh_clip_grad_norm_step3_device_operation.hpp [hunk 7]
```diff
@@ -42,13 +42,13 @@ struct MorehClipGradNormStep3Operation {
         static cached_program_t create(
             const operation_attributes_t& operation_attributes,
             const tensor_args_t& tensor_args,
-            tensor_return_value_t& tensor_return_value);
+            tensor_return_value_t& inputs);
```
Comment (dstoiljkovicTT) [inline ttnn/cpp/ttnn/operations/moreh/moreh_clip_grad_norm/moreh_clip_grad_norm_step3/device/moreh_clip_grad_norm_step3_device_operation.hpp:45]: Are these really inputs?

**Review by dstoiljkovicTT — APPROVED** [review]
Mostly nitpicking comments, feel free to decide whether this should be changed as a part of this PR or not, overall LGTM

**Review by esmalTT — APPROVED** [review]

**Review by aczajkowskiTT — APPROVED** [review]

**Review by jbaumanTT — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]

**Review by akerteszTT — APPROVED** [review]
Renaming params doesn't impact API stability.

**Comment by blozano-tt** [comment]
Thank you!🙏

**Review by mgajewskiTT — APPROVED** [review]

**Review by TT-BrianLiu — APPROVED** [review]

**Comment by blozano-tt** [comment]
Let infra team know if you think bypassing remaining codeowners is warranted- given simple changes + holiday schedules.

**Review by sjameelTT — APPROVED** [review]

File: tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp [hunk 8]
```diff
@@ -274,7 +274,7 @@ class ControlPlane {
     // Tries to get a valid downstream channel from the candidate_target_chans
     // First along same routing plane, but if not available, take round robin from candidates
     chan_id_t get_downstream_eth_chan_id(
-        chan_id_t src_chan_id, const std::vector<chan_id_t>& candidate_target_chans) const;
```
Comment (Riddy21) [inline tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp:277]: I think this should remain as channel id, we never call our channel values as routing plane ids

**Review by abhullar-tt — APPROVED** [review]

**Review by dchenTT — APPROVED** [review]

**Review by gsarabandoTT — APPROVED** [review]

**Review by afuller-TT — APPROVED** [review]

File: tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp (hunk 8 above)
Comment (pavlejosipovic) [reply tt_metal/api/tt-metalium/experimental/fabric/control_plane.hpp:277]: I'm not making up the names here, this is automatic change to match names in headers to the ones found in cpp

**Review by blozano-tt — APPROVED** [review]
✅ CodeOwners bypass approval granted by @dpopovTT (metalium-developers-infra team)
