### PR TITLE
#35290: Fix forward GELU ULP precision with piecewise CDF polynomials

### LINKED ISSUE #35290: [TTNN]: ttnn.gelu() has catastrophic ULP errors in multiple regions (up to 32,767 ULP)
### Component / Area

TTNN / Eltwise Operations / GELU (Accurate/Chebyshev mode)

### Issue Type (optional)

Bad Outputs

### Observed

`ttnn.gelu()` in accurate mode (default, `fast_and_approximate_mode=False`) has **THREE** problematic regions with catastrophic ULP errors:

#### Region 1: Deep Negative Tail (x < -5.5) — WORST

| Input | Expected | Actual | ULP Error |
|-------|----------|--------|-----------|
| -13.5 | -1.06e-40 | 0.0 | **32,767** |
| -12.0 | -2.13e-32 | 0.0 | 29,987 |
| -10.0 | -7.62e-24 | 0.0 | 24,481 |
| -7.0 | -8.96e-12 | 0.0 | 21,219 |
| -5.5625 | -7.40e-08 | 0.0 | 19,554 |

**Cause**: Hardware returns exactly 0.0 for x < -5.5, but exact GELU has tiny negative values.

#### Region 2: Near-Zero (|x| < ~1e-4)

| Input | Expected (0.5×x) | Actual | ULP Error |
|-------|------------------|--------|-----------|
| 1e-38 | 5e-39 | 2.98e-05 | **14,276** |
| 1e-30 | 5e-31 | 2.98e-05 | 10,968 |
| 1e-20 | 5e-21 | 2.98e-05 | 6,718 |
| 1e-10 | 5e-11 | 2.98e-05 | 2,463 |

**Cause**: Chebyshev polynomial c0 coefficient (2.98e-05) dominates for tiny inputs.

#### Region 3: Transition Region (-5.5 to ~-4.0)

| Input | Expected | Actual | ULP Error |
|-------|----------|--------|-----------|
| -5.5 | -1.04e-07 | -3.11e-04 | 1,475 |
| -5.375 | -2.06e-07 | -1.06e-04 | 1,155 |
| -5.0 | -1.43e-06 | -1.26e-04 | 836 |

**Cause**: Polynomial is poorly fitted near the -5.5 threshold boundary.

#### Overall Statistics (Full BFloat16 Sweep)

```
Total values tested: 65,278
Max ULP error: 32,767 (maximum possible for BF16!)
Mean ULP error: 3,266
Values with ULP > 1000: 27,089 (41.5%)
Values with ULP > 100: 29,243 (44.8%)
Values with ULP <= 1: 34,254 (52.5%)
```

### Expected

For all inputs, GELU should have ULP error ≤ 10. Research shows Max ULP ≤ 1 is achievable with proper implementation (see https://github.com/ivoitovych/bf16_gelu_research).

### 1. Steps (exact commands)

**Prerequisites:** tt-metal must be cloned and built per standard instructions.

```bash
cd tt-metal

# Cherry-pick the reproducer tests (single commit with all files)
git fetch https://github.com/ivoitovych/tt-metal.git ivoitovych/bug-report-gelu-floor-value-ulp-03
git cherry-pick FETCH_HEAD

# Rebuild only the C++ test target (incremental, ~30 seconds)
cmake --build build_Debug --target unit_tests_ttnn

# Run Python reproducer (24 tests)
pytest tests/ttnn/unit_tests/operations/eltwise/test_gelu_floor_value_bug.py -v -s

# Run C++ reproducer (14 tests: 10 ULP verification + 4 GELU bug reproduction)
./build_Debug/test/ttnn/unit_tests_ttnn --gtest_filter="*GeluUlp*:*BFloat16Ulp*"
```

**Reproducer files (all in single commit):**
- Python test: `tests/ttnn/unit_tests/operations/eltwise/test_gelu_floor_value_bug.py`
- C++ test: `tests/ttnn/unit_tests/gtests/test_gelu_ulp_bug.cpp`
- This report: `tests/ttnn/unit_tests/operations/eltwise/GELU_FLOOR_VALUE_BUG_REPORT.md`

**Branch URL:** https://github.com/ivoitovych/tt-metal/tree/ivoitovych/bug-report-gelu-floor-value-ulp-03

### 2. Input data / link or description

**Minimal reproducer for Region 1 (Deep Negative Tail):**
```python
import torch
import ttnn

device = ttnn.open_device(device_id=0)

# Deep negative value — hardware returns 0.0, should return tiny negative
input_val = -13.5
torch_input = torch.tensor([[input_val]], dtype=torch.bfloat16)
tt_input = ttnn.from_torch(torch_input, dtype=ttnn.bfloat16, device=device, layout=ttnn.TILE_LAYOUT)

result = ttnn.gelu(tt_input, fast_and_approximate_mode=False)
actual = ttnn.to_torch(result).item()

print(f"Input:    {input_val}")
print(f"Expected: ~-1e-40 (tiny negative)")
print(f"Actual:   {actual}")  # Will print 0.0

ttnn.close_device(device)
```

**Minimal reproducer for Region 2 (Near-Zero):**
```python
import torch
import ttnn

device = ttnn.open_device(device_id=0)

# Tiny positive value — hardware returns 2.98e-05, should return 0.5*x
input_val = 1e-20
torch_input = torch.tensor([[input_val]], dtype=torch.bfloat16)
tt_input = ttnn.from_torch(torch_input, dtype=ttnn.bfloat16, device=device, layout=ttnn.TILE_LAYOUT)

result = ttnn.gelu(tt_input, fast_and_approximate_mode=False)
actual = ttnn.to_torch(result).item()

print(f"Input:    {input_val:.2e}")
print(f"Expected: {0.5 * input_val:.2e}")
print(f"Actual:   {actual:.6e}")  # Will print ~2.98e-05

ttnn.close_device(device)
```

### 3. Frequency

100% reproducible. The full BFloat16 sweep shows:
- Region 1 (x < -5.5): 172 values affected with ULP > 1000
- Region 2 (near-zero): 26,917 values affected with ULP > 1000
- Region 3 (transition): ~200 values with ULP 100-1500

### 1. Software Versions

- tt-metal: main branch (commit 38355f582c or later)
- Python: 3.10
- OS: Ubuntu 22.04

### 2. Hardware Details

- Device: Wormhole n150 L
- Board ID: 0100018611902024
- FW Bundle: 18.5.0

**Additional Verification — Blackhole P150 (FW 19.1.0):**

| Input | Wormhole ULP | Blackhole ULP | Notes |
|-------|--------------|---------------|-------|
| -13.5 | 32,767 | 32,767 | ✓ Match |
| -12.0 | 29,987 | 29,987 | ✓ Match |
| -10.0 | 24,481 | 25,928 | ~6% variance |
| -5.5625 | 19,554 | 19,554 | ✓ Match |
| Near-zero | exact | exact | ✓ Match |
| Transition | exact | exact | ✓ Match |

Bug pattern and severity consistent across both architectures.

### Is this a regression?

Unknown

### Regression Details

N/A

### Logs & Diagnostics

**Full test output with all regions:**
```
====================================================================================================
TOP 50 WORST ULP ERRORS
====================================================================================================
         Value |       Expected |         Actual |  ULP Error |   BF16 Hex
----------------------------------------------------------------------------------------------------
 -1.350000e+01 |  -1.055539e-40 |   0.000000e+00 |     32,767 | 0xC158
 -1.343750e+01 |  -2.449291e-40 |   0.000000e+00 |     32,766 | 0xC157
 -1.337500e+01 |  -5.661216e-40 |   0.000000e+00 |     32,762 | 0xC156
 ...
 -5.531250e+00 |  -8.793492e-08 |   0.000000e+00 |     19,524 | (threshold)
 -5.500000e+00 |  -1.044426e-07 |  -3.108978e-04 |      1,475 | (transition)
 ...
  1.000000e-38 |   5.000000e-39 |   2.980232e-05 |     14,276 | (near-zero)

====================================================================================================
REGIONS WITH ULP > 1000
====================================================================================================

Found 2 distinct region(s) with ULP > 1000:

Region 1: DEEP NEGATIVE TAIL
  Range: [-13.5, -5.375]
  Max ULP: 32,767
  Count: 172 values

Region 2: NEAR-ZERO
  Range: [-6e-05, 2.7e-07]
  Max ULP: 14,330
  Count: 26,917 values
```

#### Root Cause Analysis

The GELU accurate mode uses `calculate_gelu_chebyshev()` defined in:
`tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h`

```cpp
template <bool APPROXIMATION_MODE, int ITERATIONS = 8>
inline void calculate_gelu() {
    // ...
    v_if(in == 0.0f) { result = 0.0f; }
    v_elseif(in < 3.0f) { result = calculate_gelu_chebyshev(in); }
    v_endif;
    // ...
}

inline sfpi::vFloat calculate_gelu_chebyshev(sfpi::vFloat val) {
    sfpi::vFloat result = 0.0f;
    v_if(val >= -5.5f) {
        result = POLYVAL15(
            // ... coefficients ...
            2.98325768482e-05,    // c0  <-- FLOOR VALUE BUG
            val);
        result = setsgn(result, val);
    }
    v_endif;  // <-- Returns 0.0 for val < -5.5  (DEEP TAIL BUG)
    return result;
}
```

**Bug 1 (Deep Negative Tail):** The `v_if(val >= -5.5f)` returns 0.0 for x < -5.5, but exact GELU has tiny negative values that are representable in BF16.

**Bug 2 (Near-Zero):** The constant term c0 = 2.98e-05 dominates for tiny inputs since all higher-order polynomial terms become negligible.

**Bug 3 (Transition):** The polynomial is poorly fitted near the -5.5 boundary.

#### Proposed Fixes

**For Region 1 (Deep Negative Tail):**
The threshold of -5.5 is too aggressive. For BFloat16, GELU approaches 0 only at x ≈ -13.5625 (saturation threshold). Options:
1. Lower the threshold to -13.5
2. Use asymptotic expansion: `GELU(x) ≈ -φ(x)·(1 - 1/x² + 3/x⁴)` for deep negatives
3. Accept returning 0.0 for x < -13.5 only

**For Region 2 (Near-Zero):**
Add special handling for tiny inputs:
```cpp
v_if(abs_val < 1e-6f) {
    result = val * 0.5f;  // Taylor: GELU(x) ≈ 0.5*x for small x
}
```

**For Region 3 (Transition):**
Refit the Chebyshev polynomial with better boundary handling, or use a piecewise approach with separate polynomial for the transition region.

### Priority

P2

### Impact

- **44.8% of all BFloat16 values** have ULP error > 100
- **41.5% of all BFloat16 values** have ULP error > 1000
- Max ULP of 32,767 is catastrophic (maximum possible error)
- Affects any model using GELU with:
  - Deep negative activations (e.g., after failed training, bad initialization)
  - Near-zero activations (residual connections, normalized values)
  - Training stability in edge cases

#### References

- BFloat16 GELU approximation research: https://github.com/ivoitovych/bf16_gelu_research
- Research shows Max ULP ≤ 1 is achievable with adaptive polynomial approach
- Source file: `tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h`

### PR DESCRIPTION
**Pull request by epam-iaroslav-voitovych**
### Ticket
Fixes #35290

### Problem description
`ttnn::gelu()` (forward, `fast_and_approx=false`) uses a degree-15 Chebyshev polynomial (`calculate_gelu_chebyshev()`) that:
1. Returns 0 for all `x < -5.5`, but `GELU(-5.5) ~ -1.8e-7` (not 0) → Max ULP = 32,767
2. Has a hardcoded floor value of `2.98e-05` near zero → Max ULP = 14,276
3. Has poor polynomial fit in the transition region `(-5.5, -4.0)` → Max ULP = 1,475

Under the DAZ+FTZ hardware model (denormals treated as zero), the effective Max ULP is still 32,767 — the worst possible for BF16.

### What's changed
Replaced `calculate_gelu_chebyshev()` with `calculate_gelu_piecewise()` using a CDF polynomial approach: `GELU(x) = x * Phi(x)`, where `Phi(x) = 0.5 * (1 + erf(x/sqrt(2)))` is approximated by piecewise polynomials. This ensures `GELU(0) = 0` exactly (since `x * Phi(0) = 0 * 0.5 = 0`).

#### 3 active regions (plus zero default)

| Region | Method | Max ULP |
|--------|--------|---------|
| `x <= -13.1875` | Saturation to 0 | **0** (exact) |
| `(-13.1875, -3.125)` | Moroz `exp_21f(-x²/2)` × degree-4 correction polynomial | **1** |
| `[-3.125, 2.78125)` | Core CDF polynomial (degree 15, factored via `u = x²`) | **1** |
| `x >= 2.78125` | Identity (`return x`) | **0** (exact) |

#### Identity threshold

With RNE rounding (round-to-nearest-even, matching hardware pack behavior per [`tech_reports/data_formats/data_formats.md`](https://github.com/tenstorrent/tt-metal/blob/main/tech_reports/data_formats/data_formats.md)), `GELU(x)` rounds to `x` in BF16 for all `x >= 2.78125` (BF16 `0x4032`). This is the exact boundary verified by exhaustive BF16 sweep with fp64 golden reference. The kernel uses this precise threshold.

#### Results across all ~65K BF16 values

| Metric | Before | After |
|--------|--------|-------|
| Max ULP | 32,767 | **1** |
| Mean ULP | ~155 | **0.05** |
| % exact (ULP = 0) | ~49% | **99.97%** |
| % within 1 ULP | ~50% | **100%** |

#### Per-region breakdown (hardware-validated, Wormhole n150)

```
                             Region     Count    Mean ULP     Max ULP       Worst x
------------------------------------------------------------------------------------
    Saturation to 0 (x <= -13.1875)     15917        0.00           0      0.000e+00
      Exp-based (-13.1875, -3.125)        266        0.09           1     -3.141e+00
     Core CDF poly [-3.125, 2.78125)    32637        0.00           1      2.342e-38
            Identity (x >= 2.78125)     16206        0.00           0      0.000e+00
------------------------------------------------------------------------------------
                            OVERALL     65026        0.00           1      2.342e-38
```

#### Saturation thresholds

Verified by exhaustive BF16 sweep with fp64 golden reference (RNE rounding):
- **Negative zero saturation:** `x <= -13.1875` → `GELU(x)` rounds to 0 in BF16
- **Positive identity saturation:** `x >= 2.78125` (BF16 `0x4032`) → `GELU(x)` rounds to `x` in BF16 with RNE rounding

#### Exp region: Moroz exp_21f + correction polynomial

The exp-based region uses Moroz `exp_21f` (compact integer bit-trick exp) instead of the library `_sfpu_exp_f32_accurate_()` call or Cody-Waite range reduction. The correction factor `P(x) ≈ GELU(x)·exp(x²/2)` is a degree-4 minimax polynomial in `x`, fitted to the TRUE erfc-based function via Chebyshev approximation. This replaces the asymptotic Mills ratio `1 - 1/x² + 3/x⁴ - ...` and eliminates the reciprocal call and its LUT init entirely.

#### Branch pattern: v_if/v_and narrowing

Uses `v_if`/`v_and` progressive narrowing instead of `v_if`/`v_elseif` branching. Starts with the widest region (exp), narrows to core CDF, then identity. This avoids separate branch mask setup per region.

#### Performance (host-side timing, Wormhole n150)

The `APPROXIMATION_MODE=true` (fast) path is unchanged. Only the `APPROXIMATION_MODE=false` (accurate) path is affected. [Benchmark script](https://gist.github.com/epam-iaroslav-voitovych/f3d26419569744b3b3f3f05ede25d009).

| Shape | Tiles | Original (us) | This PR (us) | Ratio |
|-------|------:|--------------:|-------------:|------:|
| [1,1,32,32] | 1 | 291 | 248 | 0.85x (15% faster) |
| [1,1,256,256] | 64 | 194 | 192 | 0.99x (same) |
| [1,1,1024,1024] | 1,024 | 191 | 213 | 1.12x slower |
| [1,1,4096,4096] | 16,384 | 634 | 771 | 1.22x slower |

A/B measured in the same session on the same device with kernel cache cleared between phases (main `8071cf40e1`, 2026-04-01). At small shapes (dispatch-dominated), performance is comparable or faster. At 16,384 tiles (compute-dominated), the piecewise kernel is 1.22x slower than the original branchless degree-15 Horner — the cost of achieving Max ULP = 1 (vs 32,767). The SFPU executes all region code for all elements with masking, so branch evaluation overhead adds cost even when most elements fall in the core polynomial region.

#### A/B hardware verification (Wormhole n150)

Main (`8071cf40e1`) kernel vs this PR's kernel, same build, same device, kernel cache cleared between phases.

| Metric | Phase A (main) | Phase B (this PR) |
|--------|---------------------|-------------------|
| ULP tests | 7/11 FAILED | **11/11 PASSED** |
| Max ULP | 32,767 | **1** |
| 16K tiles host timing | 634 us | 771 us |

Phase A confirms the original kernel fails the accuracy tests. Phase B confirms the fix passes with 1.22x performance cost.

#### Backward GELU unaffected

The backward path (`calculate_gelu_derivative_piecewise()`) is independent code in the same file and is not touched by this PR.

#### Files changed

| File | Change |
|------|--------|
| `tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h` | Add `calculate_gelu_piecewise()` with Moroz exp_21f, correction polynomial, v_if/v_and narrowing; update `calculate_gelu()` dispatch with RNE rounding guard |
| `tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h` | Byte-identical copy of WH version |
| `tt_metal/hw/inc/api/compute/eltwise_unary/gelu.h` | Use `SFPU_TWO_PARAM_KERNEL`/`SFPU_TWO_TEMPLATE_PARAM_INIT` macros for `DST_ACCUM_MODE` passthrough |
| `tests/ttnn/unit_tests/gtests/test_gelu_fw_ulp.cpp` | **New** — 11 C++ ULP tests (comprehensive BF16 sweep, per-region analysis, special values, saturation boundary verification, reference verification) |
| `tests/ttnn/unit_tests/gtests/sources.cmake` | Register new test file |

### Checklist

- [x] [Sanity tests](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml)
- [x] [Nightly tt-metal L2 tests](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml)

### CODE REVIEW

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 1]
```diff
@@ -6,85 +6,166 @@
...
+        sfpi::vFloat t = x2 * (-0.5f);  // t = -x^2/2
+
+        // Use general-purpose exp for the forward case
+        // (no fused method needed: result magnitude > exp(t) magnitude)
+        sfpi::vFloat exp_val = _sfpu_exp_f32_accurate_(t);
+
+        // Mills ratio asymptotic correction
+        sfpi::vFloat inv_x2 = _sfpu_reciprocal_<2>(x2);  // 1/x^2
+        sfpi::vFloat inv_x4 = inv_x2 * inv_x2;           // 1/x^4
+        sfpi::vFloat correction = 1.0f - inv_x2 + 3.0f * inv_x4;
```
Comment (mateusznowakTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: (3.0f * inv_x2 - 1) * inv_x2 + 1.0f will do 2xMAD instead of MUL+MAD+ADD

**Review by mateusznowakTT — CHANGES_REQUESTED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 2]
```diff
@@ -6,85 +6,166 @@
...
+// - Identity saturation: x >= 2.78125 (GELU(x) rounds to x in BF16 with RNE)
+//   2.78125 is the exact BF16 boundary (0x4032) where GELU first rounds to identity
+// =============================================================================
+
+// Degree-16 CDF polynomial for Phi(x) over [-3, 3]
+// Phi(x) is an even function offset by 0.5: Phi(x) = 0.5 + odd_function(x)
+// So even-degree coefficients (c2, c4, ...) are effectively zero
+constexpr float GELU_CDF_CORE_C0 = 5.000000000e-01f;
+constexpr float GELU_CDF_CORE_C1 = 3.989383512e-01f;
+constexpr float GELU_CDF_CORE_C2 = 0.0f;
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: These zero coefficients are wasting cycles.
Each recursion level emits one `SFPMUL` and one `SFPADD/SFPADDI` on the SFPU. For a zero coefficient, 0.0f + x * eval(...) still generates:
1. SFPMUL (2 cycles + 1 SFPNOP = 3 cycles) - multiply by x
2. SFPADD (2 cycles + 1 SFPNOP = 3 cycles) - add zero

These are hardware intrinsic operations on vector lane registers, the compiler cannot elide them.

Cost of the waste:
8 zero coefficients * 2 wasted ops each = 16 wasted SFPU operations
16 ops * 3 cycles = 48 wasted cycles per invocation
With `ITERATIONS=8` in the outer loop: ~384 wasted cycles per `calculate_gelu()` call

Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: The polynomial has only odd powers (plus the constant), so it can be rewritten using `u = x^2`:

Current (Horner on x, degree 16):  `p(x) = c0 + x*(c1 + x*(0 + x*(c3 + x*(0 + x*(c5 + ...)))))`  == 16 MULs + 16 ADDs = 32 SFPU ops

Optimized (Horner on x^2, factored):  `u = x * x  p(x) = c0 + x * (c1 + u*(c3 + u*(c5 + u*(c7 + u*(c9 + u*(c11 + u*(c13 + u*c15)))))))`  == 1 MUL(u=x^2) + 7 MULs(u*...) + 1 MUL(x*inner) + 8 ADDs = 17 SFPU ops

32 ops -> 17 ops = 47% reduction in the core polynomial evaluation.

This would look like:
```cpp
v_elseif(x >= -3.0f) {
    sfpi::vFloat u = x * x;
    sfpi::vFloat odd_poly = PolynomialEvaluator::eval(
        u,
        GELU_CDF_CORE_C1,
        GELU_CDF_CORE_C3,
        GELU_CDF_CORE_C5,
        GELU_CDF_CORE_C7,
        GELU_CDF_CORE_C9,
        GELU_CDF_CORE_C11,
        GELU_CDF_CORE_C13,
        GELU_CDF_CORE_C15);
    sfpi::vFloat phi = GELU_CDF_CORE_C0 + x * odd_poly;
    result = x * phi;
}
```

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 1 above)
Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Nice catch!

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 2 above)
Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Could you please benchmark these changes for perf?

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 1 above)
Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: I think we can do even better. With your proposal, we have:
```cpp
sfpi::vFloat correction = (3.0f * inv_x2 - 1.0f) * inv_x2 + 1.0f;  // 2 MADs
result = exp_val * NEG_INV_SQRT_2PI * correction;                  // 2 MULs
```
But we can make it into:
```cpp
constexpr float K = -0.3989422804014327f;   // -1/sqrt(2*pi)
constexpr float K3 = 3.0f * K;              // -3/sqrt(2*pi)
sfpi::vFloat scaled = (K3 * inv_x2 - K) * inv_x2 + K;  // 2 MADs (same)
result = exp_val * scaled;                             // 1 MUL
```
3 cycles per invocation, ~24 per `calculate_gelu()`

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 2 above)
Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Also, for BFloat16, C13 and C15 are below the precision threshold.
They contribute accuracy that is lost when converting back to BFloat16. A degree-11 polynomial (dropping C13 and C15) might suffice for BF16 mode, saving 4 more SFPU ops.

Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Great suggestion, thank you\! Implemented exactly as proposed — removed all 8 zero-coefficient constants and evaluate the odd-power polynomial via `u = x*x`. All 11 C++ tests and 5 Python tests pass with identical accuracy (Max ULP = 2, same single value at x = -5.0).

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 1 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you\! Implemented, and combined with @fvranicTT's suggestion below to fold the constant into the correction terms — the exp region now does 2 MADs + 1 MUL instead of the original 5 ops. All 11 C++ and 5 Python tests pass with identical accuracy.

Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Great idea, thank you\! Implemented exactly as proposed — `K` and `K3` folded into the correction, eliminating `inv_x4` and saving one MUL. Combined with @mateusznowakTT's 2×MAD rewrite above.

Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Cool. Can we measure the perf difference between the original and this PR? @nmauriceTT could show you how he does it.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 2 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Great suggestion, thank you\! Tested three options with a full refit (not just truncation — dropping terms changes all remaining coefficients):

| Degree | Max ULP | SFPU ops |
|--------|---------|----------|
| 15 (was) | 1 | 17 |
| 13 (now) | 1 | 15 |
| 11 | 7 | 13 |

Degree-11 degrades near x = −3 (boundary), but degree-13 matches degree-15 exactly. Implemented degree-13 — same accuracy, 2 fewer SFPU ops.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 1 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Absolutely, happy to benchmark. @nmauriceTT, could you share your perf measurement approach so we can use the same methodology?

**Review by fvranicTT — APPROVED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 1 above)
Comment (nmauriceTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: @epam-iaroslav-voitovych 
I have a few scripts at https://github.com/nmauriceTT/ttnn-eltwise-op-tester/

For performance measurement, you can do `python bench.py --operation gelu -t bfloat16` (make sure export TT_METAL_HOME / PYTHON and source tt-metal directory beforehand).
This will return the number of cycles / element and the number of cycles/tile. 

Note: This time is obtained by running tracy on sharded tensors. While this includes the overhead of other parts of the metal kernel, it should still be accurate enough for this type of sfpu kernel.

File: tests/ttnn/unit_tests/operations/eltwise/generate_gelu_fw_coefficients.py [hunk 3]
```diff
@@ -0,0 +1,508 @@
...
+    left_nodes = chebyshev_nodes(24, -5.0, -3.0)
+    left_cdf_values = np.array([cdf_reference(float(x)) for x in left_nodes])
+    left_nodes_shifted = left_nodes + 4.0
+    left_cdf = np.polyfit(left_nodes_shifted, left_cdf_values, 8)[::-1]
+    print("Phi(t) coefficients where t = x+4:")
+    for i, c in enumerate(left_cdf):
+        print(f"  c{i:2d} = {c:.15e}")
+
+    # Right CDF [3, 5.375], degree 8
+    print("\n--- Right CDF [3, 5.375]: Degree 8 ---")
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/eltwise/generate_gelu_fw_coefficients.py]: Please use logger.

To not add too many lines to CI logs consider using debug level.

**Review by bbradelTT — APPROVED** [review]

**Review by mateusznowakTT — APPROVED** [review]

File: tests/ttnn/unit_tests/operations/eltwise/generate_gelu_fw_coefficients.py (hunk 3 above)
Comment (epam-iaroslav-voitovych) [reply tests/ttnn/unit_tests/operations/eltwise/generate_gelu_fw_coefficients.py]: Thank you for the review. This file has been removed from the PR — it was a development-only coefficient generation script that doesn't belong in the test tree.

**Review by fvranicTT — CHANGES_REQUESTED** [review]
Based on the benchmarks, it seems the new approach is 2.5x slower than what we had. Do we know why? That could affect performance of our models. Please check that before merging this.
I am not sure we are Ok to merge at this time.
FYI @mateusznowakTT @nmauriceTT

**Review by epam-iaroslav-voitovych — COMMENTED** [review]
@fvranicTT Thank you for the review. You're right — unlike the tanh_bw fix, where fusing a composite into a single kernel gave both ULP = 1 and a performance gain, here the accuracy improvement comes at a performance cost that needs to be addressed.

The optimization possibilities are far from exhausted. Parts of the current implementation are overcomplicated — the exp-based region uses reciprocal calls and complex formulas that add significant overhead. Polynomials work well for the smooth regions but are useless for the steep exponential descent in the deep negative tail — that requires a combination of polynomials with exponent manipulation, which can be made much simpler than the current approach. The number of segments and polynomial orders can likely be reduced as well. The per-segment complexity should be brought in line with the original degree-15 Horner.

Could you specify which models should be benchmarked to assess real-world impact? That would help prioritize the optimization work.

**Comment by mateusznowakTT** [comment]
Started APC, BPC, Nightly (jobs accessible from PR description) and device perf regressions https://github.com/tenstorrent/tt-metal/actions/runs/22944463430 to see what impact it has. Once this is figured out, we can tackle other model perf jobs.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 4]
```diff
@@ -1,90 +1,175 @@
...
+// Validated: Max ULP = 1 across all 266 BF16 values in the region.
+constexpr float GELU_EXP_CORR_C0 = -2.9069766448e-01f;
+constexpr float GELU_EXP_CORR_C1 = 3.9288617802e-02f;
+constexpr float GELU_EXP_CORR_C2 = 5.8260409601e-03f;
+constexpr float GELU_EXP_CORR_C3 = 3.9454728181e-04f;
+constexpr float GELU_EXP_CORR_C4 = 1.0058581740e-05f;
+
+// Forward GELU Evaluation with CDF Polynomial Approximation
+// GELU(x) = x * Phi(x) where Phi is approximated piecewise
+template <bool APPROXIMATION_MODE>
```
Comment (mateusznowakTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: This template parameter can be removed, it seems unused inside this function.

**Review by mateusznowakTT — CHANGES_REQUESTED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 5]
```diff
@@ -1,90 +1,175 @@
...
+sfpi_inline sfpi::vFloat calculate_gelu_piecewise(sfpi::vFloat x) {
+    sfpi::vFloat result = sfpi::vConst0;  // Default: 0 for x <= -13.1875
+
+    v_if(x >= 2.78125f) { result = x; }
+    // Core CDF region [-3.125, 2.78125): GELU(x) = x * Phi_core(x)
+    // Phi(x) = C0 + x*(C1 + x^2*(C3 + x^2*(C5 + ... + x^2*C15)))
+    // Factored via u=x^2 to eliminate zero even-power coefficients
+    v_elseif(x >= -3.125f) {
+        sfpi::vFloat u = x * x;
```
Comment (mateusznowakTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: x^2 can be computed once and reused across branches.

**Review by mateusznowakTT — CHANGES_REQUESTED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 5 above)
Comment (fvranicTT) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Yup, hoisting this one out should save 1 mul.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 6]
```diff
@@ -1,90 +1,175 @@
...
+
+        // Degree-5 Taylor for exp(r), |r| < ln(2)/2 ≈ 0.347
+        sfpi::vFloat p = PolynomialEvaluator::eval(
+            r,
+            sfpi::vConst1,   // 1
+            sfpi::vConst1,   // r
+            0.5f,            // r²/2!
+            1.0f / 6.0f,     // r³/3!
+            1.0f / 24.0f,    // r⁴/4!
+            1.0f / 120.0f);  // r⁵/5!
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: We might get away with dropping `1.0f/120.0f` degree. We'd need to check if it affect accuracy. This saves one MAD.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 7]
```diff
@@ -1,90 +1,175 @@
...
+        constexpr float INV_LN2 = 1.4426950408889634f;
+        sfpi::vFloat z = t * INV_LN2;
+
+        sfpi::vInt k_int;
+        sfpi::vFloat k = _sfpu_round_nearest_int32_(z, k_int);
+
+        constexpr float LN2_HI = -0.6931152343750000f;
+        constexpr float LN2_LO = -3.19461832987e-05f;
+        sfpi::vFloat r = k * LN2_HI + t;
+        r = k * LN2_LO + r;
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]:
```suggestion
        // Single-step range reduction: BFP16 precision (~8 bits) doesn't
        // benefit from the LN2_HI/LN2_LO split (~40-bit precision).
        constexpr float NEG_LN2 = -0.6931471805599453f;
        sfpi::vFloat r = k * NEG_LN2 + t;
```
We could test this in isolation, too.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 8]
```diff
@@ -1,90 +1,175 @@
...
+    // P(x) is a degree-4 correction polynomial fitted to the TRUE function
+    // GELU(x)·exp(x²/2) via minimax approximation over x ∈ (-13.1875, -3.125).
+    //
+    // Uses inline Cody-Waite range reduction instead of library exp call.
+    // For x ∈ (-13.1875, -3.125), t = -x²/2 ∈ (-86.8, -4.88), so z = t/ln2
+    // ∈ (-125.3, -7.0). No overflow/underflow/NaN possible in this range,
+    // so all special-case checks from _sfpu_exp_f32_accurate_ are skipped.
+    // Degree-5 Taylor (vs degree-7 in library): error < 3.3e-9 relative,
+    // negligible for BF16 output.
+    v_elseif(x > -13.1875f) {
```
Comment (fvranicTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Can we use Moroz exp_21f instead of Cody-Waite? Should yield 4 instructions less compared to what we have on the branch.
```cpp
v_elseif(x > -13.1875f) {
    sfpi::vFloat x2 = x * x;
    sfpi::vFloat t = x2 * (-0.5f);

    constexpr float ONE_LN2 = 1.4426950216293334961f;
    sfpi::vFloat xlog2 = t * ONE_LN2 + 127.0f;

    sfpi::vInt z = _float_to_int32_for_exp21f_(xlog2);
    sfpi::vInt exponential_part = sfpi::exexp_nodebias(sfpi::reinterpret<sfpi::vFloat>(z));
    sfpi::vInt fractional_part = sfpi::exman9(sfpi::reinterpret<sfpi::vFloat>(z));

    sfpi::vFloat frac = sfpi::int32_to_float(fractional_part, 0);
    frac = PolynomialEvaluator::eval(frac, 1.0017248f, 7.839635491371155e-08f, 4.791750143340323e-15f);
    sfpi::vFloat exp_val = sfpi::setexp(frac, exponential_part);

    sfpi::vFloat correction = PolynomialEvaluator::eval(
        x, GELU_EXP_CORR_C0, GELU_EXP_CORR_C1, GELU_EXP_CORR_C2, GELU_EXP_CORR_C3, GELU_EXP_CORR_C4);

    result = exp_val * correction;
}
```

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 4 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you\! Applied — removed the `APPROXIMATION_MODE` template parameter from `calculate_gelu_piecewise()`. The dispatch between approximate and accurate modes happens in the caller (`calculate_gelu`), not in the piecewise evaluation itself. 11/11 ULP tests pass.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 5 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you both\! Hoisted `x²` before the `v_if`/`v_elseif` chain — both core CDF and exp regions now share it. 16K tiles: 955 → 932 us (2.4% faster). 11/11 ULP tests pass, Max ULP = 1 unchanged.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 6 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you\! Confirmed — dropping the r⁵/5\! term has no effect on BF16 accuracy (Max ULP = 1 unchanged across all 65,026 values). The max relative error from the degree-4 Taylor is ~2.6e-7, well below BF16 precision (~3.9e-3). 16K tiles: 932 → 907 us (2.7% faster).

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 7 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you! Applied — replaced the two-step LN2_HI/LN2_LO Cody-Waite subtraction with a single `r = k * NEG_LN2 + t`. As you noted, BF16's ~8-bit mantissa doesn't benefit from the ~40-bit extended precision. Saves 1 MAD per element. 16K tiles: 907 → 883 us (2.7% faster). Max ULP = 1 unchanged.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 8 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you! Applied the Moroz exp_21f exactly as you proposed (with the function name corrected to `_float_to_int32_for_exp_21f_`). This is a nice win — replaces the entire Cody-Waite sequence (round + LN2 subtraction + degree-4 Taylor + exponent manipulation) with the compact exp_21f path. 16K tiles: 883 → 825 us (6.6% faster). Max ULP = 1 unchanged across all 65,026 BF16 values. 11/11 tests pass.

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h [hunk 9]
```diff
@@ -144,31 +144,150 @@ inline sfpi::vFloat calculate_gelu_chebyshev(sfpi::vFloat val) {
...
+        //
+        // Uses Moroz exp_21f instead of Cody-Waite range reduction, saving ~4
+        // instructions. The exp_21f algorithm packs floor(t/ln2) and frac(t/ln2)
+        // into a single int32 via _float_to_int32_for_exp_21f_, then extracts
+        // exponential and fractional parts via exexp_nodebias/exman9.
+        sfpi::vFloat t = x2 * (-0.5f);  // t = -x²/2
+
+        // Moroz exp_21f: compact exp via integer bit tricks
+        constexpr float ONE_LN2 = 1.4426950216293334961f;
+        sfpi::vFloat xlog2 = t * ONE_LN2 + 127.0f;
```
Comment (mateusznowakTT) [inline tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: I think t is unnecessary, ONE_LN2 can be divided by -2, and then x2 used here directly to save 1 mul.

**Review by mateusznowakTT — CHANGES_REQUESTED** [review]

File: tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h (hunk 9 above)
Comment (epam-iaroslav-voitovych) [reply tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu/ckernel_sfpu_gelu.h]: Thank you! Applied — folded `t = x2 * (-0.5f)` into the Moroz log2 constant: `x2 * NEG_HALF_ONE_LN2 + 127.0f` where `NEG_HALF_ONE_LN2 = -0.5 / ln(2)`. Saves 1 mul. 16K tiles: 793 → 770 us (2.9% faster). Max ULP = 1 unchanged, 11/11 tests pass.

**Review by mateusznowakTT — APPROVED** [review]

**Review by fvranicTT — APPROVED** [review]

File: tests/ttnn/unit_tests/gtests/test_gelu_fw_ulp.cpp [hunk 10]
```diff
@@ -0,0 +1,1001 @@
...
+
+namespace ttnn::test {
+
+// =============================================================================
+// BFloat16 ULP Calculator (shared with test_gelu_bw_ulp.cpp)
+// =============================================================================
+
+namespace bf16_ulp_fw {
+
+constexpr uint16_t BF16_EXP_MASK = 0x7F80;
```
Comment (dgomezTT) [inline tests/ttnn/unit_tests/gtests/test_gelu_fw_ulp.cpp:60]: I noticed this constants in different prs, maybe we can create an utility file and share it?

File: tests/ttnn/unit_tests/gtests/test_gelu_fw_ulp.cpp [hunk 11]
```diff
@@ -0,0 +1,1001 @@
...
+constexpr uint16_t BF16_MANTISSA_MASK = 0x007F;
+constexpr uint16_t BF16_SIGN_MASK = 0x8000;
+constexpr uint16_t BF16_POS_INF = 0x7F80;
+constexpr uint16_t BF16_NEG_INF = 0xFF80;
+
+inline uint16_t float_to_bf16_bits(float f) {
```
Comment (dgomezTT) [inline tests/ttnn/unit_tests/gtests/test_gelu_fw_ulp.cpp:66]: same with this functions, this sound familiar

**Review by dgomezTT — APPROVED** [review]
small suggestions, but looks good overall
